import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const ctx={Omega:{ResourceIndustrialNetwork:{planShipment(){return{status:'PLANNED'};},dispatchShipment(){return{status:'DISPATCHED'};}}},Game:{state:{simulation:{turn:1,year:2015,daysPerTurn:30},transport:{},resource:{},economy:{BGD:{productionAssets:[{id:'FAC1',countryId:'BGD',locationNodeKey:'FACTORY:BGD:FAC1'}]}},diplomacy:{}}},OmegaResourceSiteMasterResearchData:{sites:[{siteId:'M1',countryId:'BGD',real:{resourceId:'coal'},simulation:{transportRoute:[]}}]},OmegaResourceScenarioEngineeringData:{records:[{siteId:'M1',countryId:'BGD',resourceId:'coal',unit:'TONNES',nominalCapacity:100,minimumCapacity:50,maximumCapacity:150,utilization:.8,recovery:.9,decline:.01,maintenance:.1,scenarioLifeYears:100}]}};
ctx.globalThis=ctx;ctx.CustomEvent=function(name,opts){this.type=name;this.detail=opts?.detail};ctx.dispatchEvent=()=>true;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('omega_resource_strategic_logistics_v1.js','utf8'),ctx);
const N=ctx.Omega.ResourceIndustrialNetwork;
let r=N.setEdgeCondition({countryId:'BGD',edgeId:'R1',fromNode:'MINE:BGD:M1',toNode:'FACTORY:BGD:FAC1',mode:'ROAD',distanceKm:100,capacityPerTurn:1000,action:'OPEN'});
assert.equal(r.status,'APPLIED');
let route=N.planStrategicRoute({countryId:'BGD',siteId:'M1',factoryId:'FAC1',resourceId:'coal',quantity:500});
assert.equal(route.status,'PLANNED');assert.equal(route.distanceAuthority,'MODELED');
N.setEdgeCondition({countryId:'BGD',edgeId:'R1',action:'DESTROY'});
route=N.planStrategicRoute({countryId:'BGD',siteId:'M1',factoryId:'FAC1',resourceId:'coal',quantity:500});
assert.equal(route.status,'BLOCKED');assert.equal(route.reason,'ROUTE_DESTROYED');
N.setEdgeCondition({countryId:'BGD',edgeId:'SEA1',fromNode:'MINE:BGD:M1',toNode:'FACTORY:BGD:FAC1',mode:'SEA',distanceKm:500,capacityPerTurn:5000,action:'OPEN',seaLane:true});
route=N.planStrategicRoute({countryId:'BGD',siteId:'M1',factoryId:'FAC1',resourceId:'coal',quantity:500,navalBlockade:true});
assert.equal(route.status,'BLOCKED');
const tr=N.requestTransitRights({requesterCountryId:'BGD',transitCountryId:'IND',routeEdgeId:'E2',resourceId:'coal',quantity:200});
assert.equal(tr.status,'REQUESTED');assert.equal(N.resolveTransitRights({agreementId:tr.id,approve:true}).status,'APPROVED');
const ext=N.simulateExtractionTurn({countryId:'BGD',siteId:'M1',resourceId:'coal'});
assert.equal(ext.status,'PRODUCED');assert.ok(ext.quantity>0);
assert.equal(N.simulateExtractionTurn({countryId:'BGD',siteId:'M1',resourceId:'coal'}).reason,'ALREADY_SIMULATED_THIS_TURN');
console.log('OMEGA STRATEGIC LOGISTICS + EXTRACTION TEST PASSED');
