/** OMEGA MINISTER QUERY ROUTER v6.0.0 - delegated provider routing + semantic intent bridge */
(function(global){'use strict';
const VERSION='6.0.0';
const QueryIntent=Object.freeze({MINISTER_IDENTITY:'MINISTER_IDENTITY',RESOURCE_SECURITY:'RESOURCE_SECURITY',RESOURCE_STATUS:'RESOURCE_STATUS',RESOURCE_MINING_DISCOVERY:'RESOURCE_MINING_DISCOVERY',RESOURCE_PROCESSING_REFINING:'RESOURCE_PROCESSING_REFINING',RESOURCE_TRADE_TARIFF:'RESOURCE_TRADE_TARIFF',RESOURCE_LOGISTICS:'RESOURCE_LOGISTICS',RESOURCE_FORECAST:'RESOURCE_FORECAST',MACROECONOMICS:'MACROECONOMICS',DEMOGRAPHICS:'DEMOGRAPHICS',DEFENSE_MILITARY:'DEFENSE_MILITARY',ENERGY_POWER:'ENERGY_POWER',POLICY_DIRECTIVE:'POLICY_DIRECTIVE',GENERAL_STRATEGIC:'GENERAL_STRATEGIC',UNKNOWN:'UNKNOWN'});
const RX={security:/\b(secure|security|safe|safety|stockpile|stockpiles|reserve|reserves|buffer|depletion|shortage|runway)\b|নিরাপদ|নিরাপত্তা|সুরক্ষিত|মজুদ|মজুদাগার|স্থায়িত্ব|বাফার|ঘাটতি/i,trade:/\b(import|export|supplier|suppliers|buy|sell|purchase|trade|ship|shipping)\b|আমদানি|রপ্তানি|সরবরাহ|কেনা|বিক্রি|বাণিজ্য/i,identity:/\b(who are you|what is your name|how old are you|your age|background|ideology|minister id)\b|তুমি কে|আপনি কে|বয়স|বয়স|ব্যাকগ্রাউন্ড|পরিচয়|পরিচয়/i};
function detectIntent(prompt){const n=String(prompt||'').normalize('NFKC').trim();if(RX.identity.test(n))return QueryIntent.MINISTER_IDENTITY;if(RX.security.test(n))return QueryIntent.RESOURCE_SECURITY;if(RX.trade.test(n))return QueryIntent.RESOURCE_TRADE_TARIFF;return QueryIntent.GENERAL_STRATEGIC;}
function routeMinisterQuery(prompt,ministerContext={},worldContext={}){const b=global.OfflineSemanticBrain;if(!b)return{version:VERSION,intent:QueryIntent.UNKNOWN,domain:'UNKNOWN',entities:[],requiredData:[],confidence:0,error:'OFFLINE_SEMANTIC_BRAIN_NOT_INITIALIZED'};let p;try{p=b.parse(prompt,{countryId:worldContext.countryCode||ministerContext.countryCode,resourceId:worldContext.resourceId,ministerId:ministerContext.ministerId});}catch(error){return{version:VERSION,intent:QueryIntent.UNKNOWN,domain:'UNKNOWN',entities:[],requiredData:[],confidence:0,error:error.message||String(error)}}const detected=detectIntent(prompt),map={MINISTER_IDENTITY:QueryIntent.MINISTER_IDENTITY,TRADE:QueryIntent.RESOURCE_TRADE_TARIFF,RESOURCE:QueryIntent.RESOURCE_STATUS,CAUSE:QueryIntent.GENERAL_STRATEGIC,STRATEGIC:QueryIntent.POLICY_DIRECTIVE,GENERAL:QueryIntent.GENERAL_STRATEGIC};let intent=map[p.intent]||p.intent||QueryIntent.UNKNOWN;if(detected===QueryIntent.RESOURCE_SECURITY)intent=detected;else if(detected===QueryIntent.MINISTER_IDENTITY)intent=detected;else if(detected===QueryIntent.RESOURCE_TRADE_TARIFF&&(!p.entities?.resource||p.operation==='READ'))intent=detected;const entities=[];for(const[type,e]of Object.entries(p.entities||{}))if(e?.id)entities.push({type,id:e.id,confidence:e.confidence,source:e.source,surface:e.surface});const requiredData=[...(p.sourcePlan||[])];if(p.operation==='READ_PROPERTY')requiredData.push('MINISTER_PROFILE');if(p.operation==='TRADE_SOURCE'||p.operation==='IMPORT')requiredData.push('SUPPLIER_RANKING');if(intent===QueryIntent.RESOURCE_SECURITY)requiredData.push('RESOURCE_STOCKPILE_SECURITY');return{version:VERSION,intent,domain:p.intent||intent,entities,requiredData:[...new Set(requiredData)],confidence:p.confidence,semantic:p,executable:p.executable};}
function el(id){return typeof document!=='undefined'?document.getElementById(id):null}
function ensureAnswerPanel(){if(typeof document==='undefined')return null;const history=el('interrogation-chat-history');if(!history)return null;let n=el('omega-ai-answer');if(!n){n=document.createElement('div');n.id='omega-ai-answer';n.style.cssText='margin:8px 0;padding:10px 12px;border:1px solid rgba(0,229,255,.28);border-radius:8px;line-height:1.45;white-space:pre-wrap;';history.appendChild(n)}let head=el('omega-answer-header');if(!head){head=document.createElement('div');head.id='omega-answer-header';head.style.cssText='display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px;padding-bottom:6px;border-bottom:1px solid rgba(0,229,255,.16);';const label=document.createElement('span');label.textContent='ANSWER PROVIDER';label.style.cssText='font:11px monospace;opacity:.72;';const box=document.createElement('select');box.id='omega-answer-provider';box.setAttribute('aria-label','Answer provider');box.style.cssText='min-width:120px;height:32px;padding:0 8px;border:1px solid rgba(0,229,255,.45);border-radius:6px;background:#07111b;color:#dff8ff;font:12px monospace;';box.innerHTML='<option value="offline">OFFLINE AI</option><option value="google">GOOGLE AI</option>';let saved='offline';try{saved=localStorage.getItem('omega.answerProvider')||'offline'}catch(_){}box.value=saved;box.addEventListener('change',()=>{try{localStorage.setItem('omega.answerProvider',box.value)}catch(_){}});head.append(label,box);n.prepend(head)}return n}
function contextFromPage(){const root=document.querySelector('[data-country-code]');return{countryCode:root?.getAttribute('data-country-code')||global.OmegaGameState?.countryCode||global.GameState?.countryCode||global.OmegaCabinetUI?.activeCountry||'',countryName:root?.getAttribute('data-country-name')||global.OmegaGameState?.countryName||'',ministerId:global.OmegaCabinetUI?.currentMinister?.id||global.OmegaCabinetUI?.currentMinisterId||'',ministryId:global.OmegaCabinetUI?.currentMinistryId||''}}
function answerNode(panel){let n=el('omega-ai-answer-text');if(!n){n=document.createElement('div');n.id='omega-ai-answer-text';n.style.cssText='margin-top:6px;white-space:pre-wrap;';panel.appendChild(n)}return n}
async function submitProviderQuery(){const input=el('interrogation-input'),panel=ensureAnswerPanel(),provider=el('omega-answer-provider');if(!input||!input.value.trim()||!panel)return;const prompt=input.value.trim(),ctx=contextFromPage(),mode=provider?.value||'offline',out=answerNode(panel);out.textContent='Processing…';try{let data;if(mode==='offline'){const r=await fetch('/api/ai/semantic-query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,language:/[\u0980-\u09FF]/.test(prompt)?'bn':'en',countryId:ctx.countryCode,ministerId:ctx.ministerId})});data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||'Offline query failed');const result=data.result||{};out.textContent=result.text||result.answer||'Offline AI could not produce a grounded answer.'}else{const r=await fetch('/api/ai/minister-consult',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,ministerId:ctx.ministerId,ministerName:global.OmegaCabinetUI?.currentMinister?.name||'',ministryId:ctx.ministryId,countryName:ctx.countryName,countryCode:ctx.countryCode,language:/[\u0980-\u09FF]/.test(prompt)?'bn':'en'})});data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||'Google query failed');out.textContent=data.text||data.result?.text||'Google AI returned no answer.'}panel.dataset.provider=mode;panel.dataset.intent=detectIntent(prompt)}catch(err){out.textContent=`Answer error: ${err.message||err}`}}
function install(){if(typeof document==='undefined')return;const ensure=()=>{ensureAnswerPanel();if(document.__omegaQueryRouterInstalled)return;document.__omegaQueryRouterInstalled=true;document.addEventListener('click',e=>{const target=e.target?.closest?.('#btn-submit-interrogation');if(!target)return;e.preventDefault();e.stopPropagation();if(typeof e.stopImmediatePropagation==='function')e.stopImmediatePropagation();submitProviderQuery()},true);document.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const target=e.target;if(!target?.matches?.('#interrogation-input'))return;e.preventDefault();e.stopPropagation();submitProviderQuery()},true)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensure,{once:true});else ensure();setTimeout(ensure,250);setTimeout(ensure,1000)}
if(typeof document!=='undefined')install();
const api=Object.freeze({VERSION,QueryIntent,detectIntent,routeMinisterQuery,install,submitProviderQuery});global.MinisterQueryRouter=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:window);
