/** OMEGA MINISTER QUERY ROUTER v7.0.0 - UNIVERSAL OFFLINE EXECUTION BRIDGE */
(function(global){'use strict';
const VERSION='7.0.0';
const DATA_FILES=['resources.json','resources_2.json','economy.json','population.json','countries.json','relations.json','country_policy.json','world.json','society.json','ministers.json','resource_ontology.json','offline_semantic_knowledge.json'];
const STOP=new Set('a an the is are am was were be been being do does did can could will would shall should may might must have has had to of for from in on at by with about into through over under between and or but if then than that this these those our my your their his her its we i you he she they me us them who what which where when why how as of'.split(/\s+/));
const WORDS={QUESTION:new Set('who what which where when why how'.split(' ')),MODAL:new Set('can could will would should must may might need needs have has had want wants would like'.split(' ')),TRADE:new Set('import imports importing export exports exporting supplier suppliers buy buying purchase sell selling trade trading shipment shipping freight tariff tariffs'.split(' ')),SECURITY:new Set('secure security safe safety stockpile stockpiles reserve reserves shortage depletion runway buffer vulnerable risk'.split(' ')),COUNT:new Set('how many number count total quantity amount'.split(' ')),LOCATION:new Set('where location located based situated country'.split(' ')),COMPARE:new Set('compare versus vs higher lower more less best better largest smallest'.split(' ')),ACTION:new Set('build construct upgrade increase decrease produce mine extract refine process allocate deploy enact approve assign appoint'.split(' '))};
const BN=/[\u0980-\u09FF]/;
const norm=v=>String(v==null?'':v).normalize('NFKC').toLowerCase().replace(/[?!,.:;"'“”‘’(){}\[\]<>—–/\\]/g,' ').replace(/\s+/g,' ').trim();
const words=v=>norm(v).split(/\s+/).filter(Boolean);
const compact=v=>words(v).filter(x=>!STOP.has(x));
const num=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;const m=String(v??'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null};
const scalar=v=>['string','number','boolean'].includes(typeof v);
function flatten(v,path=[],out=[]){if(v==null)return out;if(Array.isArray(v)){v.forEach((x,i)=>flatten(x,path.concat(i),out));return out}if(typeof v!=='object')return out;for(const[k,x]of Object.entries(v)){const p=path.concat(k);if(scalar(x))out.push({key:k,path:p.join('.'),value:x});else flatten(x,p,out)}return out}
function names(v,key=''){const out=[];if(!v||typeof v!=='object')return out;for(const k of ['name','countryName','officialName','shortName','displayName','label','title','resourceName','canonicalName','baseName','name_en','name_bn','localName','nativeName','id','iso3','isoCode','countryCode','resourceId','ministerId'])if(typeof v[k]==='string'&&v[k].trim())out.push(v[k]);if(v.identity&&typeof v.identity==='object')for(const k of Object.keys(v.identity))if(/name/i.test(k)&&typeof v.identity[k]==='string')out.push(v.identity[k]);if(key&&!/^\d+$/.test(String(key)))out.push(String(key).replace(/[_-]+/g,' '));return [...new Set(out)]}
function recordize(data,source){const out=[];function visit(v,path=[],parent=null,key=''){if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach((x,i)=>visit(x,path.concat(i),v,i));return}const ns=names(v,key);const fs=flatten(v);if(ns.length||fs.length)out.push({value:v,path:path.join('.'),key:String(key),names:ns,fields:fs,source});for(const[k,x]of Object.entries(v))if(x&&typeof x==='object')visit(x,path.concat(k),v,k)}visit(data);return out}
let cache=null,loading=null;
async function loadData(){if(cache)return cache;if(loading)return loading;loading=(async()=>{const records=[];const raw={};for(const file of DATA_FILES){try{const r=await fetch('/'+file,{cache:'no-store'});if(!r.ok)continue;const d=await r.json();raw[file]=d;records.push(...recordize(d,file))}catch(e){console.warn('[OMEGA OFFLINE] dataset skipped',file,e.message)}}cache={raw,records,loadedAt:Date.now()};return cache})().finally(()=>{loading=null});return loading}
function scoreName(query,name){const q=compact(query),n=compact(name);if(!q.length||!n.length)return 0;const ns=new Set(n);let hit=0;for(const w of q)if(ns.has(w))hit++;const joined=n.join(' '),qj=q.join(' ');if(joined===qj)return 1;if(joined.includes(qj)||qj.includes(joined))return Math.max(.9,Math.min(1,.55+Math.min(q.length,n.length)/10));return hit?Math.min(.88,.35+.5*hit/Math.max(1,q.length)) : 0}
function entityCandidates(query,records){return records.map(r=>{let best=0,surface='';for(const n of r.names){const s=scoreName(query,n);if(s>best){best=s;surface=n}}return {...r,score:best,surface}}).filter(r=>r.score>=.48).sort((a,b)=>b.score-a.score||String(b.surface).length-String(a.surface).length)}
function tokenEntityScan(q,records){const toks=compact(q);const hits=[];for(const r of records){let hit=0,surface='';for(const n of r.names){const nt=new Set(compact(n));const h=toks.filter(t=>nt.has(t)).length;if(h>hit){hit=h;surface=n}}if(hit)hits.push({...r,tokenHits:hit,surface})}return hits.sort((a,b)=>b.tokenHits-a.tokenHits)}
function detectEntities(q,data){const exact=entityCandidates(q,data.records).slice(0,12);const token=tokenEntityScan(q,data.records).slice(0,30);const merged=[];for(const x of [...exact,...token])if(!merged.some(y=>y.path===x.path))merged.push(x);return merged}
function fieldMatch(record,q){const qw=compact(q);return record.fields.map(f=>{const k=compact(f.key);const val=norm(f.value);let s=0;for(const w of qw){if(k.includes(w))s+=2;if(val.includes(w))s+=.15}return {...f,score:s}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)}
function chooseCountry(q,data,ctx){const context=String(ctx?.countryId||ctx?.countryName||'');const byCtx=entityCandidates(context,data.records).find(r=>/country|countries|sovereign|nation|countryprofiles/i.test(r.path+' '+r.names.join(' ')));if(byCtx)return byCtx;const candidates=entityCandidates(q,data.records);return candidates.find(r=>/country|countries|sovereign|nation|countryprofiles/i.test(r.path+' '+r.names.join(' ')))||null}
function classify(q){const w=new Set(words(q));const has=s=>[...s].some(x=>w.has(x));const operation=has(WORDS.SECURITY)?'SECURITY':has(WORDS.TRADE)?(has(new Set(['import','imports','buy','purchase','supplier','suppliers']))?'IMPORT':'EXPORT'):has(WORDS.COMPARE)?'COMPARE':has(WORDS.LOCATION)?'LOCATION':has(WORDS.COUNT)?'COUNT':has(WORDS.ACTION)?'ACTION':'LOOKUP';const question=[...WORDS.QUESTION].find(x=>w.has(x))||null;const subject=/\b(i|me|my|our|we)\b/.test(q)?'PLAYER':null;const modality=[...WORDS.MODAL].filter(x=>w.has(x));return{operation,question,subject,modality,hasQuestion:!!question}}
function resourceRecords(data){return data.records.filter(r=>{const s=norm(r.path+' '+r.key+' '+r.names.join(' '));return /resource|commodity|mineral|hydrocarbon|petroleum|crude|ore|metal|fuel|energy|oil|gas|coal|lithium|uranium|bauxite|copper|gold|iron/.test(s)})}
function countryRecords(data){return data.records.filter(r=>{const s=norm(r.path+' '+r.key);return /country|countries|countryprofiles|sovereign|nation|state_profiles/.test(s)&&r.names.some(n=>/\b[A-Z]{3}\b/.test(n)||n.length>2)})}
function findResource(q,data){const rs=resourceRecords(data);const a=entityCandidates(q,rs);if(a[0])return a[0];const toks=tokenEntityScan(q,rs);return toks[0]||null}
function valueFor(record,terms){if(!record)return null;const f=record.fields||[];const ts=terms.map(norm);const ranked=f.map(x=>{const k=norm(x.key),p=norm(x.path);let s=0;for(const t of ts){if(k===t)s+=5;else if(k.includes(t))s+=3;if(p.includes(t))s+=1}const n=num(x.value);return{...x,score:s,number:n}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);return ranked[0]||null}
function countryName(r){return r?.names?.find(n=>n&&n.length>2)||r?.key||r?.path||'UNKNOWN'}
function supplierAnalysis(resource,q,data,home){const countries=countryRecords(data);const rq=compact(resource?.surface||resource?.names?.[0]||q);const rows=[];for(const c of countries){if(home&&c.path===home.path)continue;const fs=c.fields||[];const blob=norm(c.path+' '+c.key+' '+c.names.join(' '));let rel=0;for(const t of rq)if(blob.includes(t))rel++;const exp=valueFor(c,['export','exports','exportable','export capacity','available for export']);const prod=valueFor(c,['production','annual production','output','extraction']);const res=valueFor(c,['reserve','reserves','proved reserves']);const cap=valueFor(c,['capacity','production capacity']);const price=valueFor(c,['price','unit price','cost']);if(!(exp||prod||res||rel))continue;let score=rel*8+(exp?45:0)+(prod?20:0)+(res?10:0)+(cap?5:0)+(price?2:0);rows.push({countryId:c.names.find(n=>/^[A-Z]{3}$/.test(n))||null,country:countryName(c),score,exportable:exp?.value??null,production:prod?.value??null,reserves:res?.value??null,capacity:cap?.value??null,price:price?.value??null,source:c.path})}return rows.sort((a,b)=>b.score-a.score).slice(0,8)}
function formatNumber(v){if(typeof v!=='number')return String(v);return new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(v)}
function answer(q,ctx,data){const c=classify(q), resources=findResource(q,data), country=chooseCountry(q,data,ctx);let text='',facts=[],uncertainties=[];if(c.operation==='IMPORT'&&resources){const rows=supplierAnalysis(resources,q,data,country);if(rows.length){text=(BN.test(q)?'সম্ভাব্য আমদানি উৎস:\n':'Potential import sources:\n')+rows.slice(0,5).map((r,i)=>`${i+1}. ${r.country} | score ${r.score}${r.exportable!=null?` | export ${r.exportable}`:''}${r.production!=null?` | production ${r.production}`:''}`).join('\n');facts=rows}else text=BN.test(q)?'আমদানির জন্য যাচাইযোগ্য সরবরাহকারী ডেটা পাওয়া যায়নি।':'No verifiable supplier data was found for the requested import.'}
else if(c.operation==='EXPORT'&&resources){const rows=supplierAnalysis(resources,q,data);text=BN.test(q)?'রপ্তানি বিশ্লেষণ:\n':'Export analysis:\n';text+=rows.slice(0,5).map((r,i)=>`${i+1}. ${r.country} | score ${r.score}${r.exportable!=null?` | export ${r.exportable}`:''}`).join('\n');facts=rows}
else if(c.operation==='SECURITY'&&resources){const rr=resources;const parts=rr.names.slice(0,4).map((name,i)=>{const rec=rr;const stock=valueFor(rec,['stockpile','stock','inventory','available stock']);const cons=valueFor(rec,['consumption','demand','use','usage','burn rate']);const prod=valueFor(rec,['production','output','extraction']);const reserve=valueFor(rec,['reserve','reserves','recoverable reserves']);const runway=stock?.number!=null&&cons?.number>0?stock.number/cons.number:null;const unknown=[];if(!stock)unknown.push('stockpile');if(!cons)unknown.push('consumption/demand');if(!prod)unknown.push('production');return`${name}: ${runway!=null?(runway>=90?'SECURE':runway>=30?'STABLE':runway>=14?'VULNERABLE':'AT RISK'):'UNKNOWN'}${runway!=null?` | runway ${formatNumber(runway)}`:''}${reserve?` | reserves ${reserve.value}`:''}${unknown.length?` | unknown ${unknown.join(', ')}`:''}`});text=(BN.test(q)?'সম্পদ নিরাপত্তা:\n':'Resource security:\n')+parts.join('\n');facts=rr.slice(0,4).map(r=>({resource:r.surface||r.names[0],path:r.path}))}
else{const entities=detectEntities(q,data);const primary=entities[0];if(primary){const fields=fieldMatch(primary,q).slice(0,8);if(fields.length){text=(BN.test(q)?`${countryName(primary)} সম্পর্কিত প্রামাণ্য তথ্য:\n`:`Authoritative data for ${countryName(primary)}:\n`)+fields.map(f=>`• ${f.key}: ${f.value}`).join('\n');facts=fields}else{text=BN.test(q)?`সত্তা শনাক্ত হয়েছে: ${countryName(primary)}`:`Entity identified: ${countryName(primary)}`;facts=[{entity:countryName(primary),source:primary.path}]}}else{text=BN.test(q)?'প্রশ্নটি পার্স করা হয়েছে, কিন্তু প্রামাণ্য গেম ডেটায় মেলানো সত্তা বা তথ্য পাওয়া যায়নি।':'The sentence was parsed, but no matching game entity or authoritative data was found.';uncertainties.push('entity_resolution')};}
const frame={operation:c.operation,questionWord:c.question,subject:c.subject,modality:c.modality,resource:resources?{id:resources.names?.[0]||null,surface:resources.surface||null}:null,country:country?{name:countryName(country),path:country.path}:null,compositional:true,dataBound:true};return{ok:!!text,version:VERSION,text,answer:text,operation:c.operation,semanticFrame:frame,facts,uncertainties,trace:[`datasets:${Object.keys(data.raw).length}`,`records:${data.records.length}`],confidence:facts.length?0.9:.45,source:'OFFLINE_BROWSER_UNIVERSAL_EXECUTOR'}}
async function offlineQuery(prompt,ctx){const data=await loadData();return answer(prompt,ctx,data)}
function ensurePanel(){if(typeof document==='undefined')return null;const h=document.getElementById('interrogation-chat-history');if(!h)return null;let p=document.getElementById('omega-ai-answer');if(!p){p=document.createElement('div');p.id='omega-ai-answer';p.style.cssText='margin:8px 0;padding:10px 12px;border:1px solid rgba(0,229,255,.28);border-radius:8px;line-height:1.45;white-space:pre-wrap;';h.appendChild(p)}let sel=document.getElementById('omega-answer-provider');if(!sel){const head=document.createElement('div');head.style.cssText='display:flex;justify-content:flex-end;margin-bottom:6px';sel=document.createElement('select');sel.id='omega-answer-provider';sel.innerHTML='<option value="offline">OFFLINE AI</option><option value="google">GOOGLE AI</option>';try{sel.value=localStorage.getItem('omega.answerProvider')||'offline'}catch(_){}sel.addEventListener('change',()=>{try{localStorage.setItem('omega.answerProvider',sel.value)}catch(_){}});head.appendChild(sel);p.prepend(head)}return p}
function context(){return{countryId:global.OmegaGameState?.countryCode||global.GameState?.countryCode||global.OmegaCabinetUI?.activeCountry||'',countryName:global.OmegaGameState?.countryName||'',ministerId:global.OmegaCabinetUI?.currentMinister?.id||global.OmegaCabinetUI?.currentMinisterId||'',ministryId:global.OmegaCabinetUI?.currentMinistryId||''}}
async function submit(){const input=document.getElementById('interrogation-input'),panel=ensurePanel(),sel=document.getElementById('omega-answer-provider');if(!input||!panel||!input.value.trim())return;const q=input.value.trim(),mode=sel?.value||'offline';let out=document.getElementById('omega-ai-answer-text');if(!out){out=document.createElement('div');out.id='omega-ai-answer-text';panel.appendChild(out)}out.textContent='Processing…';try{let r;if(mode==='offline')r=await offlineQuery(q,context());else{const resp=await fetch('/api/ai/minister-consult',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:q,...context(),language:BN.test(q)?'bn':'en'})});if(!resp.ok)throw new Error(`HTTP ${resp.status}`);const d=await resp.json();if(!d.ok)throw new Error(d.error||'Google query failed');r={text:d.text||d.result?.text||'Google AI returned no answer.'}}out.textContent=r.text||r.answer||'No answer';panel.dataset.operation=r.operation||''}catch(e){out.textContent=`Answer error: ${e.message||e}`}}
function install(){if(typeof document==='undefined')return;const boot=()=>{if(document.__omegaUniversalRouter)return;document.__omegaUniversalRouter=true;ensurePanel();document.addEventListener('click',e=>{const b=e.target?.closest?.('#btn-submit-interrogation');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();submit()},true);document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.matches?.('#interrogation-input')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();submit()}},true)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();setTimeout(boot,300);setTimeout(boot,1000)}
const QueryIntent={MINISTER_IDENTITY:'MINISTER_IDENTITY',RESOURCE_SECURITY:'RESOURCE_SECURITY',RESOURCE_TRADE_TARIFF:'RESOURCE_TRADE_TARIFF',GENERAL_STRATEGIC:'GENERAL_STRATEGIC'};
function detectIntent(q){const c=classify(q);if(c.operation==='SECURITY')return QueryIntent.RESOURCE_SECURITY;if(c.operation==='IMPORT'||c.operation==='EXPORT')return QueryIntent.RESOURCE_TRADE_TARIFF;if(/\bwho\b|\bname\b|\bage\b|\bbackground\b|\bideology\b|তুমি কে|বয়স|বয়স|নাম|ব্যাকগ্রাউন্ড|পরিচয়|পরিচয়/i.test(q))return QueryIntent.MINISTER_IDENTITY;return QueryIntent.GENERAL_STRATEGIC}
function routeMinisterQuery(prompt,ministerContext={},worldContext={}){return{version:VERSION,intent:detectIntent(prompt),domain:classify(prompt).operation,entities:[],requiredData:['ALL_REPOSITORY_JSON'],confidence:.9,semantic:{raw:prompt,grammar:classify(prompt),executable:true},executable:true}}
install();global.MinisterQueryRouter=Object.freeze({VERSION,QueryIntent,detectIntent,routeMinisterQuery,install,submit,offlineQuery,loadData});if(typeof module!=='undefined'&&module.exports)module.exports=global.MinisterQueryRouter;
})(typeof globalThis!=='undefined'?globalThis:window);
