/* OMEGA UNIVERSAL DATA FINDER v11.0.0-METADATA-COMPILED
 * Runtime route compilation: Operation -> Entity -> Capability -> Dataset -> Record -> Field.
 * No country/resource/question vocabulary is authored here. Meaning is loaded from runtime data and semantic metadata.
 */
(function(global){'use strict';
const VERSION='11.0.0',A=v=>Array.isArray(v)?v:[],O=v=>v&&typeof v==='object',S=v=>String(v==null?'':v).trim(),N=v=>S(v).normalize('NFKC').toLowerCase().replace(/[?!,.:;"'“”‘’(){}\[\]<>—–\/\\]/g,' ').replace(/\s+/g,' ').trim(),U=v=>S(v).toUpperCase();
const IDS=['canonicalId','canonical_id','resourceId','resource_id','ministerId','countryId','country_id','countryCode','country_code','iso3','iso2','iso','isoCode','code','key','id'];
const NAMES=['name','countryName','country_name','officialName','official_name','shortName','displayName','nativeName','localName','name_en','name_bn','resourceName','canonicalName','label','title','baseName'];
const SCALARS=new Set(['string','number','boolean']);
function localJSON(name){try{const p=global.process,fs=p?.getBuiltinModule?.('fs'),path=p?.getBuiltinModule?.('path');if(!fs||!path)return null;const q=path.join(p.cwd(),name);return fs.existsSync(q)?JSON.parse(fs.readFileSync(q,'utf8')):null}catch(_){return null}}
function loadKnowledge(){return global.OmegaOfflineSemanticKnowledge||global.OmegaSemanticKnowledge||localJSON('offline_semantic_knowledge.json')||{}}
function metadataCapabilities(k){const out=[];for(const m of A(k?.data_finding?.dataset_capabilities))for(const c of A(m?.capabilities)){const key=S(c),map=m?.fieldMappings?.[key]||m?.fieldMappings?.[U(key)]||{};out.push({capability:U(key),dataset:S(m.dataset),metadata:m,mapping:map})}return out}
function normalizeDataset(x,i){if(O(x)&&Object.prototype.hasOwnProperty.call(x,'__datasetName'))return{name:S(x.__datasetName)||`runtime_${i}.json`,raw:Object.prototype.hasOwnProperty.call(x,'__data')?x.__data:x};if(O(x)&&Object.prototype.hasOwnProperty.call(x,'dataset')&&Object.prototype.hasOwnProperty.call(x,'data'))return{name:S(x.dataset)||`runtime_${i}.json`,raw:x.data};return{name:`runtime_${i}.json`,raw:x}}
function runtimeDatasets(input,k){const out=[],seen=new Set();A(input).forEach((x,i)=>{const d=normalizeDataset(x,i),key=N(d.name);if(d.raw!=null&&!seen.has(key)){seen.add(key);out.push({...d,type:inferType(d.name)})}});for(const name of [...new Set(metadataCapabilities(k).map(x=>x.dataset).filter(Boolean))]){const key=N(name);if(seen.has(key))continue;const raw=localJSON(name);if(raw!==null){seen.add(key);out.push({name,raw,type:inferType(name)})}}return out}
function inferType(name){const n=N(name);if(/country|countries|nation|sovereign|state/.test(n))return'COUNTRY';if(/resource|mine|deposit|commodity|ore|petroleum|gas|fuel|material|metal/.test(n))return'RESOURCE';if(/minister|cabinet|official/.test(n))return'MINISTER';return'OTHER'}
function ids(v,key=''){if(!O(v))return key&&!/^\d+$/.test(S(key))?[U(key)]:[];const out=[];for(const src of [v,O(v.identity)?v.identity:null].filter(Boolean))for(const k of IDS){const x=src[k];if(S(x))out.push(U(x))}if(key&&!/^\d+$/.test(S(key)))out.push(U(key));return[...new Set(out.filter(Boolean))]}
function names(v,key=''){if(!O(v))return key?[S(key)]:[];const out=[];for(const src of [v,O(v.identity)?v.identity:null].filter(Boolean))for(const k of NAMES){const x=src[k];if(typeof x==='string'&&S(x))out.push(S(x));else if(Array.isArray(x))for(const y of x)if(typeof y==='string'&&S(y))out.push(S(y));else if(O(x))for(const y of Object.values(x))if(typeof y==='string'&&S(y))out.push(S(y))}if(key&&!/^\d+$/.test(S(key)))out.push(S(key).replace(/[_-]+/g,' '));return[...new Set(out)]}
function leafFields(v,path='',out=[]){if(v==null)return out;if(Array.isArray(v)){v.forEach((x,i)=>leafFields(x,`${path}[${i}]`,out));return out}if(!O(v))return out;for(const[k,x]of Object.entries(v)){const p=path?`${path}.${k}`:k;if(SCALARS.has(typeof x))out.push({key:k,path:p,value:x});else if(O(x)||Array.isArray(x))leafFields(x,p,out)}return out}
function pathRead(root,path){if(path==null||S(path)==='')return root;let cur=root;const clean=S(path).replace(/^\$\.?/,'').replace(/\[([^\]]+)\]/g,'.$1');for(const p of clean.split('.').filter(Boolean)){if(cur==null)return undefined;cur=Array.isArray(cur)&&/^\d+$/.test(p)?cur[Number(p)]:cur[p]}return cur}
function recordList(raw,locator){const rp=S(locator);if(rp==='root')return[{value:raw,path:'',key:'root',ids:ids(raw),names:names(raw),fields:leafFields(raw)}];if(rp==='[key]'&&O(raw)&&!Array.isArray(raw))return Object.entries(raw).map(([k,v])=>({value:v,path:k,key:k,ids:ids(v,k),names:names(v,k),fields:leafFields(v)}));const arrMatch=rp.match(/^(.+)\[\]$/);if(arrMatch){const arr=pathRead(raw,arrMatch[1]);return Array.isArray(arr)?arr.map((v,i)=>({value:v,path:`${arrMatch[1]}.${i}`,key:String(i),ids:ids(v,String(i)),names:names(v,String(i)),fields:leafFields(v)})):[]}if(rp&&rp!=='auto'){const v=pathRead(raw,rp);return v===undefined?[]:[{value:v,path:rp,key:rp.split('.').pop()||rp,ids:ids(v,rp.split('.').pop()||rp),names:names(v,rp.split('.').pop()||rp),fields:leafFields(v)}]}return walkRecords(raw)}
function walkRecords(raw,path=[],out=[],depth=0){if(raw==null||depth>14)return out;if(Array.isArray(raw)){raw.forEach((x,i)=>walkRecords(x,path.concat(String(i)),out,depth+1));return out}if(!O(raw))return out;const key=path.at(-1)||'';out.push({value:raw,path:path.join('.'),key,ids:ids(raw,key),names:names(raw,key),fields:leafFields(raw)});for(const[k,x]of Object.entries(raw))if(O(x)||Array.isArray(x))walkRecords(x,path.concat(k),out,depth+1);return out}
function canonicalCountries(){try{const reg=global.OmegaCanonicalIdentityRegistry||global.OmegaCountrySemanticBridge;return A(reg?.exportData?.()?.countries).map(x=>({id:U(x.id),names:A(x.names).filter(Boolean),raw:x})).filter(x=>x.id)}catch(_){return[]}}
function buildEntityIndex(ds){const all=[],countries=[],resources=[];for(const d of ds)for(const r of walkRecords(d.raw)){const type=d.type,x={...r,dataset:d.name,type};all.push(x);if(type==='COUNTRY')countries.push(x);if(type==='RESOURCE')resources.push(x)}for(const c of canonicalCountries())countries.push({value:c.raw,path:`canonical:${c.id}`,key:c.id,ids:[c.id],names:c.names,fields:leafFields(c.raw),dataset:'canonical',type:'COUNTRY'});return{all,countries,resources}}
function similarity(a,b){a=N(a);b=N(b);if(!a||!b)return 0;if(a===b)return 1;if(a.includes(b)||b.includes(a))return .94;const aa=new Set(a.split(/\s+/)),bb=b.split(/\s+/);const hit=[...aa].filter(x=>bb.has(x)).length;return hit?Math.min(.9,.5+.4*hit/Math.max(aa.size,bb.size)):0}
function spans(q){const t=N(q).split(/\s+/).filter(Boolean),out=[];for(let n=t.length;n>0;n--)for(let i=0;i+n<=t.length;i++)out.push(t.slice(i,i+n).join(' '));return out}
function surfaceScore(q,name){let z=0;for(const s of spans(q))z=Math.max(z,similarity(s,name));return z}
function resolveEntity(parsed,type,idx){const e=type==='COUNTRY'?parsed?.entities?.country:parsed?.entities?.resource;const list=type==='COUNTRY'?idx.countries:type==='RESOURCE'?idx.resources:idx.all.filter(x=>x.type===type);if(e?.id)return{status:'RESOLVED',id:U(e.id),type,surface:S(e.surface||e.name||e.id),record:null,names:A(e.names)};const q=N(e?.surface||parsed?.raw||'');const hits=[];for(const r of list)for(const n of r.names||[])if(surfaceScore(q,n)>=.8)hits.push({status:'RESOLVED',id:r.ids?.[0]||null,type,surface:n,record:r,names:r.names,score:surfaceScore(q,n)});hits.sort((a,b)=>b.score-a.score||S(b.surface).length-S(a.surface).length);if(!hits.length)return{status:'UNRESOLVED',id:null,type,confidence:0,candidates:[]};const b=hits[0],s=hits[1];if(s&&b.id!==s.id&&Math.abs(b.score-s.score)<.06)return{status:'AMBIGUOUS',id:null,type,confidence:Number(b.score.toFixed(3)),candidates:hits.slice(0,8)};b.confidence=Number(b.score.toFixed(3));return b}
function assetClassTerms(k){const out=[];for(const [id,val] of Object.entries(k?.asset_classes||{})){const terms=[];for(const n of A(val?.names))terms.push(n);terms.push(id.replace(/_/g,' '));out.push({id:U(id),terms})}return out}
function opTerms(k){const out=[];for(const [id,val] of Object.entries(k?.question_semantics||{})){const terms=[...A(val?.names||val?.phrases||[])];out.push({operation:U(id),terms})}return out}
function capabilityTerms(c,k){const m=c.mapping||{},terms=[c.capability.replace(/_/g,' '),m.valuePath,m.fieldPath,m.fieldName,m.field,m.key];for(const a of assetClassTerms(k))if(U(c.capability)===a.id)terms.push(...a.terms);return [...new Set(terms.map(N).filter(x=>x.length>1))]}
function capabilityScore(c,parsed,k){const raw=N(parsed?.raw||''),prop=U(parsed?.property||''),requested=U(parsed?.requested_output||'');let s=0;if(prop&&prop===c.capability)s+=100;if(requested&&requested===c.capability)s+=90;if(U(parsed?.operation||'')===c.capability)s+=70;for(const t of capabilityTerms(c,k))if(raw.includes(t))s=Math.max(s,t===N(c.capability.replace(/_/g,' '))?80:55);const op=U(parsed?.operation||'');if(op==='COUNT'&&/COUNT/.test(c.capability))s+=18;if(op==='QUANTITY'&&/(QUANTITY|AMOUNT|STOCK|PRODUCTION|POPULATION|GDP|RESERVE)/.test(c.capability))s+=10;if(op==='LOCATION'&&/(LOCATION|CITY|MINE|DEPOSIT|FIELD|CAPITAL)/.test(c.capability))s+=10;if(op==='TIME'&&/(YEAR|DATE|TIME|HISTORY)/.test(c.capability))s+=10;if(op==='METHOD'&&/(PRODUCTION|PROCESS|METHOD)/.test(c.capability))s+=8;return s}
function registry(ds,k){const all=metadataCapabilities(k),by=new Map();for(const d of ds){const meta=all.filter(c=>N(c.dataset)===N(d.name));by.set(d.name,{...d,metadata:meta,authority:meta.length?'EXPLICIT_METADATA':'INFERRED_SCHEMA'})}return by}
function candidatePlans(parsed,entity,reg,k){const out=[];for(const [dataset,d] of reg)for(const c of d.metadata){const cs=capabilityScore(c,parsed,k);if(cs<=0)continue;const types=A(c.metadata?.entityTypes).map(U),typeOk=!entity||!types.length||types.includes(U(entity.type));const idOk=A(c.metadata?.identityFields).length>0;const priority=Number(c.metadata?.priority||c.metadata?.authorityScore||0);const coverage=Number(c.metadata?.coverageScore||c.metadata?.coverage||0);const freshness=Number(c.metadata?.freshnessScore||0);const score=cs+(typeOk?25:0)+(idOk?8:0)+(d.authority==='EXPLICIT_METADATA'?12:0)+priority+coverage+freshness;out.push({dataset,capability:c.capability,mapping:c.mapping||{},metadata:c.metadata,score,typeOk,idOk,authority:d.authority,why:{capabilityMatch:cs,entityTypeMatch:typeOk,identityMetadata:idOk,priority,coverage,freshness}})}out.sort((a,b)=>b.score-a.score||a.dataset.localeCompare(b.dataset));return out}
function identityScore(r,e){if(!r||!e?.id)return 0;const id=U(e.id);if(A(r.ids).map(U).includes(id))return 1;if(A(e.names).some(a=>A(r.names).some(b=>N(a)===N(b))))return .95;if(U(r.key)===id)return .9;return 0}
function locateRecord(plan,dataset,entity){const locator=plan.mapping?.recordPath||plan.metadata?.recordLocator||'auto';const rs=recordList(dataset.raw,locator).map(r=>({...r,dataset:dataset.name}));const hits=rs.map(r=>({...r,identityScore:identityScore(r,entity)})).filter(r=>r.identityScore>0).sort((a,b)=>b.identityScore-a.identityScore);if(hits.length)return hits[0];if(locator==='root'&&entity?.type){const recursive=walkRecords(dataset.raw).map(r=>({...r,dataset:dataset.name,identityScore:identityScore(r,entity)})).filter(r=>r.identityScore>0).sort((a,b)=>b.identityScore-a.identityScore);if(recursive.length)return recursive[0]}return null}
function extract(record,plan,parsed){const m=plan.mapping||{};for(const p of [m.valuePath,m.fieldPath,m.fieldName,m.field,m.key].filter(S)){const v=pathRead(record.value,p);if(v!==undefined)return{value:v,path:p,method:'EXPLICIT_FIELD_MAPPING'}}const wanted=new Set([N(parsed?.property||''),N(parsed?.requested_output||''),N(plan.capability||'').replace(/_/g,' ')].filter(x=>x));let best=null,score=0;for(const f of record.fields||[]){const key=N(`${f.key} ${f.path}`);let s=0;for(const w of wanted)if(w&&key.includes(w))s+=10;if(s>score){score=s;best=f}}return best?{value:best.value,path:best.path,method:'SCHEMA_FIELD_MATCH'}:null}
function policyPreflight(parsed,entity,reg,k){const needed=[];for(const c of metadataCapabilities(k)){const cap=c.capability;if(entity?.type==='RESOURCE'&&/(RESOURCE|PRODUCTION|STOCK|MINE|DEPOSIT|RESERVE|SUPPLY|DEMAND)/.test(cap))needed.push(c);if(entity?.type==='COUNTRY'&&/(RESOURCE|PRODUCTION|STOCK|MINE|DEPOSIT|RESERVE|SUPPLY|DEMAND|ECONOMY|POPULATION)/.test(cap))needed.push(c)}const uniq=[];const seen=new Set();for(const c of needed){const id=`${c.dataset}:${c.capability}`;if(!seen.has(id)){seen.add(id);uniq.push(c)}}return uniq.slice(0,12).map(c=>({dataset:c.dataset,capability:c.capability,mapping:c.mapping||{},phase:'STATE_EVIDENCE'}))}
function buildPlan(parsed,entity,reg,k){const candidates=candidatePlans(parsed,entity,reg,k);const method=U(parsed?.operation||'');const isPolicy=method==='POLICY'||method==='METHOD'||method==='FEASIBILITY'||method==='FORECAST'||method==='CAUSE';if(isPolicy)return{status:'PLANNED_POLICY_PREFLIGHT',entity:entity?{type:entity.type,id:entity.id}:null,candidates:candidates.slice(0,12),selected:candidates[0]?{dataset:candidates[0].dataset,capability:candidates[0].capability,fieldMapping:candidates[0].mapping}:null,preflight:policyPreflight(parsed,entity,reg,k),nextPhase:'POLICY_REASONING_AFTER_STATE_EVIDENCE'};return{status:candidates[0]?'PLANNED':'UNRESOLVED',entity:entity?{type:entity.type,id:entity.id}:null,candidates:candidates.slice(0,12),selected:candidates[0]?{dataset:candidates[0].dataset,capability:candidates[0].capability,fieldMapping:candidates[0].mapping}:null}}
function directIdentity(entity){return{ok:true,status:'VERIFIED_FACT',operation:'IDENTIFY',targetDomain:entity.type,entity:{id:entity.id,type:entity.type},value:entity.record?.value||entity.id,evidence:[{dataset:entity.record?.dataset||'canonical',recordLocator:entity.record?.path||null,fieldPath:null,canonicalEntityId:entity.id,rawValue:entity.record?.value||entity.id,authority:entity.record?.dataset==='canonical'?'CANONICAL_REGISTRY':'RUNTIME_DATASET'}],source:'OMEGA_UNIVERSAL_DATA_FINDER'}}
function execute(parsed,datasets=[],language='en',ctx={}){const k=loadKnowledge(),ds=runtimeDatasets(datasets,k),reg=registry(ds,k),idx=buildEntityIndex(ds);let country=resolveEntity(parsed,'COUNTRY',idx),resource=resolveEntity(parsed,'RESOURCE',idx);if(country.status==='AMBIGUOUS'||resource.status==='AMBIGUOUS')return{ok:false,status:'AMBIGUOUS',value:null,evidence:[],semantic:parsed,diagnostics:{country,resource}};let entity=null;if(country.status==='RESOLVED')entity={...country,type:'COUNTRY'};else if(resource.status==='RESOLVED')entity={...resource,type:'RESOURCE'};else if(ctx?.countryId){const id=U(ctx.countryId);const hit=idx.countries.find(x=>A(x.ids).map(U).includes(id));if(hit)entity={status:'RESOLVED',id,type:'COUNTRY',surface:hit.names?.[0]||id,record:hit,names:hit.names||[]}}if(!entity)return{ok:false,status:'NOT_FOUND',value:null,evidence:[],semantic:parsed,diagnostics:{datasets:[...reg.keys()]}};const prop=parsed?.property&&S(parsed.property)!=='answer'?parsed.property:null,identityOnly=!prop&&(!parsed?.operation||U(parsed.operation)==='IDENTIFY');if(identityOnly)return directIdentity(entity);const plan=buildPlan(parsed,entity,reg,k);if(plan.status==='PLANNED_POLICY_PREFLIGHT')return{ok:true,status:'DERIVED_PLAN',operation:U(parsed.operation),targetDomain:entity.type,entity:{id:entity.id,type:entity.type},value:null,evidence:[],plan,source:'OMEGA_POLICY_PREFLIGHT'};if(!plan.selected)return{...directIdentity(entity),ok:false,status:'UNSUPPORTED',value:null,evidence:[],plan};const d=reg.get(plan.selected.dataset),record=locateRecord(plan.selected,d,entity);if(!record)return{ok:false,status:'NOT_FOUND',value:null,evidence:[],semantic:parsed,plan,diagnostics:{reason:'IDENTITY_NOT_FOUND_IN_SELECTED_DATASET',entity:entity.id,dataset:d?.name||null}};const got=extract(record,plan.selected,parsed);if(!got)return{ok:false,status:'NOT_FOUND',value:null,evidence:[],semantic:parsed,plan,record:record.path,diagnostics:{reason:'FIELD_NOT_FOUND'}};const ev={dataset:d.name,recordLocator:record.path||null,fieldPath:got.path||null,canonicalEntityId:entity.id,rawValue:got.value,capability:plan.selected.capability,authority:plan.selected.authority,resolutionMethod:got.method};return{ok:true,status:'VERIFIED_FACT',operation:U(parsed?.operation||plan.selected.capability),targetDomain:entity.type,entity:{id:entity.id,type:entity.type},value:got.value,evidence:[ev],source:'OMEGA_UNIVERSAL_DATA_FINDER',plan:{entity:{type:entity.type,id:entity.id},capability:plan.selected.capability,dataset:d.name,recordLocator:ev.recordLocator,fieldPath:ev.fieldPath,datasetSelection:plan.candidates.slice(0,8)}}}
function index(datasets=[]){const k=loadKnowledge(),rt=runtimeDatasets(datasets,k),ix=buildEntityIndex(rt),rg=registry(rt,k);return{records:ix.all,countries:ix.countries,resources:ix.resources,datasets:rt.map(d=>({name:d.name,type:d.type,authority:rg.get(d.name)?.authority||'INFERRED_SCHEMA',capabilities:rg.get(d.name)?.metadata?.map(x=>x.capability)||[]})),routeVocabulary:{operations:opTerms(k),assetClasses:assetClassTerms(k),capabilities:metadataCapabilities(k)}}}
function buildExecutionPlan(parsed,datasets,ctx={}){const k=loadKnowledge(),rt=runtimeDatasets(datasets,k),rg=registry(rt,k),ix=buildEntityIndex(rt),c=resolveEntity(parsed,'COUNTRY',ix),r=resolveEntity(parsed,'RESOURCE',ix),e=c.status==='RESOLVED'?c:r.status==='RESOLVED'?r:null;return buildPlan(parsed,e,rg,k)}
function buildEvidenceLedger(r){return{facts:r?.facts||[],ranked:r?.ranked||[],calculations:r?.calculations||[],uncertainties:r?.uncertainties||[],trace:r?.trace||[],evidence:r?.evidence||[]}}
const api={VERSION,execute,index,buildExecutionPlan,buildEvidenceLedger,resolveResources:(q,p,idx)=>A(idx?.resources||[]).filter(x=>spans(q).some(s=>A(x.names).some(n=>surfaceScore(s,n)>=.8))).slice(0,20),securityFor:(country,re)=>execute({raw:`${country?.names?.[0]||''} ${re?.names?.[0]||''}`,operation:'SECURITY',property:'RESOURCE_SECURITY',entities:{country:country?{id:country.id,surface:country.names?.[0]}:null,resource:re?{id:re.id,surface:re.names?.[0]}:null}},[],'en',{}),supplierRows:()=>[],composeAnswer:a=>a?.text||'',realizeVerb:(subject,verb)=>S(verb)};
global.OfflineQueryEngine=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:window);
