/* OMEGA OFFLINE QUERY EXECUTOR v10.1.0-UNIVERSAL-DATA-FINDER */
(function(global){'use strict';
const VERSION='10.1.0',A=v=>Array.isArray(v)?v:[],O=v=>v&&typeof v==='object',S=v=>String(v==null?'':v).trim(),N=v=>S(v).normalize('NFKC').toLowerCase().replace(/[?!,.:;"'“”‘’(){}\[\]<>—–\/\\]/g,' ').replace(/\s+/g,' ').trim(),U=v=>S(v).toUpperCase();
const IDS=['canonicalId','canonical_id','resourceId','resource_id','ministerId','countryId','country_id','countryCode','country_code','iso3','iso2','iso','isoCode','code','key','id'];
const NAMES=['name','countryName','country_name','officialName','official_name','shortName','displayName','nativeName','localName','name_en','name_bn','resourceName','canonicalName','label','title','baseName'];
const TYPES=['string','number','boolean'];
function localJSON(name){try{const p=global.process,fs=p?.getBuiltinModule?.('fs'),path=p?.getBuiltinModule?.('path');if(!fs||!path)return null;const f=path.join(p.cwd(),name);return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):null}catch(_){return null}}
function knowledge(){return global.OmegaOfflineSemanticKnowledge||global.OmegaSemanticKnowledge||localJSON('offline_semantic_knowledge.json')||{}}
function caps(k){const out=[];for(const m of A(k?.data_finding?.dataset_capabilities))for(const c of A(m?.capabilities)){const key=S(c),map=m?.fieldMappings?.[key]||m?.fieldMappings?.[U(key)]||{};out.push({capability:U(key),dataset:S(m.dataset),metadata:m,mapping:map})}return out}
function normDataset(x,i){if(O(x)&&Object.prototype.hasOwnProperty.call(x,'__datasetName'))return{name:S(x.__datasetName)||`runtime_${i}.json`,raw:Object.prototype.hasOwnProperty.call(x,'__data')?x.__data:x};if(O(x)&&Object.prototype.hasOwnProperty.call(x,'dataset')&&Object.prototype.hasOwnProperty.call(x,'data'))return{name:S(x.dataset)||`runtime_${i}.json`,raw:x.data};return{name:`runtime_${i}.json`,raw:x}}
function datasets(input,k){const out=[],seen=new Set();A(input).forEach((x,i)=>{const d=normDataset(x,i),key=N(d.name);if(d.raw!=null&&!seen.has(key)){seen.add(key);out.push(d)}});for(const name of [...new Set(caps(k).map(x=>x.dataset).filter(Boolean))]){const key=N(name);if(seen.has(key))continue;const raw=localJSON(name);if(raw!==null){seen.add(key);out.push({name,raw})}}return out}
function ids(v,key=''){if(!O(v))return key&&!/^\d+$/.test(S(key))?[U(key)]:[];const out=[];for(const src of [v,O(v.identity)?v.identity:null].filter(Boolean))for(const k of IDS){const x=src[k];if(S(x))out.push(U(x))}if(key&&!/^\d+$/.test(S(key)))out.push(U(key));return[...new Set(out)]}
function names(v,key=''){if(!O(v))return key?[S(key)]:[];const out=[];for(const src of [v,O(v.identity)?v.identity:null].filter(Boolean))for(const k of NAMES){const x=src[k];if(typeof x==='string'&&S(x))out.push(S(x));else if(Array.isArray(x))for(const y of x)if(typeof y==='string'&&S(y))out.push(S(y))}if(key&&!/^\d+$/.test(S(key)))out.push(S(key).replace(/[_-]+/g,' '));return[...new Set(out)]}
function leafs(v,path='',out=[]){if(v==null)return out;if(Array.isArray(v)){v.forEach((x,i)=>leafs(x,`${path}[${i}]`,out));return out}if(!O(v))return out;for(const[k,x]of Object.entries(v)){const p=path?`${path}.${k}`:k;if(TYPES.includes(typeof x))out.push({key:k,path:p,value:x});else if(O(x)||Array.isArray(x))leafs(x,p,out)}return out}
function pathRead(root,path){if(path==null||S(path)==='')return root;let cur=root;const clean=S(path).replace(/^\$\.?/,'');for(const p of clean.replace(/\[([^\]]+)\]/g,'.$1').split('.').filter(Boolean)){if(cur==null)return undefined;cur=/^\d+$/.test(p)&&Array.isArray(cur)?cur[Number(p)]:cur[p]}return cur}
function recordList(raw,locator){const rp=S(locator);if(rp==='root')return[{value:raw,path:'',key:'root'}];if(rp==='[key]'&&O(raw)&&!Array.isArray(raw))return Object.entries(raw).map(([k,v])=>({value:v,path:k,key:k}));const m=rp.match(/^(.+)\[\]$/);if(m){const arr=pathRead(raw,m[1]);return Array.isArray(arr)?arr.map((v,i)=>({value:v,path:`${m[1]}.${i}`,key:String(i)})):[]}if(rp&&rp!=='auto'){const v=pathRead(raw,rp);return v===undefined?[]:[{value:v,path:rp,key:rp.split('.').pop()||rp}]}const out=[];function walk(v,p=[],depth=0){if(v==null||depth>12)return;if(Array.isArray(v)){v.forEach((x,i)=>walk(x,p.concat(String(i)),depth+1));return}if(!O(v))return;out.push({value:v,path:p.join('.'),key:p[p.length-1]||''});for(const[k,x]of Object.entries(v))if(O(x)||Array.isArray(x))walk(x,p.concat(k),depth+1)}walk(raw);return out}
function cCountries(){try{const r=global.OmegaCanonicalIdentityRegistry||global.OmegaCountrySemanticBridge;return A(r?.exportData?.()?.countries).map(x=>({id:U(x.id),names:A(x.names).filter(Boolean),raw:x})).filter(x=>x.id)}catch(_){return[]}}
function resolveEntity(parsed,type,all){const e=type==='COUNTRY'?parsed?.entities?.country:type==='RESOURCE'?parsed?.entities?.resource:null;if(e?.id)return{status:'RESOLVED',id:U(e.id),surface:S(e.surface||e.name||e.id),type};const q=N(e?.surface||parsed?.raw||'');let best=null,second=null;for(const r of all){for(const n of r.names||[]){const x=N(n);if(!x)continue;let s=q===x?1:q.includes(x)?.94:0;if(!s){const qt=new Set(q.split(/\s+/)),nt=x.split(/\s+/);const hit=nt.filter(t=>qt.has(t)).length;s=hit?Math.min(.9,.5+.4*hit/Math.max(qt.size,nt.length)):0}if(s>=.8){const h={id:r.ids?.[0]||null,surface:n,record:r,score:s,type};if(!best||s>best.score){second=best;best=h}else if(!second||s>second.score)second=h}}}if(!best)return{status:'UNRESOLVED',id:null,confidence:0,candidates:[]};if(second&&best.id!==second.id&&Math.abs(best.score-second.score)<.06)return{status:'AMBIGUOUS',id:null,confidence:best.score,candidates:[best,second]};return{status:'RESOLVED',id:best.id,surface:best.surface,record:best.record,confidence:best.score,type}}
function entityPool(ix,type){return type==='COUNTRY'?ix.countries:type==='RESOURCE'?ix.resources:ix.all.filter(x=>x.type===type)}
function buildIndex(ds){const all=[],countries=[],resources=[];for(const d of ds)for(const r of recordList(d.raw,'auto')){const x={...r,dataset:d.name,ids:ids(r.value,r.key),names:names(r.value,r.key),fields:leafs(r.value),type:/resource|mine|deposit|commodity|ore|petroleum|gas|fuel|material|metal/i.test(N(d.name))?'RESOURCE':/country|countries|nation|sovereign|state/i.test(N(d.name))?'COUNTRY':'OTHER'};all.push(x);if(x.type==='COUNTRY')countries.push(x);if(x.type==='RESOURCE')resources.push(x)}for(const c of cCountries())countries.push({value:c.raw,path:`canonical:${c.id}`,key:c.id,ids:[c.id],names:c.names,fields:leafs(c.raw),dataset:'canonical',type:'COUNTRY'});return{all,countries,resources}}
function identityScore(r,e){if(!r||!e?.id)return 0;const id=U(e.id);if(A(r.ids).includes(id))return 1;if(A(e.names).some(a=>A(r.names).some(b=>N(a)===N(b))))return .95;if(U(r.key)===id)return .9;return 0}
function capScore(c,p){const raw=N(p?.raw||''),prop=U(p?.property||''),out=U(p?.requested_output||'');if(prop&&prop===c.capability)return 1;if(out&&out===c.capability)return .99;let z=0;for(const t of [c.capability,N(c.capability).replace(/_/g,' '),N(c.mapping?.valuePath),N(c.mapping?.fieldPath),N(c.mapping?.fieldName),N(c.mapping?.field),N(c.mapping?.key)].filter(x=>x&&x.length>1))if(raw.includes(t))z=Math.max(z,t===N(c.capability).replace(/_/g,' ')?1:.88);return z}
function plans(parsed,reg,e){const out=[];for(const [name,d]of reg)for(const c of d.metadata){const q=capScore(c,parsed);if(!q)continue;const typeOk=!A(c.metadata?.entityTypes).length||A(c.metadata.entityTypes).map(U).includes(U(e.type));if(!typeOk)continue;const identityOk=A(c.metadata?.identityFields).length>0;const score=q*70+(identityOk?10:0)+(d.authority==='EXPLICIT_METADATA'?10:0)+5;out.push({dataset:name,capability:c.capability,mapping:c.mapping||{},metadata:c.metadata,score,authority:d.authority})}return out.sort((a,b)=>b.score-a.score||a.dataset.localeCompare(b.dataset))}
function findRecord(plan,d,e){const loc=plan.mapping?.recordPath||plan.metadata?.recordLocator||'auto';const rs=recordList(d.raw,loc).map(r=>({...r,dataset:d.name,ids:ids(r.value,r.key),names:names(r.value,r.key),fields:leafs(r.value)}));return rs.map(r=>({...r,s:identityScore(r,e)})).filter(r=>r.s>0).sort((a,b)=>b.s-a.s)[0]||null}
function extract(r,p,parsed){const m=p.mapping||{};for(const path of [m.valuePath,m.fieldPath,m.fieldName,m.field,m.key].filter(S)){const v=pathRead(r.value,path);if(v!==undefined)return{value:v,path,method:'EXPLICIT_FIELD_MAPPING'}}const wanted=N(parsed?.property||parsed?.requested_output||'');let hit=null,score=0;for(const f of r.fields||[]){const k=N(`${f.key} ${f.path}`),s=wanted&&k.includes(wanted)?10:k.includes(N(p.capability).replace(/_/g,' '))?6:0;if(s>score){score=s;hit=f}}return hit?{value:hit.value,path:hit.path,method:'SCHEMA_FIELD_MATCH'}:null}
function identity(e){return{ok:true,status:'VERIFIED_FACT',operation:'IDENTIFY',targetDomain:e.type,entity:{id:e.id,type:e.type},value:e.record?.value||e.id,evidence:[{dataset:e.record?.dataset||'canonical',recordLocator:e.record?.path||null,fieldPath:null,canonicalEntityId:e.id,rawValue:e.record?.value||e.id,authority:e.record?.dataset==='canonical'?'CANONICAL_REGISTRY':'RUNTIME_DATASET'}],source:'OMEGA_UNIVERSAL_DATA_FINDER'}}
function execute(parsed,datasetsInput=[],language='en',ctx={}){const k=knowledge(),ds=datasets(datasetsInput,k),by=new Map(),cs=caps(k);for(const d of ds){const meta=cs.filter(x=>N(x.dataset)===N(d.name));by.set(d.name,{...d,metadata:meta,authority:meta.length?'EXPLICIT_METADATA':'INFERRED_SCHEMA'})}const ix=buildIndex(ds);let country=resolveEntity(parsed,'COUNTRY',entityPool(ix,'COUNTRY')),resource=resolveEntity(parsed,'RESOURCE',entityPool(ix,'RESOURCE'));if(country.status==='AMBIGUOUS'||resource.status==='AMBIGUOUS')return{ok:false,status:'AMBIGUOUS',value:null,evidence:[],semantic:parsed,diagnostics:{country,resource}};let e=country.status==='RESOLVED'?country:resource.status==='RESOLVED'?resource:null;if(!e&&ctx?.countryId){const hit=ix.countries.find(r=>A(r.ids).includes(U(ctx.countryId)));if(hit)e={status:'RESOLVED',id:U(ctx.countryId),surface:hit.names?.[0]||U(ctx.countryId),record:hit,type:'COUNTRY'}}if(!e)return{ok:false,status:'NOT_FOUND',value:null,evidence:[],semantic:parsed,diagnostics:{datasets:[...by.keys()]}};const prop=S(parsed?.property||'');if(!prop&&(!parsed?.operation||U(parsed.operation)==='IDENTIFY'))return identity(e);const ps=plans(parsed,by,e);const selected=ps[0];const plan={status:selected?'PLANNED':'UNRESOLVED',entity:{type:e.type,id:e.id},candidates:ps.slice(0,12),selected:selected?{dataset:selected.dataset,capability:selected.capability,fieldMapping:selected.mapping}:null};if(!selected)return{...identity(e),ok:false,status:'UNSUPPORTED',value:null,evidence:[],plan};const d=by.get(selected.dataset),r=findRecord(selected,d,e);if(!r)return{ok:false,status:'NOT_FOUND',value:null,evidence:[],semantic:parsed,plan};const got=extract(r,selected,parsed);if(!got)return{ok:false,status:'NOT_FOUND',value:null,evidence:[],semantic:parsed,plan,record:r.path};const ev={dataset:d.name,recordLocator:r.path||null,fieldPath:got.path||null,canonicalEntityId:e.id,rawValue:got.value,capability:selected.capability,authority:selected.authority,resolutionMethod:got.method};return{ok:true,status:'VERIFIED_FACT',operation:U(parsed?.operation||selected.capability),targetDomain:e.type,entity:{id:e.id,type:e.type},value:got.value,evidence:[ev],source:'OMEGA_UNIVERSAL_DATA_FINDER',plan:{entity:{type:e.type,id:e.id},capability:selected.capability,dataset:d.name,recordLocator:ev.recordLocator,fieldPath:ev.fieldPath,datasetSelection:ps.slice(0,8)}}}
function index(input=[]){const k=knowledge(),ds=datasets(input,k),ix=buildIndex(ds),cs=caps(k),by=ds.map(d=>({name:d.name,authority:cs.some(c=>N(c.dataset)===N(d.name))?'EXPLICIT_METADATA':'INFERRED_SCHEMA',capabilities:cs.filter(c=>N(c.dataset)===N(d.name)).map(c=>c.capability)}));return{records:ix.all,countries:ix.countries,resources:ix.resources,datasets:by}}
function buildExecutionPlan(parsed,datasetsInput=[],ctx={}){return execute(parsed,datasetsInput,parsed?.language||'en',ctx)?.plan||null}
function buildEvidenceLedger(r){return{facts:r?.facts||[],ranked:r?.ranked||[],calculations:r?.calculations||[],uncertainties:r?.uncertainties||[],trace:r?.trace||[],evidence:r?.evidence||[]}}
const api={VERSION,execute,index,buildExecutionPlan,buildEvidenceLedger,resolveResources:(q,p,idx)=>A(idx?.resources).filter(r=>N(q).includes(N(r.names?.[0]||''))).slice(0,20),securityFor:(c,r)=>({ok:false,status:'UNSUPPORTED',reason:'Security capability requires explicit dataset metadata'}),supplierRows:()=>[],composeAnswer:a=>a?.text||'',realizeVerb:(s,v)=>S(v)};global.OfflineQueryEngine=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:window);
