/* OMEGA OFFLINE SEMANTIC BRAIN v4.0.1-GRAMMAR */
(function(global){'use strict';
const VERSION='4.0.1',LEARNED_KEY='OMEGA_OFFLINE_SEMANTIC_LEARNING_V4';
let runtime={countries:[],resources:[],ministers:[],vocabulary:{},datasets:[],indexes:{country:new Map(),resource:new Map(),minister:new Map()}};
const object=v=>v&&typeof v==='object',text=v=>String(v==null?'':v).trim(),clone=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
const bn=/[\u0980-\u09FF]/; const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,Number.isFinite(Number(n))?Number(n):a));
function norm(s){return text(s).normalize('NFKC').toLowerCase().replace(/[?!,.:;\"'“”‘’(){}\[\]<>]/g,' ').replace(/[—–]/g,' ').replace(/\s+/g,' ').trim()}
function compact(s){return norm(s).replace(/\s+/g,'')}
function tokens(s){return norm(s).split(/\s+/).filter(Boolean)}
function stem(w,lang){let x=w;if(lang==='en'){if(/\w{5,}ies$/.test(x))return x.replace(/ies$/,'y');if(/\w{5,}(ches|shes|xes|zes|ses)$/.test(x))return x.replace(/es$/,'');if(/\w{5,}ing$/.test(x))return x.replace(/ing$/,'');if(/\w{5,}ed$/.test(x))return x.replace(/ed$/,'');if(/\w{4,}s$/.test(x)&&!/(ss|us|is)$/.test(x))return x.slice(0,-1);return x}for(const s of ['সমূহ','গুলি','গুলো','গণ','দের','টির','টা','টি','রা','এর','কে','তে','র','ে'])if(x.length>s.length+2&&x.endsWith(s))return x.slice(0,-s.length);return x}
function nt(s,lang){return tokens(s).map(x=>stem(x,lang))}
function storage(){try{return global.localStorage||null}catch(_){return null}}
function learned(){const s=storage();if(!s)return{};try{return JSON.parse(s.getItem(LEARNED_KEY)||'{}')}catch(_){return{}}}
function saveLearned(v){const s=storage();if(!s)return false;try{s.setItem(LEARNED_KEY,JSON.stringify(v));return true}catch(_){return false}}
function learn(surface,type,id,confidence=.95){if(!surface||!type||!id||confidence<.95)return false;const m=learned();m[`${type}:${norm(surface)}`]={type,id,confidence,updatedAt:Date.now()};const ks=Object.keys(m);while(ks.length>512)delete m[ks.shift()];return saveLearned(m)}
function idOf(v,h=''){if(!object(v))return text(h).toUpperCase()||null;for(const k of ['id','iso','iso3','isoCode','countryCode','code','canonical_id','canonicalId']){const x=text(v[k]);if(/^[A-Za-z][A-Za-z0-9_-]{1,63}$/.test(x))return x.toUpperCase()}return/^[A-Za-z][A-Za-z0-9_-]{1,63}$/.test(h)?h.toUpperCase():null}
function namesOf(v,h=''){if(!object(v))return h?[h]:[];const out=[];for(const k of ['name','countryName','officialName','shortName','displayName','label','title','resourceName','canonicalName','localName','nativeName','name_en','name_bn','identity','baseName','regionalName','regional_names','regionalNames']){const x=v[k];if(typeof x==='string'&&x.trim())out.push(x);else if(object(x))for(const y of Object.values(x))if(typeof y==='string'&&y.trim())out.push(y)}if(h)out.push(h.replace(/[_-]+/g,' '));return[...new Set(out.map(text).filter(Boolean))]}
function classify(v,h){const id=idOf(v,h),blob=norm(`${h} ${namesOf(v,h).join(' ')}`);if(!id)return null;if(/country|countries|sovereign|nation|countryprofile/.test(blob))return'COUNTRY';if(/resource|commodity|mineral|hydrocarbon|fuel|ore|metal|petroleum|crude|natural gas/.test(blob))return'RESOURCE';if(('age' in v&&('stats' in v||'efficiency' in v||'personality' in v))||/minister|cabinet|official|candidate/.test(blob))return'MINISTER';return null}
function collect(nodes){const maps={COUNTRY:new Map(),RESOURCE:new Map(),MINISTER:new Map()};const visit=(v,h='')=>{if(!object(v))return;if(Array.isArray(v)){v.forEach((x,i)=>visit(x,String(i)));return}const type=classify(v,h),id=idOf(v,h);if(type&&id){const e=maps[type].get(id)||{id,names:new Set(),meta:v};namesOf(v,h).forEach(n=>e.names.add(n));maps[type].set(id,e)}for(const[k,x]of Object.entries(v))if(object(x))visit(x,k)};nodes.forEach(visit);return{COUNTRY:[...maps.COUNTRY.values()].map(x=>({...x,names:[...x.names]})),RESOURCE:[...maps.RESOURCE.values()].map(x=>({...x,names:[...x.names]})),MINISTER:[...maps.MINISTER.values()].map(x=>({...x,names:[...x.names]}))]}}
function configure(options={}){const ds=Array.isArray(options.datasets)?options.datasets.filter(object):[],all=collect(ds),mins=Array.isArray(options.ministers)?collect([{ministers_database:{all:options.ministers}}]).MINISTER:all.MINISTER;runtime={countries:all.COUNTRY,resources:all.RESOURCE,ministers:mins,vocabulary:options.vocabulary||{},datasets:ds,indexes:{country:new Map(),resource:new Map(),minister:new Map()}};for(const t of ['country','resource','minister'])for(const e of runtime[`${t}s`])for(const n of e.names){runtime.indexes[t].set(norm(n),e.id);runtime.indexes[t].set(compact(n),e.id)}return{version:VERSION,countries:runtime.countries.length,resources:runtime.resources.length,ministers:runtime.ministers.length}}
function vlist(lang,section){const g=runtime.vocabulary?.languages?.[lang]?.[section]||{},out=[];for(const[s,arr]of Object.entries(g))for(const a of Array.isArray(arr)?arr:[])out.push({semantic:s,raw:a,norm:norm(a),compact:compact(a)});return out.sort((a,b)=>b.norm.length-a.norm.length)}
function bestPhrase(q,list){const n=norm(q);let best=null;for(const p of list){if(!p.norm)continue;const hit=n===p.norm||` ${n} `.includes(` ${p.norm} `)||compact(n).includes(p.compact);if(hit){const score=n===p.norm?1:clamp(.74+p.norm.length/150);if(!best||score>best.score)best={...p,score}}}return best}
function question(q,lang){const h=bestPhrase(q,vlist(lang,'question'));if(h){const m={what:'IDENTIFY',who:'PERSON',which:'SELECT',where:'LOCATION',when:'TIME',why:'CAUSE',how:'METHOD',how_many:'COUNT',how_much:'QUANTITY',how_old:'AGE',should:'POLICY',can:'FEASIBILITY',will:'FORECAST'};return{type:m[h.semantic]||h.semantic,phrase:h.raw,confidence:h.score}}const n=norm(q),patterns=lang==='bn'?[[/^(কত|কয়|কয়)\s*(টি|টা|গুলো|গুলি)?/,'COUNT'],[/^(কত\s*(টুকু|টা|টি)?\s*(আছে|হবে|আসবে)?)/,'QUANTITY'],[/বয়স|বয়স/,'AGE'],[/^কেন\b|কারণ.*(কি|কী)/,'CAUSE'],[/^কোথায়\b|^কোথায়\b/,'LOCATION'],[/^কখন\b/,'TIME'],[/উচিত|সম্ভব|পারবে|পারা যাবে/,'POLICY'],[/ভবিষ্যতে|পূর্বাভাস|অনুমান|হবে\s*(কি|কী)/,'FORECAST'],[/^কীভাবে\b|^কিভাবে\b/,'METHOD'],[/^কে\b|^কারা\b/,'PERSON'],[/^কি\b|^কী\b|^কোন/,'IDENTIFY']]:[[/^how\s+many\b/,'COUNT'],[/^how\s+much\b/,'QUANTITY'],[/^how\s+old\b/,'AGE'],[/^why\b/,'CAUSE'],[/^where\b/,'LOCATION'],[/^when\b/,'TIME'],[/^should\b|^can\b|^could\b/,'POLICY'],[/^will\b/,'FORECAST'],[/^how\b/,'METHOD'],[/^who\b|^whom\b/,'PERSON'],[/^what\b|^which\b/,'IDENTIFY']];for(const[r,t]of patterns)if(r.test(n))return{type:t,phrase:null,confidence:.84};return{type:'UNKNOWN',phrase:null,confidence:.2}}
function property(q,lang,qt){const g=runtime.vocabulary?.languages?.[lang]?.attributes||{},hits=[];for(const[k,arr]of Object.entries(g))for(const a of Array.isArray(arr)?arr:[])if(norm(q).includes(norm(a)))hits.push({property:k,score:norm(a).length});if(qt==='AGE')hits.push({property:'age',score:999});if(qt==='COUNT'||qt==='QUANTITY')hits.push({property:'quantity',score:998});hits.sort((a,b)=>b.score-a.score);return hits[0]?.property||null}
function pronoun(q,lang){const ps=vlist(lang,'pronouns');for(const p of ps)if(p.semantic==='SELF'&&bestPhrase(q,[p]))return'SELF';for(const p of ps)if(p.semantic==='PLAYER'&&bestPhrase(q,[p]))return'PLAYER';return null}
function scoreEntity(q,name,lang){const qn=norm(q),nn=norm(name);if(!nn)return 0;if(qn===nn)return 1;if(qn.includes(nn)||compact(qn).includes(compact(nn)))return clamp(.84+nn.length/220);const a=new Set(nt(qn,lang)),b=nt(nn,lang),over=b.filter(x=>a.has(x)).length;return clamp(.32+.38*(over/Math.max(1,b.length))+.22*(over/Math.max(1,a.size)))}
function resolve(q,list,type,lang){const hits=[];for(const e of list)for(const n of e.names){const s=scoreEntity(q,n,lang);if(s>.43)hits.push({e,n,s})}for(const[k,v]of Object.entries(learned()))if(v.type===type&&norm(q).includes(k.slice(type.length+1)))hits.push({e:{id:v.id,names:[k.slice(type.length+1)]},n:k.slice(type.length+1),s:v.confidence});hits.sort((a,b)=>b.s-a.s||b.n.length-a.n.length);if(!hits.length)return{id:null,type,confidence:0,source:'UNRESOLVED',surface:null,candidates:[]};const b=hits[0],second=hits[1]?.s||0;if(b.s<.69)return{id:null,type,confidence:b.s,source:'UNRESOLVED',surface:b.n,candidates:hits.slice(0,5).map(x=>({id:x.e.id,surface:x.n,confidence:Number(x.s.toFixed(3))}))};if(second&&b.s-second<.055)return{id:null,type,confidence:b.s,source:'AMBIGUOUS',surface:b.n,candidates:hits.slice(0,5).map(x=>({id:x.e.id,surface:x.n,confidence:Number(x.s.toFixed(3))}))};return{id:b.e.id,type,confidence:b.s,source:'RUNTIME_DATASET',surface:b.n,candidates:[]}}
function asset(q,lang){const h=bestPhrase(q,vlist(lang,'assets'));return h?{id:h.semantic,type:'ASSET_CLASS',confidence:h.score,source:'LANGUAGE_VOCABULARY',surface:h.raw}:{id:null,type:'ASSET_CLASS',confidence:0,source:'UNRESOLVED',surface:null}}
function conditions(q,lang){const n=norm(q),out=[];const groups=lang==='bn'?[[/হ্রাস|কমে|ঘাটতি/,'DECREASE'],[/বৃদ্ধি|বেশি|বাড়ে|বাড়ে/,'INCREASE'],[/আমদানি|নির্ভর/,'DEPENDENCY']]:[[/decrease|decreasing|reduce|reduction|fall|shortage|deficit/,'DECREASE'],[/increase|increasing|rise|surplus/,'INCREASE'],[/import|dependent|dependency/,'DEPENDENCY']];for(const[r,op]of groups)if(r.test(n))out.push({variable:stem(n.match(r)?.[0]||'',lang),operator:op});return out}
function targets(q,lang){const n=norm(q),words=lang==='bn'?['বিদ্যুৎ','কৃষি','সার','শিল্প','সামরিক','পরিবহন','অর্থনীতি']:['electricity','power','agriculture','fertilizer','industry','military','transport','economy'];return words.filter(w=>n.includes(w)).map(w=>({type:'SECTOR',id:stem(w,lang),surface:w}))}
function output(q,lang,qt){return qt==='CAUSE'||qt==='METHOD'||qt==='IDENTIFY'?'explanation':qt==='LOCATION'?'locations':qt==='COUNT'?'count':qt==='QUANTITY'?'quantity':qt==='POLICY'?'recommendation':qt==='FORECAST'?'forecast':qt==='AGE'||qt==='PERSON'?'fact':bestPhrase(q,vlist(lang,'operators'))?.semantic==='list'?'list':'answer'}
function sources(p){const s=[];if(p.entities.minister?.id||p.subject.type==='MINISTER')s.push({authority:'MINISTER_REGISTRY',reason:'identity/property/runtime'});if(p.entities.country?.id)s.push({authority:'COUNTRY_REGISTRY',reason:'country state'});if(p.entities.resource?.id)s.push({authority:'RESOURCE_REGISTRY',reason:'resource state'});if(p.entities.resource?.id||p.entities.asset?.id)s.push({authority:'RESOURCE_ENGINE',reason:'location/production/reserve'});if(['COUNT','QUANTITY','LOCATE','READ_PROPERTY'].includes(p.operation))s.push({authority:'DETERMINISTIC_QUERY_ENGINE',reason:p.operation});if(['ANALYZE_CAUSE','CONSEQUENCE','EVALUATE_POLICY','FORECAST'].includes(p.operation))s.push({authority:'COGNITIVE_ENGINE',reason:p.operation});return s}
function parse(questionText,context={}){const surface=text(questionText),lang=bn.test(surface)?'bn':'en',q=norm(surface),qt=question(q,lang),a=asset(q,lang),country=resolve(q,runtime.countries,'COUNTRY',lang),resource=resolve(q,runtime.resources,'RESOURCE',lang),minister=resolve(q,runtime.ministers,'MINISTER',lang),self=pronoun(q,lang)==='SELF'||(/^(how old|who are you|what is your name|what is your age|what is your background|what are your skills)/i.test(q))||/^(তোমার|আপনার|তুমি|আপনি)\b/.test(q),prop=property(q,lang,qt.type);if(!country.id&&context.countryId)Object.assign(country,{id:String(context.countryId).toUpperCase(),confidence:1,source:'RUNTIME_CONTEXT'});if(!resource.id&&context.resourceId)Object.assign(resource,{id:String(context.resourceId).toUpperCase(),confidence:1,source:'RUNTIME_CONTEXT'});if(!minister.id&&context.ministerId)Object.assign(minister,{id:String(context.ministerId),confidence:1,source:'RUNTIME_CONTEXT'});
 let operation='IDENTIFY';if(qt.type==='COUNT')operation='COUNT';else if(qt.type==='QUANTITY')operation='QUANTITY';else if(qt.type==='LOCATION')operation='LOCATE';else if(qt.type==='CAUSE')operation='ANALYZE_CAUSE';else if(qt.type==='POLICY')operation='EVALUATE_POLICY';else if(qt.type==='FEASIBILITY')operation='CHECK_FEASIBILITY';else if(qt.type==='FORECAST')operation='FORECAST';else if(qt.type==='METHOD')operation='EXPLAIN_METHOD';else if(qt.type==='PERSON')operation='IDENTIFY_PERSON';else if(qt.type==='AGE')operation='READ_PROPERTY';else if(qt.type==='IDENTIFY'&&prop)operation='READ_PROPERTY';
 let intent='GENERAL_QUERY';if(self||minister.id)intent='MINISTER_IDENTITY';else if(resource.id||a.id)intent=a.id?'RESOURCE_MINING_DISCOVERY':'RESOURCE_QUERY';if(operation==='LOCATE')intent='LOCATION_QUERY';if(operation==='ANALYZE_CAUSE')intent='CAUSAL_ANALYSIS';if(operation==='EVALUATE_POLICY')intent='POLICY_EVALUATION';if(operation==='FORECAST')intent='FORECAST_QUERY';
 let subject={type:'WORLD',id:null,source:'UNRESOLVED'};if(self)subject={type:'MINISTER',kind:'SELF',id:minister.id||context.ministerId||null,source:minister.id?'RUNTIME_CONTEXT':'SELF_REFERENCE'};else if(minister.id)subject={type:'MINISTER',id:minister.id,source:'RUNTIME_DATASET'};else if(resource.id)subject={type:'RESOURCE',id:resource.id,source:'RUNTIME_DATASET'};else if(country.id)subject={type:'COUNTRY',id:country.id,source:'RUNTIME_DATASET'};
 const unresolved=[];if(a.id&&!country.id)unresolved.push('COUNTRY');if(a.id&&operation==='COUNT'&&!resource.id)unresolved.push('RESOURCE');if(operation==='LOCATE'&&!resource.id&&!a.id)unresolved.push('RESOURCE');if(self&&!minister.id)unresolved.push('MINISTER_CONTEXT');const amb=[];for(const x of [country,resource,minister])if(x.source==='AMBIGUOUS')amb.push(...(x.candidates||[]));const conf=clamp(Math.min(qt.confidence,country.id?country.confidence:1,resource.id?resource.confidence:1,a.id?a.confidence:1,minister.id?minister.confidence:1));const contract={contractVersion:'OMEGA-SEMANTIC-CONTRACT-2',language:lang,intent,operation,subject,entities:{country,resource,asset:a,minister},context:{countryId:country.id||context.countryId||null,ministerId:minister.id||context.ministerId||null,resourceId:resource.id||context.resourceId||null,timeHorizon:context.timeHorizon||null},conditions:conditions(q,lang),targets:targets(q,lang),requested_output:output(q,lang,qt.type),property:prop,question:{type:qt.type,phrase:qt.phrase,confidence:qt.confidence},surface,questionText:surface,unresolved,ambiguities:amb,confidence:Number(conf.toFixed(3)),executable:unresolved.length===0&&amb.length===0,sourcePlan:[]};contract.sourcePlan=sources(contract);return Object.freeze(contract)}
function explain(p){return{contractVersion:p.contractVersion,language:p.language,intent:p.intent,operation:p.operation,property:p.property,subject:p.subject,entities:p.entities,context:p.context,conditions:p.conditions,targets:p.targets,requested_output:p.requested_output,questionType:p.question?.type,unresolved:p.unresolved,ambiguities:p.ambiguities,sourcePlan:p.sourcePlan,confidence:p.confidence,executable:p.executable,runtimeCountryCount:runtime.countries.length,runtimeResourceCount:runtime.resources.length,runtimeMinisterCount:runtime.ministers.length}}
function execute(plan,context={}){if(!plan)return{ok:false,code:'MISSING_SEMANTIC_PLAN'};if(!plan.executable)return{ok:false,code:'UNRESOLVED_QUERY',plan};if(plan.operation==='READ_PROPERTY'&&plan.subject.type==='MINISTER'){const id=plan.subject.id||context.ministerId,m=runtime.ministers.find(x=>String(x.id).toLowerCase()===String(id||'').toLowerCase());if(!m)return{ok:false,code:'MINISTER_NOT_IN_SEMANTIC_RUNTIME',plan};const meta=m.meta||{},p=plan.property||'name',map={age:meta.age??meta.baseAge,name:meta.baseName||meta.name||meta.regionalName,background:meta.background||meta.careerBackground,gender:meta.gender,ideology:meta.ideology,role:meta.role,ministry:meta.ministry||meta.ministryId,country:meta.country||meta.countryId};const value=map[p]??meta[p]??null;return{ok:value!==null&&value!==undefined,operation:'READ_PROPERTY',property:p,value,source:'MINISTER_REGISTRY',plan}}return{ok:false,code:'SEMANTIC_ONLY_EXECUTION_DEFERRED',plan}}
function indexDatasetForQuery(query){const lang=bn.test(query)?'bn':'en',want=nt(query,lang),hits=[];const walk=(v,path=[])=>{if(!object(v))return;if(Array.isArray(v)){v.forEach((x,i)=>walk(x,path.concat(i)));return}const strings=Object.entries(v).filter(([,x])=>typeof x==='string').map(([k,x])=>`${k} ${x}`).join(' '),words=new Set(nt(strings,lang)),score=want.filter(w=>words.has(w)).length;if(score)hits.push({path,value:v,score});for(const[k,x]of Object.entries(v))if(object(x))walk(x,path.concat(k))};runtime.datasets.forEach(d=>walk(d));return hits.sort((a,b)=>b.score-a.score).slice(0,200)}
const api=Object.freeze({VERSION,configure,parse,execute,explain,learn,recall:learned,indexDatasetForQuery,normalize:norm});global.OfflineSemanticBrain=api;if(typeof module!=='undefined'&&module.exports)module.exports=api
})(typeof globalThis!=='undefined'?globalThis:window);
