/* OMEGA DEEP CORE v18.0.0
 * Deterministic repository navigation core.
 * Every execution arrow is explicit and observable:
 * QUESTION -> ENTITY -> ID -> OCCURRENCES -> DATASET -> RECORD -> RELATION -> TARGET -> FIELD -> OPERATION -> EVIDENCE.
 */
(function(global){'use strict';
const VERSION='18.0.0';
const A=v=>Array.isArray(v)?v:[];
const O=v=>v!==null&&typeof v==='object';
const S=v=>String(v==null?'':v).trim();
const U=v=>S(v).toUpperCase();
const N=v=>S(v).normalize('NFKC').toLowerCase().replace(/[?!,.:;"'“”‘’(){}[\]<>—–/\\]/g,' ').replace(/\s+/g,' ').trim();
const B=n=>{try{return global.process?.getBuiltinModule?.(n)||null}catch(_){return null}};
const M=()=>({fs:B('fs'),path:B('path'),crypto:B('crypto')});
const readJSON=f=>{try{const fs=M().fs;if(!fs||!fs.existsSync(f))return null;return JSON.parse(fs.readFileSync(f,'utf8'))}catch(_){return null}};
const root=()=>global.process?.cwd?.()||'.';
const rel=(f,r)=>{const p=M().path;return p?p.relative(r,f).replace(/\\/g,'/'):f};
function walkFiles(r){const{fs,path}=M();if(!fs||!path)return[];const blocked=new Set(['node_modules','.git','.github','.cache','dist','build','coverage']);const out=[];const go=d=>{let es=[];try{es=fs.readdirSync(d,{withFileTypes:true})}catch(_){return}for(const e of es){const f=path.join(d,e.name);if(e.isDirectory()){if(!blocked.has(e.name))go(f)}else if(e.isFile()&&/\.(json|geojson)$/i.test(e.name))out.push(f)}};go(r);return out.sort()}
function loadKnowledge(){if(global.OmegaOfflineSemanticKnowledge)return global.OmegaOfflineSemanticKnowledge;if(global.OmegaSemanticKnowledge)return global.OmegaSemanticKnowledge;const p=M().path;return p?readJSON(p.join(root(),'offline_semantic_knowledge.json'))||{}:{}}
function knowledgeEntities(k){const out=[];const walk=(v,hint='')=>{if(Array.isArray(v)){for(const x of v)walk(x,hint);return}if(!O(v))return;for(const[key,x]of Object.entries(v)){if(O(x)){let type=U(x.entityType||x.type||x.semanticType||x.semantic_type||'');if(!type&&/country/i.test(hint))type='COUNTRY';if(!type&&/resource|commodity/i.test(hint))type='RESOURCE';if(!type&&/asset/i.test(hint))type='ASSET_CLASS';if(type){const id=S(x.id||x.canonicalId||key);if(id)out.push({type,id:U(id),names:[x.name,x.lemma,...A(x.names),...A(x.aliases),...A(x.forms)].map(S).filter(Boolean)})}walk(x,key)}}};walk(k);const map=new Map;for(const e of out)map.set(e.type+'::'+e.id,e);return[...map.values()]}
function relationDefs(k){return A(k?.relations||k?.relationship_registry||k?.relationshipRegistry).filter(O).map(x=>({id:U(x.id),from:U(x.from||x.fromType||''),to:U(x.to||x.toType||''),...x})).filter(x=>x.id)}
function metadata(k){const out=[];for(const d of A(k?.data_finding?.dataset_capabilities)){if(!O(d)||!S(d.dataset))continue;for(const c of A(d.capabilities))out.push({dataset:S(d.dataset),capability:U(c),entityTypes:A(d.entityTypes).map(U),identityFields:A(d.identityFields).map(S),recordLocator:S(d.recordLocator)||null,recordKeyIsIdentity:d.recordKeyIsIdentity===true,fieldMappings:d.fieldMappings||{},authority:S(d.authority)||'EXPLICIT_METADATA'})}return out}
function metaFor(k,name){const key=N(name).replace(/\.json$/,'');const rows=metadata(k).filter(x=>N(x.dataset).replace(/\.json$/,'')===key);if(!rows.length)return null;const m={dataset:name,logicalDatasetId:rows[0].dataset,capabilities:[],entityTypes:[],identityFields:[],recordLocator:null,recordKeyIsIdentity:false,fieldMappings:{},authority:'EXPLICIT_METADATA'};for(const r of rows){for(const x of r.capabilities)if(!m.capabilities.includes(x))m.capabilities.push(x);for(const x of r.entityTypes)if(!m.entityTypes.includes(x))m.entityTypes.push(x);for(const x of r.identityFields)if(!m.identityFields.includes(x))m.identityFields.push(x);if(r.recordLocator)m.recordLocator=r.recordLocator;if(r.recordKeyIsIdentity)m.recordKeyIsIdentity=true;Object.assign(m.fieldMappings,r.fieldMappings||{})}return m}
function scalarFields(v,p='',out=[]){if(Array.isArray(v)){v.forEach((x,i)=>scalarFields(x,`${p}[${i}]`,out));return out}if(!O(v))return out;for(const[k,x]of Object.entries(v)){const pp=p?`${p}.${k}`:k;if(x===null||['string','number','boolean'].includes(typeof x))out.push({key:k,path:pp,value:x});else scalarFields(x,pp,out)}return out}
class Core{
 constructor(){this.root=root();this.k=loadKnowledge();this.catalog=new Map;this.datasets=new Map;this.records=[];this.bySig=new Map;this.ids=new Map;this.aliases=new Map;this.raw=new Map;this.refs=[];this.graph=new Map;this.rels=relationDefs(this.k);this.known=knowledgeEntities(this.k);this.initialized=false}
 reset(){this.catalog.clear();this.datasets.clear();this.records=[];this.bySig.clear();this.ids.clear();this.aliases.clear();this.raw.clear();this.refs=[];this.graph.clear();this.initialized=false}
 addMap(map,key,value){const n=N(key);if(!n)return;let a=map.get(n);if(!a)map.set(n,a=[]);a.push(value)}
 addIdentity(r,id,type,source,fieldPath){const u=U(id);if(!u)return;const t=U(type||'UNKNOWN');const key=t+'::'+u;let row=this.ids.get(key);if(!row)this.ids.set(key,row={id:u,type:t,refs:[]});const hit={signature:r.signature,dataset:r.dataset,physicalPath:r.physicalPath,locator:r.locator,fieldPath:fieldPath||null,source};if(!row.refs.some(x=>x.signature===hit.signature&&x.fieldPath===hit.fieldPath))row.refs.push(hit);r.identities.push({id:u,type:t,source,fieldPath:fieldPath||null})}
 infer(r){const meta=r.meta||{};const fields=new Set(meta.identityFields.map(N));const candidates=[];for(const f of r.fields){const key=N(f.key);if(fields.has(key)||fields.has(N(f.path))){for(const t of meta.entityTypes.length?meta.entityTypes:['UNKNOWN'])candidates.push({id:S(f.value),type:t,score:90,source:'METADATA_IDENTITY_FIELD',fieldPath:f.path})}if(typeof f.value==='string'){const id=U(f.value);for(const e of this.known)if(e.id===id)candidates.push({id:e.id,type:e.type,score:110,source:'KNOWLEDGE_ID',fieldPath:f.path});const knownAlias=this.resolveAlias(f.value);for(const e of knownAlias)candidates.push({id:e.id,type:e.type,score:95,source:'KNOWLEDGE_ALIAS',fieldPath:f.path})}}
 if(r.key&&!/^\d+$/.test(r.key)&&meta.recordKeyIsIdentity){for(const t of meta.entityTypes.length?meta.entityTypes:['UNKNOWN'])candidates.push({id:U(r.key),type:t,score:100,source:'METADATA_RECORD_KEY',fieldPath:null})}
 candidates.sort((a,b)=>b.score-a.score);r.identities=[];for(const c of candidates)if(c.id)this.addIdentity(r,c.id,c.type,c.source,c.fieldPath);r.entityType=candidates[0]?.type||meta.entityTypes[0]||'UNKNOWN';r.entityId=r.identities.find(x=>U(x.type)===U(r.entityType))?.id||r.identities[0]?.id||null}
 resolveAlias(value,type=null){const rows=this.aliases.get(N(value))||[];return rows.filter(x=>!type||U(x.type)===U(type))}
 indexAlias(id,type,name){if(!name)return;this.addMap(this.aliases,N(name),{id:U(id),type:U(type)})}
 collect(raw,e,meta){const local=[];const visit=(v,loc,key,parent,anc,depth)=>{if(!O(v)||depth>120)return;const r={dataset:e.datasetId,physicalPath:e.physicalPath,logicalDatasetId:e.logicalDatasetId,locator:loc,key:key==null?null:S(key),value:v,parent:parent?.signature||null,ancestry:anc.map(x=>x.signature),entityType:'UNKNOWN',entityId:null,identities:[],fields:scalarFields(v),meta:meta||null,fileEntry:e};r.signature=e.datasetId+'::'+loc;local.push(r);this.infer(r);for(const f of r.fields){this.raw.set(r.signature+'::'+f.path,{record:r,field:f});if(typeof f.value==='string'){this.indexAlias(f.value,'RAW',f.value);const k=N(f.key);if(meta?.identityFields?.map(N).includes(k))this.refs.push({from:r.signature,target:U(f.value),fieldPath:f.path})}}
 for(const f of r.identities)this.indexAlias(f.id,f.type,f.id);
 for(const[k,x]of Object.entries(v)){if(Array.isArray(x))x.forEach((item,i)=>O(item)&&visit(item,`${loc}.${k}[${i}]`,String(i),r,[...anc,r],depth+1));else if(O(x))visit(x,loc?`${loc}.${k}`:k,k,r,[...anc,r],depth+1)} };if(Array.isArray(raw))raw.forEach((x,i)=>O(x)&&visit(x,`[${i}]`,String(i),null,[],1));else if(O(raw)){for(const[k,x]of Object.entries(raw))if(O(x))visit(x,k,k,null,[],1);if(!local.length)visit({root:raw},'root','root',null,[],1)}else visit({value:raw},'root','root',null,[],1);for(const r of local){this.records.push(r);this.bySig.set(r.signature,r);for(const i of r.identities){const key=i.type+'::'+i.id;let a=this.graph.get(key);if(!a)this.graph.set(key,a=[]);if(!a.includes(r.signature))a.push(r.signature)}}}
 register(file){const{fs,path}=M();if(!fs)return null;let st=null,raw=null,status='PARSE_OK',error=null,text='';try{st=fs.statSync(file);text=fs.readFileSync(file,'utf8');raw=JSON.parse(text)}catch(e){status='PARSE_ERROR';error=e.message}const name=path.basename(file),m=metaFor(this.k,name),e={datasetId:N(name),name,physicalPath:rel(file,this.root),absolutePath:file,bytes:st?.size||0,modifiedAt:st?new Date(st.mtimeMs).toISOString():null,parseStatus:status,parseError:error,logicalDatasetId:m?.logicalDatasetId||name,capabilities:m?.capabilities||[],entityTypes:m?.entityTypes||[],identityFields:m?.identityFields||[],recordLocator:m?.recordLocator||null,recordKeyIsIdentity:m?.recordKeyIsIdentity===true,fieldMappings:m?.fieldMappings||{},authority:m?.authority||'PHYSICAL_DISCOVERY'};this.catalog.set(e.datasetId,e);if(raw!==null){this.datasets.set(e.datasetId,{entry:e,raw});this.collect(raw,e,m)}return e}
 build(inputs=[]){this.reset();const fs=M().fs;for(const f of(fs?walkFiles(this.root):[]))this.register(f);for(const x of A(inputs))this.registerInput(x);this.initialized=true;return this.stats()}
 registerInput(x){const name='runtime_input_'+this.datasets.size,e={datasetId:name,name,physicalPath:null,absolutePath:null,bytes:null,modifiedAt:null,parseStatus:'RUNTIME_INPUT',logicalDatasetId:name,capabilities:[],entityTypes:[],identityFields:[],recordLocator:null,recordKeyIsIdentity:false,fieldMappings:{},authority:'RUNTIME_INPUT'};this.catalog.set(name,e);this.datasets.set(name,{entry:e,raw:x});this.collect(x,e,null)}
 ensure(){if(!this.initialized)this.build();return true}
 stats(){return{files:this.catalog.size,parsed:[...this.catalog.values()].filter(x=>x.parseStatus==='PARSE_OK').length,parseErrors:[...this.catalog.values()].filter(x=>x.parseStatus!=='PARSE_OK').length,records:this.records.length,identityKeys:this.ids.size,rawOccurrences:this.raw.size}}
 resolveEntity(surface,type=null){this.ensure();const s=S(surface),u=U(surface);const exact=this.known.filter(e=>(!type||U(e.type)===U(type))&&(U(e.id)===u||e.names.some(n=>N(n)===N(s))));if(exact.length)return{status:exact.length===1?'RESOLVED':'AMBIGUOUS_IDENTITY',candidates:exact};const hits=this.resolveAlias(s,type);if(hits.length){const uniq=[...new Map(hits.map(x=>[x.type+'::'+x.id,x])).values()];return{status:uniq.length===1?'RESOLVED':'AMBIGUOUS_IDENTITY',candidates:uniq}}const rawIds=[...this.ids.values()].filter(x=>x.id===u&&(!type||U(x.type)===U(type)));if(rawIds.length)return{status:rawIds.length===1?'RESOLVED':'AMBIGUOUS_IDENTITY',candidates:rawIds.map(x=>({id:x.id,type:x.type,names:[],refs:x.refs}))};return{status:'IDENTITY_NOT_FOUND',candidates:[]}}
 lookupId(id){this.ensure();const q=U(id);const exact=[...this.ids.values()].filter(x=>x.id===q);const occ=[];for(const r of exact)for(const ref of r.refs)occ.push({...ref,value:q,entityType:r.type,entityId:r.id,kind:'IDENTITY'});const raw=[];for(const [k,v] of this.raw){const f=v.field;if(N(f.value)===N(id))raw.push({dataset:v.record.dataset,physicalPath:v.record.physicalPath,recordLocator:v.record.locator,fieldPath:f.path,entityType:v.record.entityType,entityId:v.record.entityId,value:f.value,kind:'RAW_VALUE'});if(N(f.key)===N(id))raw.push({dataset:v.record.dataset,physicalPath:v.record.physicalPath,recordLocator:v.record.locator,fieldPath:f.path,entityType:v.record.entityType,entityId:v.record.entityId,value:f.key,kind:'FIELD_NAME'})}const merged=[...occ,...raw];const uniq=[...new Map(merged.map(x=>[x.dataset+'::'+x.recordLocator+'::'+x.fieldPath+'::'+x.kind,x])).values()];return{status:uniq.length?'RESOLVED':'IDENTITY_NOT_FOUND',id:q,count:uniq.length,matches:uniq.slice(0,5000)}}
 search(q,opts={}){this.ensure();const s=N(q);let out=[];const needle=U(q);for(const r of this.records)for(const f of r.fields){if(N(f.value)===s||U(f.value)===needle||N(f.key)===s){out.push({dataset:r.dataset,physicalPath:r.physicalPath,recordLocator:r.locator,fieldPath:f.path,value:f.value,field:f.key,entityType:r.entityType,entityId:r.entityId})}}if(!out.length){const parts=s.split(' ').filter(Boolean);for(const r of this.records)for(const f of r.fields){const hay=N(f.value);if(parts.every(p=>hay.includes(p)))out.push({dataset:r.dataset,physicalPath:r.physicalPath,recordLocator:r.locator,fieldPath:f.path,value:f.value,field:f.key,entityType:r.entityType,entityId:r.entityId})}}if(opts.dataset)out=out.filter(x=>N(x.dataset)===N(opts.dataset));if(opts.type)out=out.filter(x=>!x.entityType||U(x.entityType)===U(opts.type));const uniq=[...new Map(out.map(x=>[x.dataset+'::'+x.recordLocator+'::'+x.fieldPath,x])).values()];return{status:uniq.length?'RESOLVED':'NOT_FOUND',query:S(q),count:uniq.length,matches:uniq.slice(0,Number(opts.limit||2000))}}
 resolveFromIR(ir,ctx){const raw=S(ir?.raw||ir?.surface||'');const specs=[['COUNTRY',ir?.entities?.country],['RESOURCE',ir?.entities?.resource],['ASSET_CLASS',ir?.entities?.assetClass||{id:ir?.assetClass}]];const out={};for(const[type,spec]of specs){if(spec?.id){out[type]=this.resolveEntity(spec.id,type);if(out[type].status==='RESOLVED')continue}const surfaces=[spec?.surface,spec?.name,spec?.alias,spec?.label,...A(spec?.aliases)];for(const x of surfaces){if(!x)continue;const hit=this.resolveEntity(x,type);if(hit.status==='RESOLVED'||hit.status==='AMBIGUOUS_IDENTITY'){out[type]=hit;break}}if(!out[type]&&raw){const hit=this.known.filter(e=>e.type===type&&([e.id,...e.names].some(n=>N(raw).includes(N(n)))));const uniq=[...new Map(hit.map(x=>[x.type+'::'+x.id,x])).values()];if(uniq.length===1)out[type]={status:'RESOLVED',candidates:uniq};else if(uniq.length>1)out[type]={status:'AMBIGUOUS_IDENTITY',candidates:uniq}}
 }return out}
 recordScope(anchorRefs){const keep=new Set(anchorRefs.map(x=>x.signature));const q=[...keep];while(q.length){const s=q.shift();for(const r of this.records){if(r.parent===s||r.ancestry.includes(s))if(!keep.has(r.signature)){keep.add(r.signature);q.push(r.signature)}}}for(const ref of this.refs){if(keep.has(ref.from)){const targets=[...this.ids.values()].filter(x=>x.id===ref.target).flatMap(x=>x.refs);for(const t of targets)if(!keep.has(t.signature)){keep.add(t.signature);q.push(t.signature)}}}return[...keep].map(s=>this.bySig.get(s)).filter(Boolean)}
 related(a,b){if(!a||!b)return false;const bs=new Set(b.map(x=>x.signature));for(const r of a){if(bs.has(r.signature))return true;for(const ref of this.refs.filter(x=>x.from===r.signature)){const hits=[...this.ids.values()].filter(x=>x.id===ref.target).flatMap(x=>x.refs);if(hits.some(h=>bs.has(h.signature)))return true}}return false}
 targetRecords(ir,scope){const assetId=U(ir?.entities?.assetClass?.id||ir?.assetClass||'');if(!assetId)return scope;const exact=scope.filter(r=>U(r.entityType)===assetId);if(exact.length)return exact;const aliasSet=this.known.filter(e=>U(e.type)==='ASSET_CLASS'&&U(e.id)===assetId).flatMap(e=>e.names).map(N);return scope.filter(r=>r.fields.some(f=>aliasSet.includes(N(f.value))||aliasSet.includes(N(f.key))))}
 resolveField(ir,rows){const prop=U(ir?.property||'');if(!prop)return null;for(const r of rows){const fm=r.meta?.fieldMappings||{};for(const [cap,map] of Object.entries(fm)){if(U(cap)!==prop)continue;const candidates=typeof map==='string'?[map]:A(map);for(const fieldPath of candidates){const f=r.fields.find(x=>N(x.path)===N(fieldPath)||N(x.key)===N(fieldPath));if(f)return{record:r,field:f,source:'METADATA_FIELD_MAPPING',property:prop}}}}const names=this.known.filter(e=>U(e.id)===prop).flatMap(e=>e.names).map(N);for(const r of rows)for(const f of r.fields)if(names.includes(N(f.key))||names.includes(N(f.path)))return{record:r,field:f,source:'KNOWLEDGE_PROPERTY_NAME',property:prop};return null}
 operation(ir,rows){const op=U(ir?.operation||'LOOKUP');if(op==='COUNT')return{status:rows.length?'VERIFIED_FACT':'RECORD_NOT_FOUND',value:[...new Set(rows.map(r=>r.entityId||r.signature))].length,evidence:rows.slice(0,500),fieldPath:null};if(['LIST','IDENTIFY','LOCATE'].includes(op))return{status:rows.length?'VERIFIED_FACT':'RECORD_NOT_FOUND',value:rows.slice(0,500).map(r=>({dataset:r.dataset,physicalPath:r.physicalPath,recordLocator:r.locator,entityType:r.entityType,entityId:r.entityId,key:r.key,fields:r.fields})),evidence:rows.slice(0,500),fieldPath:null};const f=this.resolveField(ir,rows);if(!f)return{status:'FIELD_NOT_FOUND',value:null,evidence:[]};const values=rows.map(r=>r.fields.find(x=>N(x.path)===N(f.field.path))).filter(x=>x&&typeof x.value==='number').map(x=>x.value);if(!values.length)return{status:'FIELD_NOT_FOUND',value:null,evidence:[]};if(op==='SUM'||op==='TOTAL')return{status:'VERIFIED_FACT',value:values.reduce((a,b)=>a+b,0),evidence:[f.record],fieldPath:f.field.path};if(op==='AVERAGE')return{status:'VERIFIED_FACT',value:values.reduce((a,b)=>a+b,0)/values.length,evidence:[f.record],fieldPath:f.field.path};if(op==='MIN')return{status:'VERIFIED_FACT',value:Math.min(...values),evidence:[f.record],fieldPath:f.field.path};if(op==='MAX')return{status:'VERIFIED_FACT',value:Math.max(...values),evidence:[f.record],fieldPath:f.field.path};if(op==='GET'||op==='QUANTITY'){const uniq=[...new Set(values)];return uniq.length===1?{status:'VERIFIED_FACT',value:uniq[0],evidence:[f.record],fieldPath:f.field.path}:{status:'SOURCE_CONFLICT',value:null,evidence:rows}}return{status:'OPERATION_UNSUPPORTED',value:null,evidence:[]}}
 execute(ir,inputs=[],language='en',ctx={}){this.ensure();const stage=[];const resolved=this.resolveFromIR(ir,ctx);stage.push({arrow:'QUESTION -> ENTITY',status:'RESOLVED',entities:resolved});const country=resolved.COUNTRY?.candidates?.[0]||null,resource=resolved.RESOURCE?.candidates?.[0]||null,asset=resolved.ASSET_CLASS?.candidates?.[0]||null;if(resolved.COUNTRY?.status==='AMBIGUOUS_IDENTITY'||resolved.RESOURCE?.status==='AMBIGUOUS_IDENTITY'||resolved.ASSET_CLASS?.status==='AMBIGUOUS_IDENTITY')return this.fail('AMBIGUOUS_IDENTITY',stage,resolved);if(ir?.entities?.country?.id&&!country)return this.fail('IDENTITY_NOT_FOUND',stage,resolved);if(ir?.entities?.resource?.id&&!resource)return this.fail('IDENTITY_NOT_FOUND',stage,resolved);const anchors=[];for(const x of [country,resource,asset])if(x?.refs)anchors.push(...x.refs);else if(x?.id){const q=this.lookupId(x.id);anchors.push(...q.matches.map(m=>({signature:m.dataset+'::'+m.recordLocator,locator:m.recordLocator,dataset:m.dataset,physicalPath:m.physicalPath})))}if(!anchors.length)return this.fail('IDENTITY_NOT_FOUND',stage,resolved);stage.push({arrow:'ENTITY -> CANONICAL ID',status:'RESOLVED',countryId:country?.id||null,resourceId:resource?.id||null,assetClassId:asset?.id||null});const scope=this.recordScope(anchors);stage.push({arrow:'CANONICAL ID -> RAW OCCURRENCES',status:scope.length?'RESOLVED':'RECORD_NOT_FOUND',count:scope.length});if(!scope.length)return this.fail('RECORD_NOT_FOUND',stage,resolved);let rows=this.targetRecords(ir,scope);if(country&&resource){const cscope=this.recordScope(country.refs||[]),rscope=this.recordScope(resource.refs||[]);rows=rows.filter(r=>cscope.includes(r)||rscope.includes(r)||this.related([r],cscope)||this.related([r],rscope))}stage.push({arrow:'RAW OCCURRENCES -> DATASET/RECORD',status:rows.length?'RESOLVED':'RECORD_NOT_FOUND',count:rows.length});if(!rows.length)return this.fail('RECORD_NOT_FOUND',stage,resolved);const out=this.operation(ir,rows);stage.push({arrow:'RECORD -> FIELD',status:out.fieldPath?'RESOLVED':(U(ir?.operation)==='COUNT'||['LIST','IDENTIFY','LOCATE'].includes(U(ir?.operation))?'NOT_REQUIRED':'FIELD_NOT_FOUND'),fieldPath:out.fieldPath||null});stage.push({arrow:'FIELD -> OPERATION',status:out.status,operation:U(ir?.operation)});if(out.status!=='VERIFIED_FACT')return{ok:false,status:out.status,value:out.value,evidence:[],trace:stage,dataAccess:this.access()};const evidence=out.evidence.map((r,i)=>({dataset:r.dataset,physicalPath:r.physicalPath,logicalDatasetId:r.logicalDatasetId,recordLocator:r.locator,fieldPath:out.fieldPath||null,canonicalEntityId:r.entityId,entityType:r.entityType,rawValue:out.fieldPath?r.fields.find(f=>N(f.path)===N(out.fieldPath))?.value:r.value,operation:U(ir?.operation),relationPath:r.ancestry,authority:r.fileEntry?.authority||'PHYSICAL_DISCOVERY',source:'DEEP_CORE_REPOSITORY_REGISTRY',index:i+1}));return{ok:true,status:'VERIFIED_FACT',value:out.value,evidence,trace:stage,dataAccess:this.access()}}
 fail(status,trace,resolved){trace.push({arrow:'VALIDATION',status});return{ok:false,status,value:null,evidence:[],trace,identityResolution:resolved,dataAccess:this.access()}}
 access(){const s=this.stats();return{repositoryIndexed:this.initialized,registryVersion:VERSION,physicalFiles:s.files,parsedFiles:s.parsed,recordsIndexed:s.records,identityKeys:s.identityKeys,rawOccurrences:s.rawOccurrences}}
 executionPlan(ir){this.ensure();return{version:VERSION,arrows:['QUESTION -> ENTITY','ENTITY -> CANONICAL ID','CANONICAL ID -> RAW OCCURRENCES','RAW OCCURRENCES -> DATASET/RECORD','DATASET/RECORD -> RELATION/SCOPE','RELATION/SCOPE -> TARGET RECORD','TARGET RECORD -> FIELD','FIELD -> OPERATION','OPERATION -> VALIDATION -> EVIDENCE'],identity:{country:ir?.entities?.country?.id||null,resource:ir?.entities?.resource?.id||null,assetClass:ir?.entities?.assetClass?.id||null},catalog:[...this.catalog.values()].map(x=>({dataset:x.name,physicalPath:x.physicalPath,capabilities:x.capabilities,entityTypes:x.entityTypes,identityFields:x.identityFields,authority:x.authority}))}}
 schema(d){this.ensure();const e=this.catalog.get(N(d));return e?{dataset:e.name,physicalPath:e.physicalPath,capabilities:e.capabilities,entityTypes:e.entityTypes,identityFields:e.identityFields,recordLocator:e.recordLocator,fieldMappings:e.fieldMappings,authority:e.authority}:null}
 diagnostics(){this.ensure();return{version:VERSION,initialized:this.initialized,root:this.root,stats:this.stats(),catalog:[...this.catalog.values()],indexes:{identityKeys:this.ids.size,aliases:this.aliases.size,rawValues:this.raw.size,relations:this.refs.length}}}
}
let C=null;const core=()=>C||(C=new Core);const API={VERSION,initializeRepository:()=>core().build(),ensureRepository:()=>core().ensure(),refresh:()=>core().build(),execute:(ir,i,l,c)=>core().execute(ir,i,l,c),lookupId:id=>core().lookupId(id),search:(q,o)=>core().search(q,o),resolve:s=>core().resolveEntity(s?.id||s?.surface||s,s?.type||null),buildExecutionPlan:ir=>core().executionPlan(ir),buildEvidenceLedger:r=>({version:VERSION,status:r?.status||'UNKNOWN',count:A(r?.evidence).length,chain:A(r?.evidence).map((e,i)=>({...e,step:i+1}))}),catalog:()=>{core().ensure();return[...core().catalog.values()]},schema:d=>core().schema(d),diagnostics:()=>core().diagnostics(),index:()=>core().diagnostics(),traverse:id=>core().lookupId(id),searchRegistry:(q,o)=>core().search(q,o)};global.OfflineQueryEngine=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:window);
