/* OMEGA CANONICAL IDENTITY BRIDGE v5.0.0-PRODUCTION
 * Single runtime identity spine for countries, cities, and cross-dataset links.
 * Source-of-truth remains repository JSON. No country/city facts are hardcoded.
 * Works in browser and Node server environments.
 */
(function(g){
'use strict';
if(g.OmegaCountrySemanticBridge?.VERSION==='5.0.0-PRODUCTION')return;
const VERSION='5.0.0-PRODUCTION';
const S=v=>String(v==null?'':v).trim();
const N=v=>S(v).normalize('NFKC').replace(/[?!,.:;'"“”‘’(){}[\]<>]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
const O=v=>v&&typeof v==='object'&&!Array.isArray(v);
const A=v=>Array.isArray(v)?v:[];
const isNode=typeof process!=='undefined'&&!!process?.versions?.node&&typeof window==='undefined';
const state={ready:false,error:null,loadedAt:null,promise:null,countries:new Map(),countryAliases:new Map(),cities:new Map(),cityAliases:new Map(),datasets:new Map(),sourceCounts:{}};
function rows(r){if(Array.isArray(r))return r;if(Array.isArray(r?.countries))return r.countries;if(Array.isArray(r?.data))return r.data;if(O(r))return Object.entries(r).map(([k,v])=>O(v)?({...v,__sourceKey:k}):({id:k,name:v,__sourceKey:k}));return[];}
function idOf(x,key=''){const i=O(x?.identity)?x.identity:(x||{});return S(i.iso2||i.countryCode||i.country_code||i.code||i.id||i.canonicalId||key).toUpperCase();}
function nameOf(x,key=''){const i=O(x?.identity)?x.identity:(x||{});return S(i.name||i.countryName||i.country_name||i.shortName||i.displayName||i.officialName||x?.name||key);}
function addCountryAlias(id,v){const n=N(v),canonical=S(id).toUpperCase();if(!n||!canonical)return;const set=state.countryAliases.get(n)||new Set();set.add(canonical);state.countryAliases.set(n,set);}
function registerCountry(x,key='',source=''){if(!O(x))return null;const id=idOf(x,key),name=nameOf(x,key);if(!id||!name)return null;const old=state.countries.get(id)||{id,names:[],officialName:'',sources:[],cities:[],raw:null,datasets:Object.create(null)};old.names=[...new Set([...old.names,name,S(x.officialName),S(x.shortName),S(x.displayName),S(x.nativeName)].filter(Boolean))];if(S(x.officialName))old.officialName=S(x.officialName);old.sources=[...new Set([...old.sources,source].filter(Boolean))];old.raw=old.raw||x;if(source)old.datasets[source]=x;state.countries.set(id,old);for(const n of old.names)addCountryAlias(id,n);for(const k of ['iso2','iso3','isoCode','countryCode','country_code','code','id','canonicalId'])if(S(x?.[k]))addCountryAlias(id,x[k]);return old;}
function ingestCountries(r){const a=rows(r);state.sourceCounts.countries=a.length;for(const x of a)registerCountry(x,x?.__sourceKey||'','countries.json');}
function cityObject(v,role=''){if(!O(v)||!S(v.name))return null;const city={...v,name:S(v.name),role:S(v.role||role||v.type||'').toUpperCase()};city.countryId=S(v.countryId||v.countryCode||v.iso2||v.iso3||'').toUpperCase();return city;}
function canonicalCityId(countryId,name){return`${S(countryId).toUpperCase()}:${N(name).replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')}`;}
function addCityAlias(id,v){const n=N(v);if(!n||!id)return;const set=state.cityAliases.get(n)||new Set();set.add(id);state.cityAliases.set(n,set);}
function ingestCities(r){const a=rows(r);state.sourceCounts.cities=a.length;for(const x of a){const countryName=nameOf(x,x?.__sourceKey||'');let countryId=S(x?.countryId||x?.countryCode||x?.iso2||x?.iso3||'').toUpperCase();if(!countryId){const ids=state.countryAliases.get(N(countryName));countryId=ids instanceof Set&&ids.size===1?[...ids][0]:(typeof ids==='string'?ids:'');}const country=countryId?registerCountry({id:countryId,name:countryName},countryId,'cities.json'):null;if(!country)continue;const collected=[];const pushOne=(v,role='')=>{const c=cityObject(v,role);if(c)collected.push(c);};const push=(v,role='')=>{for(const z of A(v))pushOne(z,role);};pushOne(x.capital,'CAPITAL');push(x.economic,'ECONOMIC');push(x.military,'MILITARY');push(x.secret,'SECRET');push(x.cities,'CITY');const merged=state.cities.get(countryId)||new Map();for(const city of collected){const cityId=S(city.id||city.cityId||city.canonicalId)||canonicalCityId(countryId,city.name);const record={...city,id:cityId,canonicalId:cityId,countryId};const prior=merged.get(cityId);merged.set(cityId,prior?{...prior,...record,name:prior.name||record.name}:record);addCityAlias(cityId,city.name);addCityAlias(cityId,cityId);}state.cities.set(countryId,merged);country.cities=[...merged.values()].map(x=>({...x}));}}
function ingestRelations(r){const root=r?.RELATION_GENERATION_ENGINE?.srie_v2_asymmetrical_salience||r?.srie_v2_asymmetrical_salience||{};let count=0;for(const[k,v]of Object.entries(root)){if(!O(v))continue;registerCountry({id:S(v.country_code||k).toUpperCase(),name:S(v.country_name||k)},k,'relation_generation_engine.json');count++;}state.sourceCounts.relations=count;}
function ingestResourceDataset(r,source){if(!O(r))return;state.datasets.set(source,r);const walk=v=>{if(!O(v))return;if(Array.isArray(v)){for(const x of v)walk(x);return;}const name=S(v.countryName||v.country_name||v.country||v.country_name_en||'');if(name){const ids=state.countryAliases.get(N(name));if(ids instanceof Set&&ids.size===1)addCountryAlias([...ids][0],name);else if(typeof ids==='string'&&ids)addCountryAlias(ids,name);}for(const x of Object.values(v))if(O(x)||Array.isArray(x))walk(x);};walk(r);state.sourceCounts[source]=1;}
async function loadJson(p,optional=false){try{if(isNode){const fs=await import('node:fs/promises');const base=S(process.env.OMEGA_ROOT||process.cwd());const text=await fs.readFile(`${base}/${p}`,'utf8');return JSON.parse(text);}const r=await fetch(p,{cache:'no-store'});if(!r.ok){if(optional)return null;throw Error(`${p}: HTTP ${r.status}`);}return await r.json();}catch(e){if(optional)return null;throw e;}}
async function init(){if(state.promise)return state.promise;state.promise=(async()=>{state.ready=false;state.error=null;try{const files=[['countries.json',false],['cities.json',false],['resources.json',false],['resources_2.json',true],['resource_ontology.json',true],['relation_generation_engine.json',true],['economy.json',true],['population.json',true]];const loaded=await Promise.all(files.map(([p,o])=>loadJson(p,o)));state.datasets.clear();state.countries.clear();state.countryAliases.clear();state.cities.clear();state.cityAliases.clear();state.sourceCounts={};for(let i=0;i<files.length;i++)if(loaded[i])state.datasets.set(files[i][0],loaded[i]);ingestCountries(loaded[0]);if(loaded[5])ingestRelations(loaded[5]);ingestCities(loaded[1]);ingestResourceDataset(loaded[2],'resources.json');if(loaded[3])ingestResourceDataset(loaded[3],'resources_2.json');if(loaded[4])ingestResourceDataset(loaded[4],'resource_ontology.json');if(loaded[6])ingestResourceDataset(loaded[6],'economy.json');if(loaded[7])ingestResourceDataset(loaded[7],'population.json');state.loadedAt=Date.now();state.ready=true;g.dispatchEvent?.(new(g.CustomEvent||class{constructor(t,i){this.type=t;this.detail=i?.detail}})('OMEGA_CANONICAL_IDENTITY_READY',{detail:diagnostics()}));installRuntimeBridges();return true;}catch(e){state.error=String(e);state.ready=false;console.error('[OMEGA Canonical Identity]',e);return false;}})();return state.promise;}
function rankMatches(text,map,contextCountryId=null){const q=N(text);if(!q)return[];const hits=[];for(const[alias,ids]of map.entries()){if(!alias||alias.length<2)continue;const exact=q===alias,boundary=(` ${q} `).includes(` ${alias} `)||q.startsWith(alias+' ')||q.endsWith(' '+alias);if(!exact&&!boundary)continue;const candidates=ids instanceof Set?[...ids]:[ids];for(const id of candidates){const sameContext=contextCountryId&&S(id).split(':')[0]===S(contextCountryId).toUpperCase();const base=exact?1:Math.min(.995,.76+alias.length/Math.max(100,q.length*2));hits.push({id,alias,score:Math.min(1,base+(sameContext?.004:0))});}}hits.sort((a,b)=>b.score-a.score||b.alias.length-a.alias.length||String(a.id).localeCompare(String(b.id)));return hits;}
function resolveCountry(q){const hits=rankMatches(q,state.countryAliases);if(!hits.length)return null;const best=hits[0],second=hits[1],ambiguous=second&&best.alias===second.alias&&best.score===second.score&&best.id!==second.id;if(ambiguous)return{id:null,type:'COUNTRY',confidence:best.score,surface:best.alias,source:'AMBIGUOUS_COUNTRY_IDENTITY',candidates:hits.filter(x=>x.alias===best.alias).map(x=>({id:x.id,surface:x.alias,confidence:x.score})),raw:null};const id=S(best.id).toUpperCase();return{id,type:'COUNTRY',confidence:best.score,surface:best.alias,source:'OMEGA_CANONICAL_COUNTRY_REGISTRY',raw:state.countries.get(id)||null};}
function resolveCity(q,contextCountryId=null){const hits=rankMatches(q,state.cityAliases,contextCountryId);if(!hits.length)return null;const best=hits[0],second=hits[1],sameAlias=second&&best.alias===second.alias;if(sameAlias&&best.id!==second.id&&best.score===second.score)return{id:null,type:'CITY',confidence:best.score,surface:best.alias,source:'AMBIGUOUS_CITY_IDENTITY',candidates:hits.filter(x=>x.alias===best.alias).map(x=>({id:x.id,confidence:x.score})),raw:null};const[countryId]=S(best.id).split(':');const city=state.cities.get(countryId)?.get(best.id)||null;return{id:best.id,type:'CITY',confidence:best.score,surface:best.alias,countryId,source:'OMEGA_CANONICAL_CITY_REGISTRY',raw:city};}
function resolve(q){const country=resolveCountry(q),city=resolveCity(q,country?.id||null);if(city?.id&&(!country?.id||city.confidence>country.confidence))return city;return country;}
function allCities(countryId){const id=S(countryId).toUpperCase();return[...(state.cities.get(id)?.values()||[])].map(x=>({...x}));}
function countryBrief(q){const h=resolveCountry(q);if(!h?.id)return null;const c=state.countries.get(h.id),cities=allCities(h.id);return{countryId:h.id,countryName:c?.names?.[0]||h.surface,realCountryName:c?.officialName||c?.names?.[0]||h.surface,cities,cityCount:cities.length,sources:c?.sources||[],datasets:Object.keys(c?.datasets||{})};}
function getDatasetRecord(source,countryId,surface=''){const root=state.datasets.get(source);if(!root)return null;const canonical=S(countryId).toUpperCase(),candidateNames=[N(surface),S(surface).toUpperCase(),N(String(surface).replace(/_/g,' '))].filter(Boolean);if(O(root))for(const key of [canonical,...candidateNames])if(root[key]!==undefined)return root[key];let found=null;const walk=v=>{if(found||!O(v))return;if(Array.isArray(v)){for(const x of v)walk(x);return;}const id=S(v.countryCode||v.country_code||v.iso2||v.iso3||v.code||v.id||'').toUpperCase();const name=N(v.countryName||v.country_name||v.name||v.officialName||'');if((id&&canonical&&id===canonical)||(name&&candidateNames.includes(name))){found=v;return;}for(const x of Object.values(v))if(O(x)||Array.isArray(x))walk(x);};walk(root);return found;}
function canonicalizePlan(question,plan){if(!plan||typeof plan!=='object')return plan;const semantic=plan.semantic&&typeof plan.semantic==='object'?{...plan.semantic}:{};const country=resolveCountry(question),city=resolveCity(question,country?.id||null);let entityCountry=country?.id?country:null;if(city?.id&&!entityCountry){const cityCountry=state.countries.get(city.countryId);entityCountry={id:city.countryId,type:'COUNTRY',confidence:city.confidence,source:'CITY_PARENT_COUNTRY',surface:cityCountry?.names?.[0]||city.countryId,raw:cityCountry||null};}if(entityCountry){semantic.entities={...(semantic.entities||{}),country:entityCountry};semantic.unresolved=A(semantic.unresolved).filter(x=>x!=='COUNTRY');semantic.confidence=Math.max(Number(semantic.confidence||0),entityCountry.confidence);}if(city?.id){semantic.entities={...(semantic.entities||{}),city};semantic.unresolved=A(semantic.unresolved).filter(x=>x!=='CITY');}if(entityCountry||city?.id){semantic.executable=semantic.operation!=='UNKNOWN'&&semantic.unresolved.length===0;semantic.identityAuthority='OMEGA_CANONICAL_IDENTITY_BRIDGE';const out={...plan,semantic,entities:semantic.entities};if(entityCountry)out.countryId=entityCountry.id;if(city?.id)out.cityId=city.id;if(entityCountry)out.countryBrief=countryBrief(entityCountry.surface);return out;}return plan;}
function installRuntimeBridges(){const rt=g.OmegaProductionSemanticRuntime;if(rt&&!rt.__canonicalIdentityV500){const oldParse=typeof rt.parse==='function'?rt.parse.bind(rt):null,oldExplain=typeof rt.explain==='function'?rt.explain.bind(rt):null,oldPlan=typeof rt.buildAnswerPlan==='function'?rt.buildAnswerPlan.bind(rt):null;if(oldParse)rt.parse=function(q,ctx={}){const base=oldParse(q,ctx);return canonicalizePlan(q,{semantic:base})?.semantic||base;};if(oldExplain)rt.explain=function(q,ctx={}){const base=oldExplain(q,ctx);return canonicalizePlan(q,{semantic:base})?.semantic||base;};if(oldPlan)rt.buildAnswerPlan=function(q,ctx={},world={},history=[]){const base=oldPlan(q,ctx,world,history);return canonicalizePlan(q,base)||base;};rt.__canonicalIdentityV500=true;}
const cog=g.OmegaCognitiveOS;if(cog&&!cog.__canonicalIdentityV500){if(typeof cog.getCountryProfile==='function')cog.getCountryProfile=function(v){const h=resolveCountry(v);return h?.id?h.raw||h:null;};if(typeof cog.getEconomy==='function')cog.getEconomy=function(v){const h=resolveCountry(v);return h?.id?getDatasetRecord('economy.json',h.id,h.surface):null;};if(typeof cog.getPopulation==='function')cog.getPopulation=function(v){const h=resolveCountry(v);return h?.id?getDatasetRecord('population.json',h.id,h.surface):null;};if(typeof cog.thinkMinisterQuestion==='function'){const old=cog.thinkMinisterQuestion.bind(cog);cog.thinkMinisterQuestion=function(question,minister,countryKey,countryDetails){const h=resolveCountry(question)||resolveCountry(countryKey);if(h?.id)return old(question,minister,h.id,countryDetails||h.raw||{});return old(question,minister,S(countryKey),countryDetails||{});};}cog.__canonicalIdentityV500=true;}
const ui=g.OmegaCabinetUI;if(ui&&!ui.__canonicalIdentityV500){if(typeof ui.processQuestionAndReply==='function'){const old=ui.processQuestionAndReply.bind(ui);ui.processQuestionAndReply=function(minister,question){const q=S(question),h=resolveCountry(q),previous=ui.activeCountry;if(h?.id)ui.activeCountry=h.id;try{return old(minister,q);}finally{if(h?.id&&previous!=null)ui.activeCountry=previous;};};}if(typeof ui.askCustomQuestion==='function'){const old=ui.askCustomQuestion.bind(ui);ui.askCustomQuestion=function(ministerId,question){const q=S(question),h=resolveCountry(q),previous=ui.activeCountry;if(h?.id)ui.activeCountry=h.id;try{return old(ministerId,q);}finally{if(h?.id&&previous!=null)ui.activeCountry=previous;};}ui.__canonicalIdentityV500=true;}}
function diagnostics(){return{version:VERSION,ready:state.ready,loadedAt:state.loadedAt,error:state.error,countryCount:state.countries.size,expectedCountryCount:197,complete:state.countries.size===197,aliasCount:state.countryAliases.size,totalCityCountries:state.cities.size,totalCityRecords:[...state.cities.values()].reduce((n,m)=>n+m.size,0),cityAliasCount:state.cityAliases.size,sourceCounts:{...state.sourceCounts},datasets:[...state.datasets.keys()]};}
g.OmegaCanonicalIdentityRegistry={VERSION,init,resolve,resolveCountry,resolveCity,countryBrief,allCities,getDatasetRecord,canonicalizePlan,diagnostics,exportData:()=>({version:VERSION,countries:[...state.countries.values()].map(c=>({id:c.id,names:c.names,officialName:c.officialName,cities:allCities(c.id),sources:c.sources,datasets:Object.keys(c.datasets||{})}))})};
g.OmegaCountrySemanticBridge={VERSION,init,resolve:resolveCountry,resolveCountry,resolveCity,countryBrief,allCities,parseCountry:(q,ctx={})=>{const h=resolveCountry(q);if(!h?.id)return null;const b=countryBrief(q);return{version:VERSION,surface:S(q),normalized:N(q),language:/[\u0980-\u09FF]/.test(S(q))?'bn':'en',operation:'IDENTIFY',targetDomain:'COUNTRY',entities:{country:h},unresolved:[],confidence:h.confidence,executable:true,countryBrief:ctx.initialTurn?b:null,responseTemplate:ctx.initialTurn?{type:'COUNTRY_FIRST_TURN',fields:['countryName','realCountryName','cities','cityCount']}:null};},countryOnly:(q,ctx={})=>{const h=resolveCountry(q);return!!h?.id&&N(q)===N(h.surface)&&(ctx.initialTurn===true||ctx.firstTurn===true||ctx.turn===0||ctx.chatTurn===0);},isExactCountry:q=>{const h=resolveCountry(q);return h?.id&&N(q)===N(h.surface)?h:null;},canonicalizePlan,diagnostics,exportData:()=>g.OmegaCanonicalIdentityRegistry.exportData(),install:installRuntimeBridges};
const boot=setInterval(()=>{installRuntimeBridges();if(state.ready)clearInterval(boot);},50);setTimeout(()=>clearInterval(boot),20000);init();

/* OMEGA DATA FINDING SYSTEM v1.0.0
 * Data-driven Question -> Entity -> Dataset -> Record -> Field -> Evidence.
 * This layer adds planning/indexing/extraction without replacing the country/resource
 * identity spines. Dataset meaning lives in offline_semantic_knowledge.json.
 */
const DFS_VERSION='1.0.0';
const dfsState={ready:false,error:null,knowledge:null,datasetMeta:[],datasetRegistry:new Map(),capabilityIndex:new Map(),entityIndex:new Map(),fieldIndex:new Map(),initPromise:null,conversation:{activeEntities:{}}};
const freezeDeep=v=>{if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const x of Object.values(v))freezeDeep(x);return Object.freeze(v)};
const pathParts=p=>S(p).replace(/^\$\.?/,'').split('.').filter(Boolean);
function pathRead(root,path){let cur=root;const parts=pathParts(path);for(const part of parts){if(cur==null)return undefined;if(/^\[\d+\]$/.test(part)){cur=cur[Number(part.slice(1,-1))];continue;}if(part==='[]')continue;cur=cur[part];}return cur;}
function inferRecordCollections(root){const out=[];const walk=(v,path='root')=>{if(Array.isArray(v)){if(v.length===0||v.some(x=>O(x)))out.push({path,kind:'array',length:v.length});for(let i=0;i<Math.min(v.length,12);i++)walk(v[i],`${path}[${i}]`);return;}if(!O(v))return;for(const [k,x]of Object.entries(v)){const p=path==='root'?k:`${path}.${k}`;if(Array.isArray(x))out.push({path:p,kind:'array',length:x.length});walk(x,p);}};walk(root);return out;}
function loadMetaFromKnowledge(k){const meta=Array.isArray(k?.data_finding?.dataset_capabilities)?k.data_finding.dataset_capabilities:[];return meta.filter(O).map(x=>({...x,capabilities:A(x.capabilities),identityFields:A(x.identityFields),fieldMappings:O(x.fieldMappings)?x.fieldMappings:{}}));}
function addCapability(cap,entry){const c=S(cap).toUpperCase();if(!c)return;const list=dfsState.capabilityIndex.get(c)||[];list.push(entry);dfsState.capabilityIndex.set(c,list);}
function datasetName(entry){return S(entry?.dataset||entry?.name);}
function registerDatasetMeta(meta,raw){const dataset=datasetName(meta);if(!dataset)return;const entry={...meta,dataset,loaded:raw!==undefined,raw,recordCollections:inferRecordCollections(raw),authority:meta.authority||'EXPLICIT_METADATA'};dfsState.datasetRegistry.set(dataset,entry);for(const cap of meta.capabilities)addCapability(cap,{dataset,metadata:entry});for(const [cap,mapping]of Object.entries(meta.fieldMappings||{})){const c=S(cap).toUpperCase();const e={dataset,capability:c,mapping:{...mapping},authority:'EXPLICIT_METADATA'};const list=dfsState.fieldIndex.get(c)||[];list.push(e);dfsState.fieldIndex.set(c,list);if(!dfsState.capabilityIndex.has(c))addCapability(c,{dataset,metadata:entry});}}
function registerHeuristicDataset(name,raw){if(dfsState.datasetRegistry.has(name))return;registerDatasetMeta({dataset:name,entityTypes:[],capabilities:[],identityFields:[],fieldMappings:{},authority:'HEURISTIC_SCHEMA_DISCOVERY'},raw);}
function identitySurfaceFromRecord(record,entry){const keys=A(entry.identityFields);const values=[];for(const k of keys){const v=pathRead(record,k);if(v!=null)values.push(v);}for(const k of ['countryId','countryCode','country_code','iso2','iso3','code','id','name','countryName','country_name'])if(record?.[k]!=null)values.push(record[k]);return values.filter(v=>typeof v==='string'||typeof v==='number').map(S).filter(Boolean);}
function canonicalCountryForRecord(record,entry,keyHint=''){const surfaces=[...identitySurfaceFromRecord(record,entry),keyHint].filter(Boolean);for(const surface of surfaces){const hit=resolveCountry(surface);if(hit?.id)return hit;}return null;}
function indexRecord(dataset,recordLocator,record,entry,keyHint=''){const country=canonicalCountryForRecord(record,entry,keyHint);if(!country?.id)return {status:'UNRESOLVED',country:null};const key=country.id;const byDataset=dfsState.entityIndex.get(key)||new Map();const list=byDataset.get(dataset)||[];list.push({recordLocator,record,keyHint,identity:country});byDataset.set(dataset,list);dfsState.entityIndex.set(key,byDataset);return{status:'MATCHED',country};}
function indexDatasetRecords(entry){const raw=entry.raw;if(raw==null)return;const dataset=entry.dataset;const locator=S(entry.recordLocator||'');if(locator.endsWith('[]')){const base=locator.slice(0,-2);const arr=base?pathRead(raw,base):Array.isArray(raw)?raw:null;if(Array.isArray(arr))arr.forEach((r,i)=>indexRecord(dataset,`${locator}[${i}]`,r,entry,''));return;}if(entry.recordKeyIsIdentity&&O(raw)){for(const [k,v]of Object.entries(raw))indexRecord(dataset,`[${JSON.stringify(k)}]`,v,entry,k);return;}if(Array.isArray(raw)){raw.forEach((r,i)=>indexRecord(dataset,`root[${i}]`,r,entry,''));return;}if(O(raw)){for(const [k,v]of Object.entries(raw))if(O(v))indexRecord(dataset,`root[${JSON.stringify(k)}]`,v,entry,k);}}
async function loadKnowledge(){try{const k=await loadJson('offline_semantic_knowledge.json',true);dfsState.knowledge=k||{};dfsState.datasetMeta=loadMetaFromKnowledge(dfsState.knowledge);return k||{};}catch{return{};}}
function installKnownDataIntoRegistry(){for(const entry of dfsState.datasetMeta){const raw=state.datasets.get(entry.dataset);registerDatasetMeta(entry,raw);if(raw!==undefined)indexDatasetRecords(dfsState.datasetRegistry.get(entry.dataset));}for(const [name,raw]of state.datasets.entries())registerHeuristicDataset(name,raw);for(const [name,entry]of dfsState.datasetRegistry.entries())if(entry.authority==='HEURISTIC_SCHEMA_DISCOVERY')indexDatasetRecords(entry);}
function rebuildIndexes(){dfsState.capabilityIndex.clear();dfsState.fieldIndex.clear();dfsState.datasetRegistry.clear();dfsState.entityIndex.clear();installKnownDataIntoRegistry();}
async function dfsInit(){if(dfsState.initPromise)return dfsState.initPromise;dfsState.initPromise=(async()=>{await init();await loadKnowledge();rebuildIndexes();dfsState.ready=true;return diagnosticsDFS();})().catch(e=>{dfsState.error=String(e);dfsState.ready=false;return diagnosticsDFS();});return dfsState.initPromise;}
function resolveResourceViaBridge(surface){const bridge=g.OmegaResourceSemanticBridge;if(!bridge)return null;try{if(typeof bridge.resolveResource==='function'){const r=bridge.resolveResource(surface);if(r?.id||r?.canonicalId||r)return{type:'RESOURCE',id:S(r.id||r.canonicalId),raw:r,confidence:Number(r.confidence||1)};}if(typeof bridge.resolve==='function'){const r=bridge.resolve(surface);if(r?.id||r?.canonicalId)return{type:'RESOURCE',id:S(r.id||r.canonicalId),raw:r,confidence:Number(r.confidence||1)};}}catch{}return null;}
function vocabularyEntries(){const out=[];const add=(group,type)=>{for(const [id,v]of Object.entries(group||{})){if(!O(v))continue;const names=A(v.names);out.push({id,type,names});}};add(dfsState.knowledge?.countries,'COUNTRY');add(dfsState.knowledge?.resources,'RESOURCE');return out;}
function semanticEntityHints(question){const q=N(question),hits=[];for(const x of vocabularyEntries())for(const name of x.names){const n=N(name);if(!n)continue;const exact=q===n,contains=q.includes(n);if(contains)hits.push({type:x.type,id:x.id,surface:name,score:exact?1:Math.min(.98,.72+n.length/Math.max(100,q.length*2))});}return hits.sort((a,b)=>b.score-a.score||String(a.id).length-String(b.id).length);}
function resourceHint(question){const hit=semanticEntityHints(question).find(x=>x.type==='RESOURCE');return hit?resolveResourceViaBridge(hit.surface):null;}
function capabilityCandidates(semantic){const props=A(semantic?.requirements||semantic?.requestedCapabilities||semantic?.capabilities);if(semantic?.property?.type)props.push(semantic.property.type);if(semantic?.request?.capability)props.push(semantic.request.capability);if(semantic?.operation&&semantic.operation!=='LOOKUP'&&semantic.operation!=='UNKNOWN')props.push(semantic.operation);return[...new Set(props.map(x=>S(x).toUpperCase()).filter(Boolean))];}
function matchCapabilityFromQuestion(question,semantic){const q=N(question),hits=[];for(const [cap,entries]of dfsState.capabilityIndex.entries()){const names=A(dfsState.knowledge?.capabilities?.[cap]?.names);const direct=names.some(n=>q.includes(N(n)));if(direct)hits.push({capability:cap,score:1});}for(const c of capabilityCandidates(semantic))if(dfsState.capabilityIndex.has(c))hits.push({capability:c,score:.99});return[...new Map(hits.map(x=>[x.capability,x])).values()].sort((a,b)=>b.score-a.score);}
function readMappingValue(record,mapping){if(!mapping)return undefined;return pathRead(record,mapping.valuePath||'');}
function resolveRecordForEntity(dataset,entity,mapping){const list=dfsState.entityIndex.get(entity?.canonicalId||entity?.id)||new Map();const entries=list.get(dataset)||[];if(entries.length===1)return entries[0];if(entries.length>1&&mapping?.recordEntity==='COUNTRY')return entries.find(x=>x.identity?.id===entity.id)||entries[0];return entries[0]||null;}
function buildQueryPlan(question,semantic,context={}){const sourceSemantic=semantic&&typeof semantic==='object'?semantic:{};const countryHit=sourceSemantic.entities?.country||resolveCountry(context?.countryId||context?.countryCode||question);const resourceHit=sourceSemantic.entities?.resource||resourceHint(question);const cityHit=sourceSemantic.entities?.city||resolveCity(question,countryHit?.id||null);const capHints=matchCapabilityFromQuestion(question,sourceSemantic);let capability=capHints[0]?.capability||S(sourceSemantic?.request?.capability).toUpperCase();if(resourceHit&&!capability)capability='RESOURCE';const entity=countryHit?.id?{type:'COUNTRY',canonicalId:countryHit.id,surface:countryHit.surface,confidence:countryHit.confidence}:{type:resourceHit?.type||'UNKNOWN',canonicalId:resourceHit?.id||null,surface:resourceHit?.raw?.surface||resourceHit?.raw?.name||'',confidence:resourceHit?.confidence||0};const unresolved=[];if(!entity.canonicalId)unresolved.push(entity.type==='COUNTRY'?'COUNTRY_IDENTITY':'ENTITY');if(!capability)unresolved.push('CAPABILITY');const sources=[];if(capability){for(const x of dfsState.capabilityIndex.get(capability)||[])sources.push(x);}const dataSources=sources.map(x=>({dataset:x.dataset,recordLocator:x.metadata.recordLocator||null,identityFields:A(x.metadata.identityFields),fieldMapping:x.metadata.fieldMappings?.[capability]||null,authority:x.metadata.authority||x.authority}));const status=unresolved.length?'UNRESOLVED':dataSources.length?'RESOLVABLE':'CAPABILITY_UNSUPPORTED_BY_CURRENT_DATA';return freezeDeep({version:DFS_VERSION,operation:S(sourceSemantic.operation||'LOOKUP').toUpperCase(),entity,request:{capability:capability||null},context:{countryId:countryHit?.id||context?.countryId||null,cityId:cityHit?.id||null,resourceId:resourceHit?.id||null},dataSources,status,unresolved,semantic:sourceSemantic});}
function executePlan(plan){if(!plan||typeof plan!=='object')return{ok:false,status:'INVALID_QUERY_PLAN'};if(plan.status==='UNRESOLVED'){return{ok:false,status:plan.entity?.type==='COUNTRY'?'COUNTRY_IDENTITY_UNRESOLVED':'ENTITY_UNRESOLVED',plan};}if(plan.status==='CAPABILITY_UNSUPPORTED_BY_CURRENT_DATA')return{ok:false,status:'CAPABILITY_UNSUPPORTED_BY_CURRENT_DATA',capability:plan.request?.capability||null,plan};const entity=plan.entity;const outputs=[];for(const source of A(plan.dataSources)){const entry=dfsState.datasetRegistry.get(source.dataset);if(!entry?.loaded)continue;if(entity.type==='COUNTRY'){const rec=resolveRecordForEntity(source.dataset,{id:entity.canonicalId},source.fieldMapping||{});if(!rec){outputs.push({status:'NOT_FOUND_IN_SOURCE',dataset:source.dataset,entityId:entity.canonicalId});continue;}const mapping=source.fieldMapping;const value=mapping?readMappingValue(rec.record,mapping):rec.record;const evidence={dataset:source.dataset,recordLocator:rec.recordLocator,entityId:entity.canonicalId,capability:plan.request.capability,fieldPath:mapping?.valuePath||null,rawValue:value,identity:rec.identity,authority:entry.authority,confidence:Math.min(1,Number(entity.confidence||0)),classification:value===undefined?'NOT_FOUND':'VERIFIED_FACT'};outputs.push(value===undefined?{status:'NOT_FOUND_IN_SOURCE',evidence}:{status:'SUCCESS',value,evidence});}else if(entity.type==='RESOURCE'){const bridge=resolveResourceViaBridge(entity.canonicalId);outputs.push(bridge?{status:'DELEGATED_TO_RESOURCE_BRIDGE',value:bridge.raw,evidence:{entityId:entity.canonicalId,capability:plan.request.capability,source:'OmegaResourceSemanticBridge',classification:'VERIFIED_FACT'}}:{status:'NOT_FOUND_IN_SOURCE',entityId:entity.canonicalId});}}
if(!outputs.length)return{ok:false,status:'NOT_FOUND_IN_SOURCE',plan};const successful=outputs.filter(x=>x.status==='SUCCESS'||x.status==='DELEGATED_TO_RESOURCE_BRIDGE');if(!successful.length)return{ok:false,status:outputs[0].status||'NOT_FOUND_IN_SOURCE',results:outputs,plan};return{ok:true,status:successful.length>1?'MULTI_SOURCE_RESULT':'SUCCESS',results:outputs,value:successful.length===1?successful[0].value:successful.map(x=>x.value),evidence:successful.map(x=>x.evidence),plan};}
function find(question,semantic={},context={}){if(!dfsState.ready)return{ok:false,status:'DATA_FINDER_NOT_READY'};const plan=buildQueryPlan(question,semantic,context);return executePlan(plan);}
function diagnosticsDFS(){return{version:DFS_VERSION,ready:dfsState.ready,error:dfsState.error,datasets:dfsState.datasetRegistry.size,capabilities:dfsState.capabilityIndex.size,fieldMappings:dfsState.fieldIndex.size,indexedEntities:dfsState.entityIndex.size,knowledgeLoaded:!!dfsState.knowledge};}
function setConversationEntity(entity){if(!entity?.type||!entity?.canonicalId)return false;dfsState.conversation.activeEntities[entity.type.toLowerCase()]={canonicalId:entity.canonicalId};return true;}
function getConversationEntity(type){return dfsState.conversation.activeEntities[S(type).toLowerCase()]||null;}
function dataQuestion(question,semantic={},context={}){const active=getConversationEntity('COUNTRY');const mergedContext={...context,countryId:context.countryId||active?.canonicalId};const plan=buildQueryPlan(question,semantic,mergedContext);const result=executePlan(plan);if(result?.ok&&plan.entity?.type)setConversationEntity(plan.entity);return{plan,result};}
function installDFSRuntimeBridge(){const rt=g.OfflineQueryEngine;if(rt&&!rt.__omegaDataFindingV100&&typeof rt.execute==='function'){const original=rt.execute.bind(rt);rt.execute=function(semantic,datasets,language,ctx={}){const q=S(semantic?.surface||semantic?.question||ctx?.prompt||ctx?.query||'');if(q&&dfsState.ready){const found=dataQuestion(q,semantic,ctx);if(found.result?.ok||['CAPABILITY_UNSUPPORTED_BY_CURRENT_DATA','COUNTRY_IDENTITY_UNRESOLVED','ENTITY_UNRESOLVED','NOT_FOUND_IN_SOURCE'].includes(found.result?.status))return found.result;}return original(semantic,datasets,language,ctx);};rt.__omegaDataFindingV100=true;}}
const existingInstall=installRuntimeBridges;installRuntimeBridges=function(){existingInstall();installDFSRuntimeBridge();};
g.OmegaDataFindingSystem={VERSION:DFS_VERSION,init:dfsInit,find,dataQuestion,buildQueryPlan,executePlan,diagnostics:diagnosticsDFS,setConversationEntity,getConversationEntity,resolveCountry,resolveCity,getDataset:(name)=>dfsState.datasetRegistry.get(S(name)),getCapability:(cap)=>[...(dfsState.capabilityIndex.get(S(cap).toUpperCase())||[])],indexes:()=>({entities:dfsState.entityIndex,capabilities:dfsState.capabilityIndex,fields:dfsState.fieldIndex}),authority:'repository-data-with-explicit-metadata-first'};
dfsInit();
})(typeof globalThis!=='undefined'?globalThis:window);

/* OMEGA DATA FINDING CONTRACT EXTENSION v1.0.0
 * Adds immutable semantic-query output and repository-wide convergence diagnostics.
 * No country/resource facts are embedded here.
 */
(function(g){
'use strict';
const dfs=g.OmegaDataFindingSystem;
const country=g.OmegaCanonicalIdentityRegistry;
if(!dfs||dfs.__contractExtensionV100)return;
const freeze=v=>{if(!v||typeof v!=='object'||Object.isFrozen(v))return v;for(const x of Object.values(v))freeze(x);return Object.freeze(v)};
const baseBuild=dfs.buildQueryPlan.bind(dfs);
const baseFind=dfs.find.bind(dfs);
function withSemanticQuery(question,semantic,context,plan){const p=plan&&typeof plan==='object'?plan:{};const s=p.semantic&&typeof p.semantic==='object'?p.semantic:{};const property=p.request?.capability?{type:p.request.capability}:s.property||null;const entities={...(s.entities||{})};if(p.entity?.canonicalId){const key=S_SAFE(p.entity.type).toLowerCase()||'entity';entities[key]={type:p.entity.type,canonicalId:p.entity.canonicalId,surface:p.entity.surface||'',confidence:p.entity.confidence||0};}const query={operation:p.operation||s.operation||'LOOKUP',entity:p.entity||null,property,resource:p.context?.resourceId?{canonicalId:p.context.resourceId}:entities.resource||null,modifiers:s.modifiers||[],location:s.location||null,unresolved:Array.isArray(p.unresolved)?p.unresolved:[],language:s.language||(/[\u0980-\u09FF]/.test(String(question))?'bn':'en')};return freeze({...p,semanticQuery:query});}
function S_SAFE(v){return String(v==null?'':v).trim();}
dfs.buildQueryPlan=function(question,semantic={},context={}){return withSemanticQuery(question,semantic,context,baseBuild(question,semantic,context));};
dfs.find=function(question,semantic={},context={}){if(typeof baseFind!=='function')return{ok:false,status:'DATA_FINDER_NOT_READY'};const result=baseFind(question,semantic,context);if(result?.plan)return{...result,plan:withSemanticQuery(question,semantic,context,result.plan)};return result;};
function crossDatasetAudit(){const data=dfs.indexes?.()||{};const entities=data.entities instanceof Map?data.entities:new Map();const report=[];for(const [canonicalId,byDataset]of entities.entries()){const datasets={};if(byDataset instanceof Map){for(const [dataset,records]of byDataset.entries()){const count=Array.isArray(records)?records.length:0;datasets[dataset]=count===1?'MATCHED':count===0?'MISSING': 'CONFLICT';}}report.push({country:canonicalId,canonicalId,datasets});}return{version:'1.0.0',entityCount:report.length,rows:report};}
async function selfTest(){await dfs.init();const exported=country?.exportData?.();const rows=Array.isArray(exported?.countries)?exported.countries:[];const checks=[];for(const c of rows){const surfaces=Array.isArray(c.names)?c.names:[];const hits=[];for(const surface of surfaces.slice(0,12)){const r=dfs.resolveCountry(surface);hits.push({surface,ok:!!r?.id,resolvedId:r?.id||null});}checks.push({canonicalId:c.id,nameCount:surfaces.length,allResolved:hits.length?hits.every(x=>x.ok&&x.resolvedId===c.id):false,checks:hits});}const audit=crossDatasetAudit();return{ok:checks.length>0&&checks.every(x=>x.allResolved),countryCount:checks.length,checks,crossDataset:audit};}
const oldDiag=dfs.diagnostics.bind(dfs);dfs.diagnostics=function(){return{...oldDiag(),semanticQueryContract:true,crossDatasetAuditAvailable:true,selfTestAvailable:true};};
dfs.crossDatasetAudit=crossDatasetAudit;dfs.selfTest=selfTest;dfs.__contractExtensionV100=true;
})(typeof globalThis!=='undefined'?globalThis:window);
