/* OMEGA LIVE MINISTER SELECTOR + SEMANTIC QUESTION BINDING v4.0.0-PRODUCTION */
(function(global){
'use strict';
var VERSION='4.0.0-PRODUCTION',KEY='OMEGA_APPOINTED_MINISTERS_V4',profiles=null,loading=null;
function text(v){return v==null?'':String(v).trim();}
function norm(v){return text(v).toLowerCase().replace(/[&/]+/g,' ').replace(/[._-]+/g,' ').replace(/\s+/g,' ').trim();}
function game(){return global.Game||{};}
function country(){var g=game(),s=g.state||{};return text(g.currentActiveCountry||s.countryId||s.playerCountryId||'BANGLADESH').toUpperCase().replace(/\s+/g,'_');}
function ministryId(){var ui=global.OmegaCabinetUI||{},g=game(),s=g.state||{};return text(global.OmegaLayerManager&&global.OmegaLayerManager.activeMinistryId||ui.activeMinistryId||ui.currentMinistryId||s.activeMinistryId||'');}
function load(){try{return JSON.parse(global.localStorage.getItem(KEY)||'{}');}catch(e){return{};}}
function save(v){try{global.localStorage.setItem(KEY,JSON.stringify(v));}catch(e){}}
function selectedIndex(m){var v=Number(load()[country()+'_'+m]);return isFinite(v)&&v>=0?Math.floor(v):0;}
function remove(){var x=document.getElementById('omega-live-minister-selector');if(x&&x.parentNode)x.parentNode.removeChild(x);}
function fromUI(m){var ui=global.OmegaCabinetUI;if(!ui||typeof ui.getMinisterProfile!=='function')return[];try{var p=ui.getMinisterProfile(m,country());return p&&Array.isArray(p.candidates)?p.candidates:[];}catch(e){return[];}}
function fromDataset(m){if(!profiles)return[];var wanted=norm(m),out=[];if(Array.isArray(profiles)){for(var i=0;i<profiles.length;i++){var p=profiles[i]||{};if(norm(p.ministryId||p.ministry||p.department||'')===wanted)out.push(p);}return out;}for(var k in profiles){if(!Object.prototype.hasOwnProperty.call(profiles,k))continue;var a=profiles[k];if(!Array.isArray(a))continue;if(norm(k)===wanted||a.some(function(p){return norm(p&&p.ministryId||p&&p.ministry||'')===wanted;})){for(var j=0;j<a.length;j++)out.push(a[j]);}}return out;}
function candidates(m){var a=fromUI(m);return a.length?a:fromDataset(m);}
function setActive(ui,m,c,i){if(!c)return;ui.appointedMinisterIndex=ui.appointedMinisterIndex||{};ui.appointedMinisterIndex[m]=i;ui.currentInterrogatedMinister={};for(var k in c)if(k!=='__omegaIndex')ui.currentInterrogatedMinister[k]=c[k];ui.currentInterrogatedMinister.ministerId=text(c.ministerId||c.id);ui.currentInterrogatedMinister.ministryId=m;ui.currentInterrogatedMinister.countryCode=country();ui.currentInterrogatedMinister.ministerName=text(c.ministerName||c.name||c.baseName);}
function install(m){var ui=global.OmegaCabinetUI,dash=document.getElementById('ministry-dashboard-view');if(!ui||!dash||!m)return false;var cs=candidates(m);if(!cs.length)return false;remove();var i=Math.min(selectedIndex(m),cs.length-1);if(i<0)i=0;var box=document.createElement('div');box.id='omega-live-minister-selector';box.className='omega-minister-selector';box.setAttribute('data-minister-selector','live');box.innerHTML='<label>MINISTER</label><select id="omega-minister-choice" aria-label="Change Minister"></select><button type="button" id="omega-minister-appoint">CHANGE MINISTER</button><span id="omega-minister-selector-status">CURRENT</span>';var select=box.querySelector('#omega-minister-choice');for(var n=0;n<cs.length;n++){var c=cs[n]||{},o=document.createElement('option');o.value=String(n);o.textContent=text(c.name||c.baseName||c.ministerName||c.id||('Candidate '+(n+1)))+' • '+text(c.id||c.ministerId||'');select.appendChild(o);}select.value=String(i);cs[i].__omegaIndex=i;setActive(ui,m,cs[i],i);var host=dash.querySelector('.sticky-layer-header');if(host&&host.parentNode)host.parentNode.insertBefore(box,host);else dash.insertBefore(box,dash.firstChild||null);box.querySelector('#omega-minister-appoint').addEventListener('click',function(){var k=Number(select.value),c=cs[k];if(!c)return;var store=load();store[country()+'_'+m]=k;save(store);c.__omegaIndex=k;setActive(ui,m,c,k);box.querySelector('#omega-minister-selector-status').textContent='APPOINTED: '+ui.currentInterrogatedMinister.ministerName;});select.addEventListener('change',function(){box.querySelector('#omega-minister-selector-status').textContent='READY TO CHANGE';});return true;}
function loadProfiles(){if(profiles||loading)return;loading=fetch('ministers.json',{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('ministers.json HTTP '+r.status);return r.json();}).then(function(d){profiles=d&&d.ministers_database||d&&d.ministers||d;return profiles;}).catch(function(e){console.warn('[OMEGA Minister Selector] dataset load failed',e);profiles=null;}).finally(function(){loading=null;});}
function patchSelector(){var ui=global.OmegaCabinetUI;if(!ui||ui.__omegaSelectorV4)return false;ui.__omegaSelectorV4=true;loadProfiles();if(typeof ui.renderMinistryDashboard==='function'){var render=ui.renderMinistryDashboard;ui.renderMinistryDashboard=function(m){var r=render.apply(this,arguments);setTimeout(function(){install(m);},0);setTimeout(function(){if(!document.getElementById('omega-live-minister-selector'))install(m);},300);return r;};}return true;}
function patchQuestion(){var ui=global.OmegaCabinetUI,semantic=global.OmegaProductionSemanticRuntime;if(!ui||!semantic||typeof semantic.buildAnswerPlan!=='function'||typeof semantic.formatOfflineAnswer!=='function'||typeof ui.processQuestionAndReply!=='function')return false;if(ui.__omegaSemanticV4)return true;ui.__omegaSemanticV4=true;var original=ui.processQuestionAndReply;ui.processQuestionAndReply=function(minister,questionText){var q=text(questionText),m=minister||ui.currentInterrogatedMinister||{},id=text(m.ministerId||m.id);try{var identity={countryCode:country(),ministryId:text(m.ministryId||ministryId()),ministerId:id,ministerName:text(m.ministerName||m.name||m.baseName)},plan=semantic.buildAnswerPlan(q,identity,game().state||{},ui.chatHistories&&ui.chatHistories[id]||[]),answer=semantic.formatOfflineAnswer(plan);if(answer&&id){ui.chatHistories=ui.chatHistories||{};ui.chatHistories[id]=ui.chatHistories[id]||[];ui.chatHistories[id].push({sender:'USER',text:q,timestamp:Date.now()});ui.chatHistories[id].push({sender:'MINISTER',text:answer,response:answer,timestamp:Date.now(),semanticPlan:plan.semantic||plan,evidence:plan.result||null,source:'OMEGA_PRODUCTION_SEMANTIC_RUNTIME_V4_1'});if(typeof ui.renderChatHistory==='function')ui.renderChatHistory(id);return answer;}}catch(e){console.error('[OMEGA semantic question]',e);}return original.call(ui,minister,questionText);};return true;}
function observe(){var dash=document.getElementById('ministry-dashboard-view');if(!dash||dash.__omegaObserverV4)return;if(typeof MutationObserver==='function'){var ob=new MutationObserver(function(){if(dash.style.display!=='none'){var m=ministryId();if(m&&!document.getElementById('omega-live-minister-selector'))install(m);}});ob.observe(dash,{childList:true,subtree:true,attributes:true,attributeFilter:['style','class']});dash.__omegaObserverV4=true;}}
function boot(){patchSelector();patchQuestion();observe();var m=ministryId();if(m)install(m);setTimeout(boot,500);}
global.OmegaLiveMinisterSelector={VERSION:VERSION,install:install};boot();
})(typeof globalThis!=='undefined'?globalThis:window);