/* OMEGA UNIVERSAL AI RUNTIME v2.0.0 */
(function(global){'use strict';
  const KEY='omega.universal.ai.history.v2', MAX_TURNS=200, MAX_INPUT=20000;
  let installed=false, queue=Promise.resolve(), dataPromise=null;
  const text=v=>String(v==null?'':v).normalize('NFKC').trim();
  const bn=v=>/[\u0980-\u09FF]/.test(String(v||''));
  function readHistory(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x.slice(-MAX_TURNS):[]}catch(_){return[]}}
  function writeHistory(h){try{localStorage.setItem(KEY,JSON.stringify(h.slice(-MAX_TURNS)))}catch(_) {}}
  function context(){const gs=global.Game?.state||global.gameState||global.Omega?.World?.state||{};const ui=global.OmegaCabinetUI||{};const m=ui.currentInterrogatedMinister||ui.currentMinister||ui.activeMinister||global.OmegaMinisterState?.activeMinister||{};return{countryId:gs.countryCode||gs.countryId||gs.playerCountryId||ui.activeCountry||'',countryName:gs.countryName||gs.country?.name||ui.activeCountry||'',ministerId:m.id||ui.currentMinisterId||'',ministerName:m.name||m.displayName||'',ministerRole:m.role||m.title||'',ministryId:m.ministryId||ui.currentMinistryId||'',gameState:gs}}
  function output(answer,question,meta){let node=document.getElementById('omega-ai-answer-text');if(!node){node=document.createElement('div');node.id='omega-ai-answer-text';const host=document.getElementById('omega-ai-answer')||document.getElementById('minister-ai-answer')||document.getElementById('interrogation-answer')||document.getElementById('interrogation-modal-content');if(host)host.appendChild(node)}if(!node)return;node.textContent=String(answer||'');node.dataset.source=meta?.source||'OMEGA_LANGUAGE_SYSTEM';node.dataset.operation=meta?.operation||'';if(meta?.reasoning)node.dataset.reasoning=JSON.stringify(meta.reasoning).slice(0,2000);if(meta?.analysis)node.dataset.languageAnalysis=JSON.stringify(meta.analysis).slice(0,2000);const h=readHistory();h.push({role:'user',content:question,timestamp:Date.now()},{role:'assistant',content:String(answer||''),timestamp:Date.now(),source:meta?.source||'',operation:meta?.operation||''});writeHistory(h)}
  async function postJson(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let d=null;try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d?.error||`HTTP_${r.status}`);return d||{}}
  async function ensureLanguage(){if(global.OmegaLanguageSystem)return global.OmegaLanguageSystem;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='./omega_language_system.js';s.onload=resolve;s.onerror=()=>reject(new Error('OMEGA_LANGUAGE_SYSTEM_LOAD_FAILED'));document.head.appendChild(s)});if(!global.OmegaLanguageSystem)throw new Error('OMEGA_LANGUAGE_SYSTEM_UNAVAILABLE');return global.OmegaLanguageSystem}
  async function loadDatasets(){if(dataPromise)return dataPromise;dataPromise=(async()=>{const files=['resources.json','resources_2.json','economy.json','population.json','countries.json','relations.json','country_policy.json','world.json','society.json','resource_ontology.json'];const loaded=await Promise.all(files.map(async f=>{try{const r=await fetch('./'+f,{cache:'no-store'});return r.ok?await r.json():null}catch(_){return null}}));return loaded.filter(Boolean)})().catch(e=>{dataPromise=null;throw e});return dataPromise}
  async function offline(question,ctx,language){const lang=await ensureLanguage();const datasets=await loadDatasets();lang.configure({datasets,context:ctx});return lang.run(question,ctx)}
  async function turn(question){const q=text(question);if(!q||q.length>MAX_INPUT)return;const ctx=context(), language=bn(q)?'bn':'en', lang=await ensureLanguage();
    try{const direct=await offline(q,ctx,language);output(direct.answer,q,{source:'OMEGA_LANGUAGE_SYSTEM_OFFLINE',operation:direct.analysis?.operation,reasoning:direct.reasoning,analysis:direct.analysis});return}catch(e){console.warn('[OMEGA] Browser offline language path failed:',e.message)}
    try{const data=await postJson('/api/ai/semantic-query',{prompt:q,language,...ctx,gameState:ctx.gameState});const answer=data?.result?.text||data?.text||lang.realize(data?.result||{},language);output(answer,q,{source:'SERVER_GROUNDED_FALLBACK',operation:data?.result?.operation||data?.semantic?.operation,analysis:data?.semantic||null,reasoning:data?.reasoning||null});return}catch(e){output(language==='bn'?'বর্তমান গেম ডেটা থেকে প্রামাণ্য উত্তর তৈরি করা যায়নি।':'An evidence-backed answer could not be produced from the current game data.',q,{source:'PIPELINE_ERROR'});console.error('[OMEGA] interrogation failed:',e)}}
  function enqueue(q){queue=queue.then(()=>turn(q)).catch(e=>console.error('[OMEGA] queue failure',e))}
  function submitFromUI(){const input=document.getElementById('interrogation-input');const q=input?.value||'';if(!text(q))return;input.value='';enqueue(q)}
  function install(){if(installed||typeof document==='undefined')return;installed=true;document.addEventListener('click',e=>{const b=e.target?.closest?.('#btn-submit-interrogation');if(!b)return;e.preventDefault();e.stopImmediatePropagation();submitFromUI()},true);document.addEventListener('keydown',e=>{if(e.key!=='Enter'||e.shiftKey||e.isComposing||e.target?.id!=='interrogation-input')return;e.preventDefault();e.stopImmediatePropagation();submitFromUI()},true);global.OmegaUniversalAIRuntime=Object.freeze({enqueue,submitFromUI,context,readHistory,version:'2.0.0'});console.log('[OMEGA] Universal AI runtime installed through canonical language boundary.')}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})(window);
