/* OMEGA SEMANTIC RUNTIME v3.1
 * Runtime-only world knowledge. Language semantics come from JSON.
 */
(function(g){'use strict';
if(g.OmegaSemanticRuntimeV31)return;
const V='3.1.0-PRODUCTION',S={ready:false,vocab:null,knowledge:null,countries:new Map(),resources:new Map(),ministers:new Map(),datasets:new Map(),question:new Map(),attributes:new Map(),assets:new Map(),errors:[]};
const t=v=>String(v==null?'':v).trim(),n=v=>t(v).normalize('NFKC').replace(/[?!,.:;'"(){}\[\]<>]/g,' ').replace(/\s+/g,' ').trim().toLowerCase(),o=v=>v&&typeof v==='object',a=v=>Array.isArray(v)?v:[],bn=v=>/[\u0980-\u09ff]/.test(t(v)),cp=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
function addErr(c,d){S.errors.push({code:c,detail:d||null,time:Date.now()});if(S.errors.length>50)S.errors.shift()}
function load(path){return fetch(path,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(path+': HTTP '+r.status);return r.json()})}
function names(x,f){if(!o(x))return f?[t(f)]:[];const ks=['name','countryName','officialName','shortName','displayName','label','title','resourceName','canonicalName','localName','nativeName','name_en','name_bn','baseName','ministerName'];const r=[];for(const k of ks){const v=x[k];if(typeof v==='string'&&v.trim())r.push(v);else if(o(v))for(const z of Object.values(v))if(typeof z==='string'&&z.trim())r.push(z)}if(f)r.push(t(f).replace(/[_-]+/g,' '));return[...new Set(r.map(t).filter(Boolean))]}
function id(x,f){if(!o(x))return t(f||'');return t(x.id||x.canonicalId||x.canonical_id||x.iso3||x.isoCode||x.countryCode||x.code||x.key||x.ministerId||f||'')}
function forms(x){const r=new Set([n(x)]),bnS=S.vocab?.morphology?.bn_suffixes||[],enS=S.vocab?.morphology?.en_suffixes||[];for(const s of [...bnS,...enS]){const q=n(s);if(q&&n(x).endsWith(q)&&n(x).length>q.length+1)r.add(n(x).slice(0,-q.length))}return[...r]}
function add(type,x,f,source,map){const I=id(x,f);if(!I)return;const E={id:I,type,names:names(x,f),raw:cp(x),source};map.set(I,E);for(const z of E.names)for(const q of forms(z)){const key=type+':'+q;const bucket=S.aliasIndex?.get(key)||[];if(!bucket.includes(I))bucket.push(I);S.aliasIndex=S.aliasIndex||new Map();S.aliasIndex.set(key,bucket)}}
S.aliasIndex=new Map();
function ingestCountries(x){const q=Array.isArray(x)?x:(x?.countries||x?.data||Object.values(x||{}));q.forEach(z=>add('COUNTRY',z,id(z), 'countries.json',S.countries))}
function ingestMinisters(x){const db=x?.ministers_database||x?.ministers||x;if(!o(db))return;for(const [m,ls]of Object.entries(db))if(Array.isArray(ls))for(const z of ls)add('MINISTER',{...z,ministryId:z.ministryId||m},z.id,'ministers.json',S.ministers)}
function ingestResources(x){if(!x||!o(x)||!Object.keys(x).length)return;const root=x.resources||x.resourceDatabase||x.RESOURCE_DATABASE||x.COMMODITY_ONTOLOGIES||x;if(Array.isArray(root))root.forEach(z=>add('RESOURCE',z,id(z),'RESOURCE_DATASET',S.resources));else if(o(root))for(const[k,z]of Object.entries(root))add('RESOURCE',o(z)?z:{id:k,name:z},k,'RESOURCE_DATASET',S.resources)}
function ingestVocabulary(){const L=S.vocab?.languages||{};for(const [lang,v]of Object.entries(L)){for(const [q,ps]of Object.entries(v.question||{}))for(const p of a(ps))S.question.set(lang+':'+n(p),q);for(const [x,ps]of Object.entries(v.attributes||{}))for(const p of a(ps))S.attributes.set(lang+':'+n(p),x);for(const [x,ps]of Object.entries(v.assets||{}))for(const p of a(ps))S.assets.set(lang+':'+n(p),x)}}
function phrase(q,map,lang){const hits=[];for(const [k,v]of map){if(!k.startsWith(lang+':'))continue;const p=k.slice(lang.length+1);if(q===p)hits.push({v,p,s:1});else{const re=new RegExp('(^|\\s)'+p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=\\s|$)');if(re.test(q))hits.push({v,p,s:0.97});else if(q.includes(p))hits.push({v,p,s:0.88)}}}hits.sort((x,y)=>y.s-x.s||y.p.length-x.p.length);return hits[0]||null}
function entity(q,type){const map=type==='COUNTRY'?S.countries:type==='RESOURCE'?S.resources:S.ministers,hits=[];for(const E of map.values())for(const z of E.names)for(const f of forms(z)){if(q===f)hits.push({E,z,s:1});else{const re=new RegExp('(^|\\s)'+f.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=\\s|$)');if(re.test(q))hits.push({E,z,s:0.98});else if(q.includes(f))hits.push({E,z,s:0.90)}}}const lm=(()=>{try{return JSON.parse(g.localStorage?.getItem('OMEGA_SEMANTIC_LEARNING_V3')||'{}')}catch(_){return{}}})();for(const z of Object.values(lm))if(z.entityType===type){const surface=Object.keys(lm).find(k=>lm[k]===z)?.split(':').slice(1).join(':');if(surface&&q.includes(surface))hits.push({E:{id:z.canonicalId,names:[surface],source:'LEARNED'},z:surface,s:z.confidence})}hits.sort((x,y)=>y.s-x.s||y.z.length-x.z.length);if(!hits.length)return{id:null,type,confidence:0,source:'UNRESOLVED',candidates:[]};const b=hits[0],second=hits[1]?.s||0,min=Number(S.knowledge?.ambiguity_policy?.minimum_confidence??.82),margin=Number(S.knowledge?.ambiguity_policy?.margin_over_second_best??.08);if(b.s<min||(second&&b.s-second<margin))return{id:null,type,confidence:b.s,source:'AMBIGUOUS',surface:b.z,candidates:hits.slice(0,5).map(x=>({id:x.E.id,surface:x.z,confidence:x.s}))};return{id:b.E.id,type,confidence:b.s,source:b.E.source||'RUNTIME_DATASET',surface:b.z,raw:cp(b.E.raw)}}
function activeMinister(ctx){const r=g.OmegaMinisterStateRegistry,c=t(ctx?.countryId||ctx?.countryCode||g.Game?.state?.countryId||g.Game?.state?.playerCountryId||g.Game?.currentActiveCountry||'').toUpperCase(),m=t(ctx?.ministryId||g.Game?.state?.activeMinistryId||'');if(r&&c&&m&&typeof r.getActiveMinister==='function')try{const x=r.getActiveMinister(c,m);if(x)return x}catch(_){}for(const x of [ctx?.ministerId,g.Game?.state?.activeMinisterId,g.OmegaCabinetUI?.currentInterrogatedMinister?.ministerId])if(x&&S.ministers.has(String(x)))return S.ministers.get(String(x));return null}
function attr(q,lang){return phrase(q,S.attributes,lang)}
function parse(question,ctx={}){const surface=t(question),lang=bn(surface)?'bn':'en',q=n(surface),qh=phrase(q,S.question,lang),at=attr(q,lang),country=entity(q,'COUNTRY'),resource=entity(q,'RESOURCE'),minister=entity(q,'MINISTER'),m=activeMinister(ctx),self=/(^|\s)(you|your|yours|yourself)(\s|$)|তুমি|তোমার|আপনি|আপনার|নিজের/.test(q);if(!minister.id&&self&&m)minister={id:m.ministerId||m.id,type:'MINISTER',confidence:1,source:'AUTHORITATIVE_ACTIVE_MINISTER'};const qt=qh?.v||'UNKNOWN',op=qt==='how_many'?'COUNT':qt==='how_much'?'QUANTITY':qt==='how_old'?'ATTRIBUTE':at?'ATTRIBUTE':qt==='where'?'LOCATE':qt==='what'||qt==='who'?'IDENTIFY':qt==='which'?'SELECT':qt==='why'?'CAUSE':qt==='how'?'METHOD':qt==='should'?'POLICY':qt==='can'?'FEASIBILITY':qt==='will'?'FORECAST':'UNKNOWN';let target=minister.id?'MINISTER':country.id&&resource.id?'COUNTRY_RESOURCE':resource.id?'RESOURCE':country.id?'COUNTRY':self?'MINISTER':'GENERAL';const unresolved=[];if(self&&!minister.id)unresolved.push('MINISTER');if((op==='COUNT'||op==='LOCATE')&&!country.id&&!resource.id)unresolved.push('SUBJECT');return{version:V,surface,language:lang,question:{type:qt,phrase:qh?.p||null,confidence:qh?.s||0},attribute:at?{name:at.v,phrase:at.p,confidence:at.s}:null,targetDomain:target,operation:op,entities:{country,resource,minister},unresolved,confidence:Math.min(qh?.s||1,country.id?country.confidence:1,resource.id?resource.confidence:1,minister.id?minister.confidence:1),executable:!unresolved.length&&op!=='UNKNOWN'}}
function profile(id){const r=g.OmegaMinisterStateRegistry;if(r&&typeof r.getMinister==='function')try{const x=r.getMinister(id);if(x)return x}catch(_){}return S.ministers.get(id)?.raw||null}
function ministerValue(id,k){const x=profile(id);if(!x)return null;const p=x.staticProfile||x.profile||x.identity||x,r=x.runtimeState||x.runtime||{},l=x.learningState||x.learning||{};const map={name:p.baseName??p.name??x.name??id,age:p.baseAge??p.age,background:p.background,gender:p.gender,role:p.role??p.ministryId??r.ministryId,ministry:r.ministryId??x.ministryId,country:r.countryId??x.countryId,experience:l.totalServiceTime,stress:r.stress,workload:r.workload,skill:p.baseStats??p.stats};return map[k]??null}
function walk(v,path,out){if(!o(v))return;if(Array.isArray(v)){v.forEach((x,i)=>walk(x,path.concat(String(i)),out));return}out.push({v,path});for(const[k,x]of Object.entries(v))if(o(x))walk(x,path.concat(k),out)}
function runtimeRoots(){return[...S.datasets.values(),g.ResourceMinistryEngine,g.WorldEcosystemEngine,g.Game?.state,g.gameState,g.Omega?.World,g.Omega?.Resources,g.Omega?.Resource].filter(Boolean)}
function assetRecords(countryId,resourceId,assetClass){const out=[],r=S.resources.get(resourceId),ra=(r?.names||[resourceId]).map(n),words=[];for(const [k,v]of S.assets)if(k.startsWith('en:')||k.startsWith('bn:'))if(v===assetClass)words.push(k.slice(3));const visit=(v,path=[])=>{if(!o(v))return;if(Array.isArray(v)){v.forEach((x,i)=>visit(x,path.concat(String(i))));return}const blob=n(JSON.stringify(v)),pblob=path.map(n).join(' ');const cm=!countryId||blob.includes(n(countryId))||pblob.includes(n(countryId));const rm=!resourceId||blob.includes(n(resourceId))||ra.some(x=>blob.includes(x));const am=words.some(w=>blob.includes(w)||pblob.includes(w));if(cm&&rm&&am)out.push({v,path});for(const[k,x]of Object.entries(v))if(o(x))visit(x,path.concat(k))};runtimeRoots().forEach(x=>walk(x,[],[]));const uniq=new Map();for(const x of out)uniq.set(x.path.join('.'),x);return[...uniq.values()]}
function locations(records){const out=[];const visit=(v,path=[])=>{if(!o(v))return;if(Array.isArray(v)){v.forEach((x,i)=>visit(x,path.concat(String(i))));return}for(const[k,x]of Object.entries(v)){const q=n(k);if(typeof x==='string'&&/(location|region|province|district|city|site|field|basin|deposit|address|latitude|longitude|lat|lng|lon|coordinates|area)/i.test(q))out.push({field:k,value:x,path:path.concat(k)});else if(o(x))visit(x,path.concat(k))}};records.forEach(x=>visit(x.v,x.path));const u=new Set();return out.filter(x=>{const k=x.field+':'+x.value;if(u.has(k))return false;u.add(k);return true}).slice(0,100)}
function resourceState(countryId,resourceId){const e=g.ResourceMinistryEngine;if(e&&typeof e.getIntegratedResourceState==='function')try{const x=e.getIntegratedResourceState(countryId);if(x)return{value:x,source:'ResourceMinistryEngine'}}catch(_){}return null}
function execute(p,ctx={}){if(!S.ready)return{ok:false,reason:'NOT_READY',text:p.language==='bn'?'অফলাইন জ্ঞান স্তর এখনো প্রস্তুত হচ্ছে।':'Offline knowledge is still loading.'};const e=p.entities;if(p.targetDomain==='MINISTER'){if(!e.minister.id)return{ok:false,reason:'MINISTER_UNRESOLVED',text:p.language==='bn'?'বর্তমান মন্ত্রী নির্ধারণ করা যায়নি।':'The current minister could not be resolved.'};const k=p.attribute?.name;if(k){const v=ministerValue(e.minister.id,k);return v===null||v===undefined?{ok:false,reason:'ATTRIBUTE_UNAVAILABLE'}:{ok:true,operation:'ATTRIBUTE',attribute:k,value:v,source:'AUTHORITATIVE_MINISTER_STATE'}}return{ok:true,operation:'IDENTIFY',value:profile(e.minister.id),source:'AUTHORITATIVE_MINISTER_STATE'}}if(p.operation==='COUNT'){const rows=assetRecords(e.country.id,e.resource.id,ctx.assetClass||'MINE');return{ok:true,operation:'COUNT',count:rows.length,countryId:e.country.id||null,resourceId:e.resource.id||null,assetClass:ctx.assetClass||'MINE',evidence:rows.slice(0,50).map(x=>x.path.join('.')),source:'RUNTIME_DATASET_SEARCH'}}if(p.operation==='LOCATE'){const rows=assetRecords(e.country.id,e.resource.id,ctx.assetClass||'MINE');return{ok:true,operation:'LOCATE',count:rows.length,locations:locations(rows),source:'RUNTIME_DATASET_SEARCH',evidence:rows.slice(0,50).map(x=>x.path.join('.'))}}if(p.operation==='QUANTITY'&&e.country.id&&e.resource.id){const s=resourceState(e.country.id,e.resource.id);return s?{ok:true,operation:'QUANTITY',countryId:e.country.id,resourceId:e.resource.id,value:s.value,source:s.source}:{ok:false,reason:'RESOURCE_STATE_UNAVAILABLE'}}if(p.operation==='IDENTIFY'&&e.resource.id)return{ok:true,operation:'IDENTIFY',value:S.resources.get(e.resource.id)?.raw||null,source:'RESOURCE_DATASET'};if(p.operation==='IDENTIFY'&&e.country.id)return{ok:true,operation:'IDENTIFY',value:S.countries.get(e.country.id)?.raw||null,source:'countries.json'};return{ok:false,reason:'NO_EXECUTOR',text:p.language==='bn'?'প্রশ্নটি বোঝা হয়েছে, কিন্তু নির্ভরযোগ্য রানটাইম ডেটা পথ নেই।':'The question was understood, but no reliable runtime data path exists.'}}
function format(p,r){if(!r?.ok)return r?.text||(p.language==='bn'?'নির্ভরযোগ্য তথ্য পাওয়া যায়নি।':'Reliable runtime evidence is not available.');if(r.operation==='ATTRIBUTE')return p.language==='bn'?`${r.attribute}: ${r.value}`:`${r.attribute}: ${r.value}`;if(r.operation==='COUNT')return p.language==='bn'?`রানটাইম ডেটা অনুযায়ী ${r.countryId||'অনুরোধ করা দেশের'}-এ ${r.resourceId?r.resourceId+' সম্পর্কিত ':''}${r.assetClass} রেকর্ডের সংখ্যা ${r.count}টি।`:`Runtime data reports ${r.count} ${r.assetClass}${r.resourceId?' records for '+r.resourceId:''} in ${r.countryId||'the requested country'}.`;if(r.operation==='LOCATE')return p.language==='bn'?`রানটাইম ডেটায় ${r.count}টি রেকর্ড পাওয়া গেছে। ${locations(r.locations||[]).slice(0,20).map(x=>x.field+': '+x.value).join('; ')}`:`The runtime dataset contains ${r.count} matching records. ${r.locations?.slice(0,20).map(x=>x.field+': '+x.value).join('; ')||'No explicit location field was exposed.'}`;if(r.operation==='IDENTIFY')return r.value?.baseName||r.value?.name||r.value?.id||JSON.stringify(r.value||{},null,2);return JSON.stringify(r.value??r,null,2)}
async function init(){try{const[v,k,c,m,o,r]=await Promise.all([load('/offline_language_vocabulary.json'),load('/offline_semantic_knowledge.json'),load('/countries.json'),load('/ministers.json'),load('/resource_ontology.json'),load('/resources.json')]);S.vocab=v;S.knowledge=k;ingestVocabulary();ingestCountries(c);ingestMinisters(m);ingestResources(o);ingestResources(r);S.datasets.set('countries.json',c);S.datasets.set('ministers.json',m);S.datasets.set('resource_ontology.json',o);S.datasets.set('resources.json',r);S.ready=true;g.dispatchEvent(new CustomEvent('OMEGA_SEMANTIC_RUNTIME_READY',{detail:diagnostics()}))}catch(e){addErr('BOOT_FAILED',e.message);console.error('[OMEGA Semantic V3.1]',e)}}
function diagnostics(){return{version:V,ready:S.ready,countries:S.countries.size,resources:S.resources.size,ministers:S.ministers.size,datasets:[...S.datasets.keys()],errors:cp(S.errors)}}
function plan(q,identity={},world={},history=[]){const p=parse(q,{countryId:identity.countryCode||world.countryCode,ministryId:identity.ministryId,ministerId:identity.ministerId});const r=execute(p,{});return{version:V,language:p.language,operation:p.operation,intent:p.targetDomain,entities:p.entities,semantic:p,result:r,derived:r?.operation==='COUNT'?[{metric:'count',value:r.count}]:[],identity,history:a(history).slice(-24)}}
const api={VERSION:V,init,parse,execute,buildAnswerPlan:plan,formatOfflineAnswer:p=>format(p,p.result),diagnostics,registerDataset:(name,data)=>{S.datasets.set(name,data);return diagnostics()},learn:(surface,type,canonicalId,confidence)=>{if(confidence<.95)return false;try{const x=JSON.parse(g.localStorage?.getItem('OMEGA_SEMANTIC_LEARNING_V3')||'{}');x[`${type}:${n(surface)}`]={entityType:type,canonicalId,confidence};g.localStorage?.setItem('OMEGA_SEMANTIC_LEARNING_V3',JSON.stringify(x));return true}catch(_){return false}},recall:()=>{try{return JSON.parse(g.localStorage?.getItem('OMEGA_SEMANTIC_LEARNING_V3')||'{}')}catch(_){return{}}}};
g.OmegaSemanticRuntimeV31=api;
g.OmegaAIIntegrity=Object.freeze({VERSION:V,canonicalMinisterIdentity:x=>({countryCode:t(x.countryCode||x.country||'').toUpperCase(),countryName:t(x.countryName||x.country||''),ministryId:t(x.ministryId||'').toUpperCase(),ministerId:t(x.ministerId||x.id||''),name:t(x.ministerName||x.name||x.id||''),role:t(x.ministerRole||x.role||''),age:Number.isFinite(Number(x.age))?Number(x.age):null,background:t(x.background||''),ideology:typeof x.ideology==='string'?x.ideology:x.ideology?.type||'',efficiency:Number.isFinite(Number(x.efficiency))?Number(x.efficiency):null,profileSource:t(x.profileSource||'RUNTIME_CANONICAL_IDENTITY')}),buildAnswerPlan:plan,formatOfflineAnswer:p=>format(p,p.result),parse,explain:(q,c)=>parse(q,c),diagnostics,learn:api.learn,recall:api.recall});
g.MinisterQueryRouter=Object.freeze({VERSION:V,routeMinisterQuery:(q,m={},w={})=>{const p=parse(q,{...m,...w});return{version:V,intent:p.targetDomain,domain:p.targetDomain,entities:Object.values(p.entities).filter(x=>x?.id),requiredData:[p.operation],semantic:p,executable:p.executable}}});
init();
})(typeof globalThis!=='undefined'?globalThis:window);
