/* OMEGA LIVE MINISTER CONTROL + SEMANTIC INTERROGATION v5.0.0-PRODUCTION */
(function(global){
'use strict';
var VERSION='5.0.0-PRODUCTION',KEY='OMEGA_APPOINTED_MINISTERS_V5',profiles=null,loading=null;
function text(v){return v==null?'':String(v).trim();}
function norm(v){return text(v).toLowerCase().replace(/[&/]+/g,' ').replace(/[._-]+/g,' ').replace(/\s+/g,' ').trim();}
function game(){return global.Game||{};}
function country(){var g=game(),s=g.state||{};return text(g.currentActiveCountry||s.countryId||s.playerCountryId||'BANGLADESH').toUpperCase().replace(/\s+/g,'_');}
function currentMinistry(){var ui=global.OmegaCabinetUI||{},g=game(),s=g.state||{};return text(global.OmegaLayerManager&&global.OmegaLayerManager.activeMinistryId||ui.activeMinistryId||ui.currentMinistryId||s.activeMinistryId||'');}
function storage(){try{return global.localStorage}catch(e){return null;}}
function load(){var s=storage();if(!s)return{};try{return JSON.parse(s.getItem(KEY)||'{}');}catch(e){return{};}}
function save(v){var s=storage();if(!s)return;try{s.setItem(KEY,JSON.stringify(v));}catch(e){}}
function indexFor(m){var v=Number(load()[country()+'_'+m]);return isFinite(v)&&v>=0?Math.floor(v):0;}
function fromUI(m){var ui=global.OmegaCabinetUI;if(!ui||typeof ui.getMinisterProfile!=='function')return[];try{var p=ui.getMinisterProfile(m,country());return p&&Array.isArray(p.candidates)?p.candidates:[];}catch(e){return[];}}
function fromDataset(m){if(!profiles)return[];var wanted=norm(m),out=[],k,a,i,p; if(Array.isArray(profiles)){for(i=0;i<profiles.length;i++){p=profiles[i]||{};if(norm(p.ministryId||p.ministry||p.department||'')===wanted)out.push(p);}return out;} for(k in profiles){if(!Object.prototype.hasOwnProperty.call(profiles,k))continue;a=profiles[k];if(!Array.isArray(a))continue;if(norm(k)===wanted){for(i=0;i<a.length;i++)out.push(a[i]);}else{for(i=0;i<a.length;i++){p=a[i]||{};if(norm(p.ministryId||p.ministry||p.department||'')===wanted)out.push(p);}}}return out;}
function candidates(m){var a=fromUI(m);return a.length?a:fromDataset(m);}
function regionKey(m,c){var ui=global.OmegaCabinetUI;try{var r=ui&&typeof ui.getRegionForCountry==='function'?norm(ui.getRegionForCountry(c)):'';if(r)return r.replace(/\s+/g,'_');}catch(e){}return 'islamic';}
function ministerName(c){var n=text(c&& (c.name||c.ministerName||c.baseName));if(n)return n;var rn=c&&c.regional_names;if(rn&&typeof rn==='object'){var k=regionKey(null,country()),keys=[k,'islamic','south_asia','western','east_asia','sub_saharan','latin_america','slavic','south_east_asia'],i;for(i=0;i<keys.length;i++)if(text(rn[keys[i]]))return text(rn[keys[i]]);}return text(c&& (c.id||c.ministerId||'Minister'));}
function candidateIdentity(c,m,i){return{...c,__omegaIndex:i,name:ministerName(c),ministerId:text(c&& (c.ministerId||c.id)),ministryId:m,countryCode:country(),ministerName:ministerName(c)};}
function syncIdentity(ui,m,c,i){if(!ui||!c)return;var key=country()+'_'+m;ui.appointedMinisterIndex=ui.appointedMinisterIndex||{};ui.appointedMinisterIndex[key]=i;ui.appointedMinisterIndex[m]=i;var x=candidateIdentity(c,m,i);ui.currentInterrogatedMinister=x;if(global.OmegaMinisterStateRegistry&&typeof global.OmegaMinisterStateRegistry.getActiveMinister!=='function'){}try{if(global.OmegaMinisterSystem&&typeof global.OmegaMinisterSystem.getActive==='function'&&typeof global.OmegaMinisterSystem.getMinister==='function'){}}catch(e){} }
function patchDisplayedMinister(ui,m,c){var dash=document.getElementById('ministry-dashboard-view');if(!dash||!c)return;var name=ministerName(c),strongs=dash.querySelectorAll('strong'),i,node;for(i=0;i<strongs.length;i++){node=strongs[i];if(/^\s*Eng\.|^\s*Minister\b/i.test(node.textContent||'')){node.textContent=name;}}var all=dash.querySelectorAll('div,span,p,h1,h2,h3,h4');for(i=0;i<all.length;i++){var t=text(all[i].textContent||'');if(t.indexOf('Minister:')===0&&all[i].querySelector('strong'))all[i].querySelector('strong').textContent=name;}}
function install(m){var ui=global.OmegaCabinetUI,dash=document.getElementById('ministry-dashboard-view'),content=document.getElementById('ministry-dashboard-content');if(!ui||!dash||!content||!m)return false;var cs=candidates(m);if(!cs.length)return false;var old=document.getElementById('omega-live-minister-selector');if(old&&old.parentNode)old.parentNode.removeChild(old);var i=Math.min(indexFor(m),cs.length-1);if(i<0)i=0;var box=document.createElement('section');box.id='omega-live-minister-selector';box.className='omega-minister-selector';box.setAttribute('data-minister-selector','live');box.innerHTML='<div class="omega-minister-selector-title"><label for="omega-minister-choice">ACTIVE MINISTER</label><span id="omega-minister-selector-status">CURRENT</span></div><div class="omega-minister-selector-row"><select id="omega-minister-choice" aria-label="Select Minister"></select><button type="button" id="omega-minister-appoint">CHANGE MINISTER</button></div><div class="omega-minister-selector-meta">Candidate profile, ID, skills and live state are sourced from the minister dataset.</div>';var select=box.querySelector('#omega-minister-choice'),n,c;for(n=0;n<cs.length;n++){c=cs[n]||{};var o=document.createElement('option');o.value=String(n);o.textContent=ministerName(c)+' • '+text(c.id||c.ministerId||'');select.appendChild(o);}select.value=String(i);syncIdentity(ui,m,cs[i],i);patchDisplayedMinister(ui,m,cs[i]);content.insertBefore(box,content.firstChild||null);function refreshIdentity(k){var candidate=cs[k];if(!candidate)return;var store=load();store[country()+'_'+m]=k;save(store);syncIdentity(ui,m,candidate,k);patchDisplayedMinister(ui,m,candidate);var label=box.querySelector('#omega-minister-selector-status');if(label)label.textContent='APPOINTED: '+ministerName(candidate);if(typeof ui.renderMinistryDashboard==='function'){ui.__omegaSelectorRefreshing=true;ui.renderMinistryDashboard(m);setTimeout(function(){ui.__omegaSelectorRefreshing=false;install(m);},60);}}
select.addEventListener('change',function(){var label=box.querySelector('#omega-minister-selector-status');if(label)label.textContent='READY TO CHANGE: '+ministerName(cs[Number(select.value)]||{});});box.querySelector('#omega-minister-appoint').addEventListener('click',function(){refreshIdentity(Number(select.value));});return true;}
function loadProfiles(){if(profiles||loading)return;loading=fetch('ministers.json',{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('ministers.json HTTP '+r.status);return r.json();}).then(function(d){profiles=d&&d.ministers_database||d&&d.ministers||d;return profiles;}).catch(function(e){console.warn('[OMEGA Minister Control] profile load failed',e);profiles=null;}).finally(function(){loading=null;});}
function patchDashboard(){var ui=global.OmegaCabinetUI;if(!ui||ui.__omegaMinisterControlV5)return false;ui.__omegaMinisterControlV5=true;loadProfiles();if(typeof ui.renderMinistryDashboard==='function'){var render=ui.renderMinistryDashboard;ui.renderMinistryDashboard=function(m){var r=render.apply(this,arguments);setTimeout(function(){if(!ui.__omegaSelectorRefreshing)install(m);},0);return r;};}return true;}
function semanticQuestion(){var ui=global.OmegaCabinetUI,semantic=global.OmegaProductionSemanticRuntime;if(!ui||!semantic||typeof semantic.buildAnswerPlan!=='function'||typeof semantic.formatOfflineAnswer!=='function'||typeof ui.processQuestionAndReply!=='function')return false;if(ui.__omegaSemanticQuestionV5)return true;ui.__omegaSemanticQuestionV5=true;ui.__omegaOriginalProcessQuestionAndReply=ui.processQuestionAndReply;ui.processQuestionAndReply=function(minister,questionText){var q=text(questionText),m=minister||ui.currentInterrogatedMinister||{},id=text(m.ministerId||m.id);try{var active=ui.currentInterrogatedMinister||m,identity={countryCode:country(),ministryId:text(active.ministryId||currentMinistry()),ministerId:text(active.ministerId||active.id||id),ministerName:ministerName(active)},history=ui.chatHistories&&ui.chatHistories[identity.ministerId]||[],plan=semantic.buildAnswerPlan(q,identity,game().state||{},history),answer=semantic.formatOfflineAnswer(plan);if(!id)id=identity.ministerId;if(!ui.chatHistories)ui.chatHistories={};if(!ui.chatHistories[id])ui.chatHistories[id]=[];ui.chatHistories[id].push({sender:'USER',text:q,timestamp:Date.now()});ui.chatHistories[id].push({sender:'MINISTER',text:answer,response:answer,timestamp:Date.now(),semanticPlan:plan.semantic||plan,evidence:plan.result||null,source:'OMEGA_RUNTIME_SEMANTIC_V5'});if(typeof ui.renderChatHistory==='function')ui.renderChatHistory(id);return answer;}catch(e){console.error('[OMEGA semantic interrogation]',e);var msg='Semantic runtime could not produce a grounded answer. No canned minister response was used.';if(!ui.chatHistories)ui.chatHistories={};if(!ui.chatHistories[id])ui.chatHistories[id]=[];ui.chatHistories[id].push({sender:'MINISTER',text:msg,response:msg,timestamp:Date.now(),source:'OMEGA_RUNTIME_ERROR'});if(typeof ui.renderChatHistory==='function')ui.renderChatHistory(id);return msg;}};return true;}
function observe(){var dash=document.getElementById('ministry-dashboard-view');if(!dash||dash.__omegaObserverV5)return;if(typeof MutationObserver==='function'){var ob=new MutationObserver(function(){if(dash.style.display!=='none'){var m=currentMinistry();if(m&&!document.getElementById('omega-live-minister-selector'))install(m);}});ob.observe(dash,{childList:true,subtree:true,attributes:true,attributeFilter:['style','class']});dash.__omegaObserverV5=true;}}
function boot(){patchDashboard();semanticQuestion();observe();var m=currentMinistry();if(m)install(m);setTimeout(boot,500);}
global.OmegaLiveMinisterSelector={VERSION:VERSION,install:install};boot();
})(typeof globalThis!=='undefined'?globalThis:window);