/* OMEGA RESOURCE SEMANTIC BRIDGE v4.0.0
 * Grounded resource intelligence over the existing JSON/semantic architecture.
 * No resource/country facts are hardcoded here.
 */
(function(g){
  'use strict';
  const VERSION='4.0.0-PRODUCTION';
  if(g.OmegaResourceSemanticBridge?.VERSION===VERSION)return;
  const S=v=>String(v==null?'':v).trim();
  const N=v=>S(v).normalize('NFKC').replace(/[?!,.:;'"(){}\[\]<>]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
  const O=v=>v&&typeof v==='object'&&!Array.isArray(v);
  const A=v=>Array.isArray(v)?v:[];
  const C=v=>{try{return v===undefined?undefined:JSON.parse(JSON.stringify(v));}catch(_){return null;}};
  const TOKEN=v=>S(v).replace(/[^a-z0-9_]+/gi,'_').replace(/^_+|_+$/g,'').toUpperCase();
  const state={ready:false,error:null,loadedAt:null,ontology:null,countriesRaw:null,resourcesRaw:[],resources:new Map(),resourceRecords:[],countries:new Map(),countryAliases:new Map(),resourceAliases:new Map(),profiles:new Map(),diagnostics:{countrySourceCount:0,countryProfileCount:0,countryIdCount:0,expectedCountryIdCount:197,resourceTypeCount:0,resourceRecordCount:0,linkedResourceCountryCount:0,unresolvedResourceCountryCount:0,exportReady:false}};
  function first(v,keys=[]){if(!O(v))return null;for(const k of keys){const x=v[k];if(x!==undefined&&x!==null&&S(x)!=='')return x;}return null;}
  function addAlias(map,key,id){const n=N(key);if(n&&id!=null)map.set(n,S(id).toUpperCase());}
  function countryRows(raw){if(Array.isArray(raw))return raw;if(Array.isArray(raw?.countries))return raw.countries;if(Array.isArray(raw?.data))return raw.data;if(O(raw))return Object.entries(raw).map(([key,val])=>O(val)?({...val,__sourceKey:key}):({id:key,name:val,__sourceKey:key}));return[];}
  function countryIdentity(raw,fallbackKey=''){const i=O(raw?.identity)?raw.identity:raw;const iso2=S(first(i,['iso2','countryCode','code'])).toUpperCase();const iso3=S(first(i,['iso3','countryId','canonicalId','id'])).toUpperCase();const name=S(first(i,['name','officialName','countryName','shortName','displayName']))||S(raw?.name)||S(fallbackKey);return{iso2,iso3,name,id:iso3||iso2||TOKEN(name)};}
  function findExistingCountryId(i){for(const x of [i.iso3,i.iso2,i.name].filter(Boolean)){const id=state.countryAliases.get(N(x));if(id&&state.countries.has(id))return id;}return null;}
  function migrateCountryKey(oldId,newId){const old=S(oldId).toUpperCase(),next=S(newId).toUpperCase();if(!old||!next||old===next)return;const x=state.countries.get(old);if(x){state.countries.delete(old);state.countries.set(next,{...x,id:next});}for(const[a,id]of state.countryAliases.entries())if(S(id).toUpperCase()===old)state.countryAliases.set(a,next);for(const r of state.resourceRecords)if(S(r.countryId).toUpperCase()===old)r.countryId=next;}
  function registerCountry(raw,fallbackKey='',source='countries.json'){if(!O(raw))return null;const i=countryIdentity(raw,fallbackKey);if(!i.id)return null;const existingId=findExistingCountryId(i);const id=(i.iso3||existingId||i.iso2||TOKEN(i.name)).toUpperCase();if(existingId&&existingId!==id)migrateCountryKey(existingId,id);const old=state.countries.get(id);const merged={id,iso2:i.iso2||old?.iso2||'',iso3:i.iso3||old?.iso3||'',name:i.name||old?.name||'',mapData:source==='countries.json'?C(raw):(old?.mapData||null),profile:source!=='countries.json'?C(raw):(old?.profile||null),sources:[...new Set([...(old?.sources||[]),source])]};state.countries.set(id,merged);for(const x of [id,i.iso2,i.iso3,i.name,first(raw,['officialName','countryName','shortName'])].filter(Boolean))addAlias(state.countryAliases,x,id);return merged;}
  function ingestCountriesJson(raw){state.countriesRaw=C(raw);const rows=countryRows(raw);rows.forEach(x=>registerCountry(x,'','countries.json'));state.diagnostics.countrySourceCount=rows.length;}
  function ingestProfiles(raw){const root=raw?.GSRSK_Master_CountryProfiles_v14?.countryProfiles||raw?.countryProfiles||raw?.countries||raw?.data||{};const entries=Array.isArray(root)?root.map((x,i)=>[x?.identity?.iso3||x?.identity?.iso2||x?.id||String(i+1),x]):Object.entries(root);for(const[key,p]of entries){if(!O(p))continue;const c=registerCountry(p,key,'GSRSK_Master_CountryProfiles');if(c)state.profiles.set(c.id,C(p));}state.diagnostics.countryProfileCount=state.profiles.size;}
  function ingestRelationCountries(raw){const root=raw?.RELATION_GENERATION_ENGINE?.srie_v2_asymmetrical_salience||raw?.srie_v2_asymmetrical_salience||{};for(const[key,v]of Object.entries(root)){if(!O(v))continue;registerCountry({country_code:v.country_code,country_name:v.country_name||key},key,'relation_generation_engine');}}
  function resourceRoot(raw){if(!O(raw))return{};return raw?.COMMODITY_ONTOLOGIES||raw?.resource_types||raw?.resources||raw?.resourceDatabase||raw?.RESOURCE_DATABASE||raw?.GSRSK_Master_Resource_Data_v14?.resource_types||{};}
  function registerResourceType(raw,key=''){if(raw==null)return null;const id=TOKEN(first(raw,['id','key','resource_id','resourceTypeId'])||key);if(!id)return null;const names=[];if(O(raw))for(const k of ['name','resourceName','canonicalName','displayName','label','name_en','name_bn'])if(typeof raw[k]==='string'&&raw[k].trim())names.push(raw[k]);names.push(key,id);const old=state.resources.get(id);const entry={id,names:[...new Set([...(old?.names||[]),...names])],raw:O(raw)?C(raw):{id:key,name:raw}};state.resources.set(id,entry);for(const n of entry.names){addAlias(state.resourceAliases,n,id);addAlias(state.resourceAliases,String(n).replace(/_/g,' '),id);}return entry;}
  function ingestOntology(raw){state.ontology=C(raw);const root=resourceRoot(raw);for(const[k,v]of Object.entries(root||{}))registerResourceType(v,k);state.diagnostics.resourceTypeCount=state.resources.size;}
  function recordCandidate(v,key=''){if(!O(v))return null;const id=S(first(v,['resourceInstanceId','instanceId','depositId','mineId','resource_id','resourceId','id'])||key);const type=first(v,['resourceTypeId','resource_type_id','resourceType','resource','commodityId','commodity','resourceName','commodityName']);const country=first(v,['countryId','countryID','country_id','countryCode','iso3','iso2']);const asset=first(v,['assetClass','assetType','entityType','facilityType','kind']);if(!id&&!type&&!country&&!/(resource|commodity|mine|deposit|ore|field|asset)/i.test(key))return null;return{instanceId:id||key,resourceTypeId:type, countryRaw:country,assetClass:S(asset),raw:v};}
  function ingestResourceDataset(raw,source){if(!O(raw)&&!Array.isArray(raw))return;state.resourcesRaw.push({source,raw:C(raw)});const roots=[];for(const k of ['resources','resourceDatabase','RESOURCE_DATABASE','resource_types'])if(raw?.[k]!=null)roots.push([k,raw[k]]);if(raw?.GSRSK_Master_Resource_Data_v14?.resource_types)roots.push(['GSRSK_Master_Resource_Data_v14',raw.GSRSK_Master_Resource_Data_v14.resource_types]);if(!roots.length&&raw?.GSRSK_Master_CountryProfiles_v14)return;const walk=(v,path,parentType=null)=>{if(Array.isArray(v)){v.forEach((x,i)=>walk(x,path.concat(String(i)),parentType));return;}if(!O(v))return;const key=path[path.length-1]||'';if(['GSRSK_Master_CountryProfiles_v14','countryProfiles','countries'].includes(key))return;const c=recordCandidate(v,key);if(c){const id=TOKEN(c.instanceId||`${source}_${state.resourceRecords.length+1}`);const rt=TOKEN(c.resourceTypeId||parentType||'');const cr=resolveCountry(c.countryRaw);state.resourceRecords.push({id,resourceTypeId:rt||null,countryId:cr.id||S(c.countryRaw).toUpperCase()||null,source,path:path.join('.'),raw:C(c.raw),assetClass:c.assetClass||null});}for(const[k,x]of Object.entries(v)){if(['GSRSK_Master_CountryProfiles_v14','countryProfiles','countries'].includes(k))continue;const next=/resource_types|resources|resourceDatabase|RESOURCE_DATABASE/i.test(key)?TOKEN(k):parentType;walk(x,path.concat(k),next);}};for(const[rootKey,root]of roots)walk(root,[rootKey],null);state.diagnostics.resourceRecordCount=state.resourceRecords.length;}
  function resolveCountry(q){const x=N(q);if(!x)return{id:null,type:'COUNTRY',confidence:0,source:'UNRESOLVED'};const direct=state.countryAliases.get(x);if(direct){const c=state.countries.get(direct);return{id:direct,type:'COUNTRY',confidence:1,source:c?.sources?.join('+')||'COUNTRY_DATA',surface:x,raw:C(c)};}const compact=TOKEN(q);const token=state.countries.get(compact);if(token)return{id:token.id,type:'COUNTRY',confidence:1,source:'COUNTRY_DATA',surface:x,raw:C(token)};let best=null;for(const c of state.countries.values())for(const alias of [c.id,c.iso2,c.iso3,c.name].filter(Boolean)){const a=N(alias);if(a&&x.includes(a)){const score=Math.min(.98,.70+a.length/Math.max(100,x.length*2));if(!best||score>best.confidence)best={id:c.id,type:'COUNTRY',confidence:score,source:c.sources?.join('+')||'COUNTRY_DATA',surface:a,raw:C(c)};}}return best||{id:null,type:'COUNTRY',confidence:0,source:'UNRESOLVED'};}
  function resourceNames(id){const r=state.resources.get(String(id).toUpperCase());return[...new Set([String(id),...(r?.names||[])].map(N).filter(Boolean))];}
  function resolveResource(q){const x=N(q);if(!x)return{id:null,type:'RESOURCE',confidence:0,source:'UNRESOLVED'};const direct=state.resourceAliases.get(x);if(direct&&state.resources.has(direct)){const r=state.resources.get(direct);return{id:r.id,type:'RESOURCE',confidence:1,source:'resource_ontology.json',surface:x,raw:C(r.raw)};}const compact=TOKEN(q);if(state.resources.has(compact)){const r=state.resources.get(compact);return{id:r.id,type:'RESOURCE',confidence:1,source:'RESOURCE_DATA',surface:x,raw:C(r.raw)};}let best=null;for(const[id,r]of state.resources)for(const a0 of r.names||[]){const a=N(a0);if(a&&x.includes(a)){const score=Math.min(.98,.70+a.length/Math.max(100,x.length*2));if(!best||score>best.confidence)best={id,type:'RESOURCE',confidence:score,source:'RESOURCE_DATA',surface:a,raw:C(r.raw)};}}return best||{id:null,type:'RESOURCE',confidence:0,source:'UNRESOLVED'};}
  const LOCATION_KEY=/(location|region|province|district|city|site|field|basin|deposit|address|area|zone|corridor|hub|mine|plant|facility|reservoir|coordinates|latitude|longitude|lat|lng|lon)/i;
  const IDENTIFIER_KEY=/(countryid|country_id|countrycode|iso2|iso3|resourceid|resource_id|resourcetypeid|mineid|depositid|instanceid|operatorid|ownerid)/i;
  function collectLocations(profile,resourceId){if(!O(profile))return[];const aliases=resourceNames(resourceId),out=[],seen=new Set();const push=(field,value,path,kind='location')=>{if(value==null||value==='')return;const key=`${path.join('.')}|${field}|${String(value)}`;if(seen.has(key))return;seen.add(key);out.push({field,value,path:path.join('.'),kind});};const walk=(v,path,linked=false)=>{if(Array.isArray(v)){v.forEach((x,i)=>walk(x,path.concat(String(i)),linked||containsResource(x,aliases)));return;}if(!O(v))return;for(const[k,x]of Object.entries(v)){const cp=path.concat(k);const local=linked||containsResource(k,aliases)||containsResource(x,aliases);if(typeof x==='string'){if(local&&LOCATION_KEY.test(k)&&!IDENTIFIER_KEY.test(k))push(k,x,cp,'location');}else if(O(x)||Array.isArray(x))walk(x,cp,local);}};walk(profile,[]);return out.slice(0,500);}
  function containsResource(v,aliases){const text=N(typeof v==='string'?v:JSON.stringify(v));return aliases.some(a=>a&&text.includes(a));}
  function resolveResourceRecord(entityId){const needle=TOKEN(entityId);if(!needle)return{ok:false,reason:'RESOURCE_ENTITY_ID_MISSING'};const hit=state.resourceRecords.find(r=>TOKEN(r.id)===needle||TOKEN(r.raw?.resourceInstanceId)===needle||TOKEN(r.raw?.instanceId)===needle||TOKEN(r.raw?.mineId)===needle||TOKEN(r.raw?.depositId)===needle||TOKEN(r.raw?.resourceId)===needle);if(!hit)return{ok:false,reason:'RESOURCE_ENTITY_ID_UNRESOLVED',entityId:needle};const c=hit.countryId?state.countries.get(hit.countryId):null;return{ok:true,entityId:hit.id,resourceId:hit.resourceTypeId||null,countryId:hit.countryId||null,country:C(c),assetClass:hit.assetClass||null,locations:collectLocations(hit.raw,hit.resourceTypeId||''),source:hit.source,evidencePath:hit.path,record:C(hit.raw)};}
  function queryResource({resourceId,countryId=null,operation='LOCATE',worldwide=false,assetClass=null}={}){const rr=resolveResource(resourceId);const rid=rr.id||TOKEN(resourceId);if(!rid)return{ok:false,reason:'RESOURCE_UNRESOLVED'};const cr=countryId?resolveCountry(countryId):{id:null};const cid=cr.id;const aliases=resourceNames(rid);const records=state.resourceRecords.filter(r=>(r.resourceTypeId===rid||containsResource(r.raw,aliases))&&(!cid||r.countryId===cid)&&(!assetClass||S(r.assetClass).toUpperCase()===S(assetClass).toUpperCase()));const profiles=cid?[[cid,state.profiles.get(cid)]]:[...state.profiles.entries()];const profileHits=[];for(const[id,p]of profiles){if(!p)continue;const locations=collectLocations(p,rid);if(locations.length)profileHits.push({kind:'COUNTRY_PROFILE',id,resourceId:rid,countryId:id,country:C(state.countries.get(id)),locations,source:'GSRSK_Master_CountryProfiles',path:'GSRSK_Master_CountryProfiles_v14.countryProfiles'});}const matches=[...records.map(x=>({kind:'RESOURCE_RECORD',id:x.id,resourceId:rid,countryId:x.countryId||null,country:x.countryId?C(state.countries.get(x.countryId)):null,locations:collectLocations(x.raw,rid),path:x.path,source:x.source,assetClass:x.assetClass||null,raw:C(x.raw)})),...profileHits];const linked=[...new Set(matches.map(x=>x.countryId).filter(Boolean))];state.diagnostics.linkedResourceCountryCount=linked.length;state.diagnostics.unresolvedResourceCountryCount=matches.filter(x=>!x.countryId).length;if(operation==='COUNT')return{ok:true,operation:'COUNT',resourceId:rid,countryId:cid,count:matches.length,countryIds:linked,source:'OMEGA_RESOURCE_DATA_EXPORT'};if(operation==='LOCATE')return{ok:true,operation:'LOCATE',resourceId:rid,countryId:cid,worldwide:!!worldwide,count:matches.length,countries:linked.map(id=>({countryId:id,country:C(state.countries.get(id))})),locations:matches.flatMap(x=>x.locations.map(l=>({...l,entityId:x.id,entityKind:x.kind,resourceId:rid,countryId:x.countryId||null,country:C(x.countryId?state.countries.get(x.countryId):null),source:x.source,evidencePath:x.path}))),records:matches.map(x=>({id:x.id,kind:x.kind,resourceId:x.resourceId,countryId:x.countryId,assetClass:x.assetClass||null,source:x.source,path:x.path})),source:'OMEGA_RESOURCE_DATA_EXPORT'};return{ok:true,operation,resourceId:rid,countryId:cid,count:matches.length,records:matches.map(x=>({id:x.id,kind:x.kind,resourceId:x.resourceId,countryId:x.countryId,source:x.source,path:x.path})),source:'OMEGA_RESOURCE_DATA_EXPORT'};}
  function parseWithBridge(prompt,ctx){const base=g.OmegaProductionSemanticRuntime;if(!base?.parse)return null;const parsed=base.__omegaResourceBridgeOriginalParse?base.__omegaResourceBridgeOriginalParse(prompt,ctx):base.parse(prompt,ctx);if(!parsed||typeof parsed!=='object')return parsed;const cr=resolveCountry(prompt),rr=resolveResource(prompt),entities={...(parsed.entities||{})};if(cr.id)entities.country=cr;if(rr.id)entities.resource=rr;let operation=String(parsed.operation||'').toUpperCase();const attr=N(parsed.attribute?.name||'');if(rr.id&&attr==='location')operation='LOCATE';else if(rr.id&&operation==='RETRIEVE')operation='IDENTIFY';const target=cr.id&&rr.id?'COUNTRY_RESOURCE':rr.id?'RESOURCE':cr.id?'COUNTRY':parsed.targetDomain||'GENERAL';const unresolved=(parsed.unresolved||[]).filter(x=>x!=='COUNTRY'&&x!=='RESOURCE');return{...parsed,entities,targetDomain:target,operation,unresolved,executable:unresolved.length===0&&operation!=='UNKNOWN'};}
  function executeResource(parsed){const rid=parsed?.entities?.resource?.id;if(!rid)return null;const cid=parsed?.entities?.country?.id||null;if(parsed.operation==='IDENTIFY'){const r=state.resources.get(String(rid).toUpperCase());return{ok:true,operation:'IDENTIFY',resourceId:rid,value:C(r?.raw),source:'resource_ontology.json'};}if(parsed.operation==='COUNT'||parsed.operation==='LOCATE')return queryResource({resourceId:rid,countryId:cid,operation:parsed.operation,worldwide:!cid,assetClass:parsed.assetClass||null});return null;}
  function diagnostics(){state.diagnostics.countryIdCount=state.countries.size;state.diagnostics.resourceTypeCount=state.resources.size;state.diagnostics.resourceRecordCount=state.resourceRecords.length;state.diagnostics.exportReady=state.ready&&state.diagnostics.countryIdCount>0;return{version:VERSION,ready:state.ready,loadedAt:state.loadedAt,countries:state.countries.size,countryProfiles:state.profiles.size,resources:state.resources.size,resourceRecords:state.resourceRecords.length,aliases:{countries:state.countryAliases.size,resources:state.resourceAliases.size},expectedCountryIds:state.diagnostics.expectedCountryIdCount,countryIdCoverage:`${state.countries.size}/${state.diagnostics.expectedCountryIdCount}`,countryIdCoverageComplete:state.countries.size>=state.diagnostics.expectedCountryIdCount,linkedResourceCountries:state.diagnostics.linkedResourceCountryCount,unresolvedResourceCountries:state.diagnostics.unresolvedResourceCountryCount,exportReady:state.diagnostics.exportReady,error:state.error};}
  function exportData({resourceId=null,countryId=null,entityId=null,operation='LOCATE',assetClass=null}={}){if(entityId)return resolveResourceRecord(entityId);if(resourceId)return queryResource({resourceId,countryId,operation,worldwide:!countryId,assetClass});return{ok:true,diagnostics:diagnostics(),countries:[...state.countries.values()].map(C),resources:[...state.resources.values()].map(C),resourceRecords:state.resourceRecords.map(C),source:'OMEGA_RESOURCE_DATA_EXPORT'};}
  function install(){const base=g.OmegaProductionSemanticRuntime;if(!base||typeof base.parse!=='function'||typeof base.buildAnswerPlan!=='function')return false;if(!base.__omegaResourceBridgeV400){base.__omegaResourceBridgeOriginalParse=base.parse;base.__omegaResourceBridgeOriginalBuildAnswerPlan=base.buildAnswerPlan;base.parse=(prompt,ctx={})=>parseWithBridge(prompt,ctx);base.explain=(prompt,ctx={})=>{const p=base.parse(prompt,ctx);return{language:p?.language,question:p?.question,attribute:p?.attribute,assetClass:p?.assetClass,targetDomain:p?.targetDomain,operation:p?.operation,entities:p?.entities,unresolved:p?.unresolved,confidence:p?.confidence,executable:p?.executable};};base.buildAnswerPlan=(prompt,input={},world={},history=[])=>{const p=parseWithBridge(prompt,{...input,worldState:world});const original=base.__omegaResourceBridgeOriginalBuildAnswerPlan(prompt,input,world,history);const override=executeResource(p);return override?{...original,version:VERSION,language:p.language,question:p.question,intent:p.targetDomain,operation:p.operation,entities:p.entities,semantic:p,result:override}:{...original,semantic:p,entities:p.entities,intent:p.targetDomain,operation:p.operation};};base.__omegaResourceBridgeV400=true;}return true;}
  async function loadJson(path,optional=false){try{if(typeof process!=='undefined'&&process.versions?.node){const fs=await import('node:fs/promises');const cwd=typeof process.cwd==='function'?process.cwd():'.';return JSON.parse(await fs.readFile(`${cwd}/${path}`,'utf8'));}const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);return await r.json();}catch(e){if(optional)return null;throw e;}}
  async function init(){try{const[ontology,countries,r1,r2,relations]=await Promise.all([loadJson('resource_ontology.json'),loadJson('countries.json'),loadJson('resources.json'),loadJson('resources_2.json',true),loadJson('relation_generation_engine.json',true)]);ingestCountriesJson(countries);ingestProfiles(r1);if(r2)ingestProfiles(r2);if(relations)ingestRelationCountries(relations);ingestOntology(ontology);ingestResourceDataset(r1,'resources.json');if(r2)ingestResourceDataset(r2,'resources_2.json');state.ready=true;state.loadedAt=Date.now();state.error=null;const d=diagnostics();try{g.dispatchEvent(new CustomEvent('OMEGA_RESOURCE_SEMANTIC_READY',{detail:d}));}catch(_){}return d;}catch(e){state.ready=false;state.error=e?.message||String(e);console.error('[OMEGA Resource Semantic Bridge]',state.error);return diagnostics();}}
  g.OmegaResourceSemanticBridge={VERSION,init,install,diagnostics,resolveCountry,resolveResource,resolveResourceRecord,queryResource,exportData,collectLocations,executeResource,ontology:()=>C(state.ontology)};
  const boot=setInterval(()=>{if(install()&&state.ready)clearInterval(boot);},50);setTimeout(()=>clearInterval(boot),15000);init();
})(typeof globalThis!=='undefined'?globalThis:window);
