/*
 * OMEGA LANGUAGE SYSTEM v1.3.0
 * Single-file canonical linguistic runtime.
 *
 * Batch 01 adds twelve deep semantic anchor concepts while preserving the
 * existing runtime/bridge architecture. World-state facts remain owned by
 * authoritative game datasets. No eval(), Function(), dynamic code generation
 * or answer-fact catalogue.
 */
(function (global) {
  'use strict';

  const VERSION = '1.3.0';
  const SCHEMA_VERSION = 'OMEGA-LANGUAGE-SYSTEM/1.3';
  const MAX_INPUT_CHARS = 20000;
  const MAX_HISTORY_TURNS = 200;
  const MAX_LEARNED_MAPPINGS = 512;
  const MIN_ENTITY_CONFIDENCE = 0.82;
  const SECOND_BEST_MARGIN = 0.08;

  /* Lossless in-file ontology. Batch 01 is deliberately semantic, not merely lexical. */
  const EMBEDDED_GAME_LANGUAGE_ONTOLOGY = Object.freeze({
    schema_version: '1.1.0',
    ontology_id: 'OMEGA_GAME_LANGUAGE',
    implementation_status: 'BATCH_01_DEEP_SEMANTIC_LOCKED',
    canonical_concept_target: 4500,
    counting_rule: 'A concept_id counts once. Synonyms, aliases, inflections, phrases, and bilingual realizations never count as additional concepts.',
    separation_of_concerns: {
      language_core: 'Canonical game-language concepts, lexical realizations, morphology, grammar, semantic roles, semantic relations and operational compatibility.',
      domain_knowledge: 'Existing country/resource/minister/facility datasets remain authoritative for world entities and facts.',
      capability_registry: 'Determines whether a requested game operation is actually executable; vocabulary alone never grants capability.',
      reasoning: 'Consumes deterministic runtime evidence and may infer only within the evidence boundary.'
    },
    tiers: {
      P0: 'Core game control and command language',
      P1: 'Core simulation state and operational language',
      P2: 'Strategy, policy, trade-offs and analysis',
      P3: 'Advanced analysis and specialized domain language',
      P4: 'Rare technical/domain language'
    },
    target_tiers: { core_game_language: 3200, advanced_strategy_language: 800, grammar_discourse_command_language: 500 },
    domains: [
      {id:'GAME_STATE',name:'Core Game State & Simulation',target:300},
      {id:'GOVERNMENT',name:'Government & State Administration',target:350},
      {id:'POLITICS',name:'Politics & Political Strategy',target:300},
      {id:'ECONOMY',name:'Economy & Macroeconomics',target:450},
      {id:'RESOURCES',name:'Resources & Raw Materials',target:500},
      {id:'EXTRACTION_PRODUCTION',name:'Extraction, Mining & Production',target:400},
      {id:'INDUSTRY',name:'Industrial Capacity & Factories',target:250},
      {id:'TRADE_LOGISTICS',name:'Trade, Import, Export & Logistics',target:400},
      {id:'ENERGY',name:'Energy System',target:250},
      {id:'INFRASTRUCTURE',name:'Infrastructure',target:250},
      {id:'POPULATION_SOCIETY',name:'Population & Society',target:250},
      {id:'MILITARY',name:'Military & Defense',target:350},
      {id:'DIPLOMACY',name:'Diplomacy & International Relations',target:300},
      {id:'TECHNOLOGY',name:'Technology, Research & Industrial Development',target:250},
      {id:'RISK_REASONING',name:'Risk, Causality, Strategy & Reasoning',target:300},
      {id:'GAME_ACTIONS',name:'Game Action & Policy Operators',target:250},
      {id:'LANGUAGE_CONTROL',name:'Language, Grammar & Discourse Control',target:100}
    ],
    concept_contract: {
      required: ['concept_id','domain','subdomain','semantic_type','lexical.en','lexical.bn','derivational_family','morphological_eligibility','morphology','grammar_features','semantic_roles','compatible_variables','compatible_entities','allowed_actions','relations','construction_patterns','phrase_patterns','paraphrase_family','runtime_resolution','register','priority'],
      lexical: { english:['lemma','aliases','forms','pos'], bengali:['lemma','aliases','forms','pos'] },
      semantic_identity: 'concept_id is the only canonical identity; surface strings are realizations, never identities.',
      semantic_rule: 'Parent, child, related, causal and compatibility relations describe semantic possibilities. They do not manufacture world facts or numeric effects.'
    },
    grammar: {
      source_alignment: 'Universal-Dependencies-compatible feature names where useful, with an OMEGA game-optimized subset.',
      features: ['Person','Number','Case','Tense','Aspect','Mood','Voice','Polarity','Degree','VerbForm'],
      bengali_case_subset: ['Nom','Gen','Acc','Loc'],
      verb_forms: ['Fin','Inf','Part','Vnoun'],
      dependency_relations: ['nsubj','obj','obl','advmod','aux','mark','conj','nmod'],
      rule: 'Grammar metadata describes a realization; it never creates a new canonical concept.'
    },
    semantic_pipeline: ['LEXICAL','MORPHOLOGICAL','SYNTACTIC','SEMANTIC','OPERATIONAL'],
    operational_rules: {
      direction: ['POSITIVE_CHANGE','NEGATIVE_CHANGE','NEUTRAL'],
      action_parameters: ['actor','target','amount','unit','time_horizon','scope','constraint','condition'],
      capability_boundary: 'A compatible action is a semantic possibility, not proof that the game currently permits execution.',
      unknown_entity: 'UNRESOLVED',
      ambiguous_entity: 'ASK_OR_REPORT_AMBIGUITY',
      unknown_fact: 'UNKNOWN_WHEN_NOT_EVIDENCED'
    },
    seed_concepts: [
      {
        concept_id:'STATE_VARIABLE', domain:'GAME_STATE', subdomain:'STATE', semantic_type:'STATE_VARIABLE',
        lexical:{en:{lemma:'state variable',aliases:['state','status','condition','measurable state','game state'],forms:['state variable','state','status','condition'],pos:['NOUN']},bn:{lemma:'অবস্থা চলক',aliases:['অবস্থা','স্থিতি','পরিস্থিতি','গেমের অবস্থা'],forms:['অবস্থা চলক','অবস্থা','স্থিতি','পরিস্থিতি'],pos:['NOUN']}},
        derivational_family:['state','status','stateful','state variable'], morphological_eligibility:{noun:true,adjective:false,verb:false,compound:true}, morphology:{derivation:'runtime',inflectional_features:['Number','Case']}, grammar_features:{semantic_head:'NOUN'},
        semantic_roles:['TARGET','BASELINE','CURRENT_STATE','DESIRED_STATE'], compatible_variables:['PRODUCTION','PRICE','DEMAND','SUPPLY','CAPACITY','GDP','RESERVE','READINESS','STABILITY'], compatible_entities:['COUNTRY','RESOURCE','FACILITY','ECONOMIC_VARIABLE','MILITARY_VARIABLE'], allowed_actions:['COMPARE','FORECAST','ANALYZE','MAINTAIN','INCREASE','DECREASE'],
        relations:[{relation:'semantic_root_for',target:'RESOURCE_PRODUCTION'},{relation:'semantic_root_for',target:'CAPACITY'},{relation:'semantic_root_for',target:'DEMAND'},{relation:'semantic_root_for',target:'SUPPLY'},{relation:'semantic_root_for',target:'PRICE'}],
        construction_patterns:['{state_variable} of {entity}','{entity} {state_variable}','current {state_variable}','{state_variable} is {value}'], phrase_patterns:['{target} state','state of {entity}'], paraphrase_family:'STATE_VARIABLE', runtime_resolution:{strategy:'resolve_to_game_state_variable',requires:['canonical_variable_registry'],never:['hardcoded_world_fact'],confidence_floor:0.82}, register:['neutral','formal','technical'], priority:'P1'
      },
      {
        concept_id:'RESOURCE_PRODUCTION', domain:'RESOURCES', subdomain:'PRODUCTION', semantic_type:'STATE_VARIABLE',
        lexical:{en:{lemma:'production',aliases:['output','production rate','domestic output','resource production'],forms:['production','output','production rate','domestic output'],pos:['NOUN']},bn:{lemma:'উৎপাদন',aliases:['উৎপাদনের পরিমাণ','উৎপাদন হার','আউটপুট','সম্পদ উৎপাদন'],forms:['উৎপাদন','উৎপাদনের পরিমাণ','উৎপাদন হার','আউটপুট'],pos:['NOUN']}},
        derivational_family:['produce','production','producer','productive','produced','output'], morphological_eligibility:{noun:true,verb:true,adjective:true,compound:true}, morphology:{derivation:'produce -> production',runtime_inflection:true}, grammar_features:{noun:true,verb_compatible:true},
        semantic_roles:['TARGET','BASELINE','DESIRED_STATE','MEASURED_OUTPUT','RATE'], compatible_variables:['PRODUCTION'], compatible_entities:['RESOURCE','COUNTRY','PRODUCTION_FACILITY'], allowed_actions:['INCREASE','DECREASE','MAINTAIN','FORECAST','COMPARE','ANALYZE'],
        relations:[{relation:'child_of',target:'STATE_VARIABLE'},{relation:'measured_by',target:'QUANTITY'},{relation:'measured_as',target:'RATE'},{relation:'constrained_by',target:'CAPACITY'},{relation:'changed_by',target:'ACTION_INCREASE'},{relation:'changed_by',target:'ACTION_DECREASE'}],
        construction_patterns:['{entity} production','production of {resource}','{resource} production per {unit_time}','increase/decrease {entity} production'], phrase_patterns:['{target} production','production of {target}','production rate of {target}'], paraphrase_family:'PRODUCTION', runtime_resolution:{strategy:'resolve_production_variable',requires:['resource_or_country_entity','production_variable'],fallback:'UNRESOLVED',never:['infer_numeric_value_without_game_data']}, register:['neutral','technical','formal'], priority:'P0'
      },
      {
        concept_id:'ACTION_INCREASE', domain:'GAME_ACTIONS', subdomain:'CHANGE_OF_STATE', semantic_type:'ACTION',
        lexical:{en:{lemma:'increase',aliases:['raise','boost','expand','grow','increase by'],forms:['increase','increases','increased','increasing','raise','boost','expand','grow'],pos:['VERB']},bn:{lemma:'বাড়ানো',aliases:['বৃদ্ধি করা','বাড়িয়ে দেওয়া','উন্নীত করা','বাড়ানো হবে'],forms:['বাড়ানো','বৃদ্ধি করা','বাড়িয়ে দেওয়া','উন্নীত করা'],pos:['VERB']}},
        derivational_family:['increase','increasing','increased','increment','raise','boost'], morphological_eligibility:{noun:true,verb:true,adjective:true,compound:true}, morphology:{derivation:'runtime',inflectional_features:['Tense','Aspect','Mood','Voice','Polarity','Person','Number','VerbForm']}, grammar_features:{direction:'POSITIVE_CHANGE'},
        semantic_roles:['ACTOR','TARGET','AMOUNT','UNIT','TIME_HORIZON','SCOPE','CONSTRAINT','CONDITION'], compatible_variables:['PRODUCTION','EXPORTS','IMPORTS','CAPACITY','GDP','ENERGY','POPULATION','DEMAND','SUPPLY','PRICE'], compatible_entities:['COUNTRY','RESOURCE','FACILITY','ECONOMIC_VARIABLE'], allowed_actions:['INCREASE'],
        relations:[{relation:'action_family',target:'ACTION_DECREASE'},{relation:'operates_on',target:'STATE_VARIABLE'}],
        construction_patterns:['increase {target}','{actor} increases {target}','increase {target} by {amount}','increase {target} to {desired_state}','increase {target} over {time_horizon}'], phrase_patterns:['increase {target}','raise {target}','boost {target}','বাড়াও {target}','{target} বাড়াও'], paraphrase_family:'POSITIVE_CHANGE', runtime_resolution:{strategy:'build_action_frame',required_slots:['target'],optional_slots:['actor','amount','unit','time_horizon','scope','constraint','condition'],execution_boundary:'CAPABILITY_REGISTRY'}, register:['neutral','formal','technical'], priority:'P0'
      },
      {
        concept_id:'ACTION_DECREASE', domain:'GAME_ACTIONS', subdomain:'CHANGE_OF_STATE', semantic_type:'ACTION',
        lexical:{en:{lemma:'decrease',aliases:['reduce','lower','cut','shrink','decrease by'],forms:['decrease','decreases','decreased','decreasing','reduce','lower','cut','shrink'],pos:['VERB']},bn:{lemma:'কমানো',aliases:['হ্রাস করা','কমিয়ে দেওয়া','কমানো হবে'],forms:['কমানো','হ্রাস করা','কমিয়ে দেওয়া','কমানো হবে'],pos:['VERB']}},
        derivational_family:['decrease','decreasing','decreased','reduction','reduce','lower'], morphological_eligibility:{noun:true,verb:true,adjective:true,compound:true}, morphology:{derivation:'runtime',inflectional_features:['Tense','Aspect','Mood','Voice','Polarity','Person','Number','VerbForm']}, grammar_features:{direction:'NEGATIVE_CHANGE'},
        semantic_roles:['ACTOR','TARGET','AMOUNT','UNIT','TIME_HORIZON','SCOPE','CONSTRAINT','CONDITION'], compatible_variables:['PRODUCTION','IMPORTS','EXPENDITURE','DEMAND','DEPENDENCY','EMISSIONS'], compatible_entities:['COUNTRY','RESOURCE','FACILITY','ECONOMIC_VARIABLE'], allowed_actions:['DECREASE'],
        relations:[{relation:'action_family',target:'ACTION_INCREASE'},{relation:'operates_on',target:'STATE_VARIABLE'},{relation:'direction',target:'NEGATIVE_CHANGE'}],
        construction_patterns:['decrease {target}','{actor} decreases {target}','reduce {target} by {amount}','lower {target} to {desired_state}'], phrase_patterns:['decrease {target}','reduce {target}','lower {target}','{target} কমাও'], paraphrase_family:'NEGATIVE_CHANGE', runtime_resolution:{strategy:'build_action_frame',required_slots:['target'],optional_slots:['actor','amount','unit','time_horizon','scope','constraint','condition'],execution_boundary:'CAPABILITY_REGISTRY',arbitrary_target:false}, register:['neutral','formal','technical'], priority:'P0'
      },
      {
        concept_id:'RESOURCE', domain:'RESOURCES', subdomain:'RESOURCE_CLASS', semantic_type:'ENTITY_TYPE',
        lexical:{en:{lemma:'resource',aliases:['raw material','energy resource','mineral','agricultural resource','strategic resource'],forms:['resource','resources','raw material','raw materials'],pos:['NOUN']},bn:{lemma:'সম্পদ',aliases:['কাঁচামাল','জ্বালানি সম্পদ','খনিজ','কৃষি সম্পদ','কৌশলগত সম্পদ'],forms:['সম্পদ','সম্পদসমূহ','কাঁচামাল','খনিজ'],pos:['NOUN']}},
        derivational_family:['resource','resourceful','resourcing'], morphological_eligibility:{noun:true,verb:false,adjective:true,compound:true}, morphology:{derivation:'resource -> resourcing'}, grammar_features:{entity_type:'RESOURCE'},
        semantic_roles:['ENTITY','TARGET','SOURCE','INPUT','OUTPUT','STOCK','TRADE_GOOD'], compatible_variables:['PRODUCTION','RESERVE','STOCKPILE','SUPPLY','DEMAND','PRICE','CAPACITY'], compatible_entities:['COUNTRY','PRODUCTION_FACILITY','RESOURCE','MARKET'], allowed_actions:['IDENTIFY','COUNT','QUANTITY','COMPARE','ANALYZE','INCREASE','DECREASE','IMPORT','EXPORT','ALLOCATE'],
        relations:[{relation:'semantic_root_for',target:'RESOURCE_PRODUCTION'},{relation:'has_state',target:'RESERVE'},{relation:'has_state',target:'STOCKPILE'},{relation:'traded_as',target:'TRADE_GOOD'}],
        construction_patterns:['{country} resource','resource production','resource reserve','resource supply','resource demand','resource price'], phrase_patterns:['raw material','energy resource','strategic resource','কাঁচামাল','কৌশলগত সম্পদ'], paraphrase_family:'RESOURCE_ENTITY', runtime_resolution:{strategy:'resolve_from_resource_registry',requires:['authoritative_resource_dataset'],never:['hardcoded_resource_catalog'],unknown:'UNRESOLVED'}, register:['neutral','technical','formal'], priority:'P0'
      },
      {
        concept_id:'CAPACITY', domain:'INDUSTRY', subdomain:'CAPACITY', semantic_type:'STATE_VARIABLE',
        lexical:{en:{lemma:'capacity',aliases:['production capacity','industrial capacity','processing capacity','facility capacity'],forms:['capacity','production capacity','industrial capacity','processing capacity'],pos:['NOUN']},bn:{lemma:'সক্ষমতা',aliases:['উৎপাদন সক্ষমতা','শিল্প সক্ষমতা','প্রক্রিয়াজাতকরণ সক্ষমতা'],forms:['সক্ষমতা','উৎপাদন সক্ষমতা','শিল্প সক্ষমতা','প্রক্রিয়াজাতকরণ সক্ষমতা'],pos:['NOUN']}},
        derivational_family:['capacity','capable','capability','capacitate'], morphological_eligibility:{noun:true,verb:false,adjective:true,compound:true}, morphology:{derivation:'capacity -> capable/capability'}, grammar_features:{measurement_required:true},
        semantic_roles:['TARGET','CONSTRAINT','CURRENT_STATE','MAXIMUM_RATE'], compatible_variables:['CAPACITY','PRODUCTION','INVESTMENT','TECHNOLOGY'], compatible_entities:['PRODUCTION_FACILITY','COUNTRY','INDUSTRY'], allowed_actions:['COMPARE','FORECAST','ANALYZE','INCREASE','DECREASE','UPGRADE','BUILD'],
        relations:[{relation:'constrains',target:'PRODUCTION'},{relation:'affected_by',target:'INVESTMENT'},{relation:'affected_by',target:'TECHNOLOGY'},{relation:'associated_with',target:'PRODUCTION_FACILITY'},{relation:'changed_by',target:'UPGRADE'}],
        construction_patterns:['{facility} capacity','production capacity of {facility}','increase capacity of {facility}','capacity for {resource}'], phrase_patterns:['production capacity','industrial capacity','facility capacity','উৎপাদন সক্ষমতা'], paraphrase_family:'CAPACITY', runtime_resolution:{strategy:'resolve_capacity_variable',requires:['facility_or_industry_entity'],link_to:['production_constraint_registry'],never:['assume_capacity_equals_production']}, register:['neutral','technical','formal'], priority:'P0'
      },
      {
        concept_id:'DEMAND', domain:'ECONOMY', subdomain:'MARKET_STATE', semantic_type:'STATE_VARIABLE',
        lexical:{en:{lemma:'demand',aliases:['market demand','domestic demand','consumption demand'],forms:['demand','market demand','domestic demand'],pos:['NOUN']},bn:{lemma:'চাহিদা',aliases:['বাজার চাহিদা','দেশীয় চাহিদা','ভোগ চাহিদা'],forms:['চাহিদা','বাজার চাহিদা','দেশীয় চাহিদা'],pos:['NOUN']}},
        derivational_family:['demand','demanding'], morphological_eligibility:{noun:true,verb:false,adjective:true,compound:true}, morphology:{derivation:'demand -> demanding'}, grammar_features:{market_variable:true},
        semantic_roles:['TARGET','BASELINE','MARKET','CONSUMER_SIDE'], compatible_variables:['DEMAND','PRICE','SUPPLY','IMPORT','PRODUCTION','POPULATION','CONSUMPTION'], compatible_entities:['COUNTRY','RESOURCE','MARKET','PRODUCT'], allowed_actions:['COMPARE','FORECAST','ANALYZE','INCREASE','DECREASE'],
        relations:[{relation:'related_to',target:'PRICE'},{relation:'related_to',target:'SUPPLY'},{relation:'affects',target:'IMPORT'},{relation:'affects',target:'PRODUCTION'},{relation:'influenced_by',target:'POPULATION'},{relation:'influenced_by',target:'CONSUMPTION'}],
        construction_patterns:['demand for {resource}','{country} demand for {resource}','domestic demand','demand is rising/falling'], phrase_patterns:['demand for {target}','market demand','চাহিদা {target}'], paraphrase_family:'DEMAND', runtime_resolution:{strategy:'resolve_market_variable',requires:['market_or_entity_context'],causality:'game_data_authoritative',never:['derive_causal_effect_from_ontology_only']}, register:['neutral','economic','technical'], priority:'P1'
      },
      {
        concept_id:'SUPPLY', domain:'ECONOMY', subdomain:'MARKET_STATE', semantic_type:'STATE_VARIABLE',
        lexical:{en:{lemma:'supply',aliases:['market supply','domestic supply','available supply'],forms:['supply','market supply','domestic supply'],pos:['NOUN']},bn:{lemma:'জোগান',aliases:['সরবরাহ','বাজার জোগান','দেশীয় সরবরাহ'],forms:['জোগান','সরবরাহ','বাজার জোগান','দেশীয় সরবরাহ'],pos:['NOUN']}},
        derivational_family:['supply','supplier','supplied','supplying'], morphological_eligibility:{noun:true,verb:true,adjective:true,compound:true}, morphology:{derivation:'supply -> supplier/supplying'}, grammar_features:{market_variable:true},
        semantic_roles:['TARGET','BASELINE','SOURCE_SIDE','AVAILABLE_QUANTITY'], compatible_variables:['SUPPLY','PRODUCTION','IMPORT','EXPORT','STOCKPILE','CAPACITY'], compatible_entities:['COUNTRY','RESOURCE','MARKET','PRODUCTION_FACILITY'], allowed_actions:['COMPARE','FORECAST','ANALYZE','INCREASE','DECREASE','IMPORT','EXPORT'],
        relations:[{relation:'related_to',target:'PRODUCTION'},{relation:'related_to',target:'IMPORT'},{relation:'related_to',target:'EXPORT'},{relation:'related_to',target:'STOCKPILE'},{relation:'constrained_by',target:'CAPACITY'},{relation:'paired_with',target:'DEMAND'}],
        construction_patterns:['supply of {resource}','{country} supply','supply is falling/rising','shortage in supply'], phrase_patterns:['supply of {target}','market supply','সরবরাহ {target}','জোগান {target}'], paraphrase_family:'SUPPLY', runtime_resolution:{strategy:'resolve_market_variable',requires:['market_or_entity_context'],causality:'game_data_authoritative',diagnostic_frame:'SUPPLY_CHANGE_CAUSE',never:['equate_supply_with_production']}, register:['neutral','economic','technical'], priority:'P1'
      },
      {
        concept_id:'PRICE', domain:'ECONOMY', subdomain:'MARKET_STATE', semantic_type:'MEASUREMENT',
        lexical:{en:{lemma:'price',aliases:['unit price','market price','selling price'],forms:['price','unit price','market price','selling price'],pos:['NOUN']},bn:{lemma:'দাম',aliases:['মূল্য','একক মূল্য','বাজারমূল্য','বিক্রয়মূল্য'],forms:['দাম','মূল্য','একক মূল্য','বাজারমূল্য','বিক্রয়মূল্য'],pos:['NOUN']}},
        derivational_family:['price','pricing','priced','priceless'], morphological_eligibility:{noun:true,verb:true,adjective:true,compound:true}, morphology:{derivation:'price -> pricing'}, grammar_features:{measurement:true},
        semantic_roles:['TARGET','VALUE','UNIT','MARKET','TIME'], compatible_variables:['PRICE','DEMAND','SUPPLY','COST'], compatible_entities:['RESOURCE','PRODUCT','MARKET','COUNTRY'], allowed_actions:['QUANTITY','COMPARE','FORECAST','ANALYZE','INCREASE','DECREASE'],
        relations:[{relation:'related_to',target:'DEMAND'},{relation:'related_to',target:'SUPPLY'},{relation:'distinct_from',target:'COST'}],
        construction_patterns:['price of {resource}','{resource} price','unit price of {resource}','market price'], phrase_patterns:['price of {target}','unit price','market price','{target} দাম','{target} মূল্য'], paraphrase_family:'PRICE', runtime_resolution:{strategy:'resolve_price_variable',requires:['good_or_resource_entity','unit_context_or_price_registry'],never:['treat_cost_as_price','invent_currency_or_numeric_value']}, register:['neutral','economic','technical'], priority:'P1'
      },
      {
        concept_id:'COUNTRY', domain:'GAME_STATE', subdomain:'WORLD_ENTITY_TYPE', semantic_type:'ENTITY_TYPE',
        lexical:{en:{lemma:'country',aliases:['nation','state'],forms:['country','countries','nation','nations','state','states'],pos:['NOUN']},bn:{lemma:'দেশ',aliases:['রাষ্ট্র','জাতি'],forms:['দেশ','দেশসমূহ','রাষ্ট্র','রাষ্ট্রসমূহ'],pos:['NOUN']}},
        derivational_family:['country','countries','national','nation','state'], morphological_eligibility:{noun:true,adjective:true,verb:false,compound:true}, morphology:{plural:'countries',runtime_bilingual_inflection:true}, grammar_features:{entity_type:'COUNTRY'},
        semantic_roles:['ENTITY','ACTOR','OWNER','LOCATION','SCOPE'], compatible_variables:['*'], compatible_entities:['COUNTRY'], allowed_actions:['IDENTIFY','SELECT','COMPARE','ANALYZE','INCREASE','DECREASE','IMPORT','EXPORT','ALLOCATE'],
        relations:[{relation:'entity_type_reference',target:'WORLD_DATASET'},{relation:'not_a_catalog',target:'COUNTRY_FACTS'}],
        construction_patterns:['{country} {variable}','in {country}','for {country}','{country} increases {variable}'], phrase_patterns:['country of {entity}','দেশ {entity}','রাষ্ট্র {entity}'], paraphrase_family:'COUNTRY_ENTITY_TYPE', runtime_resolution:{strategy:'resolve_entity_from_world_dataset',requires:['authoritative_country_registry'],never:['hardcoded_country_catalog','hardcoded_country_facts'],unknown:'UNRESOLVED',ambiguous:'ASK_OR_REPORT_AMBIGUITY'}, register:['neutral','formal'], priority:'P0'
      },
      {
        concept_id:'PRODUCTION_FACILITY', domain:'INDUSTRY', subdomain:'FACILITY', semantic_type:'ENTITY_TYPE',
        lexical:{en:{lemma:'production facility',aliases:['plant','factory','mine','refinery','processing facility'],forms:['production facility','plant','factory','mine','refinery','processing facility'],pos:['NOUN']},bn:{lemma:'উৎপাদন স্থাপনা',aliases:['কারখানা','খনি','শোধনাগার','প্রক্রিয়াজাতকরণ স্থাপনা'],forms:['উৎপাদন স্থাপনা','কারখানা','খনি','শোধনাগার','প্রক্রিয়াজাতকরণ স্থাপনা'],pos:['NOUN']}},
        derivational_family:['produce','production','facility','factory','industrial'], morphological_eligibility:{noun:true,adjective:true,verb:false,compound:true}, morphology:{compound:['production','facility'],runtime_inflection:true}, grammar_features:{entity_type:'FACILITY'},
        semantic_roles:['ENTITY','PRODUCER','LOCATION','OUTPUT','CAPACITY_OWNER'], compatible_variables:['CAPACITY','PRODUCTION','INVESTMENT','TECHNOLOGY'], compatible_entities:['RESOURCE','PRODUCT','COUNTRY','PRODUCTION_FACILITY'], allowed_actions:['IDENTIFY','COMPARE','BUILD','UPGRADE','INCREASE','DECREASE','ANALYZE'],
        relations:[{relation:'produces',target:'RESOURCE'},{relation:'produces',target:'PRODUCT'},{relation:'has',target:'CAPACITY'},{relation:'affected_by',target:'INVESTMENT'},{relation:'upgraded_by',target:'UPGRADE'},{relation:'located_in',target:'COUNTRY'}],
        construction_patterns:['{facility} produces {resource}','capacity of {facility}','{facility} in {country}','upgrade {facility}'], phrase_patterns:['production facility','production plant','factory producing {target}','উৎপাদন স্থাপনা'], paraphrase_family:'PRODUCTION_FACILITY', runtime_resolution:{strategy:'resolve_facility_from_world_dataset',requires:['authoritative_facility_dataset'],link_fields:['country','outputs','capacity'],never:['hardcoded_facility_catalog'],unknown:'UNRESOLVED'}, register:['neutral','technical'], priority:'P1'
      },
      {
        concept_id:'INVESTMENT', domain:'ECONOMY', subdomain:'CAPITAL_ALLOCATION', semantic_type:'PROCESS',
        lexical:{en:{lemma:'investment',aliases:['capital investment','capital spending','investing'],forms:['investment','investments','capital investment','capital spending'],pos:['NOUN']},bn:{lemma:'বিনিয়োগ',aliases:['মূলধনী বিনিয়োগ','পুঁজি বিনিয়োগ','বিনিয়োগ ব্যয়'],forms:['বিনিয়োগ','মূলধনী বিনিয়োগ','পুঁজি বিনিয়োগ','বিনিয়োগ ব্যয়'],pos:['NOUN']}},
        derivational_family:['invest','investment','investor','investing','invested'], morphological_eligibility:{noun:true,verb:true,adjective:true,compound:true}, morphology:{derivation:'invest -> investment/investor',inflectional_features:['Tense','Aspect','Mood','Voice','VerbForm']}, grammar_features:{process:true},
        semantic_roles:['ACTOR','TARGET','AMOUNT','UNIT','TIME_HORIZON','PURPOSE','CONSTRAINT','FUNDING_SOURCE'], compatible_variables:['CAPACITY','PRODUCTION','CAPITAL','BUDGET','DEVELOPMENT'], compatible_entities:['COUNTRY','PRODUCTION_FACILITY','PROJECT','MINISTRY'], allowed_actions:['ALLOCATE','INCREASE','COMPARE','ANALYZE','FORECAST'],
        relations:[{relation:'affects',target:'CAPACITY'},{relation:'affects',target:'PRODUCTION'},{relation:'requires',target:'CAPITAL'},{relation:'constrained_by',target:'BUDGET'},{relation:'associated_with',target:'DEVELOPMENT'}],
        construction_patterns:['invest in {target}','investment in {target}','increase investment in {target}','allocate {amount} to investment in {target}'], phrase_patterns:['investment in {target}','capital investment','বিনিয়োগ {target}','{target}-এ বিনিয়োগ'], paraphrase_family:'INVESTMENT', runtime_resolution:{strategy:'build_process_frame',required_slots:['target'],optional_slots:['actor','amount','unit','time_horizon','purpose','constraint','funding_source'],causality:'semantic_possibility_only',numeric_effect:'GAME_DATA_ONLY',execution_boundary:'CAPABILITY_REGISTRY'}, register:['neutral','economic','formal','technical'], priority:'P1'
      }
    ],
    semantic_hierarchy: {
      STATE_VARIABLE: ['RESOURCE_PRODUCTION','CAPACITY','DEMAND','SUPPLY'],
      RESOURCE: ['RESOURCE_PRODUCTION'],
      ACTION_INCREASE: ['RESOURCE_PRODUCTION','CAPACITY','EXPORTS','INVESTMENT'],
      ACTION_DECREASE: ['RESOURCE_PRODUCTION','IMPORTS','DEMAND','DEPENDENCY','EMISSIONS'],
      PRODUCTION_CHAIN: ['RESOURCE','RESOURCE_PRODUCTION','CAPACITY','PRODUCTION_FACILITY'],
      MARKET_STATE: ['DEMAND','SUPPLY','PRICE']
    },
    population_policy: { current_seed_count: 12, target_count: 4500, batch: 'BATCH_01', do_not_fabricate: true, depth_standard: ['canonical_identity','domain','subdomain','semantic_type','english_lexicon','bengali_lexicon','aliases','pos','derivational_family','morphological_eligibility','semantic_roles','compatible_variables','compatible_entities','allowed_actions','relations','construction_patterns','paraphrase_family','runtime_resolution'] }
  });

  const SOURCE_MANIFEST = Object.freeze({
    offline_language_vocabulary: Object.freeze({ path:'offline_language_vocabulary.json', role:'lexicon+grammar+policy', required:true }),
    offline_lexicon: Object.freeze({ path:'offline_lexicon.json', role:'full_lexical_corpus', required:true }),
    offline_semantic_knowledge: Object.freeze({ path:'offline_semantic_knowledge.json', role:'semantic_aliases+relations+normalization', required:true }),
    omega_game_language_ontology: Object.freeze({ path:'<embedded:omega_game_language_ontology.json>', role:'canonical_concepts+grammar_contract', required:true, embedded:true }),
    omega_game_language_source_inventory: Object.freeze({ path:'omega_game_language_source_inventory.json', role:'migration_inventory', required:true }),
    offline_semantic_brain: Object.freeze({ path:'offline_semantic_brain.js', role:'legacy_parser_adapter', required:true }),
    offline_query_engine: Object.freeze({ path:'offline_query_engine.js', role:'query_execution_adapter', required:true }),
    omega_game_language_bridge: Object.freeze({ path:'<embedded:omega_game_language_bridge.js>', role:'canonical_concept_adapter', required:true, embedded:true }),
    omega_reasoning_dispatcher: Object.freeze({ path:'omega_reasoning_dispatcher.js', role:'reasoning_boundary', required:true }),
    omega_cognitive_engine: Object.freeze({ path:'omega_cognitive_engine.js', role:'reasoning_consumer', required:true }),
    omega_ai_integrity_layer: Object.freeze({ path:'omega_ai_integrity_layer.js', role:'epistemic_integrity', required:true })
  });
  const SOURCE_PATHS = Object.freeze(Object.values(SOURCE_MANIFEST).filter(x=>!x.embedded).map(x=>x.path));
  const EMBEDDED_SOURCE_PATHS = Object.freeze(Object.values(SOURCE_MANIFEST).filter(x=>x.embedded).map(x=>x.path));
  const OPERATION_SET = Object.freeze(['IDENTIFY','COUNT','QUANTITY','SELECT','PERSON','LOCATION','TIME','METHOD','CAUSE','CONSEQUENCE','POLICY','FEASIBILITY','FORECAST','SCENARIO','COUNTERFACTUAL','COMPARE','ANALYZE','EXPLAIN','RECOMMEND','ASSESS_RISK','ASSESS_SECURITY','TRACE_DEPENDENCY','TRACE_SUPPLY_CHAIN','INCREASE','DECREASE','MAINTAIN','BUILD','UPGRADE','IMPORT','EXPORT','APPOINT','REMOVE','NEGOTIATE','ALLOCATE','START','HALT']);
  const EVENT_STATES = Object.freeze(['EVENT_REQUESTED','EVENT_CONFIRMED','EVENT_REJECTED','EVENT_EXECUTED','EVENT_FAILED','EVENT_PENDING']);
  const GRAMMAR_FEATURES = Object.freeze(['Person','Number','Case','Tense','Aspect','Mood','Voice','Polarity','Degree','VerbForm']);
  const DEPENDENCY_RELATIONS = Object.freeze(['nsubj','obj','obl','advmod','aux','mark','conj','nmod']);

  const RUNTIME = { loaded:false, loading:null, data:Object.create(null), datasets:[], vocabulary:null, lexicon:null, semanticKnowledge:null, ontology:EMBEDDED_GAME_LANGUAGE_ONTOLOGY, inventory:null, brain:null, query:null, bridge:null, dispatcher:null, history:[], context:Object.create(null), learned:new Map(), index:{concepts:new Map(),surfaces:new Map(),pronunciations:new Map(),events:new Map(),sourceStats:Object.create(null)}, lastAnalysis:null };
  const text=v=>String(v==null?'':v);
  const object=v=>!!v&&typeof v==='object';
  const clone=v=>{if(v===undefined)return undefined;try{return JSON.parse(JSON.stringify(v));}catch(_){return null;}};
  const normalize=v=>text(v).normalize('NFKC').toLowerCase().replace(/[\u0000-\u001F\u007F]/g,' ').replace(/[?!,.:;"'“”‘’(){}\[\]<>—–]/g,' ').replace(/\s+/g,' ').trim();
  const languageOf=v=>/[\u0980-\u09FF]/.test(text(v))?'bn':'en';
  const assertInput=v=>{const q=text(v).normalize('NFKC');if(q.length>MAX_INPUT_CHARS)throw new Error('OMEGA_LANGUAGE_INPUT_TOO_LARGE');return q;};
  function safeHistoryRead(){if(typeof localStorage==='undefined')return[];try{const x=JSON.parse(localStorage.getItem('omega.language.context.v1')||'[]');return Array.isArray(x)?x.slice(-MAX_HISTORY_TURNS):[];}catch(_){return[];}}
  function safeHistoryWrite(h){if(typeof localStorage==='undefined')return;try{localStorage.setItem('omega.language.context.v1',JSON.stringify(h.slice(-MAX_HISTORY_TURNS)));}catch(_){} }
  function recordHistory(role,content,metadata){RUNTIME.history.push({role,content:text(content).slice(0,MAX_INPUT_CHARS),timestamp:Date.now(),metadata:metadata?clone(metadata):undefined});RUNTIME.history=RUNTIME.history.slice(-MAX_HISTORY_TURNS);safeHistoryWrite(RUNTIME.history);}
  function currentContext(extra){const gs=global.Game?.state||global.gameState||global.Omega?.World?.state||{};const ui=global.OmegaCabinetUI||{};const minister=ui.currentInterrogatedMinister||ui.currentMinister||ui.activeMinister||global.OmegaMinisterState?.activeMinister||{};return Object.assign({countryId:gs.countryCode||gs.countryId||gs.playerCountryId||ui.activeCountry||'',countryName:gs.countryName||gs.country?.name||ui.activeCountry||'',ministerId:minister.id||ui.currentMinisterId||'',ministerName:minister.name||minister.displayName||'',ministerRole:minister.role||minister.title||'',ministryId:minister.ministryId||ui.currentMinistryId||'',gameState:gs},RUNTIME.context,object(extra)?extra:{});}
  function validateOntology(o){const e=[];if(!object(o))return['ONTOLOGY_NOT_OBJECT'];if(!Array.isArray(o.concept_contract?.required)||!o.concept_contract.required.length)e.push('ONTOLOGY_CONTRACT_MISSING');if(o.canonical_concept_target!==4500)e.push('ONTOLOGY_TARGET_CHANGED');if(!Array.isArray(o.seed_concepts)||o.seed_concepts.length!==12)e.push('BATCH_01_SEED_COUNT_INVALID');for(const c of o.seed_concepts||[]){for(const k of ['concept_id','domain','subdomain','semantic_type','lexical','derivational_family','morphological_eligibility','semantic_roles','compatible_variables','compatible_entities','allowed_actions','relations','construction_patterns','paraphrase_family','runtime_resolution'])if(c[k]===undefined)e.push('SEED_FIELD_MISSING:'+text(c.concept_id)+':'+k);if(c.lexical?.en?.pos?.length===0||c.lexical?.bn?.pos?.length===0)e.push('SEED_POS_MISSING:'+text(c.concept_id));}if(o.grammar?.features&&JSON.stringify(o.grammar.features)!==JSON.stringify(GRAMMAR_FEATURES))e.push('GRAMMAR_FEATURE_SET_CHANGED');if(o.grammar?.dependency_relations&&JSON.stringify(o.grammar.dependency_relations)!==JSON.stringify(DEPENDENCY_RELATIONS))e.push('DEPENDENCY_SET_CHANGED');if(o.operational_rules?.unknown_entity!=='UNRESOLVED')e.push('UNKNOWN_ENTITY_POLICY_CHANGED');if(o.operational_rules?.ambiguous_entity!=='ASK_OR_REPORT_AMBIGUITY')e.push('AMBIGUITY_POLICY_CHANGED');if(o.operational_rules?.unknown_fact!=='UNKNOWN_WHEN_NOT_EVIDENCED')e.push('UNKNOWN_FACT_POLICY_CHANGED');return e;}
  function validateVocabulary(v){const e=[];if(!object(v)||!v.languages?.en||!v.languages?.bn)e.push('BILINGUAL_VOCABULARY_MISSING');if(v?.semantic_policy?.world_entities_must_be_loaded_from_runtime_datasets!==true)e.push('WORLD_ENTITY_POLICY_CHANGED');if(v?.semantic_policy?.no_country_catalog_in_code!==true)e.push('COUNTRY_CATALOG_POLICY_CHANGED');if(v?.semantic_policy?.no_resource_catalog_in_code!==true)e.push('RESOURCE_CATALOG_POLICY_CHANGED');if(v?.semantic_policy?.no_asset_alias_catalog_in_code!==true)e.push('ASSET_CATALOG_POLICY_CHANGED');if(v?.semantic_policy?.no_answer_fact_catalog_in_code!==true)e.push('ANSWER_FACT_POLICY_CHANGED');return e;}
  async function fetchJSON(path){if(typeof fetch!=='function')throw new Error('OMEGA_LANGUAGE_FETCH_UNAVAILABLE:'+path);const r=await fetch('./'+path,{cache:'no-store'});if(!r.ok)throw new Error('OMEGA_LANGUAGE_DATA_LOAD_FAILED:'+path);return r.json();}
  async function loadScript(path){if(typeof document==='undefined')return false;if([...document.scripts].some(s=>s.src&&s.src.endsWith('/'+path)))return true;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='./'+path;s.async=false;s.onload=resolve;s.onerror=()=>reject(new Error('OMEGA_LANGUAGE_SCRIPT_LOAD_FAILED:'+path));document.head.appendChild(s);});return true;}
  function addSurface(surface,record){const s=normalize(surface);if(!s)return;if(!RUNTIME.index.surfaces.has(s))RUNTIME.index.surfaces.set(s,[]);const list=RUNTIME.index.surfaces.get(s);const key=JSON.stringify(record);if(!list.some(x=>JSON.stringify(x)===key))list.push(record);}
  function addPronunciation(value,record){const p=normalize(value);if(!p)return;if(!RUNTIME.index.pronunciations.has(p))RUNTIME.index.pronunciations.set(p,[]);RUNTIME.index.pronunciations.get(p).push(record);}
  function registerConcept(concept,source){if(!object(concept))return;const id=text(concept.concept_id||concept.id||concept.term||'').trim();if(!id)return;if(!RUNTIME.index.concepts.has(id))RUNTIME.index.concepts.set(id,{source,record:clone(concept)});for(const lang of ['en','bn']){const lex=concept.lexical?.[lang]||concept[lang]||{};for(const field of ['lemma','aliases','forms']){const vals=Array.isArray(lex[field])?lex[field]:[lex[field]];for(const v of vals)if(v)addSurface(v,{conceptId:id,language:lang,source,field});}for(const field of ['pronunciation','pronunciations','phonetic','ipa']){const vals=Array.isArray(lex[field])?lex[field]:[lex[field]];for(const v of vals)if(v)addPronunciation(v,{conceptId:id,language:lang,source,field});}}if(Array.isArray(concept.allowed_actions))for(const a of concept.allowed_actions)registerEvent(a,id,source);}
  function registerEvent(name,conceptId,source){const n=text(name).toUpperCase();if(!n)return;if(!RUNTIME.index.events.has(n))RUNTIME.index.events.set(n,{name:n,concepts:[],sources:[]});const e=RUNTIME.index.events.get(n);if(conceptId&&!e.concepts.includes(conceptId))e.concepts.push(conceptId);if(source&&!e.sources.includes(source))e.sources.push(source);}
  function walkLexicalData(value,source,path,seen){if(!object(value))return;if(seen.has(value))return;seen.add(value);if(Array.isArray(value)){value.forEach((x,i)=>walkLexicalData(x,source,path+'['+i+']',seen));return;}const conceptLike=value.concept_id||(value.lexical&&(value.lexical.en||value.lexical.bn));if(conceptLike)registerConcept(value,source);for(const[k,v]of Object.entries(value)){const p=path?path+'.'+k:k;if(['pronunciation','pronunciations','phonetic','ipa'].includes(k)){const vals=Array.isArray(v)?v:[v];vals.forEach(x=>addPronunciation(x,{source,path:p}));}if(['event','events','event_types','event_states','allowed_actions','actions'].includes(k)&&Array.isArray(v))v.forEach(x=>registerEvent(x,null,source));walkLexicalData(v,source,p,seen);}}
  function buildCanonicalIndex(){RUNTIME.index={concepts:new Map(),surfaces:new Map(),pronunciations:new Map(),events:new Map(),sourceStats:Object.create(null)};RUNTIME.data['<embedded:omega_game_language_ontology.json>']=RUNTIME.ontology;for(const[path,data]of Object.entries(RUNTIME.data)){if(!data)continue;walkLexicalData(data,path,'',new Set());RUNTIME.index.sourceStats[path]={loaded:true,topLevelKeys:object(data)?Object.keys(data).length:0};}RUNTIME.index.sourceStats['<embedded:omega_game_language_bridge.js>']={loaded:true,type:'runtime-behavior',version:GAME_LANGUAGE_BRIDGE.VERSION};for(const op of OPERATION_SET)registerEvent(op,null,'OMEGA_OPERATION_SET');for(const state of EVENT_STATES)registerEvent(state,null,'OMEGA_EVENT_STATE_SET');const learned=safeLearnedRead();for(const x of learned)if(x?.surface)RUNTIME.learned.set(x.surface,Object.freeze(x));}
  function safeLearnedRead(){if(typeof localStorage==='undefined')return[];try{const x=JSON.parse(localStorage.getItem('omega.language.learned.v1')||'[]');return Array.isArray(x)?x.slice(-MAX_LEARNED_MAPPINGS):[];}catch(_){return[];}}
  function safeLearnedWrite(){if(typeof localStorage==='undefined')return;try{localStorage.setItem('omega.language.learned.v1',JSON.stringify([...RUNTIME.learned.values()].slice(-MAX_LEARNED_MAPPINGS)));}catch(_){} }
  async function loadSources(){if(RUNTIME.loading)return RUNTIME.loading;RUNTIME.loading=(async()=>{const jsonPaths=SOURCE_PATHS.filter(p=>p.endsWith('.json'));const results=await Promise.all(jsonPaths.map(async p=>[p,await fetchJSON(p)]));for(const[p,d]of results)RUNTIME.data[p]=d;for(const p of ['offline_semantic_brain.js','offline_query_engine.js','omega_reasoning_dispatcher.js']){try{await loadScript(p);}catch(e){if(p!=='omega_reasoning_dispatcher.js')throw e;}}RUNTIME.vocabulary=RUNTIME.data['offline_language_vocabulary.json'];RUNTIME.lexicon=RUNTIME.data['offline_lexicon.json'];RUNTIME.semanticKnowledge=RUNTIME.data['offline_semantic_knowledge.json'];RUNTIME.ontology=EMBEDDED_GAME_LANGUAGE_ONTOLOGY;RUNTIME.inventory=RUNTIME.data['omega_game_language_source_inventory.json'];const errors=[...validateOntology(RUNTIME.ontology),...validateVocabulary(RUNTIME.vocabulary)];if(errors.length)throw new Error('OMEGA_LANGUAGE_CONTRACT_INVALID:'+errors.join(','));RUNTIME.brain=global.OfflineSemanticBrain||null;RUNTIME.query=global.OfflineQueryEngine||null;RUNTIME.dispatcher=global.OmegaReasoningDispatcher||null;GAME_LANGUAGE_BRIDGE.load(RUNTIME.ontology);GAME_LANGUAGE_BRIDGE.install();global.OmegaGameLanguageBridge=GAME_LANGUAGE_BRIDGE;RUNTIME.history=safeHistoryRead();buildCanonicalIndex();RUNTIME.loaded=true;return diagnostics();})().catch(error=>{RUNTIME.loading=null;RUNTIME.loaded=false;throw error;});return RUNTIME.loading;}
  function configure(options){const o=object(options)?options:{};if(Array.isArray(o.datasets))RUNTIME.datasets=o.datasets.filter(object).slice(0,128);if(object(o.vocabulary))RUNTIME.vocabulary=o.vocabulary;if(object(o.context))RUNTIME.context=Object.assign({},RUNTIME.context,clone(o.context));if(Array.isArray(o.ministers))RUNTIME.datasets.push({ministers_database:{all:o.ministers.slice(0,10000)}});if(RUNTIME.brain?.configure){try{RUNTIME.brain.configure({datasets:RUNTIME.datasets,vocabulary:RUNTIME.vocabulary,lexicon:RUNTIME.lexicon,semanticKnowledge:RUNTIME.semanticKnowledge});}catch(_){}}return diagnostics();}
  function sourceData(path){if(path==='<embedded:omega_game_language_ontology.json>')return clone(EMBEDDED_GAME_LANGUAGE_ONTOLOGY);return RUNTIME.data[path]||null;}
  function concept(conceptId){return clone(RUNTIME.index.concepts.get(text(conceptId))?.record||null);}
  function canonicalCandidates(surface,language){const q=normalize(surface);if(!q)return[];const exact=RUNTIME.index.surfaces.get(q)||[];const candidates=new Map();for(const hit of exact)candidates.set(hit.conceptId,{conceptId:hit.conceptId,language:hit.language,source:hit.source,score:1});if(!exact.length)for(const[s,hits]of RUNTIME.index.surfaces)if(s!==q&&(q.includes(s)||s.includes(q))){const score=.60+.34*Math.min(q.length,s.length)/Math.max(q.length,s.length);for(const h of hits){const old=candidates.get(h.conceptId);if(!old||score>old.score)candidates.set(h.conceptId,{conceptId:h.conceptId,language:h.language,source:h.source,score});}}return[...candidates.values()].sort((a,b)=>b.score-a.score||a.conceptId.localeCompare(b.conceptId));}
  function analyze(question,context){const raw=assertInput(question);if(!raw.trim())return{ok:false,error:'EMPTY_INPUT'};const ctx=currentContext(context);let parsed;if(RUNTIME.brain?.parse)parsed=RUNTIME.brain.parse(raw,ctx);else parsed={raw,surface:raw,language:languageOf(raw),operation:'IDENTIFY',entities:{}};parsed=object(parsed)?parsed:{raw,surface:raw,language:languageOf(raw),operation:'IDENTIFY',entities:{}};const language=parsed.language||languageOf(raw);const operation=text(parsed.operation||parsed.intent||'IDENTIFY').toUpperCase();const candidates=canonicalCandidates(parsed.surface||raw,language);const confidence=Number.isFinite(Number(parsed.confidence))?Number(parsed.confidence):(candidates[0]?.score??null);const margin=candidates.length>1?candidates[0].score-candidates[1].score:null;const ambiguity=candidates.length>1&&margin<SECOND_BEST_MARGIN;const out={...clone(parsed),raw,surface:text(parsed.surface||raw),language,operation:OPERATION_SET.includes(operation)?operation:'IDENTIFY',grammar:object(parsed.grammar)?clone(parsed.grammar):{},semanticRoles:object(parsed.semanticRoles)?clone(parsed.semanticRoles):{},unresolved:Array.isArray(parsed.unresolved)?clone(parsed.unresolved):[],confidence,canonicalCandidates:candidates.slice(0,20),ambiguity,secondBestMargin:margin,contract:{schema:SCHEMA_VERSION,unknownEntity:'UNRESOLVED',ambiguousEntity:'ASK_OR_REPORT_AMBIGUITY',unknownFact:'UNKNOWN_WHEN_NOT_EVIDENCED',capabilityBoundary:'LANGUAGE_DOES_NOT_GRANT_EXECUTION_CAPABILITY'}};if(ambiguity)out.unresolved.push('AMBIGUOUS_CANONICAL_CONCEPT');RUNTIME.lastAnalysis=out;return out;}
  function parse(q,c){return analyze(q,c);}
  function resolve(parsed,context){const p=object(parsed)?parsed:analyze(parsed,context);const ctx=currentContext(context);const unresolved=Array.isArray(p.unresolved)?[...p.unresolved]:[];const status=p.ambiguity?'AMBIGUOUS':(p.confidence!=null&&p.confidence>=MIN_ENTITY_CONFIDENCE?'RESOLVED':'PARTIAL');return{...clone(p),context:ctx,entities:clone(p.entities||{}),unresolved,resolution:{status,confidence:p.confidence??null,secondBestMargin:p.secondBestMargin??null}};}
  function executeIntent(parsed,datasets,context){const resolved=resolve(parsed,context);const ds=Array.isArray(datasets)?datasets:RUNTIME.datasets;if(!RUNTIME.query?.execute)return{ok:false,operation:resolved.operation,status:'EXECUTOR_UNAVAILABLE',facts:[],evidence:[],unknowns:['QUERY_EXECUTOR_UNAVAILABLE'],text:null,language:resolved.language};try{const r=RUNTIME.query.execute(resolved,ds,resolved.language,currentContext(context));return object(r)?clone(r):{ok:false,operation:resolved.operation,status:'EMPTY_RESULT',facts:[],evidence:[],unknowns:['EMPTY_RESULT'],text:null};}catch(e){return{ok:false,operation:resolved.operation,status:'EXECUTION_ERROR',facts:[],evidence:[],unknowns:['QUERY_EXECUTION_ERROR'],error:text(e.message).slice(0,500),text:null,language:resolved.language};}}
  function dispatchReasoning(question,parsed,result,context){if(!RUNTIME.dispatcher?.dispatch)return null;try{return clone(RUNTIME.dispatcher.dispatch(assertInput(question),parsed,result,currentContext(context)));}catch(e){return{used:false,error:'REASONING_DISPATCH_ERROR',message:text(e.message).slice(0,300)};}}
  function realize(result,language,options){const r=object(result)?result:{};const lang=language==='bn'?'bn':'en';const o=object(options)?options:{};if(typeof r.text==='string'&&r.text.trim())return r.text.trim();if(Array.isArray(r.unknowns)&&r.unknowns.length)return lang==='bn'?'বর্তমান প্রামাণ্য গেম ডেটায় এই প্রশ্নের নির্ভরযোগ্য উত্তর পাওয়া যায়নি। অজানা: '+r.unknowns.slice(0,5).join(', '):'The current authoritative game data does not provide a reliable answer. Unknown: '+r.unknowns.slice(0,5).join(', ');return o.allowEmpty===true?'':(lang==='bn'?'বর্তমান গেম ডেটা থেকে প্রামাণ্য উত্তর তৈরি করা যায়নি।':'An evidence-backed answer could not be produced from the current game data.');}
  async function run(question,context){await loadSources();const raw=assertInput(question);const analysis=resolve(analyze(raw,context),context);const result=executeIntent(analysis,RUNTIME.datasets,context);const reasoning=dispatchReasoning(raw,analysis,result,context);if(reasoning?.used&&reasoning.text&&!result.text)result.text=reasoning.text;const answer=realize(result,analysis.language);recordHistory('user',raw,{operation:analysis.operation});recordHistory('assistant',answer,{operation:analysis.operation,source:'OMEGA_LANGUAGE_SYSTEM'});return{analysis,result,reasoning,answer,language:analysis.language};}
  function learnPhrase(surface,intent,entity,confidence){const q=normalize(surface),score=Number(confidence);if(!q||!Number.isFinite(score)||score<.95)return false;if(RUNTIME.learned.size>=MAX_LEARNED_MAPPINGS&&!RUNTIME.learned.has(q))return false;RUNTIME.learned.set(q,Object.freeze({surface:q,intent:text(intent).toUpperCase()||null,entity:text(entity)||null,confidence:score}));safeLearnedWrite();return true;}
  function eventRequest(operation,parameters,context){const op=text(operation).toUpperCase();registerEvent(op,null,'RUNTIME_EVENT_REQUEST');return Object.freeze({schema:SCHEMA_VERSION,type:'GAME_EVENT_REQUEST',state:'EVENT_REQUESTED',operation:OPERATION_SET.includes(op)?op:'IDENTIFY',parameters:clone(parameters||{}),context:clone(currentContext(context)),capabilityRequired:true,executionOwner:'GAME_CAPABILITY_AND_EVENT_ENGINE'});}
  function gameLanguageOntology(){return clone(EMBEDDED_GAME_LANGUAGE_ONTOLOGY);}
  function diagnostics(){const i=RUNTIME.inventory,l=RUNTIME.lexicon,v=RUNTIME.vocabulary;return{version:VERSION,schema:SCHEMA_VERSION,ready:RUNTIME.loaded,sourceFiles:SOURCE_PATHS.slice(),embeddedSourceFiles:EMBEDDED_SOURCE_PATHS.slice(),sourceCount:SOURCE_PATHS.length,embeddedSourceCount:EMBEDDED_SOURCE_PATHS.length,ontologyTarget:RUNTIME.ontology?.canonical_concept_target??4500,ontologySeedCount:Array.isArray(RUNTIME.ontology?.seed_concepts)?RUNTIME.ontology.seed_concepts.length:0,ontologyBatch:RUNTIME.ontology?.population_policy?.batch??null,ontologyDepthStandard:RUNTIME.ontology?.population_policy?.depth_standard??[],sourceConceptCount:i?.source_concept_count??null,sourceRawSurfaceCount:i?.raw_surface_entry_count??null,sourceUniqueSurfaceCount:i?.unique_surface_entry_count??null,offlineLexiconTotalWords:l?.TOTAL_WORDS??null,languages:Object.keys(v?.languages||{}),datasetsLoaded:RUNTIME.datasets.length,canonicalConcepts:RUNTIME.index.concepts.size,indexedSurfaces:RUNTIME.index.surfaces.size,indexedPronunciations:RUNTIME.index.pronunciations.size,indexedEvents:RUNTIME.index.events.size,learnedMappings:RUNTIME.learned.size,historyTurns:RUNTIME.history.length,grammarFeatures:GRAMMAR_FEATURES.slice(),dependencyRelations:DEPENDENCY_RELATIONS.slice(),operationCount:OPERATION_SET.length,eventStates:EVENT_STATES.slice(),semanticHierarchy:clone(RUNTIME.ontology?.semantic_hierarchy||{}),sourceStats:clone(RUNTIME.index.sourceStats),security:{maxInputChars:MAX_INPUT_CHARS,maxHistoryTurns:MAX_HISTORY_TURNS,maxLearnedMappings:MAX_LEARNED_MAPPINGS,minimumEntityConfidence:MIN_ENTITY_CONFIDENCE,secondBestMargin:SECOND_BEST_MARGIN,usesEval:false,usesFunctionConstructor:false,answerFactCatalogInCode:false,worldStateOwnedByLanguageCore:false}};}
  function validate(){const ontologyErrors=validateOntology(RUNTIME.ontology),vocabularyErrors=validateVocabulary(RUNTIME.vocabulary),i=RUNTIME.inventory,seedIds=(RUNTIME.ontology.seed_concepts||[]).map(x=>x.concept_id),uniqueSeedIds=new Set(seedIds);const canonical=RUNTIME.loaded?{concepts:RUNTIME.index.concepts.size,surfaces:RUNTIME.index.surfaces.size,pronunciations:RUNTIME.index.pronunciations.size,events:RUNTIME.index.events.size}:null;return{ok:ontologyErrors.length===0&&vocabularyErrors.length===0&&seedIds.length===uniqueSeedIds.size,ontologyErrors,vocabularyErrors,canonical,batch01:{seedCount:seedIds.length,uniqueSeedCount:uniqueSeedIds.size,seedIds,deepFields:RUNTIME.ontology.population_policy.depth_standard,invariant:'canonical identity is concept_id; lexical variants never create new concepts'},migration:{sourceConcepts:i?.source_concept_count??null,rawSurfaceEntries:i?.raw_surface_entry_count??null,uniqueSurfaceEntries:i?.unique_surface_entry_count??null,invariant:'source = migrated + deduplicated + intentionally_excluded',silentLossAllowed:false,embeddedOntology:true,embeddedBridge:true}};}
  const API=Object.freeze({VERSION,SCHEMA_VERSION,SOURCE_MANIFEST,SOURCE_PATHS,EMBEDDED_SOURCE_PATHS,OPERATION_SET,EVENT_STATES,GRAMMAR_FEATURES,DEPENDENCY_RELATIONS,load:loadSources,configure,sourceData,concept,analyze,parse,resolve,executeIntent,realize,run,dispatchReasoning,eventRequest,learnPhrase,canonicalCandidates,diagnostics,validate,gameLanguageOntology,get context(){return clone(RUNTIME.context);},setContext(v){RUNTIME.context=object(v)?Object.assign({},RUNTIME.context,clone(v)):RUNTIME.context;return clone(RUNTIME.context);}});
  global.OmegaLanguageSystem=API;
  global.__OMEGA_LANGUAGE_SYSTEM_READY__=true;

  /* Exact executable bridge behavior remains embedded, with ontology-driven matching. */
  const GAME_LANGUAGE_BRIDGE_STATE={ontology:EMBEDDED_GAME_LANGUAGE_ONTOLOGY,installed:false};
  function bridgeText(value){return String(value==null?'':value).trim();}
  function bridgeNorm(value){return bridgeText(value).normalize('NFKC').toLowerCase().replace(/[?!,.:;"'“”‘’(){}\[\]<>—–]/g,' ').replace(/\s+/g,' ').trim();}
  function bridgeSurfaceForms(conceptRecord,language){const lexical=conceptRecord?.lexical?.[language]||{};return[...new Set([lexical.lemma,...(lexical.aliases||[]),...(lexical.forms||[])].filter(Boolean).map(bridgeNorm))];}
  const GAME_LANGUAGE_BRIDGE={VERSION:'1.0.2',load(value){GAME_LANGUAGE_BRIDGE_STATE.ontology=value&&typeof value==='object'?value:EMBEDDED_GAME_LANGUAGE_ONTOLOGY;return GAME_LANGUAGE_BRIDGE_STATE.ontology;},match(surface,language){const q=bridgeNorm(surface),ontology=GAME_LANGUAGE_BRIDGE_STATE.ontology;if(!q||!ontology?.seed_concepts?.length)return[];const hits=[];for(const conceptRecord of ontology.seed_concepts)for(const form of bridgeSurfaceForms(conceptRecord,language)){if(!form)continue;let score=0;if(q===form)score=1;else if(q.includes(form)||form.includes(q))score=.60+.34*Math.min(q.length,form.length)/Math.max(q.length,form.length);if(score>=.60)hits.push({concept_id:conceptRecord.concept_id,domain:conceptRecord.domain,semantic_type:conceptRecord.semantic_type,score:Number(score.toFixed(3)),priority:conceptRecord.priority,relations:clone(conceptRecord.relations||[])});}const best=new Map();for(const hit of hits)if(!best.has(hit.concept_id)||best.get(hit.concept_id).score<hit.score)best.set(hit.concept_id,hit);return[...best.values()].sort((a,b)=>b.score-a.score||a.concept_id.localeCompare(b.concept_id));},enrich(parsed){if(!parsed||typeof parsed!=='object')return parsed;const surface=bridgeText(parsed.surface||parsed.raw||''),language=parsed.language||(/[\u0980-\u09FF]/.test(surface)?'bn':'en'),candidates=GAME_LANGUAGE_BRIDGE.match(surface,language);const out={...parsed,gameLanguage:{ontologyVersion:GAME_LANGUAGE_BRIDGE_STATE.ontology.schema_version||null,candidates}};if(candidates.length&&candidates[0].score>=.94){out.gameLanguage.canonicalConcept=candidates[0].concept_id;const record=GAME_LANGUAGE_BRIDGE_STATE.ontology.seed_concepts.find(x=>x.concept_id===candidates[0].concept_id);if(record){out.gameLanguage.semanticType=record.semantic_type;out.gameLanguage.relations=clone(record.relations||[]);out.gameLanguage.runtimeResolution=clone(record.runtime_resolution||null);}}return out;},install(){if(GAME_LANGUAGE_BRIDGE_STATE.installed)return true;if(!global.OfflineSemanticBrain||typeof global.OfflineSemanticBrain.parse!=='function')return false;const original=global.OfflineSemanticBrain.parse;if(original.__omegaGameLanguageWrapped){GAME_LANGUAGE_BRIDGE_STATE.installed=true;return true;}const wrapped=function(question,context){return GAME_LANGUAGE_BRIDGE.enrich(original.call(this,question,context));};Object.defineProperty(wrapped,'__omegaGameLanguageWrapped',{value:true});global.OfflineSemanticBrain.parse=wrapped;GAME_LANGUAGE_BRIDGE_STATE.installed=true;return true;}};
  Object.defineProperty(GAME_LANGUAGE_BRIDGE,'ontology',{enumerable:true,get(){return GAME_LANGUAGE_BRIDGE_STATE.ontology;}});
  Object.freeze(GAME_LANGUAGE_BRIDGE);
  global.OmegaGameLanguageBridge=GAME_LANGUAGE_BRIDGE;
})(typeof window!=='undefined'?window:globalThis);
