/** OMEGA AI INTEGRITY LAYER v2.0.0-DATA-BOUND
 * Compatibility surface for the existing UI.
 * Entity vocabulary and factual values are resolved by canonical runtime/data systems.
 */
(function(global){'use strict';
const VERSION='2.0.0';
const MAX_HISTORY=24;
const S=v=>String(v==null?'':v).trim();
const clone=v=>{try{return v==null?v:JSON.parse(JSON.stringify(v))}catch(_){return null}};
const N=v=>S(v).normalize('NFKC').replace(/[?!,.:;'"(){}\[\]<>—–]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
const isBn=v=>/[\u0980-\u09FF]/.test(S(v));
const historyStore=new Map();
function runtime(){return global.OmegaProductionSemanticRuntime||null}
function brain(){return global.OfflineSemanticBrain||null}
function queryEngine(){return global.OfflineQueryEngine||null}
function identityBridge(){return global.OmegaCanonicalIdentityRegistry||global.OmegaCountrySemanticBridge||null}
function resourceBridge(){return global.OmegaResourceSemanticBridge||null}
function canonicalMinisterIdentity(input={}){return Object.freeze({countryCode:S(input.countryCode||input.country||'').toUpperCase(),countryName:S(input.countryName||input.country||''),ministryId:S(input.ministryId||input.portfolioId||'').toUpperCase(),ministerId:S(input.ministerId||input.id||''),name:S(input.ministerName||input.name||''),role:S(input.ministerRole||input.role||''),age:Number.isFinite(Number(input.age))?Number(input.age):null,background:S(input.background||''),ideology:S(input.ideology||''),efficiency:Number.isFinite(Number(input.efficiency))?Number(input.efficiency):null,profileSource:S(input.profileSource||'')})}
function parse(question,identity={},world={},history=[]){const rt=runtime();try{if(rt?.parse)return rt.parse(question,identity,world,history)}catch(_){}try{if(brain()?.parse)return brain().parse(question,{...identity,gameState:world})}catch(_){}return{language:isBn(question)?'bn':'en',raw:S(question),normalized:N(question),operation:'GENERAL',intent:'GENERAL',entities:{country:null,resource:null,minister:null},unresolved:['SEMANTIC_RUNTIME_UNAVAILABLE'],executable:false}}
function detectIntent(question){const p=parse(question);return{intent:S(p?.intent||p?.question?.type||'GENERAL'),confidence:Number(p?.confidence||p?.question?.confidence||0)}}
function findEntities(question){const p=parse(question);const out=[];for(const [type,e] of Object.entries(p?.entities||{})){if(Array.isArray(e)){for(const x of e)if(x?.id)out.push(S(x.id).toUpperCase())}else if(e?.id)out.push(S(e.id).toUpperCase())}return[...new Set(out)]}
function buildWorldSnapshot(input={}){const state=input.worldState||input.gameState||input.reservesData||{};return Object.freeze({version:VERSION,timestamp:Date.now(),countryCode:S(input.countryCode||state.countryCode||'').toUpperCase(),state:clone(state)||{},sources:clone(input.sources||null),source:'RUNTIME_DATA_SNAPSHOT'})}
function resolveResource(question,key){const rb=resourceBridge();try{if(rb?.resolveResource){const r=rb.resolveResource(question);if(r?.id&&(!key||N(r.id)===N(key)||N(r.surface||'')===N(key)))return r;const k=rb.resolveResource(key);if(k?.id)return k}}catch(_){}return null}
function analyseResource(snapshot,key){const r=resolveResource(key,key),raw=r?.raw||r?.record||null;const qe=queryEngine();if(qe?.execute){try{const p={raw:S(key),operation:'IDENTIFY',entities:{resource:r?{id:r.id,surface:r.surface}:null},context:{countryId:snapshot.countryCode||null}};const result=qe.execute(p,[],snapshot?.language||'en',snapshot||{});if(result)return result}catch(_){} }return{key:S(key),resourceId:r?.id||null,raw:clone(raw),facts:[],derived:[],unknown:r?.id?[]:['RESOURCE_NOT_RESOLVED']}}
function buildAnswerPlan(question,identityInput={},worldInput={},history=[]){const identity=canonicalMinisterIdentity(identityInput),rt=runtime();let base=null;try{if(rt?.buildAnswerPlan)base=rt.buildAnswerPlan(question,identity,worldInput,history)}catch(_){}if(base?.result!==undefined&&base?.result!==null)return base;const p=parse(question,identity,worldInput,history),qe=queryEngine();let result=null;try{if(qe?.execute)result=qe.execute(p,[],p.language||'en',{...worldInput,countryId:identity.countryCode})}catch(_){}return Object.freeze({version:VERSION,identity,snapshot:buildWorldSnapshot({...worldInput,countryCode:identity.countryCode}),routing:{intent:p.intent||p.question?.type||'GENERAL',confidence:p.confidence||p.question?.confidence||0},operation:p.operation||'GENERAL',entities:Object.values(p.entities||{}).filter(Boolean),semantic:p,analyses:[],facts:result?.facts||result?.evidence||[],derived:result?.calculations||[],unknown:result?.uncertainties||[],result,language:p.language|| (isBn(question)?'bn':'en'),question:S(question),generatedBy:'OMEGA_CANONICAL_DATA_PIPELINE'})}
function formatOfflineAnswer(plan){const result=plan?.result;if(result?.text)return S(result.text);if(result?.answer)return S(result.answer);const semantic=plan?.semantic||plan;const entities=semantic?.entities||{};const country=entities.country,resource=entities.resource,minister=entities.minister;const bn=semantic?.language==='bn'||isBn(plan?.question);if(country?.id){const name=S(country.surface||country.name||country.id);return bn?`${name} একটি country entity হিসেবে শনাক্ত হয়েছে। Canonical ID: ${country.id}.`:`${name} was resolved as a country entity. Canonical ID: ${country.id}.`}if(resource?.id){const name=S(resource.surface||resource.name||resource.id);return bn?`${name} একটি resource entity হিসেবে শনাক্ত হয়েছে। Canonical ID: ${resource.id}.`:`${name} was resolved as a resource entity. Canonical ID: ${resource.id}.`}if(minister?.id)return bn?`মন্ত্রী entity শনাক্ত হয়েছে: ${minister.id}.`:`A minister entity was resolved: ${minister.id}.`;return bn?'প্রশ্নের জন্য প্রামাণ্য উত্তর তৈরি করা যায়নি।':'No authoritative answer could be constructed for the question.'}
function conversationKey(identity){return[S(identity.countryCode),S(identity.ministryId),S(identity.ministerId)].join(':')}
function getConversationHistory(identity){return(historyStore.get(conversationKey(canonicalMinisterIdentity(identity)))||[]).slice()}
function answer(question,ui){const identity=canonicalMinisterIdentity(ui?.currentInterrogatedMinister||ui?.activeMinister||ui||{}),world={countryCode:identity.countryCode,gameState:global.Game?.state||{},worldState:global.Game?.worldState||{},reservesData:global.Game?.resources||null};const history=getConversationHistory(identity),plan=buildAnswerPlan(question,identity,world,history),response=formatOfflineAnswer(plan);const key=conversationKey(identity),next=history.slice(-MAX_HISTORY+1);next.push({question:S(question),operation:plan.operation,entities:clone(plan.entities)||[],answer:response,timestamp:Date.now()});historyStore.set(key,next);global.__OMEGA_LAST_AI_PLAN__=plan;global.__OMEGA_AI_CONVERSATION__=next;return response}
const API=Object.freeze({VERSION,canonicalMinisterIdentity,normalize:N,detectIntent,findEntities,buildWorldSnapshot,analyseResource,buildAnswerPlan,formatOfflineAnswer:formatOfflineAnswer,answer,getConversationHistory});
global.OmegaAIIntegrity=API;global.__OMEGA_AI_INTEGRITY__={version:VERSION,installedAt:Date.now(),api:API};
function installBridge(){const ui=global.OmegaCabinetUI;if(!ui||ui.__integrityBridgeInstalled)return false;const original=ui.thinkMinisterQuestion;ui.__integrityBridgeInstalled=true;ui.thinkMinisterQuestion=function(question,...rest){try{return answer(question,this)}catch(e){console.warn('[OMEGA AI Integrity] canonical data bridge failed:',e);return typeof original==='function'?original.call(this,question,...rest):null}};ui.__omegaOfflineAnswer=q=>answer(q,ui);return true}
let attempts=0;const timer=setInterval(()=>{attempts++;if(installBridge()||attempts>=150)clearInterval(timer)},100);installBridge();
})(typeof window!=='undefined'?window:globalThis);
