/* OMEGA SEMANTIC RUNTIME v3.2
 * Language meaning is data. World entities are runtime data. Answers are evidence-backed.
 */
(function(g){'use strict';
if(g.OmegaSemanticRuntimeV32)return;
const V='3.2.0-PRODUCTION',S={ready:false,vocab:null,knowledge:null,countries:new Map(),resources:new Map(),ministers:new Map(),datasets:new Map(),question:new Map(),attributes:new Map(),assets:new Map(),aliases:new Map(),errors:[]};
const T=v=>String(v==null?'':v).trim(),N=v=>T(v).normalize('NFKC').replace(/[?!,.:;'"(){}\[\]<>]/g,' ').replace(/\s+/g,' ').trim().toLowerCase(),O=v=>v&&typeof v==='object',A=v=>Array.isArray(v)?v:[],BN=v=>/[\u0980-\u09ff]/.test(T(v)),C=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
const load=p=>fetch(p,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(p+': HTTP '+r.status);return r.json()});
function ids(x,f){return T(O(x)?(x.id||x.canonicalId||x.canonical_id||x.iso3||x.isoCode||x.countryCode||x.code||x.key||x.ministerId||f):f)}
function names(x,f){if(!O(x))return f?[T(f)]:[];const r=[];for(const k of ['name','countryName','officialName','shortName','displayName','label','title','resourceName','canonicalName','localName','nativeName','name_en','name_bn','baseName','ministerName']){const v=x[k];if(typeof v==='string'&&v.trim())r.push(v);else if(O(v))for(const z of Object.values(v))if(typeof z==='string'&&z.trim())r.push(z)}if(f)r.push(T(f).replace(/[_-]+/g,' '));return[...new Set(r.filter(Boolean))]}
function forms(x){const q=N(x),r=new Set([q]),ss=[...(S.vocab?.morphology?.bn_suffixes||[]),...(S.vocab?.morphology?.en_suffixes||[])];for(const s of ss){const z=N(s);if(z&&q.endsWith(z)&&q.length>z.length+1)r.add(q.slice(0,-z.length))}return[...r]}
function put(type,x,f,source,map){const id=ids(x,f);if(!id)return;const e={id,type,names:names(x,f),raw:C(x),source};map.set(id,e);for(const z of e.names)for(const q of forms(z)){const k=type+':'+q, b=S.aliases.get(k)||[];if(!b.includes(id))b.push(id);S.aliases.set(k,b)}}
function ingestCountries(x){const q=Array.isArray(x)?x:(x?.countries||x?.data||Object.values(x||{}));q.forEach(z=>put('COUNTRY',z,ids(z),'countries.json',S.countries))}
function ingestMinisters(x){const db=x?.ministers_database||x?.ministers||x;if(!O(db))return;for(const[m,ls]of Object.entries(db))if(Array.isArray(ls))for(const z of ls)put('MINISTER',{...z,ministryId:z.ministryId||m},z.id,'ministers.json',S.ministers)}
function ingestResources(x){if(!O(x)||!Object.keys(x).length)return;const r=x.resources||x.resourceDatabase||x.RESOURCE_DATABASE||x.COMMODITY_ONTOLOGIES||x;if(Array.isArray(r))r.forEach(z=>put('RESOURCE',z,ids(z),'RESOURCE_DATASET',S.resources));else for(const[k,z]of Object.entries(r))put('RESOURCE',O(z)?z:{id:k,name:z},k,'RESOURCE_DATASET',S.resources)}
function vocab(){for(const[lang,v]of Object.entries(S.vocab?.languages||{})){for(const[q,ps]of Object.entries(v.question||{}))for(const p of A(ps))S.question.set(lang+':'+N(p),q);for(const[k,ps]of Object.entries(v.attributes||{}))for(const p of A(ps))S.attributes.set(lang+':'+N(p),k);for(const[k,ps]of Object.entries(v.assets||{}))for(const p of A(ps))S.assets.set(lang+':'+N(p),k)}}
function phrase(q,map,lang){const h=[];for(const[k,v]of map){if(!k.startsWith(lang+':'))continue;const p=k.slice(lang.length+1);if(q===p)h.push({v,p,s:1});else if(new RegExp('(^|\\s)'+p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=\\s|$)').test(q))h.push({v,p,s:.99});else if(q.includes(p))h.push({v,p,s:.90})}h.sort((x,y)=>y.s-x.s||y.p.length-x.p.length);return h[0]||null}
function entity(q,type){const m=type==='COUNTRY'?S.countries:type==='RESOURCE'?S.resources:S.ministers,h=[];for(const e of m.values())for(const z of e.names)for(const f of forms(z)){if(q===f)h.push({e,z,s:1});else if(new RegExp('(^|\\s)'+f.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=\\s|$)').test(q))h.push({e,z,s:.99});else if(q.includes(f))h.push({e,z,s:.90})}h.sort((x,y)=>y.s-x.s||y.z.length-x.z.length);if(!h.length)return{id:null,type,confidence:0,source:'UNRESOLVED',candidates:[]};const b=h[0],s=h[1]?.s||0,min=Number(S.knowledge?.ambiguity_policy?.minimum_confidence??.82),margin=Number(S.knowledge?.ambiguity_policy?.margin_over_second_best??.08);if(b.s<min||(s&&b.s-s<margin))return{id:null,type,confidence:b.s,source:'AMBIGUOUS',surface:b.z,candidates:h.slice(0,5).map(x=>({id:x.e.id,surface:x.z,confidence:x.s}))};return{id:b.e.id,type,confidence:b.s,source:b.e.source,surface:b.z,raw:C(b.e.raw)}}
function active(ctx){const r=g.OmegaMinisterStateRegistry,c=T(ctx?.countryId||ctx?.countryCode||g.Game?.state?.countryId||g.Game?.state?.playerCountryId||g.Game?.currentActiveCountry||'').toUpperCase(),m=T(ctx?.ministryId||g.Game?.state?.activeMinistryId||'');if(r&&c&&m&&typeof r.getActiveMinister==='function')try{const x=r.getActiveMinister(c,m);if(x)return x}catch(_){}for(const x of[ctx?.ministerId,g.Game?.state?.activeMinisterId,g.OmegaCabinetUI?.currentInterrogatedMinister?.ministerId])if(x&&S.ministers.has(String(x)))return S.ministers.get(String(x));return null}
function parse(q,ctx={}){const s=T(q),lang=BN(s)?'bn':'en',x=N(s),qh=phrase(x,S.question,lang),at=phrase(x,S.attributes,lang),country=entity(x,'COUNTRY'),resource=entity(x,'RESOURCE'),min=entity(x,'MINISTER'),am=active(ctx),self=/(^|\s)(you|your|yours|yourself)(\s|$)|তুমি|তোমার|আপনি|আপনার|নিজের/.test(x);if(!min.id&&self&&am)min={id:am.ministerId||am.id,type:'MINISTER',confidence:1,source:'AUTHORITATIVE_ACTIVE_MINISTER'};const qt=qh?.v||'UNKNOWN',op=qt==='how_many'?'COUNT':qt==='how_much'?'QUANTITY':qt==='how_old'?'ATTRIBUTE':at?'ATTRIBUTE':qt==='where'?'LOCATE':qt==='what'||qt==='who'?'IDENTIFY':qt==='which'?'SELECT':qt==='why'?'CAUSE':qt==='how'?'METHOD':qt==='should'?'POLICY':qt==='can'?'FEASIBILITY':qt==='will'?'FORECAST':'UNKNOWN';const target=min.id?'MINISTER':country.id&&resource.id?'COUNTRY_RESOURCE':resource.id?'RESOURCE':country.id?'COUNTRY':self?'MINISTER':'GENERAL';const unresolved=[];if(self&&!min.id)unresolved.push('MINISTER');if((op==='COUNT'||op==='LOCATE')&&!country.id&&!resource.id)unresolved.push('SUBJECT');return{version:V,surface:s,language:lang,question:{type:qt,phrase:qh?.p||null,confidence:qh?.s||0},attribute:at?{name:at.v,phrase:at.p,confidence:at.s}:null,targetDomain:target,operation:op,entities:{country,resource,minister:min},unresolved,confidence:Math.min(qh?.s||1,country.id?country.confidence:1,resource.id?resource.confidence:1,min.id?min.confidence:1),executable:!unresolved.length&&op!=='UNKNOWN'}}
function minister(id,k){const r=g.OmegaMinisterStateRegistry;let x=null;if(r&&typeof r.getMinister==='function')try{x=r.getMinister(id)}catch(_){}x=x||S.ministers.get(id)?.raw;if(!x)return null;const p=x.staticProfile||x.profile||x.identity||x,rt=x.runtimeState||x.runtime||{},l=x.learningState||x.learning||{};return({name:p.baseName??p.name??x.name??id,age:p.baseAge??p.age,background:p.background,gender:p.gender,role:p.role??rt.ministryId??p.ministryId,ministry:rt.ministryId??x.ministryId,country:rt.countryId??x.countryId,experience:l.totalServiceTime,stress:rt.stress,workload:rt.workload,skill:p.baseStats??p.stats})[k]}
function roots(){return[...S.datasets.values(),g.ResourceMinistryEngine,g.WorldEcosystemEngine,g.Game?.state,g.gameState,g.Omega?.World,g.Omega?.Resources,g.Omega?.Resource].filter(Boolean)}
function walk(v,path,out){if(!O(v))return;if(Array.isArray(v)){v.forEach((z,i)=>walk(z,path.concat(String(i)),out));return}out.push({v,path});for(const[k,z]of Object.entries(v))if(O(z))walk(z,path.concat(k),out)}
function assetRows(countryId,resourceId,asset){const all=[];for(const root of roots())walk(root,[],all);const ra=(S.resources.get(resourceId)?.names||[resourceId]).map(N),aw=[];for(const[k,v]of S.assets)if(v===asset)aw.push(k.slice(3));const rows=[];for(const e of all){const b=N(JSON.stringify(e.v)),p=e.path.map(N).join(' ');const cm=!countryId||b.includes(N(countryId))||p.includes(N(countryId)),rm=!resourceId||b.includes(N(resourceId))||ra.some(z=>b.includes(z)),am=aw.some(z=>b.includes(z)||p.includes(z));if(cm&&rm&&am)rows.push(e)}const u=new Set();return rows.filter(e=>{const k=e.path.join('.');if(u.has(k))return false;u.add(k);return true})}
function loc(rows){const out=[];const visit=(v,path)=>{if(!O(v))return;if(Array.isArray(v)){v.forEach((z,i)=>visit(z,path.concat(String(i))));return}for(const[k,z]of Object.entries(v)){const q=N(k);if(typeof z==='string'&&/(location|region|province|district|city|site|field|basin|deposit|address|latitude|longitude|lat|lng|lon|coordinates|area)/i.test(q))out.push({field:k,value:z,path:path.concat(k)});else if(O(z))visit(z,path.concat(k))}};rows.forEach(e=>visit(e.v,e.path));const u=new Set();return out.filter(e=>{const k=e.field+':'+e.value;if(u.has(k))return false;u.add(k);return true}).slice(0,100)}
function quantity(country,resource){const e=g.ResourceMinistryEngine;if(e&&typeof e.getIntegratedResourceState==='function')try{const x=e.getIntegratedResourceState(country);if(x)return{ok:true,value:x,source:'ResourceMinistryEngine'}}catch(_){}return{ok:false,reason:'RESOURCE_STATE_UNAVAILABLE'}}
function exec(p,ctx={}){if(!S.ready)return{ok:false,reason:'NOT_READY',text:p.language==='bn'?'অফলাইন জ্ঞান স্তর এখনো প্রস্তুত হচ্ছে।':'Offline knowledge is still loading.'};const e=p.entities;if(p.targetDomain==='MINISTER'){if(!e.minister.id)return{ok:false,reason:'MINISTER_UNRESOLVED',text:p.language==='bn'?'বর্তমান মন্ত্রী নির্ধারণ করা যায়নি।':'The current minister could not be resolved.'};if(p.attribute?.name){const v=minister(e.minister.id,p.attribute.name);return v==null?{ok:false,reason:'ATTRIBUTE_UNAVAILABLE'}:{ok:true,operation:'ATTRIBUTE',attribute:p.attribute.name,value:v,source:'AUTHORITATIVE_MINISTER_STATE'}}return{ok:true,operation:'IDENTIFY',value:g.OmegaMinisterStateRegistry?.getMinister?.(e.minister.id)||S.ministers.get(e.minister.id)?.raw,source:'AUTHORITATIVE_MINISTER_STATE'}}if(p.operation==='COUNT'){const rows=assetRows(e.country.id,e.resource.id,ctx.assetClass||'MINE');return{ok:true,operation:'COUNT',count:rows.length,countryId:e.country.id||null,resourceId:e.resource.id||null,assetClass:ctx.assetClass||'MINE',evidence:rows.slice(0,50).map(x=>x.path.join('.')),source:'RUNTIME_DATASET_SEARCH'}}if(p.operation==='LOCATE'){const rows=assetRows(e.country.id,e.resource.id,ctx.assetClass||'MINE');return{ok:true,operation:'LOCATE',count:rows.length,locations:loc(rows),source:'RUNTIME_DATASET_SEARCH',evidence:rows.slice(0,50).map(x=>x.path.join('.'))}}if(p.operation==='QUANTITY'&&e.country.id&&e.resource.id)return quantity(e.country.id,e.resource.id);if(p.operation==='IDENTIFY'&&e.resource.id)return{ok:true,operation:'IDENTIFY',value:S.resources.get(e.resource.id)?.raw||null,source:'RESOURCE_DATASET'};if(p.operation==='IDENTIFY'&&e.country.id)return{ok:true,operation:'IDENTIFY',value:S.countries.get(e.country.id)?.raw||null,source:'countries.json'};return{ok:false,reason:'NO_EXECUTOR',text:p.language==='bn'?'প্রশ্নটি বোঝা হয়েছে, কিন্তু নির্ভরযোগ্য রানটাইম ডেটা পথ নেই।':'The question was understood, but no reliable runtime data path exists.'}}
function fmt(p,r){if(!r?.ok)return r?.text||(p.language==='bn'?'নির্ভরযোগ্য তথ্য পাওয়া যায়নি।':'Reliable runtime evidence is not available.');if(r.operation==='ATTRIBUTE')return`${r.attribute}: ${r.value}`;if(r.operation==='COUNT')return p.language==='bn'?`রানটাইম ডেটা অনুযায়ী ${r.countryId||'অনুরোধ করা দেশের'}-এ ${r.resourceId?r.resourceId+' সম্পর্কিত ':''}${r.assetClass} রেকর্ডের সংখ্যা ${r.count}টি।`:`Runtime data reports ${r.count} ${r.assetClass}${r.resourceId?' records for '+r.resourceId:''} in ${r.countryId||'the requested country'}.`;if(r.operation==='LOCATE')return p.language==='bn'?`রানটাইম ডেটায় ${r.count}টি রেকর্ড পাওয়া গেছে। ${r.locations.slice(0,20).map(x=>x.field+': '+x.value).join('; ')}`:`The runtime dataset contains ${r.count} matching records. ${r.locations.slice(0,20).map(x=>x.field+': '+x.value).join('; ')||'No explicit location field was exposed.'}`;if(r.operation==='IDENTIFY')return r.value?.baseName||r.value?.name||r.value?.id||JSON.stringify(r.value||{},null,2);return JSON.stringify(r.value??r,null,2)}
function diagnostics(){return{version:V,ready:S.ready,countries:S.countries.size,resources:S.resources.size,ministers:S.ministers.size,datasets:[...S.datasets.keys()],errors:C(S.errors)}}
async function init(){try{const[v,k,c,m,o,r]=await Promise.all([load('/offline_language_vocabulary.json'),load('/offline_semantic_knowledge.json'),load('/countries.json'),load('/ministers.json'),load('/resource_ontology.json'),load('/resources.json')]);S.vocab=v;S.knowledge=k;vocab();ingestCountries(c);ingestMinisters(m);ingestResources(o);ingestResources(r);S.datasets.set('countries.json',c);S.datasets.set('ministers.json',m);S.datasets.set('resource_ontology.json',o);S.datasets.set('resources.json',r);S.ready=true;g.dispatchEvent(new CustomEvent('OMEGA_SEMANTIC_RUNTIME_READY',{detail:diagnostics()}))}catch(e){S.errors.push({code:'BOOT_FAILED',detail:e.message});console.error('[OMEGA Semantic V3.2]',e)}}
function plan(q,i={},w={},h=[]){const p=parse(q,{countryId:i.countryCode||w.countryCode,ministryId:i.ministryId,ministerId:i.ministerId}),r=exec(p,{});return{version:V,language:p.language,operation:p.operation,intent:p.targetDomain,entities:p.entities,semantic:p,result:r,derived:r?.operation==='COUNT'?[{metric:'count',value:r.count}]:[],identity:i,history:A(h).slice(-24)}}
const api={VERSION:V,init,parse,execute:exec,buildAnswerPlan:plan,formatOfflineAnswer:p=>fmt(p,p.result),diagnostics,registerDataset:(name,data)=>{S.datasets.set(name,data);return diagnostics()},learn:(s,type,id,c)=>{if(Number(c)<.95)return false;try{const x=JSON.parse(g.localStorage?.getItem('OMEGA_SEMANTIC_LEARNING_V3')||'{}');x[`${type}:${N(s)}`]={entityType:type,canonicalId:id,confidence:c};g.localStorage?.setItem('OMEGA_SEMANTIC_LEARNING_V3',JSON.stringify(x));return true}catch(_){return false}},recall:()=>{try{return JSON.parse(g.localStorage?.getItem('OMEGA_SEMANTIC_LEARNING_V3')||'{}')}catch(_){return{}}}};
g.OmegaSemanticRuntimeV32=api;g.OmegaAIIntegrity=Object.freeze({VERSION:V,canonicalMinisterIdentity:x=>({countryCode:T(x.countryCode||x.country||'').toUpperCase(),countryName:T(x.countryName||x.country||''),ministryId:T(x.ministryId||'').toUpperCase(),ministerId:T(x.ministerId||x.id||''),name:T(x.ministerName||x.name||x.id||''),role:T(x.ministerRole||x.role||''),age:Number.isFinite(Number(x.age))?Number(x.age):null,background:T(x.background||''),ideology:typeof x.ideology==='string'?x.ideology:x.ideology?.type||'',efficiency:Number.isFinite(Number(x.efficiency))?Number(x.efficiency):null,profileSource:T(x.profileSource||'RUNTIME_CANONICAL_IDENTITY')}),buildAnswerPlan:plan,formatOfflineAnswer:p=>fmt(p,p.result),parse,explain:(q,c)=>parse(q,c),diagnostics,learn:api.learn,recall:api.recall});g.MinisterQueryRouter=Object.freeze({VERSION:V,routeMinisterQuery:(q,m={},w={})=>{const p=parse(q,{...m,...w});return{version:V,intent:p.targetDomain,domain:p.targetDomain,entities:Object.values(p.entities).filter(x=>x?.id),requiredData:[p.operation],semantic:p,executable:p.executable}}});init();
})(typeof globalThis!=='undefined'?globalThis:window);
