/** OMEGA AI INTEGRITY LAYER v1.2.0
 * Canonical identity, read-only evidence grounding and bilingual offline cognition.
 */
(function (global) {
  'use strict';
  const VERSION = '1.2.0';
  const ALIASES = Object.freeze({
    CRUDE_OIL:['CRUDE_OIL','OIL','PETROLEUM','CRUDE','তেল','অপরিশোধিত তেল','পেট্রোলিয়াম'],
    NATURAL_GAS:['NATURAL_GAS','GAS','LNG','METHANE','গ্যাস','প্রাকৃতিক গ্যাস','এলএনজি'],
    RARE_EARTHS:['RARE_EARTH','RARE_EARTHS','REE','RARE EARTH ELEMENTS','বিরল মাটি','রেয়ার আর্থ','দুর্লভ খনিজ'],
    URANIUM:['URANIUM','ইউরেনিয়াম'], COAL:['COAL','কয়লা'], COPPER:['COPPER','তামা'],
    LITHIUM:['LITHIUM','লিথিয়াম'], GOLD:['GOLD','সোনা','স্বর্ণ']
  });
  const INTENTS = [
    ['MINISTER_IDENTITY',/\b(name|who are you|your name|age|background|identity)\b|নাম কী|তোমার নাম|আপনার নাম|কে আপনি|বয়স|পরিচয়/i],
    ['RESOURCE_SECURITY',/\b(secure|security|safe|stockpile|reserve|runway|shortage|supply)\b|নিরাপদ|নিরাপত্তা|মজুদ|মজুত|রিজার্ভ|ঘাটতি|সরবরাহ|কতদিন/i],
    ['RESOURCE_DISCOVERY',/\b(mine|mines|deposit|deposits|discovery|geological|basin)\b|খনি|খনিজ|ডিপোজিট|ভূতাত্ত্বিক|ভাণ্ডার|আবিষ্কার/i],
    ['MACROECONOMICS',/\b(gdp|inflation|debt|treasury|budget|fx|foreign exchange)\b|জিডিপি|মুদ্রাস্ফীতি|ঋণ|কোষাগার|বাজেট|বৈদেশিক মুদ্রা/i],
    ['POLICY_RECOMMENDATION',/\b(should|recommend|recommendation|what should|policy|plan|strategy)\b|কী করা উচিত|সুপারিশ|নীতি|পরিকল্পনা|কৌশল/i]
  ];
  const text=v=>String(v==null?'':v).trim();
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null;};
  function get(root,paths){for(const p of paths){let v=root,ok=true;for(const k of p.split('.')){if(v==null||typeof v!=='object'||!(k in v)){ok=false;break;}v=v[k];}if(ok&&v!==null&&v!==undefined)return v;}return null;}
  function identity(i={}){const cc=text(i.countryCode||i.country||'UNKNOWN').toUpperCase(),mid=text(i.ministryId||i.portfolioId||'UNKNOWN').toUpperCase();return Object.freeze({countryCode:cc,countryName:text(i.countryName||i.country||'Sovereign State'),ministryId:mid,ministerId:text(i.ministerId||i.id||`${cc}:${mid}:UNKNOWN`),name:text(i.ministerName||i.name||'Minister (Identity Unresolved)'),role:text(i.ministerRole||i.role||'Cabinet Minister'),profileSource:text(i.profileSource||'RUNTIME_CANONICAL_IDENTITY')});}
  function route(q){q=text(q);for(const [intent,re] of INTENTS)if(re.test(q))return{intent,confidence:0.95};return{intent:'GENERAL_STRATEGIC_QUERY',confidence:0.45};}
  function entities(q){const s=text(q).toLowerCase();return Object.entries(ALIASES).filter(([,a])=>a.some(x=>s.includes(x.toLowerCase()))).map(([k])=>k);}
  function snapshot(input={}){const s=input.worldState||input.gameState||input.reservesData||{};return Object.freeze({version:VERSION,timestamp:Date.now(),countryCode:text(input.countryCode||s.countryCode||s.iso||'UNKNOWN').toUpperCase(),resources:Object.freeze({...((s.resources||s.resourceState||s.strategic_resources)||{})}),economy:Object.freeze({...((s.economy||s.economic)||{})}),energy:Object.freeze({...((s.energy||s.power)||{})}),source:'READ_ONLY_WORLDSTATE_SNAPSHOT'});}
  function resource(snap,key){const r=snap.resources||{};for(const k of [key,key.toLowerCase(),key.replace(/_/g,' '),key.replace(/_/g,'')])if(Object.prototype.hasOwnProperty.call(r,k))return r[k];const f=JSON.stringify(r).toLowerCase();if(key==='CRUDE_OIL'&&f.includes('oil'))return r.oil||r.OIL||null;if(key==='NATURAL_GAS'&&f.includes('gas'))return r.gas||r.GAS||null;if(key==='RARE_EARTHS'&&(f.includes('rare')||f.includes('earth')))return r.rareEarths||r.RARE_EARTHS||null;return null;}
  function analyse(snap,key){const r=resource(snap,key),stock=num(get(r,['stockpile','stock','inventory','quantity','available','currentStock','strategicStockpile'])),demand=num(get(r,['dailyDemand','demandPerDay','dailyConsumption','consumptionPerDay','netDailyDemand'])),prod=num(get(r,['dailyProduction','productionPerDay','domesticProduction','extractionPerDay','production.daily']));const facts=[],derived=[],unknown=[];if(stock!==null)facts.push({metric:`${key}.stockpile`,value:stock,status:'VERIFIED_FACT'});else unknown.push(`${key}.stockpile`);if(demand!==null)facts.push({metric:`${key}.dailyDemand`,value:demand,status:'VERIFIED_FACT'});else unknown.push(`${key}.dailyDemand`);if(prod!==null)facts.push({metric:`${key}.domesticProduction`,value:prod,status:'VERIFIED_FACT'});else unknown.push(`${key}.domesticProduction`);if(stock!==null&&demand!==null){const burn=Math.max(0,demand-(prod||0));derived.push({metric:`${key}.runwayDays`,value:burn>0?Number((stock/burn).toFixed(2)):Infinity,status:'ESTIMATED',equation:'stockpile / max(0, dailyDemand - domesticProduction)'});}else unknown.push(`${key}.runwayDays`);return{key,facts,derived,unknown};}
  function plan(question,i,world){const id=identity(i),snap=snapshot({...world,countryCode:id.countryCode}),routing=route(question),keys=entities(question),a=keys.map(k=>analyse(snap,k)),facts=a.flatMap(x=>x.facts),derived=a.flatMap(x=>x.derived),unknown=a.flatMap(x=>x.unknown);let conclusion;if(routing.intent==='MINISTER_IDENTITY')conclusion=`I am ${id.name}, serving as ${id.role} for ${id.countryName}.`;else if(!keys.length)conclusion='The question requires domain telemetry that is not exposed through the offline evidence gateway.';else{const finite=derived.filter(x=>Number.isFinite(x.value));conclusion=finite.length?`The available telemetry supports a ${finite.sort((x,y)=>x.value-y.value)[0].value}-day calculated runway for the most constrained identified resource. This is a derived metric, not a guarantee of security.`:'The requested assessment is not computable from the available telemetry.';}return Object.freeze({version:VERSION,identity:id,routing,entities:keys,facts,derived,unknown,conclusion,recommendation:unknown.length?'Acquire missing telemetry before authorizing policy. Do not substitute invented values.':'Evaluate derived metrics against explicit simulation thresholds and policy objectives.',generatedBy:'OMEGA_AI_INTEGRITY_LAYER'});}
  function format(p,bn){if(p.routing.intent==='MINISTER_IDENTITY')return bn?`আমি ${p.identity.name}। আমি ${p.identity.countryName}-এর ${p.identity.role} হিসেবে দায়িত্ব পালন করছি।`:p.conclusion;const out=[bn?'উপলব্ধ টেলিমেট্রি অনুযায়ী মূল্যায়ন:':'Assessment from available telemetry:',p.conclusion];if(p.facts.length)out.push((bn?'যাচাইকৃত তথ্য:':'Verified facts:')+'\n'+p.facts.map(x=>`• ${x.metric}: ${x.value}`).join('\n'));if(p.derived.length)out.push((bn?'গণনাকৃত ফলাফল:':'Derived metrics:')+'\n'+p.derived.map(x=>`• ${x.metric}: ${x.value}`).join('\n'));if(p.unknown.length)out.push((bn?'অজানা/অনুপস্থিত: ':'Unknown or missing: ')+p.unknown.join(', '));out.push((bn?'সুপারিশ: ':'Recommendation: ')+p.recommendation);return out.join('\n\n');}
  const API={VERSION,canonicalMinisterIdentity:identity,detectIntent:route,findEntities:entities,buildWorldSnapshot:snapshot,analyseResource:analyse,buildAnswerPlan:plan,formatOfflineAnswer:format};global.OmegaAIIntegrity=API;global.__OMEGA_AI_INTEGRITY__={version:VERSION,installedAt:Date.now(),api:API};
  function installBridge(){const ui=global.OmegaCabinetUI;if(!ui||ui.__integrityBridgeInstalled)return false;ui.__integrityBridgeInstalled=true;const original=ui.thinkMinisterQuestion;if(typeof original!=='function')return true;ui.thinkMinisterQuestion=function(question,...rest){try{const active=ui.currentInterrogatedMinister||{};const country=global.Game?.currentActiveCountry||{};const id=identity({countryCode:country.iso||country.code||active.countryCode,countryName:country.name||country.countryName,ministryId:active.ministryId||active.id,ministerId:active.ministerId||active.id,ministerName:active.name||active.ministerName,ministerRole:active.role||active.ministerRole});const p=plan(question,id,{countryCode:id.countryCode,worldState:global.Game?.worldState,gameState:global.Game?.state,reservesData:global.Game?.resources||global.Game?.resourceState});global.__OMEGA_LAST_AI_PLAN__=p;return format(p,/[ঀ-৿]/.test(question)?'bn':'en');}catch(e){console.warn('[OMEGA AI Integrity] bridge fallback:',e);return original.call(this,question,...rest);}};return true;}
  let n=0;const timer=setInterval(()=>{n++;if(installBridge()||n>=100)clearInterval(timer);},100);installBridge();
})(typeof window!=='undefined'?window:globalThis);
