/* OMEGA COUNTRY SEMANTIC BRIDGE
 * Country identity comes from the repository registry; localized names are
 * generated from ISO data and resolved with vocabulary morphology.
 */
(function(g){'use strict';
if(g.OmegaCountrySemanticBridge)return;
const V='1.5.0';
const N=v=>String(v==null?'':v).normalize('NFKC').replace(/[?!,.:;'"(){}\[\]<>]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
let ready=false,countries=new Map(),suffixes=[];
function localized(code){const out=[];try{for(const locale of ['bn','en','ar','hi','fr','de','es','pt','ru','zh']){const d=new Intl.DisplayNames([locale],{type:'region'}).of(code);if(d)out.push(d)}}catch(_){}return out}
function add(raw,fallback){if(!raw||typeof raw!=='object')return;const id=String(raw.country_code||raw.iso3||raw.isoCode||raw.code||raw.id||fallback||'').trim().toUpperCase();if(!id)return;const names=[raw.country_name,raw.name,raw.officialName,raw.shortName,raw.displayName,raw.nativeName,...(id.length===2?localized(id):[])].filter(x=>typeof x==='string'&&x.trim());for(const x of names)countries.set(N(x),id);countries.set(N(id),id)}
async function init(){try{const[r,v]=await Promise.all([fetch('/relation_generation_engine.json',{cache:'no-store'}),fetch('/offline_language_vocabulary.json',{cache:'no-store'})]);if(!r.ok)throw Error('relation_generation_engine.json: HTTP '+r.status);const d=await r.json();const root=d?.RELATION_GENERATION_ENGINE?.srie_v2_asymmetrical_salience||d?.srie_v2_asymmetrical_salience||{};for(const[k,x]of Object.entries(root))add(x,k);if(v.ok){const lang=await v.json();suffixes=[...(lang?.morphology?.bn_suffixes||[]),...(lang?.morphology?.en_suffixes||[])].map(N)}ready=true;g.dispatchEvent(new CustomEvent('OMEGA_COUNTRY_SEMANTIC_READY',{detail:{version:V,countries:new Set(countries.values()).size}}))}catch(e){console.error('[OMEGA Country Semantic Bridge]',e)}}
function resolve(q){const x=N(q),variants=new Set([x]);for(const token of x.split(' '))for(const s of suffixes)if(s&&token.endsWith(s)&&token.length>s.length+1)variants.add(x.replace(token,token.slice(0,-s.length)));const hits=[];for(const[n,id]of countries){for(const qv of variants){if(qv===n)hits.push({id,s:1,n});else if(new RegExp('(^|\\s)'+n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=\\s|$)').test(qv))hits.push({id,s:.995,n})}}hits.sort((a,b)=>b.s-a.s||b.n.length-a.n.length);return hits[0]||null}
function currentMinister(ctx={}){const r=g.OmegaMinisterStateRegistry,c=String(ctx.countryId||ctx.countryCode||g.Game?.state?.countryId||g.Game?.state?.playerCountryId||g.Game?.currentActiveCountry||'').toUpperCase(),m=String(ctx.ministryId||g.Game?.state?.activeMinistryId||'');if(r&&c&&m&&typeof r.getActiveMinister==='function')try{const x=r.getActiveMinister(c,m);if(x)return x}catch(_){}for(const x of[ctx.ministerId,g.Game?.state?.activeMinisterId,g.OmegaCabinetUI?.currentInterrogatedMinister?.ministerId])if(x)return x;return null}
function install(){const base=g.OmegaSemanticRuntimeV32;if(!base||base.__countryBridgeV15)return false;const oldParse=base.parse,oldExecute=base.execute;
const parse=(q,c={})=>{const safe={...c,countryId:undefined,ministryId:undefined};let p;try{p=oldParse(q,safe)}catch(e){p=oldParse(q,{})}const self=/(^|\s)(you|your|yours|yourself)(\s|$)|তুমি|তোমার|আপনি|আপনার|নিজের/.test(N(q));if(self&&!p.entities.minister?.id){const m=currentMinister(c);const id=typeof m==='string'?m:(m?.ministerId||m?.id);if(id){p.entities.minister={id,type:'MINISTER',confidence:1,source:'AUTHORITATIVE_ACTIVE_MINISTER'};p.unresolved=(p.unresolved||[]).filter(x=>x!=='MINISTER');p.targetDomain='MINISTER';p.executable=p.unresolved.length===0&&p.operation!=='UNKNOWN'}}if(!p.entities.country?.id){const h=resolve(q);if(h){p.entities.country={id:h.id,type:'COUNTRY',confidence:h.s,source:'relation_generation_engine.json',surface:h.n};p.unresolved=(p.unresolved||[]).filter(x=>x!=='COUNTRY');p.executable=p.unresolved.length===0&&p.operation!=='UNKNOWN';if(p.operation==='COUNT'||p.operation==='LOCATE')p.targetDomain=p.entities.resource?.id?'COUNTRY_RESOURCE':'COUNTRY'}}return p};
const plan=(q,i={},w={},h=[])=>{const p=parse(q,{countryId:i.countryCode||w.countryCode,ministryId:i.ministryId,ministerId:i.ministerId});const r=oldExecute(p,{});return{version:V,language:p.language,operation:p.operation,intent:p.targetDomain,entities:p.entities,semantic:p,result:r,derived:r?.operation==='COUNT'?[{metric:'count',value:r.count}]:[],identity:i,history:Array.isArray(h)?h.slice(-24):[]}};
base.parse=parse;base.buildAnswerPlan=plan;base.__countryBridgeV15=true;
const prev=g.OmegaAIIntegrity||{};g.OmegaAIIntegrity={...prev,VERSION:'3.2.10-PRODUCTION',buildAnswerPlan:plan,formatOfflineAnswer:p=>{const r=p?.result;if(!r?.ok)return r?.text||'Reliable runtime evidence is not available.';if(r.operation==='COUNT')return p.language==='bn'?`রানটাইম ডেটা অনুযায়ী ${r.countryId||'অনুরোধ করা দেশে'}-এ ${r.resourceId?r.resourceId+' সম্পর্কিত ':''}${r.assetClass} রেকর্ডের সংখ্যা ${r.count}টি।`:`Runtime data reports ${r.count} ${r.assetClass}${r.resourceId?' records for '+r.resourceId:''} in ${r.countryId||'the requested country'}.`;if(r.operation==='LOCATE')return p.language==='bn'?`রানটাইম ডেটায় ${r.count}টি রেকর্ড পাওয়া গেছে।`:`The runtime dataset contains ${r.count} matching records.`;return String(r.value?.baseName||r.value?.name||r.value?.id||r.value||'Reliable runtime evidence is not available.')},parse};
const prevRouter=g.MinisterQueryRouter||{};g.MinisterQueryRouter={...prevRouter,VERSION:'3.2.10-PRODUCTION',routeMinisterQuery:(q,m={},w={})=>{const p=parse(q,{...m,...w});return{version:'3.2.10-PRODUCTION',intent:p.targetDomain,domain:p.targetDomain,entities:Object.values(p.entities).filter(x=>x?.id),requiredData:[p.operation],semantic:p,executable:p.executable}}};return true}
g.OmegaCountrySemanticBridge={VERSION:V,init,diagnostics:()=>({version:V,ready,countries:new Set(countries.values()).size}),resolve,install};
const boot=setInterval(()=>{if(install()){clearInterval(boot);init()}},50);setTimeout(()=>clearInterval(boot),15000);
})(typeof globalThis!=='undefined'?globalThis:window);
