/* OMEGA AI INTEGRITY LAYER v2.1.0-STRICT-ENTITY-GATE */
(function(global){'use strict';
const VERSION='2.1.0';
const MAX_HISTORY=24;
const S=v=>String(v==null?'':v).trim();
const N=v=>S(v).normalize('NFKC').replace(/[?!,.:;'"“”‘’(){}[\]<>—–]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
const clone=v=>{try{return v==null?v:JSON.parse(JSON.stringify(v))}catch(_){return null}};
const BN=v=>/[\u0980-\u09FF]/.test(S(v));
const historyStore=new Map();
function runtime(){return global.OmegaProductionSemanticRuntime||null}
function brain(){return global.OfflineSemanticBrain||null}
function engine(){return global.OfflineQueryEngine||null}
function countryBridge(){return global.OmegaCanonicalIdentityRegistry||global.OmegaCountrySemanticBridge||null}
function resourceBridge(){return global.OmegaResourceSemanticBridge||null}
function ministerBridge(){return global.OmegaMinisterStateRegistry||null}
function canonicalMinisterIdentity(input={}){return Object.freeze({countryCode:S(input.countryCode||input.country||'').toUpperCase(),countryName:S(input.countryName||''),ministryId:S(input.ministryId||input.portfolioId||'').toUpperCase(),ministerId:S(input.ministerId||input.id||''),name:S(input.ministerName||input.name||''),role:S(input.ministerRole||input.role||''),age:Number.isFinite(Number(input.age))?Number(input.age):null,background:S(input.background||''),ideology:S(input.ideology||''),efficiency:Number.isFinite(Number(input.efficiency))?Number(input.efficiency):null,profileSource:S(input.profileSource||'')})}
function explicitCountry(question){const b=countryBridge();try{const r=b?.resolveCountry?.(question);if(r?.id)return {...r,type:'COUNTRY',confidence:Number(r.confidence||1)}}catch(_){ }try{const rows=Array.isArray(b?.exportData?.()?.countries)?b.exportData().countries:[];const q=N(question);let best=null;for(const row of rows){const id=S(row?.id).toUpperCase();if(!id)continue;const names=[...(Array.isArray(row?.names)?row.names:[]),row?.name,row?.officialName].filter(Boolean);for(const raw of names){const n=N(raw);if(!n)continue;const exact=q===n,contains=q.includes(n),score=exact?1:contains?Math.min(.995,.90+n.length/Math.max(1,q.length*8)):0;if(score>0&&(!best||score>best.confidence))best={id,type:'COUNTRY',confidence:score,surface:raw,raw:clone(row),source:'CANONICAL_COUNTRY_DATA'}}}return best}catch(_){return null}}
function explicitResource(question){const b=resourceBridge();try{const r=b?.resolveResource?.(question);if(r?.id)return {...r,type:'RESOURCE',confidence:Number(r.confidence||1)}}catch(_){ }try{const rb=b?.exportData?.();const rows=Array.isArray(rb?.resources)?rb.resources:[];const q=N(question);let best=null;for(const row of rows){const id=S(row?.id||row?.resourceId||row?.key).toUpperCase();if(!id)continue;const names=[row?.name,row?.resourceName,row?.canonicalName,row?.displayName,...(Array.isArray(row?.names)?row.names:[])].filter(Boolean);for(const raw of names){const n=N(raw);if(!n)continue;const exact=q===n,contains=q.includes(n),score=exact?1:contains?Math.min(.995,.90+n.length/Math.max(1,q.length*8)):0;if(score>0&&(!best||score>best.confidence))best={id,type:'RESOURCE',confidence:score,surface:raw,raw:clone(row),source:'CANONICAL_RESOURCE_DATA'}}}return best}catch(_){return null}}
function baseParse(question,identity,world,history){const rt=runtime();try{if(rt?.parse)return rt.parse(question,identity,world,history)}catch(_){ }try{if(brain()?.parse)return brain().parse(question,{...identity,gameState:world})}catch(_){ }return{language:BN(question)?'bn':'en',raw:S(question),normalized:N(question),operation:'UNKNOWN',targetDomain:'GENERAL',entities:{country:null,resource:null,minister:null},unresolved:['SEMANTIC_RUNTIME_UNAVAILABLE'],executable:false}}
function repairSemantic(question,identity,world,history){const p=baseParse(question,identity,world,history)||{};const country=explicitCountry(question);const resource=explicitResource(question);const entities={...(p.entities||{})};if(country)entities.country=country;else if(entities.country?.id&&identity?.countryCode&&S(entities.country.id).toUpperCase()===S(identity.countryCode).toUpperCase()&&!new RegExp(N(identity.countryName||''),'i').test(N(question))){entities.country=null}
if(resource)entities.resource=resource;
let operation=S(p.operation||'UNKNOWN').toUpperCase();if((country||resource)&&(!operation||operation==='UNKNOWN'||operation==='GENERAL'||operation==='LOOKUP'))operation='IDENTIFY';
let target=resource&&country?'COUNTRY_RESOURCE':resource?'RESOURCE':country?'COUNTRY':p.targetDomain||'GENERAL';
if(!country&&!resource&&p.entities?.country?.id===identity?.countryCode&&!N(question).includes(N(identity?.countryName||'')))entities.country=null;
const unresolved=Array.isArray(p.unresolved)?p.unresolved.filter(x=>x!=='COUNTRY'&&x!=='RESOURCE'):[];
return Object.freeze({...p,language:p.language|| (BN(question)?'bn':'en'),operation,targetDomain:target,entities,unresolved,executable:unresolved.length===0&&operation!=='UNKNOWN'} )}
function executeSemantic(p,identity,world){const rt=runtime();try{if(rt?.execute)return rt.execute(p,{countryId:identity?.countryCode||world?.countryCode,ministerId:identity?.ministerId,ministryId:identity?.ministryId})}catch(_){ }
try{if(engine()?.execute)return engine().execute(p,[],p.language||'en',{...world,countryId:identity?.countryCode||world?.countryCode})}catch(_){ }
return{ok:false,reason:'NO_TRUSTED_EXECUTOR'} }
function buildWorldSnapshot(input={}){const state=input.worldState||input.gameState||{};return Object.freeze({version:VERSION,timestamp:Date.now(),countryCode:S(input.countryCode||state.countryCode||'').toUpperCase(),state:clone(state)||{},sources:clone(input.sources||null),source:'STRICT_DATA_SNAPSHOT'})}
function buildAnswerPlan(question,identityInput={},worldInput={},history=[]){const identity=canonicalMinisterIdentity(identityInput),historyRows=Array.isArray(history)?history.slice(-MAX_HISTORY):[],semantic=repairSemantic(question,identity,worldInput,historyRows);const result=executeSemantic(semantic,identity,worldInput);return Object.freeze({version:VERSION,identity,snapshot:buildWorldSnapshot({...worldInput,countryCode:identity.countryCode}),routing:{intent:semantic.question?.type||semantic.operation,confidence:semantic.confidence||0},operation:semantic.operation,entities:Object.values(semantic.entities||{}).filter(Boolean),semantic,analyses:[],facts:result?.facts||result?.evidence||[],derived:result?.calculations||[],unknown:result?.uncertainties||[],result,language:semantic.language,question:S(question),generatedBy:'OMEGA_STRICT_ENTITY_GATE'})}
function formatOfflineAnswer(plan){const r=plan?.result,s=plan?.semantic||{};const bn=s.language==='bn'||BN(plan?.question);if(r?.ok&&r.operation==='IDENTIFY'){const e=s.entities||{};if(e.country?.id){const name=S(e.country.surface||e.country.name||e.country.id),id=S(e.country.id).toUpperCase();return bn?`পরিচয়: ${name}। Canonical ID: ${id}.`:`Identity: ${name}. Canonical ID: ${id}.`}if(e.resource?.id){const name=S(e.resource.surface||e.resource.name||e.resource.id),id=S(e.resource.id).toUpperCase();return bn?`পরিচয়: ${name}। Resource ID: ${id}.`:`Identity: ${name}. Resource ID: ${id}.`}}
if(r?.text)return S(r.text);if(r?.answer)return S(r.answer);if(r?.ok&&r.value!=null)return typeof r.value==='string'||typeof r.value==='number'?`${s.operation}: ${r.value}`:JSON.stringify(r.value,null,2);const e=s.entities||{};if(e.country?.id)return bn?`দেশ শনাক্ত হয়েছে: ${e.country.surface||e.country.id}। Canonical ID: ${e.country.id}.`:`Country resolved: ${e.country.surface||e.country.id}. Canonical ID: ${e.country.id}.`;if(e.resource?.id)return bn?`সম্পদ শনাক্ত হয়েছে: ${e.resource.surface||e.resource.id}। Resource ID: ${e.resource.id}.`:`Resource resolved: ${e.resource.surface||e.resource.id}. Resource ID: ${e.resource.id}.`;return bn?'প্রশ্নটির জন্য নির্ভরযোগ্য ডেটা-পথ পাওয়া যায়নি।':'No reliable data route was found for this question.'}
function detectIntent(question){const p=repairSemantic(question,{},{});return{intent:p.operation||p.question?.type||'UNKNOWN',confidence:Number(p.confidence||p.question?.confidence||0)}}
function findEntities(question){const p=repairSemantic(question,{},{}),out=[];for(const e of Object.values(p.entities||{}))if(e?.id)out.push(S(e.id).toUpperCase());return[...new Set(out)]}
function analyseResource(snapshot,key){const r=explicitResource(key),rt=resourceBridge();if(!r)return{key:S(key),resourceId:null,facts:[],unknown:['RESOURCE_NOT_RESOLVED']};try{if(rt?.resolveResource)return{key:S(key),resourceId:r.id,raw:clone(r.raw||r.record||null),facts:[],derived:[],unknown:[]}}catch(_){ }return{key:S(key),resourceId:r.id,raw:clone(r.raw||null),facts:[],derived:[],unknown:[]}}
function conversationKey(identity){return[S(identity.countryCode),S(identity.ministryId),S(identity.ministerId)].join(':')}
function getConversationHistory(identity){return(historyStore.get(conversationKey(canonicalMinisterIdentity(identity)))||[]).slice()}
function answer(question,ui){const identity=canonicalMinisterIdentity(ui?.currentInterrogatedMinister||ui?.activeMinister||ui||{}),world={countryCode:identity.countryCode,gameState:global.Game?.state||{},worldState:global.Game?.worldState||{},reservesData:global.Game?.resources||null};const history=getConversationHistory(identity),plan=buildAnswerPlan(question,identity,world,history),response=formatOfflineAnswer(plan),key=conversationKey(identity),next=history.slice(-MAX_HISTORY+1);next.push({question:S(question),operation:plan.operation,entities:clone(plan.entities)||[],answer:response,timestamp:Date.now()});historyStore.set(key,next);global.__OMEGA_LAST_AI_PLAN__=plan;global.__OMEGA_AI_CONVERSATION__=next;return response}
const API=Object.freeze({VERSION,canonicalMinisterIdentity,normalize:N,detectIntent,findEntities,buildWorldSnapshot,analyseResource,buildAnswerPlan,formatOfflineAnswer,answer,getConversationHistory});
global.OmegaAIIntegrity=API;global.__OMEGA_AI_INTEGRITY__={version:VERSION,installedAt:Date.now(),api:API};
function installBridge(){const ui=global.OmegaCabinetUI;if(!ui||ui.__integrityBridgeInstalled)return false;ui.__integrityBridgeInstalled=true;for(const name of ['thinkMinisterQuestion','processMinisterQuestion','askMinister','handleMinisterQuestion']){const original=ui[name];if(typeof original==='function'&&!original.__strictIntegrityWrapped){const wrapped=function(q,...rest){try{return answer(q,this)}catch(e){console.warn('[OMEGA STRICT INTEGRITY]',e);return original.call(this,q,...rest)}};wrapped.__strictIntegrityWrapped=true;ui[name]=wrapped}}ui.__omegaOfflineAnswer=q=>answer(q,ui);ui.__omegaSemanticPlan=q=>buildAnswerPlan(q,canonicalMinisterIdentity(ui?.currentInterrogatedMinister||ui?.activeMinister||ui||{}),global.Game?.state||{},getConversationHistory(canonicalMinisterIdentity(ui?.currentInterrogatedMinister||ui?.activeMinister||ui||{})));return true}
installBridge();
})(typeof globalThis!=='undefined'?globalThis:window);
