/* OMEGA LANGUAGE EXECUTION MODULE v2.0.0 */
(function(global){'use strict';
let RUNTIME_DATASETS=[];
const O=v=>v&&typeof v==='object',S=v=>String(v==null?'':v).trim(),N=v=>S(v).normalize('NFKC').toLowerCase().replace(/[?!,.:;"'“”‘’(){}\[\]<>—–]/g,' ').replace(/\s+/g,' ').trim();
const ID_KEYS=['id','iso3','iso','isoCode','countryCode','code','canonical_id','canonicalId','resourceId','ministerId','key'];
const NAME_KEYS=['name','countryName','officialName','shortName','displayName','label','title','resourceName','canonicalName','localName','nativeName','name_en','name_bn','baseName','key'];
const METRICS={production:['production','annual_production','daily_production','monthly_production','output','extraction','produced','domestic_supply','উৎপাদন'],consumption:['consumption','annual_consumption','daily_consumption','monthly_consumption','demand','annual_demand','daily_demand','use','usage','burn_rate','offtake','চাহিদা'],reserve:['reserve','reserves','proved_reserves','recoverable_reserves','resource_reserves','in_situ','remaining_reserves','রিজার্ভ'],stock:['stockpile','stockpiles','inventory','inventories','on_hand','available_stock','current_stock','strategic_stock','buffer_stock','মজুদ','মজুত'],imports:['import','imports','import_volume','import_dependency','import_dependence','import_need','imported','আমদানি'],exports:['export','exports','export_volume','export_capacity','exportable','available_for_export','রপ্তানি'],price:['price','unit_price','market_price','spot_price','supplier_price','import_price','export_price','cost','unit_cost','দাম','মূল্য'],capacity:['capacity','production_capacity','storage_capacity','export_capacity','refining_capacity','processing_capacity','ধারণক্ষমতা'],risk:['risk','risk_score','vulnerability','exposure','threat','ঝুঁকি']};
function configureDatasets(ds){RUNTIME_DATASETS=Array.isArray(ds)?ds.filter(O).slice(0,512):[];return RUNTIME_DATASETS.length}
function walk(v,fn,p=[],key=null){if(!O(v))return;if(Array.isArray(v)){v.forEach((x,i)=>walk(x,fn,p.concat(i),String(i)));return}fn(v,p,key);for(const[k,x]of Object.entries(v))if(O(x)&&!['__proto__','constructor','prototype'].includes(k))walk(x,fn,p.concat(k),k)}
function fields(v,p='',out=[]){if(!O(v))return out;if(Array.isArray(v)){v.forEach((x,i)=>fields(x,`${p}[${i}]`,out));return out}for(const[k,x]of Object.entries(v))if(!['__proto__','constructor','prototype'].includes(k)){const q=p?`${p}.${k}`:k;if(['string','number','boolean'].includes(typeof x))out.push({key:k,path:q,value:x});else if(O(x))fields(x,q,out)}return out}
function ids(v,key){const out=[];if(O(v))for(const k of ID_KEYS)if(S(v[k]))out.push(S(v[k]).toUpperCase());if(key&&!/^\d+$/.test(S(key)))out.push(S(key).replace(/[_-]+/g,' ').toUpperCase());return[...new Set(out)]}
function names(v,key){const out=[];if(O(v))for(const k of NAME_KEYS){const x=v[k];if(typeof x==='string'&&x.trim())out.push(x);else if(O(x))for(const y of Object.values(x))if(typeof y==='string'&&y.trim())out.push(y)}if(key&&!/^\d+$/.test(S(key)))out.push(S(key).replace(/[_-]+/g,' '));return[...new Set(out)]}
function index(ds){const countries=[],resources=[],ministers=[],cm=new Set(),rm=new Set(),mm=new Set();for(const d of ds||[])walk(d,(v,p,key)=>{const e={value:v,path:p,ids:ids(v,key),names:names(v,key),key:S(key)},b=N(p.join(' ')+' '+Object.keys(v).join(' ')+' '+e.names.join(' ')+' '+e.ids.join(' '));const cid=e.ids.find(x=>/^[A-Z]{3}$/.test(x));if(cid&&/(country|nation|sovereign|countryprofiles|state_profiles|countries)/.test(b)&&!cm.has(cid)){cm.add(cid);countries.push({...e,id:cid})}if(/resource|commodity|mineral|hydrocarbon|petroleum|crude|ore|metal|fuel|critical|strategic_resource|resource_types|commodity_ontologies|mine/.test(b)){const rid=e.ids.find(x=>x.length>=3&&x.length<=64)||N(e.names[0]||'').replace(/\s+/g,'_').toUpperCase();if(rid&&!rm.has(rid)){rm.add(rid);resources.push({...e,id:rid})}}if(/minister|cabinet|official|candidate/.test(b)||('age'in v&&('stats'in v||'efficiency'in v))){const mid=e.ids.find(x=>x.length>=3&&x.length<=64)||N(e.names[0]||'').replace(/\s+/g,'_').toUpperCase();if(mid&&!mm.has(mid)){mm.add(mid);ministers.push({...e,id:mid})}}});return{countries,resources,ministers}}
function score(q,n){q=N(q);n=N(n);if(q===n)return 1;if(q.includes(n))return .97;if(n.includes(q))return .90;const a=n.split(/\s+/),b=new Set(q.split(/\s+/)),o=a.filter(x=>b.has(x)).length;return o?Math.min(.88,.4+.5*o/a.length):0}
function allMatches(q,list){return(list||[]).map(e=>{let s=0,surface=null;for(const n of e.names||[]){const x=score(q,n);if(x>s){s=x;surface=n}}return{...e,surface,score:s}}).filter(e=>e.score>.48).sort((a,b)=>b.score-a.score||S(b.surface).length-S(a.surface).length)}
function metric(v,kind){const a=(METRICS[kind]||[]).map(N);for(const f of fields(v)){const k=N(f.key);if(a.some(x=>k===x||k.includes(x))){const n=typeof f.value==='number'?f.value:Number(String(f.value).replace(/,/g,''));if(Number.isFinite(n))return{value:n,key:f.key,path:f.path}}}return null}
function daily(x){if(!x)return null;const k=N(x.key);if(/annual|year|বার্ষিক/.test(k))return x.value/365;if(/monthly|month|মাসিক/.test(k))return x.value/30;if(/weekly|week|সাপ্তাহিক/.test(k))return x.value/7;return x.value}
function node(country,re){if(!country||!re)return country?.value||null;const terms=[...(re.ids||[]),...(re.names||[]),re.surface].filter(Boolean).map(N);let hit=country.value,bs=0;walk(country.value,(v,p,key)=>{const b=N(names(v,key).join(' ')+' '+ids(v,key).join(' ')+' '+fields(v).slice(0,50).map(f=>`${f.key} ${f.value}`).join(' '));let s=0;for(const t of terms)if(t&&b.includes(t))s=Math.max(s,Math.min(.9,.45+t.length/80));if(s>bs){bs=s;hit=v}});return hit}
function resolveCountry(ir,ctx,idx){const id=S(ir?.countryId||ctx?.countryId).toUpperCase();if(id)return idx.countries.find(x=>x.id===id||x.ids.includes(id))||null;const q=ir?.entities?.find?.(x=>x.type==='COUNTRY')?.surface||ctx?.countryName||'';return q?allMatches(q,idx.countries)[0]||null:null}
function resolveResources(ir,raw,idx){const out=[];const er=ir?.entities?.find?.(x=>x.type==='RESOURCE');if(er?.id){const r=idx.resources.find(x=>x.id===S(er.id).toUpperCase());if(r)out.push(r)}for(const r of allMatches(raw,idx.resources))if(!out.some(x=>x.id===r.id))out.push(r);return out.slice(0,8)}
function execute(ir,ctx={}){const raw=S(ir?.surface||''),idx=index(Array.isArray(ctx?.datasets)?ctx.datasets:RUNTIME_DATASETS),country=resolveCountry(ir,ctx,idx),resources=resolveResources(ir,raw,idx),bn=ir?.language==='bn'||/[\u0980-\u09FF]/.test(raw),op=S(ir?.operation||'IDENTIFY').toUpperCase();if(op==='COUNT'){const resource=resources[0];if(country&&resource){const root=node(country,resource),candidate=metric(root,'production')||metric(root,'reserve')||metric(root,'stock');return{available:true,operation:op,count:candidate?1:0,candidate,resourceId:resource.id,countryId:country.id,answer:bn?`মিলেছে ${candidate?1:0}টি সংশ্লিষ্ট রেকর্ড।`:`Found ${candidate?1:0} matching record(s).`}}return{available:false,operation:op,unknowns:['count target'],answer:bn?'গণনার লক্ষ্য বর্তমান ডেটায় প্রমাণিত নয়।':'The count target is not evidenced by the current data.'}}
if(op==='QUANTITY'||op==='CALCULATE'||op==='CHECK'){const resource=resources[0],root=country&&resource?node(country,resource):country?.value||resource?.value||null;for(const k of ['production','consumption','reserve','stock','imports','exports','price','capacity','risk']){const z=metric(root,k);if(z&&new RegExp((METRICS[k]||[]).join('|'),'i').test(raw))return{available:true,operation:op,...z,resourceId:resource?.id||null,countryId:country?.id||null,answer:bn?`${k}: ${z.value}`:`${k}: ${z.value}`}}return{available:false,operation:op,unknowns:['requested metric'],answer:bn?'চাওয়া পরিমাণ বর্তমান ডেটায় প্রমাণিত নয়।':'The requested quantity is not evidenced by the current data.'}}
if(op==='RECOMMEND'&&/import|supplier|source|আমদানি|সরবরাহকারী|কোন দেশ থেকে/i.test(raw)){const re=resources[0];const rows=[];if(re)for(const c of idx.countries){if(country&&c.id===country.id)continue;const root=node(c,re),p=metric(root,'production'),e=metric(root,'exports'),r=metric(root,'reserve');if(p||e||r)rows.push({countryId:c.id,countryName:c.names?.[0]||c.id,score:(e?50:0)+(p?25:0)+(r?15:0),production:p?.value??null,exports:e?.value??null,reserves:r?.value??null})}rows.sort((a,b)=>b.score-a.score);return{available:rows.length>0,operation:op,rows:rows.slice(0,10),answer:bn?`সম্ভাব্য সরবরাহকারী:\n${rows.slice(0,5).map((r,i)=>`${i+1}. ${r.countryName} (${r.score}/100)`).join('\n')}`:`Potential suppliers:\n${rows.slice(0,5).map((r,i)=>`${i+1}. ${r.countryName} (${r.score}/100)`).join('\n')}`}}
if(op==='LOCATION'){const re=resources[0];const root=country&&re?node(country,re):null;return{available:!!root,operation:op,countryId:country?.id||null,countryName:country?.names?.[0]||null,resourceId:re?.id||null,resourceName:re?.names?.[0]||re?.surface||null,record:root,answer:root?(bn?'সংশ্লিষ্ট ডেটা রেকর্ড পাওয়া গেছে।':'A matching data record was found.'):(bn?'কোনো প্রমাণিত রেকর্ড পাওয়া যায়নি।':'No evidenced matching record was found.')}}
if(op==='IDENTIFY')return{available:true,operation:op,country:country?{id:country.id,name:country.names?.[0]||country.id}:null,resources:resources.map(r=>({id:r.id,name:r.names?.[0]||r.surface})),answer:bn?'প্রশ্নটি বর্তমান গেম ডেটার সঙ্গে মিলিয়ে নেওয়া হয়েছে।':'The query has been resolved against current game data.'};
if(['IMPORT','EXPORT','BUILD','INCREASE','DECREASE','START','HALT'].includes(op))return{available:true,operation:op,status:'ACTION_REQUESTED',event:{type:'GAME_EVENT_REQUEST',state:'EVENT_PENDING',operation:op,createdAt:Date.now()},answer:bn?`কমান্ডটি ${op} হিসেবে শনাক্ত হয়েছে এবং pending.`:`Command recognized as ${op} and is pending.`};
return{available:false,operation:op,status:'CAPABILITY_REQUIRED',unknowns:['operation capability'],answer:bn?'এই অপারেশনের জন্য নির্দিষ্ট capability engine প্রয়োজন।':'A dedicated capability engine is required for this operation.'}}
global.OmegaQueryExecutor=Object.freeze({VERSION:'2.0.0',configureDatasets,execute});
})(typeof window!=='undefined'?window:globalThis);
