/* OMEGA LANGUAGE EXECUTION MODULE v1.0.0 */
(function(global){'use strict';
const O=v=>v&&typeof v==='object';
const S=v=>String(v==null?'':v).trim();
const N=v=>S(v).normalize('NFKC').toLowerCase().replace(/[?!,.:;"'“”‘’(){}\[\]<>—–]/g,' ').replace(/\s+/g,' ').trim();
const NUM=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;const m=S(v).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null};
const ID_KEYS=['id','iso3','iso','isoCode','countryCode','code','canonical_id','canonicalId','resourceId','ministerId','key'];
const NAME_KEYS=['name','countryName','officialName','shortName','displayName','label','title','resourceName','canonicalName','localName','nativeName','name_en','name_bn','baseName','key'];
const METRICS={stock:['stockpile','stockpiles','inventory','inventories','on_hand','available_stock','current_stock','strategic_stock','strategic_reserve','buffer_stock','মজুদ','মজুত'],production:['production','annual_production','daily_production','monthly_production','output','extraction','produced','domestic_supply','উৎপাদন'],consumption:['consumption','annual_consumption','daily_consumption','monthly_consumption','demand','annual_demand','daily_demand','use','usage','burn_rate','offtake','চাহিদা','ব্যবহার'],reserve:['reserve','reserves','proved_reserves','recoverable_reserves','resource_reserves','in_situ','remaining_reserves','রিজার্ভ'],imports:['import','imports','import_volume','import_dependency','import_dependence','import_need','imported','আমদানি'],exports:['export','exports','export_volume','export_capacity','exportable','available_for_export','রপ্তানি'],price:['price','unit_price','market_price','spot_price','supplier_price','import_price','export_price','cost','unit_cost','দাম','মূল্য'],capacity:['capacity','production_capacity','storage_capacity','export_capacity','refining_capacity','processing_capacity','ধারণক্ষমতা'],risk:['risk','risk_score','vulnerability','exposure','threat','ঝুঁকি']};
const ACTION_TERMS={IMPORT:/\bimport\b|আমদানি/i,EXPORT:/\bexport\b|রপ্তানি/i,BUILD:/\bbuild|construct|establish\b|নির্মাণ|স্থাপন/i,INCREASE:/\bincrease|raise|expand\b|বৃদ্ধি|বাড়াও|বাড়াও/i,DECREASE:/\bdecrease|reduce|cut\b|কমানো|কমান/i,START:/\bstart|resume\b|চালু|শুরু/i,HALT:/\bhalt|stop|pause\b|বন্ধ|থামাও/i};
function walk(v,fn,p=[],par=null,key=null){if(!O(v))return;if(Array.isArray(v)){v.forEach((x,i)=>walk(x,fn,p.concat(i),v,i));return}fn(v,p,par,key);for(const[k,x]of Object.entries(v))if(O(x))walk(x,fn,p.concat(k),v,k)}
function fields(v,p='',out=[]){if(!O(v))return out;if(Array.isArray(v)){v.forEach((x,i)=>fields(x,`${p}[${i}]`,out));return out}for(const[k,x]of Object.entries(v))if(k!=='__proto__'&&k!=='constructor'&&k!=='prototype'){const q=p?`${p}.${k}`:k;if(['string','number','boolean'].includes(typeof x))out.push({key:k,path:q,value:x});else if(O(x))fields(x,q,out)}return out}
function ids(v,key){const out=[];if(O(v))for(const k of ID_KEYS)if(S(v[k]))out.push(S(v[k]).toUpperCase());if(key&&!/^\d+$/.test(S(key)))out.push(S(key).replace(/[_-]+/g,' ').toUpperCase());return[...new Set(out)]}
function names(v,key){const out=[];if(O(v))for(const k of NAME_KEYS){const x=v[k];if(typeof x==='string'&&x.trim())out.push(x);else if(O(x))for(const y of Object.values(x))if(typeof y==='string'&&y.trim())out.push(y)}if(key&&!/^\d+$/.test(S(key)))out.push(S(key).replace(/[_-]+/g,' '));return[...new Set(out)]}
function index(datasets){const all=[],countries=[],resources=[],ministers=[],cm=new Set(),rm=new Set(),mm=new Set();for(const d of datasets||[])walk(d,(v,p,par,key)=>{const r={value:v,path:p,ids:ids(v,key),names:names(v,key),key:S(key)};if(r.ids.length||r.names.length)all.push(r);const b=N(p.join(' ')+' '+Object.keys(v).join(' ')+' '+r.names.join(' ')+' '+r.ids.join(' '));const cid=r.ids.find(x=>/^[A-Z]{3}$/.test(x));if(cid&&/(country|nation|sovereign|countryprofiles|state_profiles|countries)/.test(b)&&!cm.has(cid)){cm.add(cid);countries.push({...r,id:cid})}if(/resource|commodity|mineral|hydrocarbon|petroleum|crude|ore|metal|fuel|critical|strategic_resource|resource_types|commodity_ontologies|mine/.test(b)){const rid=r.ids.find(x=>x.length>=3&&x.length<=64)||N(r.names[0]||'').replace(/\s+/g,'_').toUpperCase();if(rid&&!rm.has(rid)){rm.add(rid);resources.push({...r,id:rid})}}if(/minister|cabinet|official|candidate/.test(b)||('age'in v&&('stats'in v||'efficiency'in v))){const mid=r.ids.find(x=>x.length>=3&&x.length<=64)||N(r.names[0]||'').replace(/\s+/g,'_').toUpperCase();if(mid&&!mm.has(mid)){mm.add(mid);ministers.push({...r,id:mid})}}});return{all,countries,resources,ministers}}
function score(q,n){q=N(q);n=N(n);if(!q||!n)return 0;if(q===n)return 1;if(q.includes(n))return .97;if(n.includes(q))return .90;const a=n.split(/\s+/),b=new Set(q.split(/\s+/)),o=a.filter(x=>b.has(x)).length;return o?Math.min(.88,.4+.5*o/a.length):0}
function allMatches(q,list){return(list||[]).map(e=>{let s=0,surface=null;for(const n of e.names||[]){const x=score(q,n);if(x>s){s=x;surface=n}}return{...e,surface,score:s}}).filter(e=>e.score>.48).sort((a,b)=>b.score-a.score||S(b.surface).length-S(a.surface).length)}
function best(q,list){return allMatches(q,list)[0]||null}
function metric(v,kind){const aliases=(METRICS[kind]||[]).map(N);for(const f of fields(v)){const k=N(f.key);if(aliases.some(a=>k===a||k.includes(a))){const n=NUM(f.value);if(n!==null)return{value:n,raw:f.value,key:f.key,path:f.path}}}return null}
function daily(x){if(!x)return null;const k=N(x.key);if(/annual|year|yearly|বার্ষিক/.test(k))return x.value/365;if(/monthly|month|মাসিক/.test(k))return x.value/30;if(/weekly|week|সাপ্তাহিক/.test(k))return x.value/7;return x.value}
function node(country,re){if(!country||!re)return country?.value||null;const terms=[...(re.ids||[]),...(re.names||[]),re.surface].filter(Boolean).map(N);let hit=country.value,bs=0;walk(country.value,(v,p,par,key)=>{const b=N(names(v,key).join(' ')+' '+ids(v,key).join(' ')+' '+fields(v).slice(0,60).map(f=>`${f.key} ${f.value}`).join(' '));let s=0;for(const t of terms)if(t&&b.includes(t))s=Math.max(s,Math.min(.9,.45+t.length/80));if(fields(v).some(f=>/(stock|reserve|production|consumption|demand|import|export|capacity|price|risk)/i.test(f.key)))s+=.12;if(s>bs){bs=s;hit=v}});return hit}
function resolveCountry(parsed,ctx,idx){const id=S(parsed?.entities?.COUNTRY?.id||parsed?.countryId||ctx?.countryId).toUpperCase();if(id){const r=idx.countries.find(x=>x.id===id||x.ids.includes(id));if(r)return r}const q=parsed?.entities?.find?.(x=>x.type==='COUNTRY')?.surface||ctx?.countryName||'';return q?best(q,idx.countries):null}
function resolveResources(parsed,raw,idx){const found=[];const ent=parsed?.entities?.find?.(x=>x.type==='RESOURCE');if(ent?.id){const r=idx.resources.find(x=>x.id===S(ent.id).toUpperCase());if(r)found.push(r)}for(const r of allMatches(raw,idx.resources))if(!found.some(x=>x.id===r.id))found.push(r);return found.slice(0,8)}
function resolveMinister(parsed,ctx,idx){const id=S(ctx?.ministerId||'').toUpperCase();if(id)return idx.ministers.find(x=>x.id===id)||null;const q=parsed?.entities?.find?.(x=>x.type==='MINISTER')?.surface||ctx?.ministerName||'';return q?best(q,idx.ministers):null}
function security(country,re){const root=node(country,re);const s=metric(root,'stock'),c=metric(root,'consumption'),p=metric(root,'production'),r=metric(root,'reserve'),i=metric(root,'imports'),e=metric(root,'exports'),risk=metric(root,'risk');const cd=daily(c),pd=daily(p),id=daily(i);const runway=s&&cd>0?s.value/cd:null;let score=null;const evidence=[],unknowns=[];if(s){score=50+Math.min(25,Math.log10(Math.max(1,s.value))*5);evidence.push({metric:'stock',value:s.value,key:s.key})}else unknowns.push('stockpile');if(runway!==null){score+=(runway>=90?20:runway>=30?10:runway>=14?0:-20);evidence.push({metric:'runwayDays',value:Number(runway.toFixed(1))})}else unknowns.push('consumption/demand');if(r){score+=8;evidence.push({metric:'reserves',value:r.value,key:r.key})}else unknowns.push('reserves');if(pd!==null&&cd!==null)score+=pd>=cd?7:-7;else unknowns.push('production');if(id!==null&&cd!==null)score+=id/cd>.5?-10:4;if(e)score+=3;if(risk)score-=Math.max(0,Math.min(30,risk.value));if(score!==null)score=Math.max(0,Math.min(100,score));return{resourceId:re.id||re.ids?.[0]||null,resourceName:re.names?.[0]||re.surface||re.id,status:score===null?'UNKNOWN':score>=80?'SECURE':score>=60?'STABLE':score>=40?'VULNERABLE':'AT_RISK',score:score===null?null:Number(score.toFixed(1)),stockpile:s||null,consumption:c||null,production:p||null,reserves:r||null,imports:i||null,exports:e||null,runwayDays:runway===null?null:Number(runway.toFixed(1)),evidence,unknowns}}
function countAssets(raw,idx){const matches=allMatches(raw,idx.resources);return matches.map(r=>({id:r.id,name:r.names?.[0]||r.surface,count:1}))}
function suppliers(home,re,idx){const rows=[];for(const c of idx.countries){if(home&&c.id===home.id)continue;const root=node(c,re),p=metric(root,'production'),r=metric(root,'reserve'),e=metric(root,'exports'),price=metric(root,'price'),cap=metric(root,'capacity');if(!(p||r||e))continue;let sc=20;if(e)sc+=40;if(p)sc+=15;if(r)sc+=10;if(cap)sc+=5;if(price)sc+=Math.max(0,10-Math.min(10,Math.abs(price.value)));rows.push({countryId:c.id,countryName:c.names?.[0]||c.id,score:Math.max(0,Math.min(100,sc)),production:p?.value??null,reserves:r?.value??null,exportable:e?.value??null,price:price?.value??null,capacity:cap?.value??null})}return rows.sort((a,b)=>b.score-a.score).slice(0,10)}
function property(parsed,ctx,idx){const m=resolveMinister(parsed,ctx,idx);if(!m)return{ok:false,unknown:'Minister identity is not available in the authoritative runtime context.'};const q=N(parsed.surface||'');const key=parsed.property||(/how old|age|বয়স|বয়স/.test(q)?'age':/background|ব্যাকগ্রাউন্ড|ক্যারিয়ার|ক্যারিয়ার/.test(q)?'background':/ideology|মতাদর্শ/.test(q)?'ideology':/name|নাম|কে/.test(q)?'name':null);if(!key)return{ok:false,unknown:'Minister property was not specified.'};const v=m.value?.[key]??m.value?.profile?.[key]??m.value?.stats?.[key];return{ok:v!=null,property:key,value:v??null,ministerId:m.id,ministerName:names(m.value,m.key)[0]||m.id,sourcePath:m.path}}
function numericQuestion(raw,resource,country,idx){const root=country&&resource?node(country,resource):country?.value||resource?.value||null;for(const k of Object.keys(METRICS)){const z=metric(root,k);if(z&&new RegExp(METRICS[k].map(x=>S(x).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|'),'i').test(raw))return{metric:k,value:z.value,key:z.key,path:z.path,resourceId:resource?.id||null,resourceName:resource?.names?.[0]||resource?.surface||null,countryId:country?.id||null,countryName:country?.names?.[0]||null}}return null}
function execute(ir,ctx={}){const raw=S(ir?.surface||''),idx=index(ctx?.datasets||[]),country=resolveCountry(ir,ctx,idx),resources=resolveResources(ir,raw,idx),lang=ir?.language==='bn'||/[\u0980-\u09FF]/.test(raw);const op=S(ir?.operation||'IDENTIFY').toUpperCase();if(op==='PERSON')return property(ir,ctx,idx);if(op==='COUNT'){const asset=/(mine|mines|খনি|তেলক্ষেত্র|গ্যাসক্ষেত্র|facility|facilities|স্থাপনা)/i.test(raw);if(asset){const rows=[];for(const c of idx.countries){const found=allMatches(raw,idx.resources);for(const re of found){const root=node(c,re);if(root)rows.push({countryId:c.id,countryName:c.names?.[0]||c.id,resourceId:re.id,resourceName:re.names?.[0]||re.surface})}}if(country){const local=rows.filter(x=>x.countryId===country.id);return{available:true,operation:op,count:local.length,rows:local,answer:lang?`নির্বাচিত দেশের জন্য শনাক্তযোগ্য সংশ্লিষ্ট রেকর্ড: ${local.length}টি।`:`Identifiable matching records for the selected country: ${local.length}.`}}return{available:true,operation:op,count:rows.length,rows,answer:lang?`বর্তমান ডেটায় শনাক্তযোগ্য মিল: ${rows.length}টি রেকর্ড।`:`Identifiable matches in the current data: ${rows.length} records.`}}
for(const re of resources){const root=country?node(country,re):re.value;const z=metric(root,'production')||metric(root,'reserve')||metric(root,'stock');if(z)return{available:true,operation:op,count:null,metric:z,resourceId:re.id,resourceName:re.names?.[0]||re.surface,countryId:country?.id||null}}return{available:false,operation:op,unknowns:['count target'],answer:lang?'গণনার লক্ষ্য বর্তমান ডেটা থেকে নির্ভুলভাবে শনাক্ত করা যায়নি।':'The count target could not be resolved from the current data.'}}
if(op==='QUANTITY'||op==='CALCULATE'||op==='CHECK'){const z=numericQuestion(raw,resources[0],country,idx);if(!z)return{available:false,operation:op,unknowns:['requested metric'],answer:lang?'চাওয়া পরিমাণ বর্তমান ডেটায় প্রমাণিত নয়।':'The requested quantity is not evidenced by the current data.'};return{available:true,operation:op,...z,answer:lang?`${z.metric}-এর মান: ${z.value} (${z.key})`:`${z.metric}: ${z.value} (${z.key})`}}
if(op==='ASSESS_SECURITY'||/security|safe|shortage|depletion|নিরাপত্তা|ঘাটতি|মজুদ/i.test(raw)){const rows=resources.map(r=>security(country||idx.countries[0],r));return{available:rows.length>0,operation:'ASSESS_SECURITY',rows,answer:lang?rows.map(r=>`${r.resourceName}: ${r.status}${r.score!=null?` (${r.score}/100)`:''}${r.runwayDays!=null?`, প্রায় ${r.runwayDays} দিন`:''}`).join('\n'):'Resource security:\n'+rows.map(r=>`${r.resourceName}: ${r.status}${r.score!=null?` (${r.score}/100)`:''}${r.runwayDays!=null?`, runway about ${r.runwayDays} days`:''}`).join('\n')}}
if(op==='RECOMMEND'&&/import|supplier|source|আমদানি|সরবরাহকারী|কোন দেশ থেকে/i.test(raw)){const re=resources[0],rows=re?suppliers(country,re,idx):[];return{available:rows.length>0,operation:'RECOMMEND',rows,answer:lang?`যাচাইযোগ্য সম্ভাব্য সরবরাহকারী:\n${rows.slice(0,5).map((r,i)=>`${i+1}. ${r.countryName} (${r.score}/100)`).join('\n')}`:`Verifiable potential suppliers:\n${rows.slice(0,5).map((r,i)=>`${i+1}. ${r.countryName} (${r.score}/100)`).join('\n')}`}}
if(op==='LOCATION'||/where|কোথায়|কোথায়/i.test(raw)){const re=resources[0];if(country&&re){const root=node(country,re);return{available:!!root,operation:'LOCATION',countryId:country.id,countryName:country.names?.[0],resourceId:re.id,resourceName:re.names?.[0]||re.surface,record:root,answer:lang?`${country.names?.[0]||country.id}-এ ${re.names?.[0]||re.surface}-এর সংশ্লিষ্ট ডেটা রেকর্ড পাওয়া গেছে।`:`A matching ${re.names?.[0]||re.surface} record was found for ${country.names?.[0]||country.id}.`}}}
if(op==='IDENTIFY'){return{available:true,operation:op,country:country?{id:country.id,name:country.names?.[0]||country.id}:null,resources:resources.map(r=>({id:r.id,name:r.names?.[0]||r.surface})),answer:lang?'বর্তমান গেম ডেটার সঙ্গে প্রশ্নটি শনাক্ত করা হয়েছে।':'The query has been resolved against the current game data.'}}
if(ACTION_TERMS[op]){return{available:true,operation:op,status:'ACTION_REQUESTED',event:{type:'GAME_EVENT_REQUEST',state:'EVENT_PENDING',operation:op,createdAt:Date.now()},answer:lang?`কমান্ডটি ${op} হিসেবে শনাক্ত হয়েছে এবং execution engine-এর জন্য pending.`:`The command was recognized as ${op} and is pending execution by the game action engine.`}}
return{available:false,operation:op,status:'CAPABILITY_REQUIRED',unknowns:['operation executor'],answer:lang?'এই অপারেশনের জন্য নির্দিষ্ট গেম capability engine প্রয়োজন।':'A dedicated game capability engine is required for this operation.'}}
global.OmegaQueryExecutor=Object.freeze({VERSION:'1.0.0',execute});
})(typeof window!=='undefined'?window:globalThis);
