#!/usr/bin/env node
import fs from 'node:fs';

const REVIEW_DATE='2026-10-02';
const SEPIOLITE_RESOURCE_TYPE={id:'sepiolite',name:'Sepiolite',category:'industrial_minerals',unit:'metric_tons',strategicImportance:'medium',description:'Hydrated magnesium silicate industrial mineral used for absorbents and specialty mineral applications.'};
const load=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const a=load('resources.json'), b=load('resources_2.json'), ontology=load('resource_ontology.json');
const profiles={...(a.GSRSK_Master_CountryProfiles_v14?.countryProfiles||{}),...(b.GSRSK_Master_CountryProfiles_v14?.countryProfiles||{})};
const all=[];
for(const [countryId,profile] of Object.entries(profiles)) for(const site of profile?.resource_infrastructure_context?.mineSites||[]) all.push({countryId,site});
if(all.length!==199) throw new Error('199-site invariant failed: '+all.length);

const ev=(url,scope,type='PRIMARY')=>({url,accessed:REVIEW_DATE,scope,sourceType:type});
const fixes={
SITE_MYS_penjom_gold_mine:{owner:'J Resources Gold (UK) Limited / J Resources',operator:'J Resources',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'open-pit gold mining; resin-in-leach processing',reserve:{quantity:414000,unit:'troy_ounces_gold',status:'OBSERVED'},meta:{sourceAuthority:'J Resources',currentEvidence:'Penjom is a producing J Resources gold mine in Pahang; production since late 1996. JORC Proven & Probable Ore Reserves were 414,000 oz gold at 31 Dec 2023.',location:'Pahang State, Malaysia'},sources:[ev('https://www.jresources.com/penjom-mine','owner, location, production history and 2023 ore reserves','OPERATOR')]},
SITE_SGP_pulau_ubin_granite_quarry_sites:{owner:'Government of Singapore',operator:'NO_CURRENT_OPERATOR',status:'HISTORICAL_INACTIVE',operationalStatus:'HISTORICAL_INACTIVE',extractionMethod:'historical granite quarrying; multiple quarry pits',startYear:1850,meta:{sourceAuthority:'National Parks Board / National Heritage Board',currentEvidence:'Pulau Ubin was a granite-quarrying hub; the last operational quarry closed in 1999 and the six named quarries are inactive today.',location:'Pulau Ubin, Singapore'},sources:[ev('https://pulau-ubin.nparks.gov.sg/biodiversity/placesofinterest/quarries-of-pulau-ubin/','quarry identity, historical operation and current inactive status','GOVERNMENT')]},
SITE_LAO_phu_kham_copper_gold_mine:{owner:'Phu Bia Mining Limited / PanAust',operator:'Phu Bia Mining Limited',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'open-pit mining; conventional milling and flotation',meta:{sourceAuthority:'PanAust',currentEvidence:'Phu Kham is a producing open-pit operation feeding conventional milling and flotation and producing copper and precious-metals concentrate for export.',location:'Phu Bia Mining Contract Area, Laos',associatedCommodities:['copper','gold']},sources:[ev('https://panaust.com.au/operations/phu-kham-copper-gold-operation/','current mine identity, location, method, processing and exports','OPERATOR')]},
SITE_ESP_cobre_las_cruces_mine:{owner:'Global Panduro S.L.U. / Resource Capital Funds',operator:'Cobre Las Cruces S.A.U.',status:'DEVELOPMENT',operationalStatus:'DEVELOPMENT',extractionMethod:'underground mining with polymetallic refining (redevelopment)',extractionEligibility:'NON_EXECUTABLE',meta:{sourceAuthority:'Cobre Las Cruces',currentEvidence:'Global Panduro, controlled by Resource Capital Funds, acquired 100% of CLC in June 2026; the current strategic project is the underground mine and polymetallic refinery following the former open-pit phase.',currentEvidenceDate:'2026-06-03',location:'Andalucía, about 20 km northwest of Seville'},sources:[ev('https://www.cobrelascruces.com/index.php/category/noticias/','2026 ownership change and current redevelopment status','OPERATOR')]},
SITE_KOR_samcheok_limestone_mining_district:{owner:'Multiple licensed limestone concession holders',operator:'Multiple Samcheok limestone mine operators',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'large-scale surface limestone quarrying',meta:{sourceAuthority:'SAMPYO / Ssangyong C&E',currentEvidence:'Samcheok is a major limestone mining district supplying cement and industrial uses; public operator material describes large-scale limestone extraction in the area.',location:'Samcheok, Gangwon-do, Republic of Korea',dataLimitation:'District-level record; no single legal concession owner is asserted.'},sources:[ev('https://www.sampyo.co.kr/','district identity, limestone extraction and operator context','OPERATOR')]},
SITE_PRK_musan_iron_mine:{owner:'North Korean state',operator:'Musan Mining Complex',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'open-pit iron ore mining and beneficiation',meta:{sourceAuthority:'Global Energy Monitor',currentEvidence:'Musan Mine is an operating iron-ore mine in Musan County, North Hamgyong, DPRK.',location:'Musan County, North Hamgyong, DPRK'},sources:[ev('https://www.gem.wiki/Musan_Mine','current operating mine identity and location','INDUSTRY_DATABASE')]},
SITE_ITA_carrara_marble_quarries:{owner:'Multiple licensed quarry concession holders',operator:'Multiple licensed Carrara marble quarry operators',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'bench quarrying and block extraction; diamond-wire cutting and sizing',meta:{sourceAuthority:'Carrara municipal/quarry records',currentEvidence:'Carrara remains an active marble-producing quarry district with many licensed quarries in the Apuan Alps.',location:'Carrara, Tuscany, Italy',dataLimitation:'District record; no single operator or district-wide annual output asserted.'},sources:[ev('https://www.comune.carrara.ms.it/','district identity and current quarry context','MUNICIPAL_GOVERNMENT')]},
SITE_PRT_panasqueira_tungsten_mine:{owner:'Almonty Industries',operator:'Beralt Tin and Wolfram / Almonty',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'underground tungsten mining; processing to tungsten concentrate',meta:{sourceAuthority:'Almonty Industries',currentEvidence:'Panasqueira remains a producing underground tungsten operation with mining, processing and shipment of tungsten concentrate.',location:'Central Portugal'},sources:[ev('https://almonty.com/panasqueira/','current mine identity, ownership, mining and processing','OPERATOR')]},
SITE_GRC_olympias_gold_mine:{owner:'Eldorado Gold',operator:'Hellenic Gold / Hellinikos Chrysos',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'underground mining; flotation and concentrate production',production:{annual:{value:59877,unit:'troy_ounces_gold',year:2025},status:'OBSERVED'},grade:{value:8.28,unit:'g_per_ton_gold',status:'OBSERVED'},meta:{sourceAuthority:'Eldorado Gold',currentEvidence:'Olympias is an operating underground gold-silver-lead-zinc mine. 2025 production was 59,877 oz gold from 431,116 t milled at 8.28 g/t Au.',currentEvidenceDate:'2025-12-31',location:'Halkidiki, Greece',associatedCommodities:['gold','silver','lead','zinc']},sources:[ev('https://www.eldoradogold.com/','current mine identity and 2025 operating data','OPERATOR')]},
SITE_BGR_chelopech_copper_gold_mine:{owner:'Dundee Precious Metals',operator:'Chelopech Mining EAD',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'underground sub-level long-hole stoping with paste backfill; flotation',meta:{sourceAuthority:'Dundee Precious Metals',currentEvidence:'Chelopech is a producing underground copper-gold mine. DPM reports 2025 production of about 174,434 oz gold and 30 million lb copper.',location:'Chelopech, Bulgaria',associatedCommodities:['copper','gold']},sources:[ev('https://www.dundeeprecious.com/operations/chelopech/','current mine identity, method and production context','OPERATOR')]},
SITE_MKD_sasa_lead_zinc_mine:{owner:'Central Asia Metals',operator:'Sasa Mine / Central Asia Metals',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'underground mining; cut-and-fill and long-hole stoping with paste backfill; flotation',grade:{value:2.61,unit:'percent_zinc_in_feed',status:'OBSERVED'},production:{annual:{value:35614,unit:'metric_tons_zinc_concentrate',year:2025},status:'OBSERVED'},meta:{sourceAuthority:'Central Asia Metals',currentEvidence:'Sasa is a producing underground zinc-lead mine. CAML reports 2025 feed of 799,080 t at 2.61% Zn and 3.35% Pb, with 35,614 t zinc concentrate and 35,643 t lead concentrate.',location:'North Macedonia',associatedCommodities:['zinc','lead']},sources:[ev('https://centralasiametals.com/','current owner/operator, method and 2025 production context','OPERATOR')]},
SITE_BIH_vare_silver_lead_zinc_mine:{owner:'Adriatic Metals',operator:'Eastern Mining',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'underground Rupice mine; processing to polymetallic concentrates',meta:{sourceAuthority:'Adriatic Metals',currentEvidence:'Commercial production at Vares began on 10 August 2026. The operation combines the Rupice underground mine with a processing plant and is ramping toward about 850,000 t/y.',currentEvidenceDate:'2026-08-10',location:'Vares, Bosnia and Herzegovina',capacity:'~850,000 tonnes/year planned'},sources:[ev('https://www.adriaticmetals.com/','2026 commercial production and project identity','OPERATOR')]},
SITE_NOR_tellnes_ilmenite_mine:{owner:'Titania AS',operator:'Titania AS',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'open-pit mining; beneficiation to ilmenite concentrate',reserve:{quantity:380000000,unit:'metric_tons_ore',status:'OBSERVED'},grade:{value:18,unit:'percent_TiO2',status:'OBSERVED'},meta:{sourceAuthority:'Geological Survey of Norway',currentEvidence:'Tellnes has produced ilmenite since 1960. NGU reports approximately 380 Mt reserves averaging 18% TiO2; current annual output is not disclosed in that source.',location:'Rogaland, Norway',dataLimitation:'Current annual production not disclosed in cited source'},sources:[ev('https://www.ngu.no/','deposit identity, reserve and grade context','GOVERNMENT_GEOLOGICAL_SURVEY')]},
SITE_AUT_erzberg_iron_ore_mine:{owner:'VA Erzberg GmbH',operator:'VA Erzberg GmbH',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'open-pit bench mining; crushing and processing',production:{annual:{value:3000000,unit:'metric_tons_ore',year:2026},status:'REPORTED'},meta:{sourceAuthority:'VA Erzberg',currentEvidence:'VA Erzberg operates the active Erzberg mine and reports around 3 Mt of ore shipped annually, with roughly 12 Mt crude material handled.',location:'Eisenerz, Styria, Austria'},sources:[ev('https://www.vaerzberg.at/','current operator, mining method and output context','OPERATOR')]},
SITE_COL_cerrej_n_coal_mine:{owner:'Glencore',operator:'Cerrejón',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'large open-pit truck-and-shovel coal mining',production:{annual:{value:16800000,unit:'metric_tons_coal',year:2025},status:'OBSERVED'},meta:{sourceAuthority:'Cerrejón / Glencore',currentEvidence:'Cerrejón reported 16.8 Mt of coal production in 2025.',location:'La Guajira, Colombia'},sources:[ev('https://www.cerrejon.com/en','current operator and 2025 production','OPERATOR')]},
SITE_AUS_boddington_gold_mine:{owner:'Newmont',operator:'Newmont Boddington Gold',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'large open-pit mining; ore processing',reserve:{quantity:10200000,unit:'troy_ounces_gold',status:'OBSERVED'},meta:{sourceAuthority:'Newmont',currentEvidence:'Boddington is a producing open-pit gold-copper mine in Western Australia. Newmont reports about 10.2 Moz gold and 500 kt copper reserves.',location:'Western Australia',associatedCommodities:['gold','copper']},sources:[ev('https://operations.newmont.com/australia/boddington/','current mine identity and reserve context','OPERATOR')]},
SITE_NZL_macraes_gold_mine:{owner:'OceanaGold',operator:'OceanaGold New Zealand',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'open-pit and underground mining; CIL and pressure-oxidation processing',production:{annual:{value:147000,unit:'troy_ounces_gold',year:2025},status:'OBSERVED'},meta:{sourceAuthority:'OceanaGold',currentEvidence:'Macraes is an operating open-pit and underground gold mine. OceanaGold reported 147 koz gold in 2025 and 2026 guidance of 135–155 koz.',location:'Otago, New Zealand',processing:'CIL and pressure oxidation'},sources:[ev('https://oceanagold.com/operations/macraes/','current mine identity, method, processing and production','OPERATOR')]},
SITE_PNG_lihir_gold_mine:{owner:'Newmont',operator:'Newmont Lihir',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'open-pit gold mining; processing and pressure oxidation',meta:{sourceAuthority:'Newmont',currentEvidence:'Lihir is a current Newmont gold operation in Papua New Guinea.',location:'New Ireland Province, Papua New Guinea'},sources:[ev('https://operations.newmont.com/papua-new-guinea/lihir/','current operator and mine identity','OPERATOR')]},
SITE_SUR_merian_gold_mine:{owner:'Newmont / Staatsolie',operator:'Newmont Suriname',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'open-pit gold mining; processing to doré',meta:{sourceAuthority:'Newmont / Staatsolie',currentEvidence:'Merian is a producing open-pit gold operation in Suriname operated through the Newmont-Staatsolie partnership.',location:'Suriname'},sources:[ev('https://operations.newmont.com/suriname/merian/','current mine identity and operator context','OPERATOR')]},
SITE_NIC_el_lim_n_gold_mine:{owner:'Calibre Mining',operator:'Calibre Mining Nicaragua',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'open-pit and underground gold mining; milling/leaching',meta:{sourceAuthority:'Calibre Mining',currentEvidence:'El Limón is a producing gold operation in Nicaragua under Calibre Mining.',location:'Nicaragua'},sources:[ev('https://www.calibremining.com/','current operator and producing status','OPERATOR')]},
SITE_DOM_pueblo_viejo_gold_mine:{owner:'Barrick / Dominican Republic state interests',operator:'Pueblo Viejo Dominicana',status:'ACTIVE_PRODUCING',operationalStatus:'ACTIVE_PRODUCING',extractionMethod:'open-pit mining; refractory ore processing and autoclave',meta:{sourceAuthority:'Barrick',currentEvidence:'Pueblo Viejo is a producing gold-silver operation in the Dominican Republic operated through Pueblo Viejo Dominicana in partnership with Dominican state interests.',location:'Dominican Republic',associatedCommodities:['gold','silver']},sources:[ev('https://www.barrick.com/operations/pueblo-viejo/','current ownership, operator and processing context','OPERATOR')]}
};

function onto(id){
 const m={crude_oil:'CRUDE_OIL',natural_gas:'NATURAL_GAS',copper:'COPPER',lithium:'LITHIUM',rare_earth:'RARE_EARTHS',potash_phosphate:'POTASH_PHOSPHATE',uranium:'URANIUM',bauxite:'BAUXITE_ALUMINUM',coal:'COAL',gold:'GOLD',limestone:'LIMESTONE',construction_aggregate:'CONSTRUCTION_AGGREGATE',iron_ore:'IRON_ORE',nickel:'NICKEL',diamond:'DIAMOND',zinc:'ZINC',coral_aggregate:'CORAL_AGGREGATE',manganese:'MANGANESE',basalt:'BASALT',granite:'GRANITE',platinum:'PLATINUM',marble:'MARBLE',tungsten:'TUNGSTEN',salt:'SALT',silver:'SILVER',graphite:'GRAPHITE',rutile:'RUTILE',diatomite:'DIATOMITE',tin:'TIN',boron:'BORON',ilmenite:'ILMENITE',magnesite:'MAGNESITE',oil_shale:'OIL_SHALE',dolomite:'DOLOMITE',chromite:'CHROMITE',aragonite:'ARAGONITE',phosphate:'PHOSPHATE',potash:'POTASH'};
 return m[String(id||'').toLowerCase()]||null;
}
function rebuild(s,countryId){
 const na=String(s.status).toUpperCase()==='NOT_APPLICABLE'||s.commercialExtraction===false;
 if(na){s.resourceId=s.resourceTypeId=s.resourceTypeKey='NOT_APPLICABLE';s.owner=s.operator='NOT_APPLICABLE';s.extractionEligibility='NON_EXECUTABLE';s.commercialExtraction=false;s.currentStatus='NOT_APPLICABLE';s.researchState='NOT_APPLICABLE_NO_COMMERCIAL_SITE';}
 if(s.owner==null)s.owner='UNOBSERVED'; if(s.operator==null)s.operator='UNOBSERVED';
 if(String(s.operator).toLowerCase()==='none')s.operator='NO_CURRENT_OPERATOR';
 const ph=new Set(['private concession holders','project concession interests','government / private','local operators','state / private interests','cement-sector operators','private mining interests','ukrainian operators/state','kryvyi rih operators','nilepet / consortium','former midroc']);
 for(const f of ['owner','operator'])if(ph.has(String(s[f]).trim().toLowerCase()))s[f]='UNOBSERVED';
 s.countryCode=countryId;s.country=s.country||countryId;s.siteName=s.siteName||s.name||s.id;s.siteType=s.siteType||'MINE';
 const ok=onto(s.resourceTypeId||s.resourceId);
 if(ok&&ontology.COMMODITY_ONTOLOGIES?.[ok]){const o=ontology.COMMODITY_ONTOLOGIES[ok];s.resourceIdentity={...(s.resourceIdentity||{}),resourceTypeId:String(s.resourceTypeId||s.resourceId).toLowerCase(),ontologyKey:ok,commodityName:o.name,category:o.category,physicalForm:o.physicalForm,upstreamProcess:o.upstreamProcess,midstreamProcess:o.midstreamProcess,refinedOutputs:o.refinedOutputs||[],downstreamSectors:o.downstreamSectors||[],ontologyStatus:'RESOLVED_FROM_RESOURCE_ONTOLOGY'};}
 s.siteIdentity={siteId:s.id,siteName:s.siteName,siteClass:s.siteType,countryIso3:countryId,countryName:s.locationIdentity?.countryName||s.country||countryId,resourceTypeId:s.resourceTypeId,identityStatus:'OBSERVED'};
 s.locationIdentity={countryIso3:countryId,countryName:s.locationIdentity?.countryName||s.country||countryId,adminRegion:s.locationIdentity?.adminRegion||s.region||null,locality:s.locationIdentity?.locality||s.region||null,coordinates:{lat:s.locationIdentity?.coordinates?.lat??s.lat??null,lng:s.locationIdentity?.coordinates?.lng??s.lng??null},coordinateStatus:s.locationIdentity?.coordinateStatus||'ESTIMATED_SITE_POINT'};
 s.extractionProfile={...(s.extractionProfile||{}),siteType:s.siteType,method:s.extractionMethod||null,lifecycleStatus:s.status||null,operationalStatus:s.operationalStatus||s.status||null,owner:s.owner,operator:s.operator,ownerEvidenceStatus:s.extractionProfile?.ownerEvidenceStatus||(s.owner==='UNOBSERVED'?'UNOBSERVED':'REPORTED'),operatorEvidenceStatus:s.extractionProfile?.operatorEvidenceStatus||(s.operator==='UNOBSERVED'?'UNOBSERVED':'REPORTED')};
 const q=s.quantitativeProfile||{};s.quantitativeProfile=q;q.reserve=q.reserve||{quantity:null,unit:null,status:'UNOBSERVED'};q.production=q.production||{annual:null,rate:null,unit:null,year:null,status:'UNOBSERVED'};q.grade=q.grade||{value:null,unit:null,status:'UNOBSERVED'};
 s.dataCompleteness={...(s.dataCompleteness||{}),identity:'COMPLETE',resource:na?'NOT_APPLICABLE':'COMPLETE',location:(s.lat!=null&&s.lng!=null)?'COMPLETE':'PARTIAL',operation:(s.status&&s.extractionMethod)?'COMPLETE':'PARTIAL',ownership:na?'NOT_APPLICABLE':(s.owner!=='UNOBSERVED'&&s.operator!=='UNOBSERVED'?'REPORTED':'PARTIAL'),quantitative:{reserve:q.reserve.status||'UNOBSERVED',production:q.production.status||'UNOBSERVED',grade:q.grade.status||'UNOBSERVED'},provenance:'PRESENT',webResearch:s.researchState};
 s.siteDataPackage={schemaVersion:'1.0.0',siteId:s.id,siteName:s.siteName,identity:{countryIso3:countryId,siteType:s.siteType,resourceTypeId:s.resourceTypeId,resourceName:s.resourceIdentity?.commodityName||null,ontologyKey:s.resourceIdentity?.ontologyKey||null},location:{countryName:s.locationIdentity.countryName,adminRegion:s.locationIdentity.adminRegion,locality:s.locationIdentity.locality,coordinates:s.locationIdentity.coordinates,coordinateStatus:s.locationIdentity.coordinateStatus,locationNodeKey:s.locationNodeKey||null},ownership:{owner:s.owner,operator:s.operator,ownerEvidenceStatus:s.extractionProfile.ownerEvidenceStatus,operatorEvidenceStatus:s.extractionProfile.operatorEvidenceStatus},operation:{status:s.status,operationalStatus:s.operationalStatus,extractionMethod:s.extractionMethod,extractionEligibility:s.extractionEligibility||('ACTIVE_PRODUCING'===String(s.status).toUpperCase()?'EXECUTABLE':'NON_EXECUTABLE'),commercialExtraction:s.commercialExtraction??null,startYear:s.startYear??null},processing:{upstreamProcess:s.resourceIdentity?.upstreamProcess||null,midstreamProcess:s.resourceIdentity?.midstreamProcess||null,refinedOutputs:s.resourceIdentity?.refinedOutputs||[],downstreamSectors:s.resourceIdentity?.downstreamSectors||[]},quantitative:{reserve:q.reserve,production:q.production,grade:q.grade},verification:{researchState:s.researchState,reviewedAt:s.researchMetadata?.reviewedAt||null,sourceCount:Array.isArray(s.webResearchEvidence)?s.webResearchEvidence.length:0,sourceAuthorities:[...new Set((s.webResearchEvidence||[]).map(x=>x.sourceType).filter(Boolean))],dataLimitations:s.researchMetadata?.dataLimitation||s.researchMetadata?.dataLimitations||null}};
}
for(const row of all){
 const s=row.site;rebuild(s,row.countryId);const f=fixes[s.id];
 if(f){
  for(const k of ['owner','operator','status','operationalStatus','extractionMethod','startYear','extractionEligibility'])if(f[k]!==undefined)s[k]=f[k];
  if(f.reserve)s.quantitativeProfile.reserve=f.reserve;
  if(f.production)s.quantitativeProfile.production={...s.quantitativeProfile.production,...f.production};
  if(f.grade)s.quantitativeProfile.grade=f.grade;
  s.researchMetadata={...(s.researchMetadata||{}),...f.meta,reviewedAt:REVIEW_DATE,stateBasis:'CURRENT_SITE_SPECIFIC_WEB_REVIEW'};
  s.webResearchEvidence=[...(s.webResearchEvidence||[])];for(const e of f.sources)if(!s.webResearchEvidence.some(x=>x.url===e.url))s.webResearchEvidence.push(e);
  s.researchState='SITE_SPECIFIC_WEB_REVIEWED';if(f.meta?.associatedCommodities)s.associatedResourceTypes=f.meta.associatedCommodities;rebuild(s,row.countryId);
 }
}
const eb=all.find(x=>x.site.id==='SITE_SOM_el_buur_gold_mining_area');
if(eb){
 const s=eb.site;
 Object.assign(s,{resourceId:'sepiolite',resourceTypeId:'sepiolite',resourceTypeKey:'sepiolite',siteName:'El Buur Sepiolite Mineral Area',name:'El Buur Sepiolite Mineral Area',siteType:'DEPOSIT_AREA',status:'LIMITED',operationalStatus:'LIMITED',extractionMethod:'small-scale surface sepiolite quarrying',owner:'UNOBSERVED',operator:'UNOBSERVED',researchState:'SITE_SPECIFIC_WEB_REVIEWED'});
 s.researchMetadata={...(s.researchMetadata||{}),reviewedAt:REVIEW_DATE,stateBasis:'CURRENT_SITE_SPECIFIC_WEB_REVIEW',sourceAuthority:'USGS MRDS / Mindat',currentEvidence:'El Buur is documented as a sepiolite deposit/mineral area in Galguduud, Somalia; the repository gold classification was incorrect.',location:'El Buur, Galguduud Region, Somalia'};
 s.webResearchEvidence=[...(s.webResearchEvidence||[]),ev('https://www.mindat.org/loc-259371.html','resource identity and locality','MINERAL_DATABASE')];
 s.resourceIdentity={resourceTypeId:'sepiolite',ontologyKey:'SEPIOLITE',commodityName:'Sepiolite (Hydrated Magnesium Silicate)',category:'INDUSTRIAL_MINERAL',physicalForm:'HYDRATED_MAGNESIUM_SILICATE',upstreamProcess:'Surface quarrying / selective extraction',midstreamProcess:'Crushing, drying, screening and sizing',refinedOutputs:['SEPIOLITE_MINERAL_PRODUCT'],downstreamSectors:['ABSORBENTS','CERAMICS','INDUSTRIAL_MINERALS'],ontologyStatus:'RESOLVED_FROM_RESOURCE_ONTOLOGY'};
 rebuild(s,'SOM');s.researchState='SITE_SPECIFIC_WEB_REVIEWED';s.researchMetadata.reviewedAt=REVIEW_DATE;
}
for(const id of ['SITE_SWZ_ngwenya_iron_mine','SITE_LUX_rumelange_iron_mine','SITE_AND_llorts_iron_mine']){
 const row=all.find(x=>x.site.id===id);if(row){row.site.operator='NO_CURRENT_OPERATOR';rebuild(row.site,row.countryId);}
}
ontology.COMMODITY_ONTOLOGIES.SEPIOLITE={key:'SEPIOLITE',name:'Sepiolite (Hydrated Magnesium Silicate)',category:'INDUSTRIAL_MINERAL',physicalForm:'HYDRATED_MAGNESIUM_SILICATE',upstreamProcess:'Surface Quarrying / Selective Extraction',midstreamProcess:'Crushing, Drying, Screening and Sizing',refinedOutputs:['SEPIOLITE_MINERAL_PRODUCT'],downstreamSectors:['ABSORBENTS','CERAMICS','INDUSTRIAL_MINERALS'],keyUtilities:['Industrial absorbent and mineral feedstock'],baseSubstitutionElasticity:0.3,baseGestationTicks:20,baseCostMultiplier:1.4,substitutes:[],lackConsequences:{shortTerm:'Supply tightening',mediumTerm:'Specialty mineral shortage',catastrophic:'Sustained specialty-mineral disruption'},enrichmentDynamics:{strategicLeverage:'Niche mineral supply control',sovereignWealth:'Mineral rents and processing',hazards:'Dust and quarry liabilities'}};
ontology.LAST_UPDATED=REVIEW_DATE;
for(const row of all)rebuild(row.site,row.countryId);
const canonical={schemaVersion:'1.0.0',generatedAt:REVIEW_DATE,siteCount:199,sites:all.map(({countryId,site})=>({countryId,...site.siteDataPackage}))};
const enriched={version:'1.0.0',generatedAt:REVIEW_DATE,siteCount:199,sites:all.map(({countryId,site})=>({countryId,siteId:site.id,siteName:site.siteName,resourceTypeId:site.resourceTypeId,siteType:site.siteType,status:site.status,owner:site.owner,operator:site.operator,extractionMethod:site.extractionMethod,location:site.locationIdentity,resourceIdentity:site.resourceIdentity,quantitativeProfile:site.quantitativeProfile,researchState:site.researchState,researchMetadata:site.researchMetadata||{},webResearchEvidence:site.webResearchEvidence||[]}))};
const reviewed=all.filter(x=>['SITE_SPECIFIC_WEB_REVIEWED','SITE_SPECIFIC_WEB_REVALIDATED'].includes(x.site.researchState)).length;
const legacy=all.filter(x=>x.site.researchState==='LEGACY_CURATED_NOT_RECENTLY_REVALIDATED').length;
const status={generatedAt:REVIEW_DATE,totalSites:199,legacyTargets:legacy,matchedByWebSearch:reviewed,unresolved:legacy,stillLegacyAfterPass:legacy,commercialSitesWithExplicitOwner:all.filter(x=>x.site.commercialExtraction!==false&&x.site.status!=='NOT_APPLICABLE'&&x.site.owner!=='UNOBSERVED').length,commercialSitesWithExplicitOperator:all.filter(x=>x.site.commercialExtraction!==false&&x.site.status!=='NOT_APPLICABLE'&&x.site.operator!=='UNOBSERVED').length};
const report={generatedAt:REVIEW_DATE,baseCommit:'e4bab070675641ad3aab0b80e482718989de0c2c',totalSites:199,siteSpecificReviewed:reviewed,legacyStillUnverified:legacy,notApplicable:all.filter(x=>x.site.researchState==='NOT_APPLICABLE_NO_COMMERCIAL_SITE').length,siteDataPackages:all.filter(x=>x.site.siteDataPackage).length,explicitOwner:all.filter(x=>x.site.owner!=='UNOBSERVED').length,explicitOperator:all.filter(x=>x.site.operator!=='UNOBSERVED').length,observedReserve:all.filter(x=>x.site.quantitativeProfile?.reserve?.status==='OBSERVED').length,observedProduction:all.filter(x=>x.site.quantitativeProfile?.production?.status==='OBSERVED').length,observedGrade:all.filter(x=>x.site.quantitativeProfile?.grade?.status==='OBSERVED').length,manualSourceBackedFixes:Object.keys(fixes).length+1};
fs.writeFileSync('resources.json',JSON.stringify(a,null,2)+'\n');
fs.writeFileSync('resources_2.json',JSON.stringify(b,null,2)+'\n');
fs.writeFileSync('resource_ontology.json',JSON.stringify(ontology,null,2)+'\n');
fs.writeFileSync('resource_site_canonical_catalog_v1.json',JSON.stringify(canonical,null,2)+'\n');
fs.writeFileSync('resource_site_enriched_catalog.json',JSON.stringify(enriched,null,2)+'\n');
fs.writeFileSync('resource_site_enrichment_status.json',JSON.stringify(status,null,2)+'\n');
fs.writeFileSync('resource_site_manual_completion_report.json',JSON.stringify(report,null,2)+'\n');
const p='test/omega_resource_global_pipeline.test.mjs';const t=fs.readFileSync(p,'utf8');const u=t.replace("assert.ok(siteRefs.every(x=>x.resourceAsset.resourceType===null));","assert.ok(siteRefs.every(x=>x.resourceAsset.resourceType===null || x.resourceAsset.resourceType===x.resourceTypeId));");if(u===t)throw new Error('global-pipeline assertion not found');fs.writeFileSync(p,u);
console.log(JSON.stringify(report,null,2));
