const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const legacy=['offline_language_vocabulary.json','offline_lexicon.json','offline_semantic_knowledge.json','omega_game_language_ontology.json','omega_game_language_source_inventory.json','offline_semantic_brain.js','offline_query_engine.js','omega_game_language_bridge.js','omega_reasoning_dispatcher.js'];
const bundle=path.join(root,'omega_language_system.js');
assert.ok(fs.existsSync(bundle),'canonical standalone bundle is missing');
const js=fs.readFileSync(bundle,'utf8');
assert.match(js,/OMEGA LANGUAGE SYSTEM v5\.0\.0/);
assert.match(js,/STATUS:'STANDALONE_READY'/);
assert.match(js,/SOURCE_DATA/);
for(const f of legacy)assert.equal(fs.existsSync(path.join(root,f)),false,`legacy language dependency still present: ${f}`);
const executable=js.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/.*$/gm,'');
for(const re of [/\bfetch\s*\(/,/document\.createElement\(['"]script['"]\)/,/\bloadScript\s*\(/,/\bfetchJSON\s*\(/,/\beval\s*\(/,/new\s+Function\s*\(/])assert.equal(re.test(executable),false,`unsafe or legacy construct found: ${re}`);
for(const symbol of ['OmegaLanguageSystem','configure','parse','buildIR','executeIntent','realize','run','eventRequest','sourceData','sourceArchive','diagnostics','validate'])assert.ok(js.includes(symbol),`missing standalone API: ${symbol}`);
for(const marker of ['pronunciation','phonetic','ipa','EVENT_REQUESTED','EVENT_CONFIRMED','EVENT_REJECTED','EVENT_EXECUTED','EVENT_FAILED','EVENT_PENDING'])assert.ok(js.includes(marker),`language preservation marker missing: ${marker}`);
for(const op of ['IDENTIFY','COUNT','QUANTITY','COMPARE','ANALYZE','FORECAST','POLICY','IMPORT','EXPORT','APPOINT','REMOVE','NEGOTIATE','ALLOCATE','START','HALT'])assert.ok(js.includes(`'${op}'`)||js.includes(`\"${op}\"`)||js.includes(op),`operation missing: ${op}`);
assert.ok(js.includes('sourceFiles')&&js.includes('migrationInvariant'),'embedded source manifest missing');
assert.equal(/(?:\.\/)?(?:offline_language_vocabulary|offline_lexicon|offline_semantic_knowledge|omega_game_language_ontology|omega_game_language_source_inventory|offline_semantic_brain|offline_query_engine|omega_game_language_bridge|omega_reasoning_dispatcher)\.(?:json|js)/.test(executable),false,'bundle contains a runtime reference to a retired language source');
for(const f of ['omega_cognitive_engine.js','omega_ai_integrity_layer.js','omega_universal_ai_runtime.js'])if(fs.existsSync(path.join(root,f))){const s=fs.readFileSync(path.join(root,f),'utf8');assert.equal(/offline_lexicon\.json|offline_language_vocabulary\.json|offline_semantic_knowledge\.json|omega_game_language_ontology\.json|omega_game_language_source_inventory\.json|offline_semantic_brain\.js|offline_query_engine\.js|omega_game_language_bridge\.js|omega_reasoning_dispatcher\.js/.test(s),false,`${f} retains a retired language-source dependency`)}
const sandbox={console,Date,JSON,Object,Array,Map,Set,Math,RegExp,String,Number,Promise,Intl,setTimeout,clearTimeout,localStorage:{d:new Map(),getItem(k){return this.d.get(k)||null},setItem(k,v){this.d.set(k,String(v))}},Game:{state:{}}};sandbox.globalThis=sandbox;sandbox.window=sandbox;
vm.runInNewContext(js,sandbox,{filename:'omega_language_system.js'});
const L=sandbox.OmegaLanguageSystem;assert.ok(L);assert.equal(L.STATUS,'STANDALONE_READY');const d=L.sourceData();
assert.equal(d['offline_lexicon.json'].TOTAL_WORDS,7756);const inv=d['omega_game_language_source_inventory.json'];assert.equal(inv.source_concept_count,17);assert.equal(inv.raw_surface_entry_count,332);assert.equal(inv.unique_surface_entry_count,226);assert.ok(d['offline_language_vocabulary.json'].languages.en&&d['offline_language_vocabulary.json'].languages.bn);
L.configure({datasets:[]});const en=L.parse('How many iron mines are in Bangladesh?');const bn=L.parse('বাংলাদেশে কয়টি লোহার খনি আছে?');assert.equal(en.operation,'COUNT');assert.equal(bn.operation,'COUNT');const unknown=L.parse('How many facilities are in Atlantis?');assert.ok(unknown.unresolved.includes('COUNTRY'));
const ev=L.eventRequest('IMPORT',{resource:'CRUDE_OIL'});assert.equal(ev.state,'EVENT_REQUESTED');assert.equal(ev.operation,'IMPORT');
console.log('OMEGA_STANDALONE_POST_MIGRATION_CONTRACT_OK');console.log(JSON.stringify({bundleBytes:Buffer.byteLength(js),version:L.VERSION,words:7756,inventory:inv,english:en.operation,bengali:bn.operation,unknownCountryPolicy:unknown.unresolved,legacyFilesAbsent:legacy.length},null,2));
