import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const root=new URL('..',import.meta.url);
const read=n=>JSON.parse(fs.readFileSync(new URL(n,root),'utf8'));
const source=fs.readFileSync(new URL('../omega_semantic_runtime_v32.js',import.meta.url),'utf8');
const bridge=fs.readFileSync(new URL('../omega_country_semantic_bridge.js',import.meta.url),'utf8');
const files=new Map(['offline_language_vocabulary.json','offline_semantic_knowledge.json','countries.json','ministers.json','resource_ontology.json','resources.json','relation_generation_engine.json'].map(n=>['/'+n,read(n)]));
const listeners=new Map();
const sandbox={console,Date,JSON,Object,Number,String,RegExp,Map,Set,Array,Math,Promise,URL,setTimeout,clearTimeout,setInterval:()=>1,clearInterval:()=>{},localStorage:{d:new Map(),getItem(k){return this.d.get(k)||null},setItem(k,v){this.d.set(k,String(v))}},fetch:async p=>({ok:true,json:async()=>files.get(p)}),dispatchEvent(e){for(const f of listeners.get(e.type)||[])f(e);return true},addEventListener(t,f){const s=listeners.get(t)||new Set();s.add(f);listeners.set(t,s)},CustomEvent:class{constructor(type,o={}){this.type=type;this.detail=o.detail}},Game:{state:{countryId:'BD',playerCountryId:'BD'}}};
sandbox.globalThis=sandbox;
vm.runInNewContext(source,sandbox,{filename:'omega_semantic_runtime_v32.js'});
vm.runInNewContext(bridge,sandbox,{filename:'omega_country_semantic_bridge.js'});
await new Promise(r=>setTimeout(r,100));
const api=sandbox.OmegaSemanticRuntimeV32;assert.ok(api);assert.equal(api.diagnostics().ready,true);assert.ok(api.diagnostics().resources>=Object.keys(read('resource_ontology.json').COMMODITY_ONTOLOGIES||{}).length);
const countryDiag=sandbox.OmegaCountrySemanticBridge.diagnostics();assert.equal(countryDiag.ready,true);assert.ok(countryDiag.countries>=195,`canonical country bridge has only ${countryDiag.countries}`);
let p=sandbox.OmegaAIIntegrity.parse('How old are you?',{ministerId:'Finance_1',countryId:'BD',ministryId:'Finance'});assert.equal(p.question.type,'how_old');assert.equal(p.operation,'ATTRIBUTE');assert.equal(p.attribute.name,'age');
p=sandbox.OmegaAIIntegrity.parse('How many mines are in Germany?');assert.equal(p.question.type,'how_many');assert.equal(p.operation,'COUNT');assert.equal(p.entities.country.id,'DE');
p=sandbox.OmegaAIIntegrity.parse('Where are the oil mines in Germany?');assert.equal(p.question.type,'where');assert.equal(p.operation,'LOCATE');assert.equal(p.entities.country.id,'DE');assert.equal(p.entities.resource.id,'CRUDE_OIL');
p=sandbox.OmegaAIIntegrity.parse('বাংলাদেশে কয়টি লোহার খনি আছে?');assert.equal(p.question.type,'how_many');assert.equal(p.entities.country.id,'BD');assert.equal(p.entities.resource.id,'IRON_ORE');
p=sandbox.OmegaAIIntegrity.parse('How many mines are in Atlantis?');assert.equal(p.entities.country.id,null);assert.equal(p.executable,false);
console.log('OMEGA semantic runtime V3.2 + complete country bridge regression tests: PASS');
