const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const legacy=['offline_language_vocabulary.json','offline_lexicon.json','offline_semantic_knowledge.json','omega_game_language_ontology.json','omega_game_language_source_inventory.json','offline_semantic_brain.js','offline_query_engine.js','omega_game_language_bridge.js','omega_reasoning_dispatcher.js'];
const bundle=path.join(root,'omega_language_system.js');
assert.ok(fs.existsSync(bundle),'canonical standalone bundle is missing');
const js=fs.readFileSync(bundle,'utf8');
assert.match(js,/OMEGA LANGUAGE SYSTEM v4\.1\.0-STANDALONE/);
assert.match(js,/STATUS:'STANDALONE_READY'/);
assert.match(js,/SOURCE_DATA/);
for(const f of legacy)assert.equal(fs.existsSync(path.join(root,f)),false,`legacy language dependency still present: ${f}`);
const executable=js.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/.*$/gm,'');
for(const re of [/\bfetch\s*\(/,/document\.createElement\(['"]script['"]\)/,/\bloadScript\s*\(/,/\bfetchJSON\s*\(/])assert.equal(re.test(executable),false,`legacy runtime dependency found: ${re}`);
for(const symbol of ['OmegaLanguageSystem','configure','parse','executeIntent','realize','run','eventRequest','learnPhrase','sourceData','diagnostics','validate'])assert.ok(js.includes(symbol),`missing standalone API: ${symbol}`);
assert.ok(js.includes('pronunciation')&&js.includes('phonetic')&&js.includes('ipa'),'pronunciation support missing');
for(const event of ['EVENT_REQUESTED','EVENT_CONFIRMED','EVENT_REJECTED','EVENT_EXECUTED','EVENT_FAILED','EVENT_PENDING'])assert.ok(js.includes(event),`event state missing: ${event}`);
for(const op of ['IDENTIFY','COUNT','QUANTITY','COMPARE','ANALYZE','FORECAST','POLICY','IMPORT','EXPORT','APPOINT','REMOVE','NEGOTIATE','ALLOCATE','START','HALT'])assert.ok(js.includes(`'${op}'`)||js.includes(`\"${op}\"`)||js.includes(op),`operation missing: ${op}`);
assert.ok(js.includes('sourceFiles')&&js.includes('migrationInvariant'),'embedded source manifest missing');
const illegalExternalRefs=/['"]\.\/(?:offline_language_vocabulary|offline_lexicon|offline_semantic_knowledge|omega_game_language_ontology|omega_game_language_source_inventory|offline_semantic_brain|offline_query_engine|omega_game_language_bridge|omega_reasoning_dispatcher)\.(?:json|js)['"]/;
assert.equal(illegalExternalRefs.test(executable),false,'bundle contains runtime path reference to deleted language source');
console.log('OMEGA_STANDALONE_POST_MIGRATION_CONTRACT_OK');
console.log(JSON.stringify({legacyFilesAbsent:legacy.length,bundleBytes:Buffer.byteLength(js,'utf8')},null,2));
